ant-design-blazor/ant-design-blazor

components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/typography/AntParagraph.cs, components/typography/AntTypographyBase.cs, site/AntBlazor.Docs/Components/DemoCard.razor, site/AntBlazor.Docs/Pages/Typography.razor
feat:(typography)( Add copyable icon render and corresponding trial functions.
Add a console.log() wrap up for jsinterop testing.
Temporarily use log instead of copy before copy is implemented.
Add copyable demo in demo project.
=> Add Paragraph copy feature

components/core/JsInterop/interop.ts, components/typography/AntParagraph.cs, components/typography/AntText.cs, components/typography/AntTitle.cs, components/typography/AntTypographyBase.cs, site/AntBlazor.Docs/Pages/Icon.razor, site/AntBlazor.Docs/Pages/Typography.razor
Finish copyable related function in AntParagraph, AntText and AntTitle. 
Text and Copy method can be fully customized.
=> feat (typography): polish typograph copy related functions.

components/AntBlazor.xml, components/alert/AntAlert.razor, components/alert/AntAlertBase.cs, components/alert/AntAlertType.cs, site/AntBlazor.Docs/Pages/Alert.razor, site/AntBlazor.Docs/wwwroot/menu.json
=> Add Alert Component

components/AntBlazor.xml, components/badge/AntBadge.razor, components/badge/AntBadgeBase.cs, components/badge/AntBadgeColor.cs, components/badge/AntBadgeStatus.cs, site/AntBlazor.Docs/Pages/Badge.razor, site/AntBlazor.Docs/wwwroot/menu.json
Finished based on the online docs.
Just not taking Animations into account for now.
=> [Finished] Add Badge

components/AntBlazor.csproj, components/core/Base/AntComponentBase.cs, components/core/Base/AntDomComponentBase.cs, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/radio/AntRadio.razor, components/radio/AntRadioBase.cs, components/radio/AntRadioGroup.razor, site/AntBlazor.Docs/Pages/Radio.razor, site/AntBlazor.Docs/wwwroot/menu.json
I'm working on radio component.
=> feat: add component radio

README.md, docs/introduce.md
Since I can't read mandarin and I guess not everyone can, we should translate the docs to english.
=> Translate README.md to English

README-cn.md, README-zh_CN.md, README.md
This pull request fix following issues: 
#25 
#39
=> doc: Update English README, add Chinese readme back

components/AntBlazor.csproj
See [Packaging License within the nupkg · NuGet/Home Wiki](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg )
=> Packaging License within the nupkg

components/AntBlazor.xml, components/back-top/AntBackTop.razor, components/back-top/AntBackTopBase.cs, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, site/AntBlazor.Docs/Pages/BackTop.razor, site/AntBlazor.Docs/Shared/MainLayout.razor, site/AntBlazor.Docs/wwwroot/menu.json
=> feat:add back-top(MIT)

.vscode/launch.json, .vscode/tasks.json
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/
=> chore: add vscode debug setting for wasm

README-zh_CN.md, README.md
=> docs: fix dingtalk badge

components/empty/AntEmpty.razor, components/empty/AntEmptyBase.cs, components/empty/AntEmptyDefaultImg.razor, components/empty/AntEmptySimpleImg.razor, site/AntBlazor.Docs/Pages/Empty.razor, site/AntBlazor.Docs/Resources/en-US.yml, site/AntBlazor.Docs/Resources/zh-CN.yml, site/AntBlazor.Docs/wwwroot/menu.json
=> feat: add component empty and doc

components/date-picker/AntDatePicker.Razor.cs
=> fix(module: date-picker): onselect error

components/list/AntList.razor, components/list/AntList.razor.cs, components/list/AntListItem.razor, components/list/AntListItem.razor.cs, components/list/AntListItemMeta.razor, site/AntBlazor.Docs/Pages/List.razor, site/AntBlazor.Docs/Resources/en-US.yml, site/AntBlazor.Docs/Resources/zh-CN.yml, site/AntBlazor.Docs/wwwroot/menu.json
=> simple list and basic list.

components/date-picker/AntDatePicker.Razor.cs, components/date-picker/AntDatePicker.razor, components/date-picker/internal/AntDatePickerDatetimePanel.razor, components/date-picker/internal/AntDatePickerPanelBase.cs, components/dropdown/AntDropdown.razor.cs, components/dropdown/internal/AntDropdownOverlay.razor, components/dropdown/internal/AntDropdownOverlay.razor.cs, site/AntBlazor.Docs/Pages/DatePicker.razor
=> fix: datepicker issue #94

components/affix/AntAffix.razor.cs, site/AntBlazor.Docs/Shared/MainLayout.razor
=> fix(module: affix): affix not working as root container updated

site/AntBlazor.Docs.Build.CLI/Utils/ConsoleUtils.cs
=> Remove unuse method

components/notification/Notification.razor.cs, components/notification/NotificationItem.razor.cs, components/notification/NotificationService.cs, site/AntBlazor.Docs/Demos/Notification/demo/Basic.razor, site/AntBlazor.Docs/Demos/Notification/demo/CustomIcon.razor, site/AntBlazor.Docs/Demos/Notification/demo/Duration.razor, site/AntBlazor.Docs/Demos/Notification/demo/Placement.razor, site/AntBlazor.Docs/Demos/Notification/demo/Update.razor, site/AntBlazor.Docs/Demos/Notification/demo/WithBtn.razor, site/AntBlazor.Docs/Demos/Notification/demo/WithIcon.razor, site/AntBlazor.Docs/Demos/Notification/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Notification/doc/index.zh-CN.md
- Modify according to review comments
- Add config api which remove on remove instance
- fix the bug which rendering behavior of server and client is inconsistent
=> fix: different render behavior in wasm and server

.github/workflows/gh-pages.yml, .github/workflows/style-sync.yml
因为这个 Action 只有官方仓库才有权限，所以不应该在 Fork 里面跑
详细请看 [GitHub 的 Action 如何禁用](https://blog.lindexi.com/post/GitHub-%E7%9A%84-Action-%E5%A6%82%E4%BD%95%E7%A6%81%E7%94%A8.html )
=> Only run style sync in origin repo

site/AntBlazor.Docs/Pages/Components.razor, site/AntBlazor.Docs/Pages/Components.razor.cs, site/AntBlazor.Docs/Shared/CodeBox.razor, site/AntBlazor.Docs/Shared/HighlightedCode.razor
=> docs: fix state updating for demo code

components/core/Base/AntInputComponentBase.cs
* fix: Fix a bug that could cause a crash
=> fix: fix input bug

components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/drawer/Drawer.razor.cs, components/modal/Dialog.razor.cs
fix: drawer animation transition
fix: when modal is opening, body scroll bar dispaly
=> fix: drawer and modal bug

components/drawer/Drawer.razor.cs
=> fix: drawer unresponsive In the WASM

components/modal/Dialog.razor, components/modal/Modal.razor.cs
=> fix: event not responding #203

components/form/Form.razor, components/form/Form.razor.cs, site/AntBlazor.Docs/Demos/Form/demo/Loading.razor, site/AntBlazor.Docs/Demos/Form/demo/loading.md
提供From组件载入状态属性，功能类似“table”的“Loading”属性
Provide loading status attribute, function similar to "table" "Loading" attribute
=> feat: form supports loading state

.github/workflows/gh-pages.yml
via https://github.com/dotnet/aspnetcore/issues/22353
=> fix: workaround for PWA manifest version updating

components/calendar/Calendar.razor.cs, components/date-picker/IDatePicker.cs, components/date-picker/internal/DatePickerBase.cs, components/date-picker/internal/DatePickerDatePanel.razor, components/date-picker/internal/DatePickerDatetimePanel.razor, components/date-picker/internal/DatePickerFooter.razor, components/date-picker/internal/DatePickerHeader.razor, components/date-picker/internal/DatePickerLocaleHelper.cs, components/date-picker/internal/DatePickerMonthPanel.razor, components/date-picker/internal/DatePickerQuarterPanel.razor, components/date-picker/internal/DatePickerYearPanel.razor, components/date-picker/types/DatePickerPlaceholder.cs, site/AntBlazor.Docs/Demos/DatePicker/demo/Basic.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Bordered.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/DateRender.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Disabled.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/DisabledDate.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/ExtraFooter.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Format.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Globalization.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/RangePickerDemo.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Size.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/Time.razor, site/AntBlazor.Docs/Demos/DatePicker/demo/globalization.md, site/AntBlazor.Docs/Demos/DatePicker/doc/index.zh-CN.md
WeekPicker is not fully supported
=> feat: add localization option to DatePicker

components/collapse/Collapse.razor, components/collapse/Collapse.razor.cs, components/collapse/CollapseExpandIconPosition.cs, components/collapse/Panel.razor, components/collapse/Panel.razor.cs, components/descriptions/Descriptions.razor.cs, site/AntBlazor.Docs/Demos/Collapse/demo/Accordion.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Basic.md, site/AntBlazor.Docs/Demos/Collapse/demo/Basic.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Borderless.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Custom.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Extra.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Mix.razor, site/AntBlazor.Docs/Demos/Collapse/demo/Noarrow.razor, site/AntBlazor.Docs/Demos/Collapse/demo/accordion.md, site/AntBlazor.Docs/Demos/Collapse/demo/borderless.md, site/AntBlazor.Docs/Demos/Collapse/demo/custom.md, site/AntBlazor.Docs/Demos/Collapse/demo/extra.md, site/AntBlazor.Docs/Demos/Collapse/demo/mix.md, site/AntBlazor.Docs/Demos/Collapse/demo/noarrow.md, site/AntBlazor.Docs/Demos/Collapse/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Collapse/doc/index.zh-CN.md, site/AntBlazor.Docs/Resources/en-US.yml, site/AntBlazor.Docs/Resources/zh-CN.yml, site/AntBlazor.Docs/wwwroot/menu.json
1、除动画效果外其余功能已完成
2、有两个demo存在问题，还需调整
=> feat: add Collapse component

components/skeleton/Skeleton.razor, components/skeleton/Skeleton.razor.cs, components/skeleton/SkeletonElement.razor, components/skeleton/SkeletonElement.razor.cs, components/skeleton/SkeletonType.cs, site/AntBlazor.Docs/Demos/Skeleton/demo/Active.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/Basic.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/Children.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/Complex.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/Element.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/List.razor, site/AntBlazor.Docs/Demos/Skeleton/demo/active.md, site/AntBlazor.Docs/Demos/Skeleton/demo/basic.md, site/AntBlazor.Docs/Demos/Skeleton/demo/children.md, site/AntBlazor.Docs/Demos/Skeleton/demo/complex.md, site/AntBlazor.Docs/Demos/Skeleton/demo/element.md, site/AntBlazor.Docs/Demos/Skeleton/demo/list.md, site/AntBlazor.Docs/Demos/Skeleton/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Skeleton/doc/index.zh-CN.md, site/AntBlazor.Docs/Resources/zh-CN.yml, site/AntBlazor.Docs/wwwroot/menu.json
完成功能和文档编写。
经过赋值操作对比，将属性类拆分成了独立属性在可读性和操作性上更加，对比如下
=> feat: add skeleton

components/core/AntContainer.razor, components/core/Base/TemplateComponentBase.cs, components/core/ServiceCollectionExtensions.cs, components/drawer/Drawer.razor.cs, components/drawer/DrawerContainer.razor, components/drawer/DrawerContainer.razor.cs, components/drawer/DrawerRef.cs, components/drawer/DrawerService.cs, components/drawer/DrawerTemplate.razor.cs, components/drawer/config/DrawerConfig.cs, components/modal/Comfirm.razor, components/modal/Comfirm.razor.cs, components/modal/ConfirmDialog.razor.cs, components/modal/Dialog.razor.cs, components/modal/Modal.razor.cs, components/modal/ModalFooter.razor.cs, components/modal/ModalService.cs, components/modal/config/ConfirmOptions.cs, components/modal/config/DialogOptions.cs, site/AntBlazor.Docs/Demos/Drawer/ComponentTemplate.razor, site/AntBlazor.Docs/Demos/Drawer/CompontentTemplate.razor, site/AntBlazor.Docs/Demos/Drawer/demo/Drawer_service.razor, site/AntBlazor.Docs/Demos/Drawer/demo/drawer_service.md, site/AntBlazor.Docs/Demos/Modal/demo/Confirm.razor, site/AntBlazor.Docs/Demos/Modal/demo/ConfirmPromise.razor, site/AntBlazor.Docs/Demos/Modal/demo/ConfirmRouter.razor, site/AntBlazor.Docs/Demos/Modal/demo/Info.razor, site/AntBlazor.Docs/Demos/Modal/demo/Locale.razor, site/AntBlazor.Docs/Demos/Modal/demo/Manual.razor, site/AntBlazor.Docs/Demos/Modal/demo/confirm-promise.md
support create drawer from an existing component template
=> feat: add DrawerService

components/list/AntList.razor, components/list/AntList.razor.cs, components/list/AntListItem.razor, components/list/AntListItem.razor.cs, site/AntBlazor.Docs/Demos/List/demo/Grid.razor, site/AntBlazor.Docs/Demos/List/demo/Loadmore.razor, site/AntBlazor.Docs/Demos/List/demo/Resposive.razor, site/AntBlazor.Docs/Demos/List/demo/Simple.razor, site/AntBlazor.Docs/Demos/List/demo/Vertical.razor
=> feat: add list resposive

components/input-number/InputNumber.razor.cs, components/input/Input.cs, site/AntBlazor.Docs/Demos/Input/demo/Clear.razor, site/AntBlazor.Docs/Demos/InputNumber/demo/Generic.razor
把InputNumber demo中decimal示例注释了
=> docs: fix InputNumber demo

.github/workflows/release.yml
Static files are currently missing. This PR is trying to fix them.
=> chore: fix static file compile for release ci

components/table/Table.razor, components/table/Table.razor.cs, components/table/TableSize.cs, site/AntBlazor.Docs/Demos/Table/demo/Bordered.razor, site/AntBlazor.Docs/Demos/Table/demo/Size.razor, site/AntBlazor.Docs/Demos/Table/demo/bordered.md, site/AntBlazor.Docs/Demos/Table/demo/size.md
Add size, bordered option and footer/header to table component
=> feat: add size, bordered option and footer/header to table component

components/table/Table.razor, components/table/Table.razor.Pagination.cs, components/table/Table.razor.cs
fix the total counter for client side #249
=> fix(module: table): refresh when datasource is changed

components/date-picker/DatePicker.Razor.cs, components/date-picker/DatePicker.razor, components/date-picker/RangePicker.razor, components/date-picker/RangePicker.razor.cs, components/date-picker/internal/DatePickerBase.cs, components/date-picker/internal/DatePickerInput.razor
fix: some styling regarding range pickers
Wasn't sure how I was supposed to clear the datepicker value as the date can't be null unless we make it nullable?
Edit: Also starting to feel that DatePickerInput might need to be cleaned up a bit, it's starting to become a mess of nested if statements
=> feat: allow clearing datepicker view

components/table/Table.razor.cs
修复Table组件未使用Selection时导致切换分页异常问题
=> fix(module: Table): when no rows were selected, page turning is abnormal

components/cascader/Cascader.razor.cs, components/date-picker/DatePicker.Razor.cs, components/date-picker/internal/DatePickerBase.cs, components/input-number/InputNumber.razor.cs, components/switch/Switch.razor.cs, site/AntBlazor.Docs/Demos/Form/demo/Size.razor
修正问题
1、首次绑定model时，默认值没有正确赋值的问题，涉及控件Cascader，DatePicker，InputNumber，Switch
已知问题
1、直接对form绑定的model进行修改值，Cascader，DatePicker不能正确刷新成新的值，请@笨木头 帮忙修复一下
=> fix: fix the form binding value bug

components/table/Column.razor, components/table/Column.razor.cs, components/table/IFieldColumn.cs, components/table/ITable.cs, components/table/Table.razor, components/table/Table.razor.Pagination.cs, components/table/Table.razor.Selection.cs, components/table/Table.razor.cs, components/table/TableModels/ITableSortModel.cs, components/table/TableModels/QueryModel.cs, components/table/TableModels/SortModel.cs, components/table/TableModels/SortType.cs, site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
- sortable column
~~- mutiple/single~~ later
- query model changed event
~~- pre-process delegate~~ later
=> feat(module: table): sortable

.github/workflows/algolia-config.json, .github/workflows/docsearch.yml
Action to add indices to DocSearch
=> DocScrape action

.github/workflows/algolia-config.json, site/AntBlazor.Docs/Pages/Components.razor.cs, site/AntBlazor.Docs/Resources/en-US.yml, site/AntBlazor.Docs/Resources/zh-CN.yml, site/AntBlazor.Docs/Shared/MainLayout.razor.cs, site/AntBlazor.Docs/wwwroot/js/docsearch.js
Modify the configuration after PR #271
=> docs: replace algolia config items

components/steps/Step.razor, components/steps/Step.razor.cs, site/AntBlazor.Docs/Demos/Steps/demo/Clickable.razor, site/AntBlazor.Docs/Demos/Steps/demo/CustomizedProgressDot.razor, site/AntBlazor.Docs/Demos/Steps/demo/Error.razor, site/AntBlazor.Docs/Demos/Steps/demo/Icon_.razor, site/AntBlazor.Docs/Demos/Steps/demo/Nav.razor, site/AntBlazor.Docs/Demos/Steps/demo/ProgressDot.razor, site/AntBlazor.Docs/Demos/Steps/demo/Simple.razor, site/AntBlazor.Docs/Demos/Steps/demo/SmallSize.razor, site/AntBlazor.Docs/Demos/Steps/demo/Vertical.razor, site/AntBlazor.Docs/Demos/Steps/demo/VerticalSmall.razor
add templateRef to step component. affect prop: Title, Subtitle, Description
=> add templateRef to step component

components/form/Form.razor.cs, components/form/Internal/IForm.cs, site/AntBlazor.Docs/Demos/Form/demo/FormContext.md, site/AntBlazor.Docs/Demos/Form/demo/FormContext.razor
I exposed a method to trigger is form modified of the EditContext of the EditForm. 
So, still, I am not sure why is triggering at the second input trigger, in any field on the form, or if you type two characters in the same input filed.
@ElderJames    you can test this and check it, but I think that is related to the EditContext and EditForm of the AspNetCore.Components. I'll check it. 
Still, I am thinking that is a good time to expose this method and keep it as public in the Form class.
Kind regards,
=> Form context, IsModified property

components/core/JsInterop/interop.ts
修改upload的成功条件为 xhr.status == 200
=> fix(module: upload) :  Determine success based on status==200

components/form/FormItem.razor, components/form/FormItem.razor.cs
Support the use of native HTML elements to display the require tag (*) in FormItem compontent
=> feat(module: form): add Required paramater

components/core/Base/AntInputComponentBase.cs, components/core/Extensions/DataConvertionExtensions.cs, components/slider/Slider.razor, components/slider/Slider.razor.cs, site/AntBlazor.Docs/Demos/Slider/demo/Basic.razor, site/AntBlazor.Docs/Demos/Slider/demo/Customer.razor, site/AntBlazor.Docs/Demos/Slider/demo/Event.razor, site/AntBlazor.Docs/Demos/Slider/demo/Graduated.razor, site/AntBlazor.Docs/Demos/Slider/demo/Icon1.razor, site/AntBlazor.Docs/Demos/Slider/demo/Input.razor, site/AntBlazor.Docs/Demos/Slider/demo/Reversed.razor, site/AntBlazor.Docs/Demos/Slider/demo/Tooltip.razor, site/AntBlazor.Docs/Demos/Slider/demo/Vslider.razor, site/AntBlazor.Docs/Demos/Space/demo/Customize.razor
=> feat(module: slider): implement two-way binding

components/modal/Modal.razor.cs
fix #371: modal crashes when DestroyOnClose is set to true
=> fix(module: modal): crashes when DestroyOnClose is set to true (#371)

components/avatar/Avatar.razor, components/avatar/Avatar.razor.cs
=> fix(module: avatar): dead-loop rendering

components/core/JsInterop/interop.ts, components/upload/Upload.razor.cs
=> fix(module: upload): Upload with other form parameters

components/core/JsInterop/interop.ts
fix: drawer, modal and confirm on multi level open can not reset scroll bar correctly (#393)
=> fix: drawer, modal and confirm multi level open scroll bar bug (#393)

components/core/JsInterop/interop.ts
=> fix(module:modal): the width will be added when there is no scroll bar

components/timeline/Timeline.razor, components/timeline/Timeline.razor.cs, components/timeline/TimelineItem.cs
=> fix(module: timeline): missing default constructor

.github/workflows/gh-pages.yml, scripts/npm/Program.cs, scripts/npm/package.csproj, scripts/npm/package.json
| 🇺🇸 English | Publish assets to npm for cdn    |
| 🇨🇳 Chinese |    发布资源文件到 npm ，用于CDN      |
=> chore: publish assets to npm

site/AntBlazor.Docs/Resources/en-US.yml, site/AntBlazor.Docs/Resources/zh-CN.yml
Language resources for 'Examples' is mssing
=> fix: missing language resources for 'Examples'

components/upload/Upload.razor, components/upload/Upload.razor.cs, site/AntBlazor.Docs/Demos/Upload/demo/PictureStyle.razor
There are missing OnRemove delegate for upload component.
=> fix(module: upload): add OnRemove delegate

site/AntBlazor.Docs/Demos/Button/demo/Loading.razor
**Problem:**
According to the current implementation of Blazor(https://github.com/dotnet/aspnetcore/issues/16213#issuecomment-381124723), it runs in single-thread mode. Thus the call to `System.Threading.Thread.Sleep` will block the UI thread as well. It means when clicking the loading button, the UI freezes. 
| 🇺🇸 English |        Update the demo code for Loading Button to use `Task.Delay` to not block the UI thread. |
=> Docs: Update the demo code for Loading Button

components/checkbox/Checkbox.razor.cs, components/checkbox/CheckboxGroup.razor, components/checkbox/CheckboxGroup.razor.cs, components/core/Extensions/EnumerableExtensions.cs, components/form/FormItem.razor.cs, site/AntBlazor.Docs/Demos/Checkbox/demo/Group.razor, site/AntBlazor.Docs/Demos/Select/demo/Basic.razor
=> fix(module: checkbox): default value binding

components/button/Button.razor.cs, components/carousel/Carousel.razor.cs
It's a follow-up of #436.
According to the current implementation of Blazor(dotnet/aspnetcore#16213 (comment)), it runs in single-thread mode. Thus the call to `System.Threading.Thread.Sleep` will block the UI thread as well. It means when clicking the button, the UI freezes.
For example, in button component, the UI will freeze for 500ms. It's a relatively small time, however Chrome does give a warning to this:
***[Violation] 'setTimeout' handler took 500ms***
| 🇺🇸 English |    Use Task.Delay to replace Thread.Sleep in order to remove UI freezes.       |
⚠️ Please check all …
=> Use Task.Delay to replace Thread.Sleep in order to remove UI freezes. 

components/auto-complete/AutoComplete.razor.cs, site/AntBlazor.Docs/Demos/AutoComplete/demo/Basic.razor, site/AntBlazor.Docs/Demos/AutoComplete/demo/Custom.razor
| 🇺🇸 English |     Fixed the problem that AutoComplete input text is not correctly assigned to bind-value      |
| 🇨🇳 Chinese |   修正了AutoComplete输入文本没有正确赋值到bind-value的问题        |
=> fix: autoComplete bind-value bug

.github/workflows/release.yml
=> chore: add npm release action

.github/workflows/gh-pages.yml
=> chore: prepare for 0.3.0 version

components/form/Form.razor.cs
| 🇺🇸 English |   null check for form submit  |
=> fix(module: form): null check for submit

components/table/Selection.razor.cs, site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor, site/AntBlazor.Docs/Demos/Table/demo/RouterPagging.razor, site/AntBlazor.Docs/Demos/Table/demo/router-pagging.md, site/AntBlazor.Docs/Pages/Mock.razor
| 🇺🇸 English |  add router pagging demo   |
| 🇨🇳 Chinese |  增加路由url分页 demo  |
=> feat(module: table): add router pagging demo

components/drawer/Drawer.razor, components/drawer/Drawer.razor.cs
| 🇺🇸 English | add parameter handler to drawer component   |
| 🇨🇳 Chinese |    drawer组件新增参数handler       |
=> feat(module: drawer): add parameter handler

components/date-picker/RangePicker.razor.cs
Fixes #458 which was preventing a new start date from being selected.
=> fix(module:date-picker): fix inability to select new start date (#458)

package.json
=> Add missing "run" from wasm start command

components/message/Message.razor.cs
fix #452 
| 🇺🇸 English |  remove message DOM after the last message dissapear  |
| 🇨🇳 Chinese |  在最后一个message消失时清除message的DOM |
=> fix: remove the last message DOM after message disappears

components/steps/Step.razor, components/steps/Step.razor.cs, components/steps/Steps.razor.cs, site/AntBlazor.Docs/Demos/Components/Steps/demo/Progress.razor, site/AntBlazor.Docs/Demos/Components/Steps/demo/progress.md
https://github.com/ant-design-blazor/ant-design-blazor/issues/447
| 🇨🇳 Chinese | add progress step |
=> feat: add progress step

LICENSE, LICENSE-ant-design.txt
=> chore: update license 3rd party

components/core/Helpers/Formatter.cs, components/core/Reflection/TypeDefined.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor
#482 
| 🇺🇸 English |     fix formatting with nullable type for table column      |
| 🇨🇳 Chinese |   修复表列的可空类型格式化问题        |
=> fix(module: table): formatting with nullable type

components/gulpfile.js
Now it causes the project path to go out of range.
=> fix: ignore wwwroot for copying .less source files

components/list/AntList.razor, components/list/AntList.razor.cs, components/list/AntListItem.razor, components/list/AntListItem.razor.cs, site/AntBlazor.Docs/Demos/Components/List/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/List/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/List/doc/index.zh-CN.md
#419 
| 🇺🇸 English |    add OnItemClick event callback  for list items       |
| 🇨🇳 Chinese |     添加OnItemClick事件回调      |
=> feat(module: list): add OnItemClick event callback  for list items   

components/core/Helpers/Formatter.cs, components/table/Table.razor
=> fix(module: table): empty column count and formatter

components/typography/Paragraph.cs, components/typography/Text.cs, components/typography/Title.cs
=> fix(module: typography): missing Style property

components/tabs/Tabs.razor, components/tabs/Tabs.razor.cs, site/AntBlazor.Docs/Demos/Components/Tabs/demo/Basic.razor
=> fix(module: tabs): missing event callbacks

components/layout/Sider.razor.cs
=> fix(module: sider): cannot update theme dynamically

components/radio/Radio.razor.cs, components/radio/style/entry.less, site/AntBlazor.Docs/Demos/Components/Radio/demo/Style.razor
=> fix(module: radio): disabled in radio group doesn't work

components/core/Extensions/EnumerableExtensions.cs, components/layout/Sider.razor, components/layout/Sider.razor.cs, components/menu/Menu.razor.cs, components/menu/SubMenu.razor.cs
=> fix(module: sider): can't collapse in demo

README-zh_CN.md, README.md, docs/introduce.en-US.md, docs/introduce.zh-CN.md
=> docs: show how to create a project with template

components/statistic/Statistic.razor, components/statistic/Statistic.razor.cs
=> fix(module: statistic): separate decimal incorrectly

components/core/Component/overlay/Overlay.razor.cs, components/menu/SubMenu.razor.cs
=> fix(module: menu): can't open submenu while sider is collapsed

components/input/Input.cs
=> fix(module: input): composition event conflict

components/AntDesign.csproj, components/core/Extensions/HttpClientExtensions.cs, components/core/Extensions/ServiceCollectionExtensions.cs, components/icon/IconService.cs
=> refactor: make the extensions class for HttpClient internal

components/checkbox/Checkbox.razor.cs, components/checkbox/CheckboxGroup.razor, components/checkbox/CheckboxGroup.razor.cs, site/AntBlazor.Docs/Demos/Components/Checkbox/demo/Group.razor
=> fix(module: checkbox): options.value works incorrectly

components/carousel/Carousel.razor.cs
=> fix(module: carousel): make carousel responsive

components/upload/Upload.razor
=> fix(module: upload): files that aren't pictures can't be downloaded

components/core/Base/AntComponentBase.cs, components/core/JsInterop/interop.ts, components/upload/Upload.razor, components/upload/Upload.razor.cs, site/AntBlazor.Docs/Demos/Components/Upload/demo/PictureCard.razor, site/AntDesign.Docs.Server/Pages/_Host.cshtml
=> fix(module: upload): fileList can't be refreshed while it was changed

components/typography/Paragraph.cs, components/typography/Text.cs, site/AntBlazor.Docs/Demos/Components/Typography/demo/Style.razor
- [x ] New feature
- [x ] Demo update
| 🇺🇸 English |    text add keyboard parameter and update demo       |
| 🇨🇳 Chinese |   text 添加 keyboard 参数以及更新demo         |
=> feat: add text keyboard parameter,and update demo

components/statistic/Statistic.razor
=> fix(module: statistic): there is no title but the element is rendered

components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/drawer/Drawer.razor.cs, components/modal/Dialog.razor.cs
#568 
| 🇺🇸 English | fixed the bug that the body scroll bar failed to respond correctly under multiple modal |
| 🇨🇳 Chinese | 修复body滚动条在多modal下无法正确响应bug |
=> fix(module: modal and drawer): body scroll bar does not respond correctly (#568)

components/cascader/Cascader.razor
=> fix(module: cascader): crashes when options is null

components/AntDesign.csproj, components/core/Extensions/EnumerableExtensions.cs, components/table/Table.razor.RowData.cs, components/table/Table.razor.cs, tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html, tests/AntDesign.Tests.csproj, tests/AntDesignTestBase.cs, tests/RecordedTestExtensions.cs, tests/table/TableTests.cs
This change does a few things:
1) Fix the issue ``System.InvalidOperationException: Collection was modified; enumeration operation may not execute.`` reported by an user in the Slack channel. 
2) Removes a potenticial performance issue by avoiding multiple evaluations of a same IEnumerable when possible;
3) Introduces a way of recording the markup generated by a component at the end of a test so it can be compared against future changes.
The last item is a proposition on how we can compare results of tests without a ridiculous amount of effort -- all you need to do is run the test once to record the output and the next executions will be measured against …
=> fix(module: table): fix collection modified exception

components/AssemblyInfo.cs, components/core/Helpers/Formatter.cs, components/slider/Slider.razor.cs, components/statistic/CountDown.razor, components/statistic/CountDown.razor.cs, components/table/Column.razor, site/AntBlazor.Docs/Demos/Components/Statistic/demo/Countdown.razor, tests/Core/FormatterTests.cs
=> refactor(formatter): merge the special method of timespan into formatter

components/core/Extensions/ServiceCollectionExtensions.cs, components/locale-provider/Locale.cs, components/locale-provider/LocaleProvider.cs, docs/i18n.en-US.md, docs/i18n.zh-CN.md, tests/AntDesignTestBase.cs
=> docs: add i18n docs

components/table/Table.razor.cs
=> fix(module: table): the sorter doesn't work

components/drawer/DrawerContainer.razor, components/drawer/DrawerContainer.razor.cs, components/drawer/DrawerRef.cs, components/drawer/DrawerService.cs, components/drawer/config/DrawerOptions.cs, site/AntBlazor.Docs/Demos/Components/Drawer/demo/Drawer_service.razor, site/AntBlazor.Docs/Demos/Components/Drawer/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Drawer/doc/index.zh-CN.md
fix #522 
| 🇺🇸 English |  merge oncancel and onclose of drawer |
| 🇨🇳 Chinese |   合并drawer组件的 oncancel 和 onclose 事件 |
=> fix(module: drawer): merge oncancel and onclose (#522)

components/core/Component/overlay/Overlay.razor, components/core/Component/overlay/Overlay.razor.cs, components/core/Component/overlay/OverlayTrigger.razor, components/core/Component/overlay/OverlayTrigger.razor.cs, components/select/Select.razor, components/select/Select.razor.cs, components/select/SelectOption.razor.cs, components/select/internal/SelectBase.cs, components/select/internal/SelectContent.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/CustomDropdownMenu.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Search.razor
| 🇺🇸 English |      add overlay, fix some serious bugs     |
| 🇨🇳 Chinese |     将下拉弹出功能改为使用overlay，修复部分严重的bug    |
=> refactor(module: select): add overlay, fix some serious bugs

components/select/Select.razor
=> fix(module: select): wrong overlay style

components/list/AntListItem.razor
=> fix(module: list) grid not working

.github/workflows/gh-pages.yml, .github/workflows/pr-preview.yml, LICENSE, LICENSE-ant-design.txt
=> chore: prepare for 0.4.0

.github/ISSUE_TEMPLATE/bug_report.md
to further point out that code is preferred
=> extend steps to repoduce title

.github/workflows/pr-preview.yml
=> chore: revert the pr preview action

components/core/Base/TemplateComponentBase.cs, components/drawer/DrawerContainer.razor, components/drawer/DrawerContainer.razor.cs, components/drawer/DrawerRef.cs, components/drawer/DrawerService.cs, components/drawer/DrawerTemplate.razor.cs, components/drawer/IDrawerRef.cs, components/drawer/config/DrawerClosingEventArgs.cs, components/modal/ModalService.cs, components/modal/ModalTemplate.razor.cs, site/AntBlazor.Docs/Demos/Components/Drawer/DrawerTemplateDemo.razor, site/AntBlazor.Docs/Demos/Components/Drawer/demo/Drawer_service.razor, site/AntBlazor.Docs/Demos/Components/Modal/ModalTemplateDemo.razor
| 🇺🇸 English |    1. Fix the aging issue of the Close event. 2. Increase the mode box way to open the drawer.       |
| 🇨🇳 Chinese |    1、修正Close事件时效问题。2、增加模式框方式打开抽屉。       |
=> fix: drawer close event bug

components/select/Select.razor, components/select/internal/SelectBase.cs
=> fix(module: select): add PopupContainerSelector parameter

components/menu/Menu.razor.cs
=> fix(module: menu): the selected menu item would unselect itself after is clicked again 

components/select/Select.razor.cs, components/select/internal/SelectContent.razor
=> fix(module: select): broken removing of selected tag

.github/workflows/gh-pages.yml, .github/workflows/pr-preview.yml, .github/workflows/pull-request.yml, site/AntBlazor.Docs/AntDesign.Docs.csproj, site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj, site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj, tests/AntDesign.Tests.csproj
=> chore: update the docs project to .net 5 rc1

components/menu/Menu.razor.cs, site/AntBlazor.Docs/Routing/ConventionRouter.cs
=> fix: follow up the .net 5 docs and fix the culture issue

components/list/AntList.razor, components/list/AntList.razor.cs, components/list/ListItem.razor, components/list/ListItem.razor.cs, site/AntBlazor.Docs/Demos/Components/Drawer/demo/Userprofile.razor
=> fix(module: list): list item layout in listitem

components/core/Component/overlay/Overlay.razor, components/core/Component/overlay/OverlayTrigger.razor.cs, components/modal/Dialog.razor.cs, components/modal/Modal.razor, components/select/Select.razor, components/select/Select.razor.cs, components/select/internal/SelectBase.cs, components/select/internal/SelectContent.razor, site/AntBlazor.Docs/Demos/Components/Modal/demo/DropdownInModal.razor, site/AntBlazor.Docs/Demos/Components/Modal/demo/dropdown-in-modal.md
| 🇺🇸 English |    fix: [dropdown、select] work incorrectly in modal       |
| 🇨🇳 Chinese |      fix: [dropdown、select]在Modal中出现异常     |
=> fix: [dropdown、select] work incorrectly in modal

site/AntBlazor.Docs/Pages/Components.razor.cs, site/AntBlazor.Docs/Pages/Docs.razor.cs, site/AntBlazor.Docs/Services/DemoService.cs, site/AntBlazor.Docs/Shared/MainLayout.razor.cs, site/AntBlazor.Docs/Shared/NavMenu.razor.cs, site/AntBlazor.Docs/Shared/PrevNextNav.razor, site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs
=> docs: fix prev-next navbar

components/modal/Modal.razor, components/select/Select.razor.cs, components/select/internal/SelectBase.cs, site/AntBlazor.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
| 🇺🇸 English |     fix: incorrect dropdown style     |
| 🇨🇳 Chinese |    修复：下拉样式不正常       |
=> fix(module: select): incorrect dropdown style

components/card/Card.razor, components/card/Card.razor.cs, components/card/CardGrid.razor, components/card/CardGrid.razor.cs, components/card/CardMeta.razor, components/tabs/Tabs.razor, components/tabs/Tabs.razor.cs, site/AntBlazor.Docs/Demos/Components/Card/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Customized.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Loading.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Noborder.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Support.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Tabs1.razor, site/AntBlazor.Docs/Demos/Components/Card/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Card/doc/index.zh-CN.md, site/AntBlazor.Docs/Pages/Index.razor, site/AntBlazor.Docs/Services/DemoService.cs
=> fix(module: card): grid and tabs has wrong styles

components/statistic/CountDown.razor, components/statistic/CountDown.razor.cs, components/statistic/Statistic.razor, components/statistic/StatisticComponentBase.razor.cs
=> fix: allow setting class for statistic component

components/menu/SubMenu.razor, site/AntBlazor.Docs/Demos/Components/Menu/demo/Horizontal.razor
=> fix: subMenu of subMenu rendering is invalid

components/core/Component/overlay/OverlayTrigger.razor.cs, components/descriptions/Descriptions.razor.cs, components/slider/Slider.razor.cs
=> fix: the prerendering interop exception with some components

site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
=> docs: disable the linker for workaround the table page breaking

site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
https://github.com/dotnet/runtime/issues/42536
=> docs: workaround for the linker bug

components/badge/Badge.razor, components/badge/Badge.razor.cs, components/badge/style/entry.less, site/AntBlazor.Docs/Demos/Components/Badge/demo/Dot.razor, site/AntBlazor.Docs/Demos/Components/Badge/demo/Offset.razor, site/AntBlazor.Docs/Demos/Components/Badge/demo/Size.razor, site/AntBlazor.Docs/Demos/Components/Badge/demo/offset.md, site/AntBlazor.Docs/Demos/Components/Badge/demo/size.md, site/AntBlazor.Docs/Demos/Components/Badge/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Badge/doc/index.zh-CN.md
fixed #640 
| 🇺🇸 English |  add size  property    |
| 🇨🇳 Chinese |   增加尺寸属性        |
=> fix(module: badge): incorrect status dot & disappeared scroll number

components/input/TextArea.razor
| 🇨🇳 Chinese |   修正下面出现的滚动条   |
```
<Drawer Closable="true" Visible="visible" Placement="right" Title='("Basic Drawer")' OnClose="_=>close()">
<p>Some contents...</p>
<p>Some contents...</p>
<p>Some contents...</p>
<Form Model="model" LabelCol="new ColLayoutParam() {Span = 8 }">
<FormItem Label="描述">
<TextArea @bind-Value="@context.Str" MinRows="4" />
</FormItem>
</Form>
</Drawer>
```
=> fix: textarea display bug

components/auto-complete/AutoComplete.razor, components/auto-complete/AutoComplete.razor.cs
=> fix(module: auto-complete): could not select value by chance

components/table/ActionColumn.razor, components/table/Column.razor, components/table/ColumnBase.cs, components/table/Selection.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/ColspanRowspan.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/colspan-rowspan.md, tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html, tests/table/TableTests.cs
| 🇺🇸 English |   add colspan & rowspan for table    |
| 🇨🇳 Chinese |    表格增加   colspan & rowspan 设置合并行、列    |
=> feat(module: table): add colspan & rowspan

components/core/JsInterop/DomEventService.cs, components/core/JsInterop/DomEventSubscription.cs, components/slider/Slider.razor.cs
=> fix(module: slider): cannot slide

components/modal/ConfirmDialog.razor.cs, components/modal/config/ConfirmOptions.cs
#651 
| 🇺🇸 English |  fix unable to set the width of Confirm component |
| 🇨🇳 Chinese |  修复无法设置Confirm组件的宽度问题 |
=> fix(module: confirm): cannot config confirm width (#651)

scripts/gh-pages/index.html, site/AntBlazor.Docs/AntDesign.Docs.csproj, site/AntBlazor.Docs/Demos/Charts/Introduce/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Charts/Introduce/doc/index.zh-CN.md, site/AntBlazor.Docs/Pages/Components.razor, site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs, site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs, site/AntDesign.Docs.Server/Pages/_Host.cshtml, site/AntDesign.Docs.Wasm/wwwroot/index.html
=> docs: update charts library

.github/workflows/gh-pages.yml, .github/workflows/pr-preview.yml, .github/workflows/pull-request.yml, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj, site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj
=> docs: update to rc2

components/core/Component/overlay/Overlay.razor, components/core/Component/overlay/Overlay.razor.cs, components/core/Component/overlay/OverlayTrigger.razor, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/popconfirm/Popconfirm.razor, components/popover/Popover.razor, components/tooltip/Tooltip.razor
| 🇺🇸 English |      fix: bugs when overlay is nested     |
| 🇨🇳 Chinese |    修复：overlay重叠使用时出现的bug       |
=> fix: bugs when overlay is nested

components/auto-complete/AutoComplete.razor, site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Performance.razor, site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/performance.md
| 🇺🇸 English |    Optimized the performance when autocomplete selection list is closed       |
| 🇨🇳 Chinese |   优化了autocomplete选择列表关闭时的性能，这个只是在autocomplete中表面处理了一下，需要改进Overlay才能彻底解决这个问题。        |
=> fix: autocomplete performance

site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
=> docs: fix the missing globalization data by linking

components/date-picker/RangePicker.razor, components/date-picker/internal/DatePickerDatePanel.razor
before:
fix:
| 🇺🇸 English |     fix duplicate footer on rangepicker      |
=> fix: duplicate footer on rangepicker

components/tree/Tree.razor.cs, components/tree/TreeNode.razor.cs
1. change `TreeNode`'s `ChildNodes` accessbility to public
2. add `FindFirstOrDefaultNode` funcation
3. add `ExpandToNode` function
=> tree enhancement

components/input-number/InputNumber.razor, components/input-number/InputNumber.razor.cs
Hi,
based on the [Issue #697 ](https://github.com/ant-design-blazor/ant-design-blazor/issues/697) which i created yesterday, i wrote a little patch to enhance the InputNumber component.
- [x ] New feature
1. [Issue #697 ](https://github.com/ant-design-blazor/ant-design-blazor/issues/697)
| 🇺🇸 English |  Added a OnChange Callback to the InputNumber component.    |
=> Enhancement: InputNumber - OnChange Callback

components/table/TableModels/SortModel.cs
=> fix ITableSortModel.SetSortType(SortType)

components/transfer/Transfer.razor, components/transfer/Transfer.razor.cs, components/transfer/TransferChangeArgs.cs, components/transfer/TransferItem.cs, components/transfer/TransferLocale.cs, components/transfer/TransferScrollArgs.cs, components/transfer/TransferSearchArgs.cs, components/transfer/TransferSelectChangeArgs.cs, site/AntBlazor.Docs/Demos/Components/Transfer/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Transfer/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Transfer/doc/index.zh-CN.md
Hello everyone,
some small fixes for the transfer module.
fix(module: transfer): Added localization support (LocaleProvider.CurrentLocale.Transfer).  Property name is 'Locale'. #645
fix(module: transfer): Fixed no data image.
fix(module: transfer): Header alignment
fix(module: transfer): Fixed header count suffix
fix(module: transfer): Fixed a bug in the checkbox state if there is 'no item' or no 'not deactivated' item in the selection list.
fix(module: transfer): Duplicate item filter bug fixed (#711)
feat(module: transfer): Added clear button to the filter input
feat(module: transfer): Filter option is now InvariantCultureIgnoreCase (please change it if there is a problem with chinese language)
style(module: transfer): removed unused usings, fixed some style issues
docs(module: …
=> fix(module: transfer): Fixed multiple issues

components/select/Select.razor, components/select/Select.razor.cs, components/select/SelectLocale.cs, components/select/SelectOption.razor.cs, components/select/internal/SelectBase.cs, components/select/internal/SelectContent.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Multiple.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Search.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/ShowInFormModal.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Size.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/Tags.razor, site/AntBlazor.Docs/Demos/Components/Select/demo/show-in-form-modal.md
Hello everyone,
fix(module: select): Typo in method generation
fix(module: select): Fixed empty data image
fix(module: select): Fixed "focused"-style problem, now it looks like the React implementation
fix(module: select): Internal server error when the page was reloaded (#695)
fix(module: select): Fixed multiple reset issues (#674, #557)
fix(module: select): Added 'No Data' on `Select Mode="multiple"` when `HideSelected ` is `true` and all options are selected
fix(module: select): Added clear button to `Select Mode="multiple"` and `Select Mode="tags"` (#588)
fix(module: select): Default value for `OptionLabelProp` was not set. (Select.razor.cs - Line 275-277) (Makes the workaround with the multiple `@item's` obsolete)
docs(module: select): Added/Changed some demos for testing purposes …
=> fix(module: select): Fixed multiple issues

components/core/Extensions/EnumerableExtensions.cs
* 当array==null时，改为返回Array.Empty<T>()
* 考虑T类型为引用类型时，集合元素可能为null，原有逻辑会触发null.Equals()的问题
=> 修复EnumerableExtensions的Remove()实现的两个逻辑问题

components/checkbox/Checkbox.razor, components/checkbox/Checkbox.razor.cs
| 🇺🇸 English |    Cleaned up some redundant code       |
| 🇨🇳 Chinese |  清理了一些多余的代码  |
=> fix: optimized code

components/date-picker/DatePicker.razor, components/date-picker/RangePicker.razor
Fixed DatePicker OnOpenChange
Fixed duplicate footer on time rangepicker
| 🇺🇸 English |  DatePicker OnOpenChange now works, fixed duplicate footer on time rangepicker  |
=> DatePicker improvements

tests/grid/ColTests.cs
- This is to complete #343.
- #343 which was written by me but I was unable to finish up the tests because of a derecho.
This is to complete the required tests. I expanded it to include most of the other properties in `Col` including various overlap rendering to catch both positive and negative tests on the change.
- Added only tests, should have no visible or breaking changes.
- No documentation changes needed since it is just verification.
=> test(module: grid): added rendering tests for properties of columns

components/AntDesign.csproj
=> chore: add source link

components/modal/ConfirmDialog.razor, components/modal/ConfirmDialog.razor.cs
#749 
| 🇺🇸 English |  Fixed a bug that was not removed from the DOM when confirm was hidden  |
| 🇨🇳 Chinese |  修复当confirm隐藏时不会从dom中移除的bug  |
=> fix(module: confirm): cannot remove Dialog from the dom tree when confim is hidden (#749)

components/core/Component/overlay/OverlayTrigger.razor.cs
=> fix(module: overlay) don't close overlay if is controlled via visable param fixes #742

README-zh_CN.md, README.md, docs/getting-started.en-US.md, docs/getting-started.zh-CN.md, docs/introduce.en-US.md, docs/introduce.zh-CN.md
=> docs: update links

components/table/Table.razor, components/table/Table.razor.Pagination.cs, components/table/Table.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor, site/AntDesign.Docs.Server/Pages/_Host.cshtml
| 🇺🇸 English |   fix table's pagination didn't change while pageIndex was changed        |
| 🇨🇳 Chinese |   修复表格 pageIndex 改变但是页码没变的问题        |
=> fix(module: table): pagination didn't change while pageindex was changed

components/AntDesign.csproj, components/table/Table.razor, components/table/Table.razor.cs, components/table/TableModels/RowData.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/Expand.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/expand.md
| 🇺🇸 English |  table support for expand row         |
| 🇨🇳 Chinese |  表格支持行展开   |
=> feat(module: table): support for expand row

components/core/CssSizeLength.cs, components/table/ActionColumn.razor, components/table/Column.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/IColumn.cs, components/table/ITable.cs, components/table/Selection.razor, components/table/Selection.razor.cs, components/table/Table.razor, components/table/Table.razor.RowData.cs, components/table/Table.razor.Selection.cs, components/table/Table.razor.cs, components/table/TableModels/RowData.cs, site/AntBlazor.Docs/AntDesign.Docs.csproj, site/AntBlazor.Docs/Demos/Components/Table/demo/Expand.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/TreeData.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/tree-data.md, tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html
=> feat(module: table): support for tree data

components/progress/Progress.razor, components/progress/Progress.razor.cs, site/AntBlazor.Docs/Demos/Components/Progress/demo/GradientLine.razor
=> fix(module: progress): single stroke color

components/menu/Menu.razor.cs, components/menu/MenuLink.cs
=> fix(module: menu): mark state has changed after menu items were deselect

components/icon/Icon.razor.cs, components/icon/IconFont.razor.cs, components/icon/IconService.cs, tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html, tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html, tests/table/TableTests.cs
- [ x] Bug fix
检查Ant Design react的元件库，发现blazor 库的Icon的Css设定有问题。
antIcon-spin被设定在SPAN标签上了， 其实应该设定在svg上。
原来的是这样
public static string GetStyledSvg(string svgImg,  string width = "1em", string height = "1em", string fill = "currentColor", int rotate = 0)
更改为：
public static string GetStyledSvg(string svgImg, string svgClass = null, string width = "1em", string height = "1em", string fill = "currentColor", int rotate = 0)
| 🇨🇳 Chinese |    x       |
- [x ] Changelog is provided or not needed
=> fix:  the issue #762 switch loading icon has a little shift

components/menu/MenuLink.cs
=> fix(module: menu): menulink active incorrectly

components/date-picker/DatePicker.Razor.cs
| 🇺🇸 English |     fix(module: datepicker): bind-value is useless without form      |
| 🇨🇳 Chinese |     修复DatePickerBug: 在Form以外的地方使用时，bind-value无法双向绑定      |
=> fix(module: datepicker): bind-value is useless without form

components/affix/Affix.razor, components/affix/Affix.razor.cs, site/AntBlazor.Docs/Demos/Components/Affix/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Affix/doc/index.zh-CN.md
Code cleaning and updated the documentation to match the implementation.
Compiler warnings.
Code cleaning and updated the documentation to match the implementation.
| 🇺🇸 English |      Code cleaning and updated the documentation to match the implementation.     |
| 🇨🇳 Chinese |    Code cleaning and updated the documentation to match the implementation.       |
=> fix(modul: affix) code cleaning, doc update

components/avatar/Avatar.razor.cs, site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.zh-CN.md
Code cleaning and updated the documentation to match the implementation.
- Renamed Error event to OnError.
Compiler warnings, no documentation
Code cleaning and updated the documentation to match the implementation.
- Renamed Error event to OnError.
| 🇺🇸 English |  Code cleaning and updated the documentation to match the implementation. Renamed Error event to OnError        |
| 🇨🇳 Chinese | Code cleaning and updated the documentation to match the implementation. Renamed Error event to OnError          |
=> fix(module: avatar): code cleaning, doc update

README-zh_CN.md, README.md
=> docs: add template badges

components/core/Component/overlay/OverlayTrigger.razor.cs, site/AntBlazor.Docs/Demos/Components/Dropdown/demo/ContextMenu.razor, site/AntBlazor.Docs/Demos/Components/Dropdown/demo/context-menu.md
| 🇺🇸 English |     Dropdown's ContextMenu support offsetX/offsetY in net5     |
| 🇨🇳 Chinese |     Dropdown的ContextMenu模式支持offsetX/offsetY （net5版本）    |
=> feat(module: dropdown): ContextMenu support offsetX/offsetY in net5

components/calendar/Calendar.razor.cs
| 🇺🇸 English |     fix(module: calendar): method or operation is not implemented      |
| 🇨🇳 Chinese |    修复Calendar报错： method or operation is not implemented       |
- [] Changelog is provided or not needed
=> fix(module: calendar): method or operation is not implemented

components/date-picker/internal/DatePickerMonthPanel.razor, site/AntBlazor.Docs/Demos/Components/DatePicker/demo/ExtraFooter.razor
| 🇺🇸 English |      datepicker's ExtraFooter bug in month mode     |
| 🇨🇳 Chinese |     DatePicker的月份面板的ExtraFooter无法展示      |
=> fix: datepicker's ExtraFooter bug in month mode

site/AntBlazor.Docs/Demos/Components/Drawer/demo/DropdownInDrawer.razor, site/AntBlazor.Docs/Demos/Components/Drawer/demo/dropdown-in-drawer.md
| 🇺🇸 English |    docs(module: drawer): add dropdown in drawer demo       |
| 🇨🇳 Chinese |    docs(module: drawer): 添加 dropdown in drawer  示例     |
=> docs(module: drawer): add dropdown in drawer demo

components/form/Form.razor.cs, components/form/FormItem.razor.cs, site/AntBlazor.Docs/Demos/Components/Form/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/ColLayout.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/ComplexFormControl.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/ControlHooks.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/CustomizedFormControls.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/FormContext.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/IsModified.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/Loading.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/Size.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/colLayout.md
1、对于Form中的Lable和Wrapper占比设置几乎只会用到Span和Offset两个属性，所以增加了两个属性用于设置Span和Offset，这可以让代码更加易读
=> feat: simplify ColLayout

.github/workflows/gh-pages.yml
=> docs: cname to antblazor.com

components/locale-provider/LocaleProvider.cs
无
根据[i18n文档](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/i18n.zh-CN.md#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE)，LocaleProvider.SetLocale的可见性应为public。
| 🇺🇸 英文 | Change `LocaleProvider.SetLocale` to public method |
| 🇨🇳 中文 | `LocaleProvider.SetLocale` 改正为公开方法 |
=> fix(module: locale-provider): change SetLocale to public method

components/form/Form.razor, components/form/Form.razor.cs, site/AntBlazor.Docs/Demos/Components/Form/demo/CustomizedFormValidator.razor, site/AntBlazor.Docs/Demos/Components/Form/demo/customized-form-validator.md, site/AntBlazor.Docs/Demos/Components/Form/objects/CustomValidator.cs
| 🇺🇸 English | Make the form validator customizable |
| 🇨🇳 Chinese | 使表单验证器可以自定义 |
=> feat(module: form): make the form validator customizable

components/core/Component/overlay/Overlay.razor.cs, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/select/internal/SelectContent.razor
| 🇺🇸 English | Fix the behavior when Overlay is disabled. Remove clear icon when Select is disabled |
| 🇨🇳 Chinese | 修正Overlay禁用时的行为，Select禁用时不显示清空图标  |
=> Fix the behavior when Overlay is disabled. Remove clear icon when Select is disabled

components/tabs/TabPane.razor, components/tabs/TabPane.razor.cs, components/tabs/Tabs.razor, components/tabs/Tabs.razor.cs
=> fix(module: tabs): ink malposition and card tabs didn't active

components/table/ActionColumn.razor, components/table/Column.razor, components/table/ColumnBase.cs, components/table/Table.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/Basic.razor
[Issue#699](https://github.com/ant-design-blazor/ant-design-blazor/issues/699)
| 🇺🇸 English |feat(module: table): add TitleTemplate for column title|
| 🇨🇳 Chinese |功能（模块：表格）：为列标题实现自定义模板|
=> feat(module: table): add TitleTemplate for column title

components/slider/Slider.razor, components/slider/Slider.razor.cs
#859 
#864 
#855 
#865 
#868 
#867 
#855 solution as described in the issue
#864 If detected both values are changed, then the simplest solution is to reset ```_leftValue``` and ```_rightValue``` to their default min/max and let the procedure do "from scratch" evaluation
#855 In connection to described solution in the issue, there was another issue - the edges were still moving on click when a click was initiated and current active window (at least in Windows OS) was not the browser. The changes include evaluating of ```JsonElement``` data in ```OnMouseDown``` and ```OnMouseUp``` event handlers.
#868 Reverse property change refreshes styles
#867 Value property is overridden to handle the validation. New method ```SortValue``` is created to sort values inside tuple
#865 Added ```Clamp``` …
=> fix: Slider edge lock, range initial values, both range value change

components/layout/Sider.razor.cs
- [ x ] Other (about what?)
API Change
I want to be able to toggle the collapsing of the sider with some code, so this API needs to be exposed
Exposing the API to toggle should be sufficient
- [ x ] Doc is updated/provided or not needed
- [ x ] Demo is updated/provided or not needed
- [ x ] Changelog is provided or not needed
=> Expose sider togglecollapse

components/collapse/Panel.razor, components/collapse/Panel.razor.cs
=> fix(module: collapse): missing style and can not collapse

components/statistic/Statistic.razor.cs
=> fix(module: statistic): remove the redundant 0

components/tabs/Tabs.razor.cs
=> fix(module: tabs): style change dynamically

components/grid/Row.razor.cs, components/grid/RowCol.cs, site/AntBlazor.Docs/Pages/Index.razor, site/AntBlazor.Docs/Pages/Index.razor.cs, site/AntBlazor.Docs/Shared/HeaderMenu.razor, site/AntBlazor.Docs/Shared/HeaderMenu.razor.cs, site/AntBlazor.Docs/Shared/MainHeader.razor, site/AntBlazor.Docs/Shared/MainLayout.razor, site/AntBlazor.Docs/Shared/MainLayout.razor.cs, site/AntBlazor.Docs/Shared/NavMenu.razor, site/AntBlazor.Docs/style/drawer.less, site/AntBlazor.Docs/style/index.less
=> docs: make the site menu responsive

components/descriptions/Descriptions.razor
Colspan calculates error fix
| 🇺🇸 English |      Colspan calculates error fix      |
| 🇨🇳 Chinese |   修复 Colspan 计算错误        |
=> fix(module:descriptions)  Colspan calculates error fix

components/core/Base/AntDomComponentBase.cs, components/table/ActionColumn.razor, components/table/Column.razor, components/table/ColumnBase.cs, components/table/Selection.razor, components/table/Table.razor, components/table/TableSize.cs
=> 增加Table的TitleStyle，拆分开标题和内容的Style，并调整扩展列的折叠按钮居中。

components/list/ListItem.razor
=> fix(module: antlistitem) column width is overwritten by flex style

components/table/Table.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/TreeData.razor
=> fix(module: table): tree data doesn't work in asynchrony

components/timeline/Timeline.razor.cs, components/timeline/TimelineItem.cs
=> fix(module: timeline): add/remove item dynamically

components/core/JsInterop/DomEventService.cs, site/AntBlazor.Docs/Pages/Index.razor, site/AntBlazor.Docs/Pages/Index.razor.cs, site/AntBlazor.Docs/Shared/MainHeader.razor, site/AntBlazor.Docs/Shared/MainLayout.razor, site/AntBlazor.Docs/Shared/MainLayout.razor.cs
=> docs: fix header & breakpoint

site/AntBlazor.Docs/Shared/MainHeader.razor
| 🇺🇸 English |     overlayStyle should not change menu's width      |
| 🇨🇳 Chinese |    不应该用OverlayStyle设置菜单的宽度       |
=> fix(module: mainHeader): overlayStyle should not change menu's width

components/tree/IRendered.cs, components/tree/Tree.razor, components/tree/Tree.razor.cs, components/tree/TreeNode.razor, components/tree/TreeNode.razor.cs, components/tree/TreeNodeCheckbox.razor, components/tree/TreeNodeCheckbox.razor.cs, components/tree/TreeNodeSwitcher.razor, components/tree/TreeNodeSwitcher.razor.cs, components/tree/TreeNodeTitle.razor, components/tree/TreeNodeTitle.razor.cs, site/AntBlazor.Docs/Demos/Components/Tree/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/BasicControlled.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/Event.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/Line.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.md, site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/Property.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/Template.razor, site/AntBlazor.Docs/Demos/Components/Tree/demo/line.md, site/AntBlazor.Docs/Demos/Components/Tree/demo/property.md, site/AntBlazor.Docs/Demos/Components/Tree/demo/template.md
=> Tree Bug fix and New feature

.github/workflows/issue-labeled.yml
When you add `help wanted` label, the GitHub Actions will help you comment this.
| 🇺🇸 English |  -         |
| 🇨🇳 Chinese |       -    |
=> ci: create issue labeled reply

components/core/CssSizeLength.cs, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, components/table/ActionColumn.razor, components/table/Column.razor, components/table/ColumnBase.cs, components/table/ColumnContext.cs, components/table/IColumn.cs, components/table/ITable.cs, components/table/Selection.razor, components/table/Table.razor, components/table/Table.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/FixedColumns.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/FixedColumnsHeader.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/fixed-columns-header.md, site/AntBlazor.Docs/Demos/Components/Table/demo/fixed-columns.md, site/AntBlazor.Docs/Demos/Components/Table/demo/fixed-header.md
| 🇺🇸 English |   Support fixed table header and columns   |
| 🇨🇳 Chinese |  支持表头与列的固定        |
=> feat(module: table): fixed header & columns

components/cascader/Cascader.razor
=> fix(module: cascader): duplicated highlighting for the same label

components/tree/TreeIndent.razor, components/tree/TreeIndent.razor.cs, components/tree/TreeNode.razor, components/tree/TreeNode.razor.cs, components/tree/TreeNodeCheckbox.razor, components/tree/TreeNodeCheckbox.razor.cs, components/tree/TreeNodeSwitcher.razor, components/tree/TreeNodeSwitcher.razor.cs, components/tree/TreeNodeTitle.razor, components/tree/TreeNodeTitle.razor.cs
=> fix(module: tree): add missing ComponentBase

components/table/Column.razor, components/table/ColumnBase.cs, components/table/ITable.cs, components/table/Table.razor, components/table/Table.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/Ellipsis.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/FixedColumnsHeader.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/ellipsis.md
=> feat(module: table): add ellipsis column

components/button/Button.razor, components/button/Button.razor.cs
=> add StopPropagation of OnClick to Button Component

components/table/Column.razor.cs, components/table/TableModels/SortModel.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/CustomSort.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/custom-sort.md
| 🇺🇸 English | Table component add custom comparer, fix table's blazor demo |
| 🇨🇳 Chinese | 表格组件添加自定义比较器, 修复表格复刻例子 |
=> feat(module: table): add custom comparer

components/upload/Upload.razor, components/upload/Upload.razor.cs, components/upload/UploadButton.razor, components/upload/UploadButton.razor.cs, components/upload/UploadFileItem.cs, site/AntBlazor.Docs/Demos/Components/Upload/demo/Basic.razor, site/AntBlazor.Docs/Demos/Components/Upload/demo/Directory.razor, site/AntBlazor.Docs/Demos/Components/Upload/demo/PictureCard.razor
=> fix(module: upload): file list style

components/back-top/BackTop.razor, components/back-top/BackTop.razor.cs
=> fix(module: back-top): fix visible styles

components/core/Extensions/JSRuntimeExtensions.cs, components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/interop.ts, site/AntBlazor.Docs/Routing/ConventionRouter.cs
=> docs: scroll to hash anchor after pages are rendered

tests/AntDesign.Tests.csproj, tests/table/TableTests.cs, tests/tabs/TabsTests.cs
bUnit update to 1.0.0-preview-01
=> chore: bUnit update to 1.0.0-preview-01

components/core/Helpers/PropertyAccessHelper.cs, components/core/Reflection/PropertyReflector.cs, components/table/Column.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/Internal/ColumnDataIndexHelper.cs, components/table/Table.razor, components/table/TableModels/DataIndexSortModel.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/DataIndex.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/custom-sort.md, site/AntBlazor.Docs/Demos/Components/Table/demo/data-index.md
| 🇺🇸 English | add DataIndex parameter |
| 🇨🇳 Chinese | 增加DataIndex参数 |
=> feat(module: table): add DataIndex parameter

components/modal/core/Dialog.razor, components/modal/core/Dialog.razor.cs, components/modal/core/DialogWrapper.razor, components/modal/modalDialog/Modal.razor
#814
#951
| 🇺🇸 English |     fix select issue with multiple modals     |
| 🇨🇳 Chinese |     修复在多个Modal同时存在时下拉选择等弹出组件无法弹出的问题      |
=> fix: select issue with multiple modals

components/table/Column.razor.cs, components/table/Internal/ColumnDataIndexHelper.cs, components/table/Table.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/MultipleSorter.razor, site/AntBlazor.Docs/Demos/Components/Table/demo/multiple-sorter.md
=> feat(module: table): support multiple sorter

components/table/Selection.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/FixedHeader.razor
=> fix(module: table): selection was broken with scroll y

Directory.Build.props, components/AntDesign.csproj, package.json, site/AntBlazor.Docs/AntDesign.Docs.csproj, site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
| 🇺🇸 English | Standalone document generation |
| 🇨🇳 Chinese | 独立的文档生成 |
=> build: standalone document generation

components/card/Card.razor, components/card/Card.razor.cs, components/card/CardAction.razor, components/card/CardAction.razor.cs, components/grid/GridCol.cs, site/AntBlazor.Docs/Demos/Components/Card/demo/Inner.razor, site/AntBlazor.Docs/Demos/Components/Card/demo/Support.razor, site/AntBlazor.Docs/Demos/Components/Card/doc/index.en-US.md, site/AntBlazor.Docs/Demos/Components/Card/doc/index.zh-CN.md, site/AntBlazor.Docs/Shared/MainHeader.razor, site/AntBlazor.Docs/Shared/MainLayout.razor
=> feat(module: card): add a separate action component

components/tabs/Tabs.razor, components/tabs/Tabs.razor.cs
=> fix(module: tabs): ink delay change

components/image/ImagePreview.razor, components/image/ImagePreview.razor.cs, components/modal/config/DialogOptionsBase.cs, components/modal/core/Dialog.razor
| 🇺🇸 English | add animation for image preview, fix clicking mask cannot close dialog if dialog content was clicked |
| 🇨🇳 Chinese | 为 Image 预览添加动画，修复如果 Dialog 的内容被点击过，点击 mask 无法关闭 Dialog 的 bug |
=> feat(module image): add animation for image preview

components/table/Column.razor.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/head.md
=> fix(module: table): mistaken sortable

components/image/Image.razor, components/image/Image.razor.cs, components/image/ImagePreview.razor, components/image/ImagePreview.razor.cs, components/image/ImagePreviewContainer.razor, components/image/ImagePreviewContainer.razor.cs, components/image/ImagePreviewGroup.razor, components/image/ImagePreviewGroup.razor.cs, components/image/ImageRef.cs, components/image/ImageService.cs, site/AntBlazor.Docs/Demos/Components/Image/demo/PreviewGroup.razor, site/AntBlazor.Docs/Demos/Components/Image/demo/PreviewSrc.razor, site/AntBlazor.Docs/Demos/Components/Image/demo/previewGroup.md, site/AntBlazor.Docs/Demos/Components/Image/demo/previewSrc.md
=> feat(module: image): add preview group

components/image/Image.razor.cs, components/image/ImagePreview.razor, components/image/ImagePreview.razor.cs, components/image/ImagePreviewGroup.razor.cs
=> fix(module: image): disables previewing error images and hides buttons when there is only one image

components/table/Table.razor.cs
https://ant-design-blazor.gitee.io/zh-CN/components/table#components-table-demo-custom-sort
当点击排序时，报错并无反应
=> fix(module: table): sorter was blocked

components/table/Table.razor.cs
| 🇺🇸 English |   fix the scroll position calculate method        |
| 🇨🇳 Chinese |   修复滚动位置计算的方法        |
=> fix(module: table): fix the scroll position calculate method

components/layout/Sider.razor.cs, components/menu/Menu.razor.cs, site/AntBlazor.Docs/Demos/Components/Layout/demo/Side.razor
| 🇺🇸 English |  fix the menu can't collapse follow the sider    |
| 🇨🇳 Chinese |  修复菜单不能跟随Sider侧边栏收起的问题         |
=> fix(menu): collapsed follow sider

components/steps/Step.razor, components/steps/Step.razor.cs, components/steps/Steps.razor.cs
| 🇺🇸 English |   Fix steps wrong progress style     |
| 🇨🇳 Chinese |     修复 Steps 进度条样式      |
=> fix(module: steps): wrong progress style

components/menu/Menu.razor.cs, components/menu/MenuItem.razor.cs, components/menu/SubMenu.razor.cs
| 🇺🇸 English |    add inline indent parameter       |
| 🇨🇳 Chinese |    菜单增加   inline indent 属性    |
=> feat(module: menu): add inline indent parameter

components/table/TableModels/SortModel.cs, site/AntBlazor.Docs/Demos/Components/Table/demo/MultipleSorter.razor
| 🇺🇸 English |  fix missing value for the sort property of SortModel         |
| 🇨🇳 Chinese |    修复SortModel中丢失的Sort属性值       |
=> fix(module: table): missing value for the sort property of SortModel

.github/workflows/algolia-config.json, .github/workflows/docsearch.yml, .github/workflows/gh-pages.yml, components/anchor/Anchor.razor, components/anchor/AnchorLink.razor, components/core/JsInterop/InteropService.cs, site/AntBlazor.Docs/Pages/Index.razor.cs, site/AntBlazor.Docs/Routing/ConventionRouter.cs, site/AntBlazor.Docs/Shared/CodeBox.razor, site/AntBlazor.Docs/Shared/GithubButton.razor.cs, site/AntBlazor.Docs/Shared/HeaderMenu.razor, site/AntBlazor.Docs/wwwroot/js/docsearch.js
=> docs: fix anchor and improvement

components/menu/SubMenu.razor.cs
#1133 
| 🇺🇸 English |    Nav Menu Collapse Unresponsive       |
| 🇨🇳 Chinese |    导航菜单折叠无响应       |
=> fix: Nav Menu Collapse Unresponsive

components/select/Select.razor.cs
#1160 
Perf optimization: `Select` for tags was calling `ClearSelect()` twice when "ENTER" was pressed.
=> fix(module:select): click to select on new tag

components/message/type/MessageAnimationType.cs, components/modal/type/ModalAnimation.cs, components/notification/type/AnimationType.cs
| 🇺🇸 English |  fix: animation classs name change of Modal, Message and Notification componments   |
| 🇨🇳 Chinese |  修复 Modal、Message 和 Notification 组件与 AntD 官方的 class 不一致的问题 |
=> fix: animation classs name change of Modal, Message and Notification componments

components/table/Table.razor.cs
=> fix(module: table): tree data error

components/table/Column.razor
| 🇺🇸 English |   Fix expand row can't be expanded        |
| 🇨🇳 Chinese | 修复expand row不能展开的问题          |
=> fix(module: table): doesn't refresh when expand row

components/table/ITable.cs, components/table/Table.razor.cs, components/table/TableModels/QueryModel.cs
| 🇺🇸 English |  add `GetQueryModel` method        |
| 🇨🇳 Chinese |   增加 `GetQueryModel` 方法        |
=> feat(module: table): add a method to get query model

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> changelog: 0.7.1

.github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml, .github/workflows/preview-start.yml
=> chore: add github actions for auto preview

components/table/Column.razor.cs, components/table/ITable.cs, components/table/Table.razor.cs
`OnExpan` event was missing in comparison to antd (and I needed it :smirk:).
| 🇺🇸 English |  Added event handler `OnExpand`.       |
=> feat(module:table): add OnExpand event

components/divider/Divider.razor, components/divider/Divider.razor.cs, site/AntDesign.Docs/Demos/Components/Divider/demo/Without.razor
=> fix(module: divider): style was default to plain

components/badge/Badge.razor, components/badge/Badge.razor.cs, site/AntDesign.Docs/Demos/Components/Badge/demo/Change.razor, site/AntDesign.Docs/Demos/Components/Badge/demo/Colorful.razor, site/AntDesign.Docs/Demos/Components/Badge/demo/NoWrapper.razor, site/AntDesign.Docs/Demos/Components/Badge/demo/no-wrapper.md
=> fix(module: badge): color behaviour

.github/workflows/preview-build.yml, site/AntDesign.Docs/Pages/Components.razor, site/AntDesign.Docs/Pages/Components.razor.cs, site/AntDesign.Docs/Pages/Docs.razor, site/AntDesign.Docs/Pages/Docs.razor.cs, site/AntDesign.Docs/Shared/CodeBox.razor, site/AntDesign.Docs/Shared/ContributorsList.razor, site/AntDesign.Docs/Shared/ContributorsList.razor.cs
=> docs: add contributors list

components/table/ColumnBase.cs, components/table/ITable.cs, components/table/SummaryCell.razor, components/table/SummaryRow.razor, components/table/Table.razor, components/table/Table.razor.cs, site/AntDesign.Docs/Demos/Components/Table/demo/Summary.razor, site/AntDesign.Docs/Demos/Components/Table/demo/summary.md
| 🇺🇸 English |     add summary row       |
| 🇨🇳 Chinese |    增加总结行       |
=> feat(module: table): add summary

components/core/Component/overlay/OverlayTrigger.razor.cs, components/table/Column.razor
| 🇺🇸 English |     fix: clicking on a blank space couldn't close filter panel      |
| 🇨🇳 Chinese |     修复：点击空白地方无法关闭筛选面板     |
=> fix(module: column): clicking on a blank space couldn't close filter panel

components/auto-complete/AutoComplete.razor, components/back-top/BackTop.razor.cs, components/cascader/Cascader.razor, components/core/Component/overlay/OverlayTrigger.razor.cs, components/date-picker/DatePicker.razor, components/date-picker/RangePicker.razor, components/menu/SubMenu.razor.cs, components/popconfirm/Popconfirm.razor.cs, components/popover/Popover.razor.cs, components/select/Select.razor, components/tooltip/Tooltip.razor.cs, site/AntDesign.Docs/Demos/Components/Popover/demo/Placement.razor
| 🇺🇸 English | Add class prefix to slide-up and zoom-big animation to fix animation |
| 🇨🇳 Chinese | 补充slide-up和zoom-big动画前缀，修复动画失效问题 |
=> Fix animation

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> changelog: 0.7.2

components/cascader/Cascader.razor, components/cascader/Cascader.razor.cs
| 🇺🇸 English |   Fix an issue where the style attribute could not affect the style of the cascader        |
| 🇨🇳 Chinese |   修复不能通过style属性影响cascader的样式的问题        |
=> fix(module: cascader): style and class properties

LICENSE, README-zh_CN.md, README.md, components/AntDesign.csproj, site/AntDesign.Docs/Shared/MainFooter.razor
=> add the copyright of .NET Foundation

components/tree/TreeNode.razor
#1163 
为了改善性能问题，在`[CascadingParameter]`添加了`IsFixed`属性造成的问题，目前为了功能能正常使用，先把`IsFixed`属性去掉了，之后的性能优化问题在后续特性跟新中进行。
| 🇨🇳 Chinese |    修正节点无法展开的问题      |
=> bug: The correction tree does not expand correctly

components/core/Component/overlay/type/PlacementType.cs
=> fix(module: dropdown): Animations for down and up are inverse

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> changelog 0.7.3

components/table/ActionColumn.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/Table.razor.cs
=> (fix) Table ExpandableRow not working with ActionColumn #1284

components/form/FormItem.razor, components/form/FormItem.razor.cs, site/AntDesign.Docs/Demos/Components/Form/demo/CustomizedLabel.razor, site/AntDesign.Docs/Demos/Components/Form/demo/complex-form-control.md, site/AntDesign.Docs/Demos/Components/Form/demo/customized-label.md
=> #1287 Added LabelTemplate in FormItem

site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj, site/AntDesign.Docs.Server/Pages/_Host.cshtml, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj, site/AntDesign.Docs/AntDesign.Docs.csproj, tests/grid/ColTests.cs
=> docs: add changelog in document

components/table/Table.razor.cs
#1288 
| 🇺🇸 English | fix table re-render when ScrollX is set |
| 🇨🇳 Chinese | 修复设置ScrollX时表格不重新渲染的问题 |
=> fix(module: table): fix table re-render when ScrollX is set

site/AntDesign.Docs/Demos/Components/Table/demo/RouterPagging.razor, site/AntDesign.Docs/Demos/Components/Table/demo/router-pagging.md
| 🇺🇸 English | fix Table RouterPagging demo |
| 🇨🇳 Chinese | 修复表格路由分页示例 |
=> docs(module: table): fix RouterPagging demo

components/core/Direction.cs, components/core/DirectionVHType.cs, components/divider/Divider.razor.cs, components/space/Space.razor, components/space/Space.razor.cs, components/space/SpaceItem.razor, components/space/SpaceItem.razor.cs, components/typography/Link.cs, site/AntDesign.Docs/Demos/Components/Divider/demo/Vertical.razor, site/AntDesign.Docs/Demos/Components/Image/demo/Placeholder.razor, site/AntDesign.Docs/Demos/Components/Space/demo/Align.razor, site/AntDesign.Docs/Demos/Components/Space/demo/Customize.razor, site/AntDesign.Docs/Demos/Components/Space/demo/Split.razor, site/AntDesign.Docs/Demos/Components/Space/demo/Vertical.razor, site/AntDesign.Docs/Demos/Components/Space/demo/Wrap.razor, site/AntDesign.Docs/Demos/Components/Space/demo/align.md, site/AntDesign.Docs/Demos/Components/Space/demo/split.md, site/AntDesign.Docs/Demos/Components/Space/demo/wrap.md, site/AntDesign.Docs/Demos/Components/Space/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Space/doc/index.zh-CN.md, site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Table/demo/Size.razor
=> feat(module: space): add wrap,split and size array

scripts/gh-pages/index.html, site/AntDesign.Docs.Wasm/wwwroot/index.html, site/AntDesign.Docs.WasmHost/Pages/_Host.cshtml
=> docs: fix default css link

components/core/Component/overlay/OverlayTrigger.razor.cs
Bug from copy-paste. Incorrect method was removed from event handler during disposal.
=> fix(module:overlaytrigger): correct method disposal

components/table/Column.razor.cs, components/table/ColumnBase.cs
PR #1303 caused code duplication with PR #1208. This fixes this issue.
=> feat(module:table): bring PR1208 to PR1303 merge master into feature

components/pagination/Pagination.razor, components/pagination/Pagination.razor.cs, site/AntDesign.Docs/Demos/Components/Pagination/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Pagination/doc/index.zh-CN.md
| 🇺🇸 English | add TotalBoundaryShowSizeChanger parameter |
| 🇨🇳 Chinese | 添加TotalBoundaryShowSizeChanger参数 |
=> feat(module: pagination): add TotalBoundaryShowSizeChanger parameter

components/result/Result.razor.cs, site/AntDesign.Docs/Demos/Components/Result/demo/ChangeTheResult.razor, site/AntDesign.Docs/Demos/Components/Result/demo/changeTheResult.md
=> fix(module:result): modify status unsuccessfully after initialization(#1328)

components/table/Table.razor
Fixes #1339
So a constant reminder, that if you won't do something quickly, it is likely you are going to forget about it...
This fix should have been applied immediately after [this](https://github.com/ant-design-blazor/ant-design-blazor/pull/1304/files#r606704414) review concluded. This PR addresses that.
=> fix(module:table): Table tree children limit remove

site/AntDesign.Docs/Demos/Components/Form/demo/IsModified.razor
Fixes #1333
The issue is a dupe of #1139.
@Hona, since this is still confusing, I decided to make a PR for that documentation, so hopefully this won't come back. If you are continuing work on #1131, please include my change.
=> docs(module:form): IsModified sample fix

components/date-picker/DatePicker.Razor.cs, components/date-picker/RangePicker.razor.cs
=> fix(module:datepicker): OnChange invoke after typing

components/affix/Affix.razor.cs, site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.md, site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.razor, site/AntDesign.Docs/Demos/Components/Affix/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Affix/doc/index.zh-CN.md
=> fix(module: affix): affix to the viewport (#1327)

components/core/Component/overlay/OverlayTrigger.razor.cs, components/core/Component/overlay/type/PlacementType.cs
=> fix(module: tooltip): wrong popup direction

components/locales/en-GB.json, components/locales/pl-PL.json, components/table/TableLocale.cs
Crashing exceptions whenever locale set to something else than zn-CH or en-US.
Applied same solutions as in PR #1054 - added defaults (taken from en-US).
Included translations in en-GB & pl-PL for the missing fields. 
=> fix(module:table): locale fix

components/table/Column.razor.cs
=> fix(module: table): incorrect bool filter

components/drawer/Drawer.razor, components/drawer/Drawer.razor.cs
=> fix(module:drawer): z-index has effect

components/affix/Affix.razor, components/affix/Affix.razor.cs, site/AntDesign.Docs/Demos/Components/Affix/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.razor
=> fix(module: affix): can't affix while OffsetTop is zero

components/input/Input.cs, components/input/TextArea.razor.cs
| 🇺🇸 English |  fix binding data when the Enter key is pressed        |
| 🇨🇳 Chinese |  修复按回车键的数据绑定问题          |
=> fix(module: input): binding data when the Enter key is pressed

components/table/Table.razor.cs
=> fix(module: table): ellipsis can't work

components/table/Internal/ColumnExpressionHelper.cs
fixes https://github.com/ant-design-blazor/ant-design-blazor/issues/1381
| 🇺🇸 English | fix the problem of using not nullable property with DataIndex nullable mode |
| 🇨🇳 Chinese | 修复Column组件无法为不可为空的属性使用DataIndex可空模式的问题 |
=> fix(module:table): can not use DataIndex nullable mode with not nullable property

components/table/Column.razor.cs
fixes https://github.com/ant-design-blazor/ant-design-blazor/issues/1384
| 🇺🇸 English | fix column header sorter not refresh after ClearSorter is called |
| 🇨🇳 Chinese | 修复清除排序方向后列头排序状态不刷新的问题 |
=> fix(module:table): column header sorter not refresh after ClearSorter is called

components/tag/Tag.razor, components/tag/Tag.razor.cs, site/AntDesign.Docs/Demos/Components/Tag/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Tag/demo/Checkable.razor, site/AntDesign.Docs/Demos/Components/Tag/demo/Controlled.razor, site/AntDesign.Docs/Demos/Components/Tag/demo/Dynamic.razor, site/AntDesign.Docs/Demos/Components/Tag/demo/Event.razor, site/AntDesign.Docs/Demos/Components/Tag/demo/Hot.razor, site/AntDesign.Docs/Demos/Components/Tag/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Tag/doc/index.zh-CN.md
| 🇺🇸 English |   `Mode` was deleted, use `Closable` and `Checkable` instead.      |
| 🇨🇳 Chinese |   `Mode` 属性被删除了，请用 `Closable` 或 `Checkable` 替代          |
=> fix(module: tag): closable typo and delete mode

components/table/Table.razor, components/table/Table.razor.Pagination.cs, site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Table/demo/CustomPagination.razor, site/AntDesign.Docs/Demos/Components/Table/demo/custom-pagination.md
=> #1366 Allow custom pagination template

components/table/Column.razor, components/table/ColumnBase.cs, site/AntDesign.Docs/Demos/Components/Table/demo/ToggleColumn.razor, site/AntDesign.Docs/Demos/Components/Table/demo/toggle-column.md
=> #1346 Columns Show/Hide functionality

components/table/Column.razor.cs
=> fix(module: table): check null in set sorter method

components/cascader/Cascader.razor.cs, tests/AntDesign.Tests/Cascader/CascaderTests.razor
=> fix(module: cascader): incorrect size

components/cascader/Cascader.razor.cs, components/core/Base/AntInputComponentBase.cs, site/AntDesign.Docs/Demos/Components/Cascader/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Change.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Default.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Disabled.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Hover.razor, site/AntDesign.Docs/_Imports.razor
=> fix(module: cascader): add SelectedNodesChanged and invoke it after clear selected

components/core/Helpers/THelper.cs, components/select/SelectOption.razor.cs
fixes #1450
| 🇺🇸 English | fix error for nullable TItem of SelectOption |
| 🇨🇳 Chinese | 修复在SelectOption中使用可空值类型时的错误 |
=> fix(module:select): fix error for nullable TItem

components/checkbox/Checkbox.razor.cs, components/core/Base/AntInputBoolComponentBase.cs, tests/AntDesign.Tests/Checkbox/CheckboxTests.razor
=> fix(module:checkbox): remove Value initialization blocking

components/modal/core/Dialog.razor.cs
#1414 
| 🇺🇸 English | modify Delay time  of Dialog componment  to DOM_ MIN_ TIMEOUT_ VALUE (4ms)  |
| 🇨🇳 Chinese |  修改 Dialog 组件中 Mask 点击判断 Task.Delay 的时间为 DOM_ MIN_ TIMEOUT_ VALUE (4ms) |
=> fix(module: Dialog): modify Delay time to DOM_ MIN_ TIMEOUT_ VALUE (4ms) 

components/cascader/Cascader.razor, components/cascader/Cascader.razor.cs, components/cascader/CascaderNode.cs, site/AntDesign.Docs/Demos/Components/Cascader/demo/Search_.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/search.md
| 🇺🇸 English |  cascader support showSearch         |
| 🇨🇳 Chinese |  cascader  支持搜索         |
=> feat(module: cascader): support showSearch

components/input-number/InputNumber.razor
Fixes #1489 
Added `onmouseoutevent` handlers
https://user-images.githubusercontent.com/12235437/117531512-a0585c80-af97-11eb-9229-ee63a324340a.mp4
=> fix(module:inputnumber): Fix input number self changing

site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
#1441
| 🇺🇸 English |  Add detailed description for Draggable parameter |
| 🇨🇳 Chinese |   添为 Draggable 添加详细说明        |
=> docs: update modal docs (#1441)

components/table/Column.razor
=> fix(module: table): fix built-in filter select option width

site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor
#1481 
| 🇺🇸 English | update ‘fork official sample’ demo to enable the sorters |
| 🇨🇳 Chinese | 更新“复刻官方示例”示例以使排序可用 |
=> docs(module: table): update ‘fork official sample’ demo

components/input-number/InputNumber.razor.cs, tests/AntDesign.Tests/InputNumber/InputNumberTests.razor
Fixes #1545 
Reintroduced `Parser` check & usage.
Added regression test.
=> fix(module:inputnumber): include parser in value evaluation

docs/getting-started.en-US.md
The article is missing the dependency registration. If these dependencies are not registered, the library couldn't be used (at least in my case).
=> Added essential step in get started procedure

components/date-picker/DatePicker.Razor.cs, components/date-picker/RangePicker.razor.cs, components/date-picker/internal/DatePickerBase.cs, site/AntDesign.Docs/Demos/Components/DatePicker/demo/Format.razor, site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.zh-CN.md
1. Fixes #1582
2. Format demo does not clear on clear button press:
Expected behavior:
1. Exposed eventcallback `OnClearClick` (same as already existing in `DatePickerInput`)
2. Altered demo to align with react docs.
| 🇺🇸 English |  DatePicker / RangePicker: Add OnClearClick eventcallback         |
=> feat(module:datepicker): Picker clear button event

components/table/Column.razor
=> refactor(module:table): optimize render fragments

components/table/Column.razor, components/table/Column.razor.cs
Fixes #1601
| 🇺🇸 English | fix can not close filter by confirm button |
| 🇨🇳 Chinese | 修复点击筛选器确定按钮筛选器面板不关闭的问题 |
=> fix(module:table): fix can not close filter by confirm button

components/table/Column.razor
Fixes #1593
| 🇺🇸 English | fix the issue that filters are not applied when close the filter panel by clicking filter icon area |
| 🇨🇳 Chinese | 修复点击筛选图标关闭筛选器面板时不应用筛选操作的问题 |
=> fix(module:table): fix filter not applied

components/table/Column.razor, components/table/Column.razor.cs
In #1563, I change `Table.FIlters` to `IEnumerable<TableFilter>` type, it's better to change it back.
| 🇺🇸 English | (not needed) |
| 🇨🇳 Chinese | (不需要在changelog中体现) |
=> refactor(module:table): restore Table.Filters to IEnumerable<TableFilter> type

components/input-number/InputNumber.razor.cs
Fixes #1610
| 🇺🇸 English | fix the exception which is throwed when an InputNumber component for nullable type loses focus |
| 🇨🇳 Chinese | 修复可空类型的InputNumber组件失去焦点时抛出的异常 |
=> fix(module:input-number): fix error when blur

components/affix/Affix.razor.cs
=> fix(affix): remove wrong event listeners

components/select/internal/SelectItemPropertyHelper.cs, site/AntDesign.Docs/Demos/Components/Drawer/demo/DropdownInDrawer.razor, site/AntDesign.Docs/Demos/Components/Drawer/demo/drawer_service.md, site/AntDesign.Docs/Demos/Components/Modal/ModalTemplateDemo.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_confirm.md, site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_modal.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md
| 🇺🇸 English |  update modal and drawer docs    |
| 🇨🇳 Chinese |    update modal and drawer docs  |
=> docs: update modal and drawer docs

components/table/Selection.razor, components/table/Selection.razor.cs, components/table/Table.razor, components/table/Table.razor.Selection.cs, components/table/TableModels/RowData.cs, site/AntDesign.Docs/Demos/Components/Table/demo/RowSelection_.razor
Fixes #1370 
Fixes #1585 
Fixes #1619 
Fixes #1622
=> fix(module:table): fix selection issues

components/checkbox/CheckboxGroup.razor
Fixes #1633
| 🇺🇸 English | fix in-form behavior of CheckboxGroup component  |
| 🇨🇳 Chinese | 修复CheckboxGroup组件不能在Form中使用的问题 |
=> fix(module:checkbox): fix checkbox group in-form behavior

components/image/Image.razor, components/image/Image.razor.cs, site/AntDesign.Docs/Demos/Components/Image/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Image/doc/index.zh-CN.md
fixed https://github.com/ant-design-blazor/ant-design-blazor/discussions/1641
=> fix(module: image): fix the style property postion

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> changelog 0.8.2

components/grid/Col.razor.cs, components/grid/Row.razor, components/grid/Row.razor.cs
| 🇺🇸 English |   gutter adjustment on col initialize        |
| 🇨🇳 Chinese |  修复Grid的Col在初始化时的默认间距调整         |
=> fix(module: grid): gutter adjustment on col initialize

site/AntDesign.Docs/Demos/Components/Form/demo/AdvancedSearch.razor, site/AntDesign.Docs/Demos/Components/Form/demo/advanced-search.md
| 🇺🇸 English |   add advanced search demo        |
| 🇨🇳 Chinese |   增加 form 的高级搜索 demo        |
=> feat(module: form): add advanced search demo

components/core/Base/AntInputComponentBase.cs, components/form/Form.razor.cs, components/form/FormItem.razor.cs, components/form/Internal/IForm.cs
Fixes #1661
| 🇺🇸 English | allow to use input components without bind-Value attribute inside customized form control |
=> fix(module: form): fix input components inside customized form control

.github/workflows/nightly-build-AOT.yml, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
#1572
NOTE: 
- user must install net6 to build source if merged
- It will cose about 26-30 mins in github action to build a AOT docs site
| 🇺🇸 English |  Enlable AOT in docs site         |
=> Add files to enable AOT in docs site

components/date-picker/internal/DatePickerDatePanel.razor, components/date-picker/internal/DatePickerDatetimePanel.razor, components/date-picker/internal/DatePickerTemplate.razor, components/date-picker/internal/DatePickerTemplate.razor.cs
Fixes #1646
| 🇺🇸 English | fix low datetime error |
=> fix(module:date-picker): fix low datetime error

components/table/Column.razor, components/table/Column.razor.cs
Fixes #1665
| 🇺🇸 English | allow set filters after table initialization |
| 🇨🇳 Chinese | 允许在表格初始化之后设置筛选器 |
=> fix(module:table): allow set filters after table initialization

components/checkbox/Checkbox.razor.cs
#1688 
Remove redundant class to fix checkbox not being vertically centred.
| 🇺🇸 English | remove redundant class |
| 🇨🇳 Chinese | 删除多余的class |
=> fix(module: checkbox): remove redundant class

components/table/Column.razor
Fixes #1501
| 🇺🇸 English | fix the bug that changing filter and/or operator closes the filter dropdown |
| 🇨🇳 Chinese | 修复选择筛选器的 与/或 条件会关闭筛选器面板的错误 |
=> fix(module:table): add PopupContainerSelector for filter and/or selector

tests/AntDesign.TestKit/AntDesign.TestKit.csproj, tests/AntDesign.Tests/Checkbox/CheckboxGroupTests.razor, tests/AntDesign.Tests/Checkbox/CheckboxTests.razor
=> fix(module: checkbox): fix the test following up PR #1689

components/tabs/Reuse/IReuseTabsPage.cs, components/tabs/Reuse/ReuseTabs.razor, components/tabs/Reuse/ReuseTabs.razor.cs, components/tabs/Reuse/ReuseTabsPageItem.cs, components/tabs/Reuse/ReuseTabsPageTitleAttribute.cs, components/tabs/Reuse/ReuseTabsRouteView.cs
=> feat(module: tabs): add reuse tabs routeview

components/core/Component/Overlay/Overlay.razor, components/core/Component/Overlay/Overlay.razor.cs, components/core/Component/Overlay/OverlayTrigger.razor, components/core/Component/Overlay/OverlayTrigger.razor.cs, components/dropdown/Dropdown.razor, components/menu/internal/SubMenuTrigger.razor, components/popconfirm/Popconfirm.razor, components/popover/Popover.razor, components/tooltip/Tooltip.razor
Fixes #1690
| 🇺🇸 English | OnMaskClick event will fire correctly when the overlay size changes |
| 🇨🇳 Chinese | 当弹出层大小改变时会触发OnMaskClick事件 |
=> fix(module:overlay): better judge whether mouse is inside the overlay when click

components/tabs/Reuse/ReuseTabs.razor
The exception is `Delegate to an instance method cannot have null 'this'`. Related the official issue https://github.com/dotnet/aspnetcore/issues/10270
=> fix(module: tabs): Exception caused by cascade assignment to TabTemplate

components/empty/EmptyLocale.cs, components/form/FormLocale.cs, components/icon/IconLocale.cs, components/image/ImageLocale.cs, components/locale-provider/GlobalLocale.cs, components/locale-provider/Locale.cs, components/modal/confirmDialog/ConfirmLocale.cs, components/modal/modalDialog/ModalLocale.cs, components/page-header/PageHeaderLocale.cs, components/popconfirm/PopconfirmLocale.cs, components/table/TableLocale.cs, components/time-picker/TimePickerLocale.cs, components/transfer/TransferLocale.cs, components/typography/TextLocale.cs, components/upload/UploadLocale.cs
#1707
#1556
| 🇨🇳 Chinese | 当资源文件中节点缺失时，使用默认值，不抛出运行时异常 |
=> fix(module:locale-provider): add missing nodes default values

components/locales/ru-RU.json
Based on https://github.com/ant-design-blazor/ant-design-blazor/issues/1707
Based on https://github.com/ant-design-blazor/ant-design-blazor/issues/1707
=> Russian locale resources additions

components/upload/UploadFileItem.cs
UploadFileItem.GetResponse Provide default configuration: ignore case
=> UploadFileItem Provide default configuration: ignore case

components/tree/Tree.razor.cs
There was no method for checking all items in a tree.
**Added support for checking all items in a Tree from code.** 
| 🇺🇸 English |   Added support for checking all items in a Tree from code.        |
=> feat(module: tree): support check all from code

components/core/Feedback/FeedbackComponent.cs, components/core/Feedback/IFeedbackRef.cs, components/core/Feedback/IOkCancelRef.cs, components/drawer/DrawerContainer.razor.cs, components/modal/config/IModalTemplate.cs, components/modal/confirmDialog/ComfirmContainer.razor.cs, components/modal/confirmDialog/ConfirmRef.cs, components/modal/modalDialog/ModalContainer.razor.cs, components/modal/modalDialog/ModalRef.cs, site/AntDesign.Docs/Demos/Components/Drawer/DrawerTemplateDemo.razor, site/AntDesign.Docs/Demos/Components/Modal/ConfirmTemplateDemo.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_confirm.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_modal.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_confirm.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
Add example for #1643 
| 🇺🇸 English |  Modal and Drawer render reducing, update document and demo   |
| 🇨🇳 Chinese |   Modal and Drawer 组件减少重复渲染，进行文档和demo的更新   |
=> Modal and Drawer render reducing and update document and demo 

AntDesign.sln, components/AntDesign.csproj, site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj, site/AntDesign.Docs.Build/AntDesign.Docs.Build.csproj, site/AntDesign.Docs/AntDesign.Docs.csproj
=> chore: refactor the build process

components/modal/core/Dialog.razor, components/modal/core/Dialog.razor.cs
The last fix was merged into the feature branch, so this fix wants to be merged into the feature branch
| 🇺🇸 English |  fix: click dialog cause the mask click event triggered   |
| 🇨🇳 Chinese |     修复dialog点击导致mask的点击事件被触发的bug      |
=> fix: click dialog cause the mask click event triggered

site/AntDesign.Docs/Demos/Components/Table/demo/EditRow.razor
=> fix(module: table): edit row demo can't recovery the editing on cancel

components/core/Helpers/EnumHelper.cs, components/select/EnumSelect.cs, components/table/Column.razor
1. Change `Column` code to use enum select for table filter
2. Allow to use nullable enum type with enum select
| 🇺🇸 English | (nothing) |
=> refactor(module:table): use enum select for table filter

components/select/Select.razor.cs
Fixes #1784
| 🇺🇸 English | remove ValueName null check for non-datasource approach |
=> fix(module: select): remove ValueName null check for non-datasource approach

components/table/ActionColumn.razor, components/table/Column.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/Table.razor.cs, components/table/style/entry.less, components/table/style/patch.less, site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md
| 🇺🇸 English |     support responsive      |
| 🇨🇳 Chinese |     增加响应式模式      |
=> feat(model: table): support responsive

components/table/Column.razor.cs, components/table/ITable.cs, components/table/Table.razor.cs
=> fix(module: table): missing sorter model on first change

components/core/JsInterop/modules/components/uploadHelper.ts
On upload button click, the file picker dialog was not opening.
Fixes in `uploadHelper.ts` - missing event & remove event `preventDefault()`.
=> fix(module:upload): basic functionality restored

components/table/Column.razor.cs
| 🇺🇸 English | use "or" filter condition for List type built-in filter |
=> fix(module:table): use "or" filter condition for List type built-in filter

components/auto-complete/AutoCompleteInput.cs, components/auto-complete/AutoCompleteSearch.cs, components/auto-complete/IAutoCompleteInput.cs, components/input/Input.cs
=> fix(module: auto-complete): turn off the input `autocomplete` attribute

components/input-number/InputNumber.razor.cs
=> fix(module: input-number): `OnChange` cannot be triggered during keyboard input

components/date-picker/internal/DatePickerBase.cs, components/table/Column.razor
Fixes #1806
| 🇺🇸 English | allow to set time in the filter |
=> fix(module:table): fix datetime built-in filter

components/table/Column.razor.cs, components/table/ITable.cs, components/table/Table.razor.cs
| 🇺🇸 English |   fix initial load and render         |
| 🇨🇳 Chinese |   修复服务端模式初次加载时不触发OnChange的问题        |
=> fix(module: table): fix initial load and render

components/radio/ButtonStyle.cs, components/radio/RadioGroup.razor, components/radio/RadioGroup.razor.cs, components/radio/RadioOption.cs, site/AntDesign.Docs/Demos/Components/Icon/demo/List.razor, site/AntDesign.Docs/Demos/Components/Radio/demo/Button_.razor, site/AntDesign.Docs/Demos/Components/Radio/demo/Optional.razor
| 🇺🇸 English |   add options property for `RadioGroup`    |
| 🇨🇳 Chinese |   `RadioGroup` 增加 options 属性       |
Breaking Change:  The type of `ButtonStyle` change to `RadioButtonStyle` enum.
=> feat(module: radio): add `Options` for `RadioGroup`

components/checkbox/CheckboxGroup.razor.cs, site/AntDesign.Docs/Demos/Components/Checkbox/demo/Group.razor
| 🇺🇸 English |   fixed  checked state didn't follow the value change      |
| 🇨🇳 Chinese |  修复当Value被修改时，对应选项未选中的问题        |
=> fix(module: checkbox): checked state didn't follow the value change

components/image/Image.razor, components/image/Image.razor.cs, components/image/ImagePreviewGroup.razor.cs, components/image/ImageRef.cs, site/AntDesign.Docs/Demos/Components/Image/demo/PreviewGroupVisible.razor, site/AntDesign.Docs/Demos/Components/Image/demo/preview-group-visible.md, site/AntDesign.Docs/Demos/Components/Image/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Image/doc/index.zh-CN.md
=> feat(module: image): support preview visible

components/tag/Tag.razor.cs, tests/AntDesign.Tests/Tag/TagTests.razor
https://github.com/ant-design-blazor/ant-design-blazor/issues/1846
Change the timing of calling `GetStyle`
| 🇺🇸 English |      fix Tag component style parameters are not rendered     |
| 🇨🇳 Chinese |     修复Tag组件Style参数设置无效      |
=> fix(module: tag): Tag component style parameters are not rendered (#1846)

components/tree/Tree.razor.cs, components/tree/TreeNodeTitle.razor.cs, site/AntDesign.Docs/Demos/Components/Tree/demo/Basic.razor
=> fix(module: tree): SelectedNodeChanged would be fired twice twice

components/table/Column.razor
=> fix(module: table): prevent propagation of expand button click events

components/table/Column.razor.cs, components/table/ColumnContext.cs, site/AntDesign.Docs/Demos/Components/Table/demo/Ajax.razor
=> fix(module: table): avoid `OnChange` being called multiple times during initialization

components/table/Table.razor.cs
=> fix(module: table): didn't refresh when using client side data source

CONTRIBUTING.md
=> docs(CONTRIBUTING.md): update CONTRIBUTING

components/table/Table.razor.cs
Fixes `Table filter and sort does not work` #1874  
As of version `0.9.2` table filtering and sorting does not work.
The call of `StateHasChanged()` was missed in `InternalRender()` method
N/A
| 🇺🇸 English |   Call `StateHasChanged` from `InternalRender()` method        |
=> fix(module: table):call StateHasChanged in InternalRender (#1874)

components/table/ActionColumn.razor.cs, components/table/Selection.razor.cs
Fixed an issue where a table would not automatically load after initialization when an ActionColumn was used.
=> fix(module: table): not automatically load with ActionColumn

site/AntDesign.Docs/Demos/Components/Table/demo/NestedTable.razor, site/AntDesign.Docs/Demos/Components/Table/demo/nested-table.md
=> feat(module: table): add nested table demo

components/core/JsInterop/modules/components/modalHelper.ts, components/modal/config/ConfirmOptions.cs, components/modal/confirmDialog/Confirm.razor, components/modal/confirmDialog/Confirm.razor.cs, components/modal/core/Dialog.razor, components/modal/core/Dialog.razor.cs, components/modal/modalDialog/Modal.razor.cs
#1762 
| 🇺🇸 English |  fix Modal and Confirm cannot auto focus |
| 🇨🇳 Chinese |   修复 Modal 和 Confirm 无法自动focus的bug      |
=> fix Modal and Confirm cannot auto focus

components/table/Column.razor
#1856 add a new kind of datetime filter operator: same date operator. When change the operator, the `ShowTime` property of `DatePicker` component is changed between `true` and `false`. However, this is not enough because the input format doesn't change with the operator.
the effect of this pr:
| 🇺🇸 English | (nothing, #1856 is merged after 0.9.2 version) |
=> fix(module:table): fix the format issue of datetime samedate filter

components/tree/Tree.razor, components/tree/Tree.razor.cs, components/tree/TreeNode.razor, components/tree/TreeNode.razor.cs, site/AntDesign.Docs/Demos/Components/Tree/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/CustomizedIcon.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/Directory.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/Line.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/SwitcherIcon.razor
Allow user set tree nodes directly.
=> feat(module: tree): add ChildContent for Tree and TreeNode

components/core/JsInterop/JSInteropConstants.cs, components/core/JsInterop/modules/components/tableHelper.ts, components/table/Table.razor, components/table/Table.razor.cs
=> pref(module: table): put fixed column style into js

README-zh_CN.md, README.md
I wanted to develop locally, but when I started the Server `npm run start:wasm` it failed because the assets were not built yet.
=> Add Building Demo Assets To the Readme for Local Development

components/table/ActionColumn.razor, components/table/Column.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/Selection.razor, components/table/SummaryCell.razor, components/table/TableModels/CellData.cs, site/AntDesign.Docs/Demos/Components/Table/demo/Expand.razor, site/AntDesign.Docs/Demos/Components/Table/demo/OnRowAndOnCell.razor
=> feat(module: table): add `CellData` for `CellRender`

site/AntDesign.Docs/Demos/Components/Card/doc/index.en-US.md
| 🇺🇸 English | Updated typo, changed `ard` -> `Card`         |
=> Fixed typo

tests/AntDesign.Tests/Select/Actions/Select.ClearTests.razor, tests/AntDesign.Tests/Select/Actions/Select.OnDataSourceChangeTests.razor
=> Add some unit tests for Select

components/input/TextArea.razor
Wrong event got `stopPropagation`.
Corrected the `onclick:stopPropagation` to `onchange:stopPropagation`.
=> fix(module:textarea): replace wrong event

components/menu/MenuItem.razor, site/AntDesign.Docs/Demos/Components/Menu/demo/InlineCollapsed.razor
=> fix(module: menu): collapsed menu title can't hide while use router link

components/affix/Affix.razor.cs, components/core/JsInterop/Window.cs, components/grid/Row.razor.cs, components/layout/BreakpointType.cs, components/layout/Sider.razor.cs, components/list/AntList.razor, components/list/AntList.razor.cs, components/list/IAntList.cs, components/list/ListItem.razor, components/list/ListItem.razor.cs, site/AntDesign.Docs/Demos/Components/Grid/demo/UseBreakpoint.razor, site/AntDesign.Docs/Demos/Components/List/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/List/demo/Grid.razor, site/AntDesign.Docs/Demos/Components/List/demo/Resposive.razor
=> fix(module: list): resposive style doesn't work

components/timeline/Timeline.razor, components/timeline/Timeline.razor.cs, components/timeline/TimelineItem.cs, components/timeline/TimelineMode.cs, site/AntDesign.Docs/Demos/Components/Timeline/demo/Alternate.razor, site/AntDesign.Docs/Demos/Components/Timeline/demo/Label.razor, site/AntDesign.Docs/Demos/Components/Timeline/demo/Right.razor, tests/AntDesign.Tests/Timeline/TimelineTests.razor
#1929 
| 🇺🇸 English |   fix missing Label parameter      |
| 🇨🇳 Chinese |  修复 Label  属性       |
Breaking changes:
Change the type of  `Mode` to `TimelineMode`
=> fix(module: timeline): label missing

.github/workflows/nightly-build-AOT.yml, .github/workflows/preview-build.yml, .github/workflows/release.yml, site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
=> docs: update to .NET6 RC1

components/select/Select.razor.cs, components/select/SelectBase.cs
=> correct select DefaultValue xml comment

components/table/Column.razor
=>  fix(module: table): label display incorrectly in responsive mode

site/AntDesign.Docs/Demos/Components/Button/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Block.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Danger.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Disabled.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Ghost.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Icon_.razor, site/AntDesign.Docs/Demos/Components/Button/demo/LegacyGroup.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Loading.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Multiple.razor, site/AntDesign.Docs/Demos/Components/Button/demo/Size.razor
=> Cleanup button docs

components/table/ActionColumn.razor.cs, components/table/Column.razor, components/table/Column.razor.cs, components/table/ISelectionColumn.cs, components/table/ITableRow.cs, components/table/Selection.razor, components/table/Selection.razor.cs, components/table/Table.razor, components/table/Table.razor.RowData.cs, components/table/Table.razor.Selection.cs, components/table/Table.razor.cs, components/table/TableRow.razor
Fixes #1911
| 🇺🇸 English | improve selection performance |
=> perf(module:table): improve table selection

components/slider/Slider.razor.cs, site/AntDesign.Docs/Demos/Components/Slider/demo/Basic.razor
https://github.com/ant-design-blazor/ant-design-blazor/issues/1898
When the Minimum of the Slider is not set to 0 (e.g. 15), the slider is empty up until the Minimum is reached. To fix/update this, the Slider needs to take the Minimum and Maximum into account when calculating the positioning of the slider's handles.
I show how this may be able to be implemented. Some open questions are, should this be configurable? What is the apprpriate behavior? 
This PR also fixes some initialization issues when passing in Parameters to the Slider. Calls `SetStyle` in `OnInitialized` so two way binding initializes correctly
This is still a work in progress, but wanted to get some initial thoughts. Thanks!
| 🇨🇳 Chinese | …
=> Slider Positioning Using Min/Max

components/descriptions/Descriptions.razor
=> fix(module: descriptions): header styles

README.md
| 🇺🇸 English | Changed project short description and fixed incorrect information in readme.|
=> Improved project readme and details 

components/tree/Tree.razor.cs
When set `CheckedKeys` the check status is not updated. So need to fix it.
=> fix(module: tree)：Update check status when set [CheckedKeys] property

site/AntDesign.Docs/Demos/Components/List/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/List/demo/Loadmore.razor
| 🇺🇸 English | update the demos to use avatar template |
=> docs(module:list): update the demos to use avatar template

site/AntDesign.Docs/Demos/Components/Form/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Form/doc/index.zh-CN.md
Supplement the API documentation section about Form
| 🇺🇸 English |      Improve the API part about Form in the component document.   |
| 🇨🇳 Chinese |      完善组件文档中关于Form的API部分     |
=> Improve the API part about Form in the component document

docs/faq.en-US.md
- #1822
- #732
Add explanation on how to use CSS isolation with AntDesign Blazor components.
=> docs(faq): CSS isolation explanation

components/tree/Tree.razor.cs, components/tree/TreeNodeTitle.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/Line.razor, site/AntDesign.Docs/Demos/Components/Tree/demo/Search_.razor
fixed #2012 
fixed #2037 
fixed #2055 
fixed #2061
=> fix(module: tree): nodes would collapses when SearchValue was set

components/core/JsInterop/modules/dom/manipulationHelper.ts
#2207
| 🇺🇸 English |   fix: wrong width when without scroll bar  |
| 🇨🇳 Chinese |    修复没有滚动条时错误的宽带设置       |
=> fix: wrong width when without scroll bar

site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md
Supplement the API documentation section about Table
| 🇺🇸 English |      Improve the API part about Table in the component document.   |
| 🇨🇳 Chinese |      完善组件文档中关于Table的API部分     |
=> Improve the API part about Table in the component document

components/table/Table.razor, components/table/Table.razor.Pagination.cs, site/AntDesign.Docs/Demos/Components/Table/demo/CustomPagination.razor
| 🇨🇳 Chinese | 允许在定义PaginationTemplate时使用组件内置逻辑 |
=> feat(module:table): improve pagination template

components/pagination/Pagination.razor, components/pagination/PaginationOptions.razor.cs
Use same Locale for Pagination and PaginationOptions, part of #1747
| 🇺🇸 English | Use same Locale for Pagination and PaginationOptions |
=> fix(module:pagination): Use same Locale for Pagination and PaginationOptions

components/pagination/Pagination.razor.cs, components/pagination/PaginationSize.cs, components/table/Table.razor, components/table/TableSize.cs, site/AntDesign.Docs/Demos/Components/Pagination/demo/Mini.razor
part of #1747
| 🇺🇸 English | use small size `Pagination` for compacted table; **Breaking change:** change `Pagination.Size` to enum type |
=> feat(module:table&pagination): use small size Pagination for compacted table, add PaginationSize enum type

site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md, site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md
Supplement the API documentation section about Table
| 🇺🇸 English |      Improve the API part about Input and Select in the component document.   |
| 🇨🇳 Chinese |      完善组件文档中关于Input和Select组件的API部分     |
=> Improve the documentation of the API section of the Input and Select component

components/locales/cs-CZ.json
=> Fix incorrect order of czech week days in datepicker

components/core/Helpers/Formatter.cs, components/table/ActionColumn.razor.cs, components/table/Column.razor, components/table/Column.razor.cs, components/table/ColumnBase.cs, components/table/Selection.razor.cs, components/table/SummaryCell.razor, components/table/TableModels/CellData.cs, site/AntDesign.Docs/Demos/Components/Table/demo/DataIndex.razor
=> feat(module: table): allow access field value from `CellRender` context

AntDesign.sln, components/modal/config/DialogOptions.cs, components/modal/config/ModalOptions.cs, components/modal/core/Dialog.razor, components/modal/core/Dialog.razor.cs, components/modal/modalDialog/Modal.razor.cs, site/AntDesign.Docs/Demos/Components/Modal/demo/FormInModal.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/MaxBodyHeight.razor, site/AntDesign.Docs/Demos/Components/Modal/demo/form-in-modal.md, site/AntDesign.Docs/Demos/Components/Modal/demo/max-body-height.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
#2254
| 🇺🇸 English |  Modal最大内容高度设置  |
| 🇨🇳 Chinese | Modal max content body set supported    |
=> feat(module Modal): max content body height support

components/upload/UploadButton.razor, tests/AntDesign.Tests/Upload/UploadTests.razor
Implements the mentioned solution in issue #1969.
Replace <div> element with <span> as suggested in issue. Tested in components view (see screenshot) and adjusted test cases to reflect changes of structure.
=> fix(module:upload): Fix center layout of upload

components/anchor/Anchor.razor.cs, components/core/Base/AntComponentBase.cs, components/core/Component/Overlay/Overlay.razor.cs, components/core/Extensions/JSRuntimeExtensions.cs, components/core/JsInterop/InteropService.cs, components/descriptions/Descriptions.razor.cs, components/mentions/Mentions.razor.cs, components/menu/SubMenu.razor.cs, components/message/MessageResult.cs, components/pagination/Pagination.razor.cs, components/skeleton/Skeleton.razor.cs
#2161 #2210 
Code contained a lot of `Console.WriteLine` calls, which are all only used for debugging. They should not leave the development environment. Other than that, they should be replaced by injecting `ILogger` and using the `LogDebug` method on it. `Console.WriteLine` is not supported on all platforms which could lead to issues.
I removed all `Console.WriteLine` calls (or commented them out if I thought they would be used later again). I did not implement any `ILogger`, if it's necessary later it can still be added.
| 🇺🇸 English | X          |
=> Remove 'Console.WriteLine' calls in code

site/AntDesign.Docs/Demos/Components/Upload/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Upload/doc/index.zh-CN.md
Supplemental minimal api implementation
| 🇺🇸 English |     Supplemental minimal api implementation      |
| 🇨🇳 Chinese |     添加最小api实现参考      |
=> Improve the upload component FQ part

components/image/ImagePreview.razor
#2269
| 🇺🇸 English |    fix: image cannot be centered vertically    |
| 🇨🇳 Chinese |     修复图片无法居中      |
=> fix(module image): image cannot be centered vertically (#2269)

components/core/Component/Overlay/Overlay.razor.cs
I have found redundant (judging by git history) 'else' in Overlay.razor.cs code 
=> fix - redundant else

.github/workflows/release-AOT.yml
=> remove jsdelivr assets for gitee site

components/badge/Badge.razor.cs, components/badge/style/entry.less, components/badge/style/patch.less
| 🇺🇸 English |   remove the gap of numbers        |
| 🇨🇳 Chinese |  修复 Badge 数字间的间隙         |
=> fix(module: badge): remove the gap of numbers

components/tree/Tree.razor.cs
fixed. issues #2260, The tree component causes the browser to crash
=> fixed. issues #2260

components/tabs/Tabs.razor, tests/AntDesign.TestApp/Client/AntDesign.TestApp.Client.csproj, tests/AntDesign.TestApp/Client/Pages/Counter.razor, tests/AntDesign.TestApp/Server/AntDesign.TestApp.Server.csproj, tests/AntDesign.TestApp/Server/Data/ApplicationDbContext.cs
fixed #2083
| 🇺🇸 English |  fixed TabTemplate can't display in the overflow dropdown        |
| 🇨🇳 Chinese |   修复  Tab数量超出范围时 TabTemplate 不能显示在 dropdown  中的问题       |
=> fix(module: tabs): TabTemplate can't display in the overflow dropdown

components/core/Reflection/PropertyReflector.cs
=> fix(module: input): throw exception when binding a list item.

components/upload/UploadButton.razor, tests/AntDesign.Tests/Upload/UploadTests.razor
=> fix(module: upload): wrong drag area

components/cascader/Cascader.razor.cs
=> fix(module: cascader): dropdown can't open correctly on click.

AntDesign.sln, scripts/gh-pages/index.html, site/AntDesign.Docs/Demos/Components/Input/demo/WithTooltip.razor, site/AntDesign.Docs/Shared/ContributorsList.razor.cs
Reverts ant-design-blazor/ant-design-blazor#2374
=> Revert "docs: fix broken CDN"

.github/workflows/release-AOT.yml, scripts/print-changelog.js
=> docs: fix gitee ci

components/tree/Tree.razor.cs, components/tree/TreeNode.razor.cs
fixed #2384
提升展开大量下级节点操作的运行效率
由 luckcheer (1050400225@qq.com 敬天乐事) 修改, 本人帮忙提交
=> Optimize the speed of expanding nodes 

package.json
=> chore: fix security alert

components/table/Table.razor.cs, site/AntDesign.Docs/Demos/Components/Table/demo/ResponsiveMode.razor, site/AntDesign.Docs/Demos/Components/Table/demo/responsive-mode.md
| 🇺🇸 English |   make Responsive default to false   (with a breaking change)      |
| 🇨🇳 Chinese |   修改  Responsive 属性默认值为false，需要响应式样式时需要设为true       |
=> refactor(module: table): make Responsive default to false (with a breaking change)

site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs, site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs, site/AntDesign.Docs/AntDesign.Docs.csproj, site/AntDesign.Docs/Demos/Experimental/Introduce/doc/index.en-US.md, site/AntDesign.Docs/Demos/Experimental/Introduce/doc/index.zh-CN.md, site/AntDesign.Docs/Pages/Components.razor, site/AntDesign.Docs/Pages/Components.razor.cs, site/AntDesign.Docs/Services/DemoService.cs, site/Shared/DemoComponent.cs
=> docs: add experimental category

components/tree/TreeNodeTitle.razor, scripts/gitee-pages/index.html
fixed #2362 
| 🇨🇳 Chinese |  修复 Tree 节点含有 \| 字符，并且 SearchVaule 搜索 \| 时的显示异常问题         |
=> fix(module: tree): the display of the problem when nodetitle and searchvalue contains '|' at the same time

components/menu/MenuItem.razor, site/AntDesign.Docs/Demos/Components/Menu/demo/IconTemplate.razor
=> fix(module: menu): IconTemplate does not work in MenuItem of SubMenu

AntDesign.sln, components/affix/Affix.razor.cs, components/anchor/Anchor.razor.cs, components/carousel/Carousel.razor.cs, components/core/Component/Overlay/Overlay.razor.cs, components/core/Component/Overlay/OverlayTrigger.razor.cs, components/core/JsInterop/DomEventListener.cs, components/core/JsInterop/IDomEventListener.cs, components/descriptions/Descriptions.razor.cs, components/grid/Row.razor.cs, components/input/TextArea.razor.cs, components/layout/Sider.razor.cs, components/list/ListItem.razor.cs, components/select/Select.razor.cs, components/select/internal/SelectContent.razor.cs, components/slider/Slider.razor.cs, components/table/Table.razor.cs
=> fix(module: table): null exception cause by event listener

scripts/gh-pages/index.html, scripts/gitee-pages/index.html, site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj, site/AntDesign.Docs.Server/Pages/_Host.cshtml, site/AntDesign.Docs.Wasm/wwwroot/index.html, site/AntDesign.Docs/Services/DemoService.cs, site/AntDesign.Docs/Shared/HeaderMenu.razor, site/AntDesign.Docs/Shared/HeaderMenu.razor.cs, site/AntDesign.Docs/Shared/MainHeader.razor, site/AntDesign.Docs/Shared/MainLayout.razor.cs, site/AntDesign.Docs/wwwroot/js/docsearch.js
=> docs: update docsearch 3

components/upload/UploadButton.razor.cs, site/AntDesign.Docs/Demos/Components/Upload/demo/InputFile_.razor, site/AntDesign.Docs/Demos/Components/Upload/demo/input-file.md
| 🇨🇳 Chinese |  支持结合原生 InputFile 组件         |
=> feat(module: upload): support build-in InputFilie

components/table/ITable.cs, components/table/Table.razor, components/table/Table.razor.cs, components/table/style/patch.less, site/AntDesign.Docs/Demos/Components/Table/demo/FixedColumnsHeader.razor, site/AntDesign.Docs/Demos/Components/Table/demo/fixed-columns-header.md, site/AntDesign.Docs/Demos/Components/Table/demo/fixed-columns.md, site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md
| 🇺🇸 English |   support setting table scrollbar width using `ScrollBarWidth` parameter        |
| 🇨🇳 Chinese |   支持用表格的   `ScrollBarWidth` 来设置滚动条的宽度     |
=> feat(module: table): support setting table scrollbar width using `ScrollBarWidth` parameter

site/AntDesign.Docs/Pages/Components.razor.cs
=> docs: fix exception cause by hash url

components/cascader/Cascader.razor.cs
=> fix(module: cascader): Avoid adding items in search list in a loop

components/core/JsInterop/modules/components/tableHelper.ts
=> fix(module: table): exception caused by js interop with `addEventListener`

components/select/Select.razor.cs, tests/AntDesign.TestKit/AntDesign.TestKit.csproj, tests/AntDesign.Tests/Select/Actions/Select.OnDataSourceChange.Tests.razor
…ments was not in the right order
#2439 
=> fix(module: select): replacing a datasource with some of the same items was not in the right order

scripts/gh-pages/index.html
=> docs: remove loading .br files

scripts/gh-pages/staticwebapp.config.json
=> chore: add swa config

components/table/style/patch.less
=> fix(module: table): too length content in responsive mode will brace up the table

components/date-picker/internal/DatePickerTemplate.razor
=> 修复DatePicker

.github/workflows/nightly-build.yml, .github/workflows/pr-preview.yml, package.json
=> chore: fix publish target framework

components/tree/Tree.razor.cs, components/tree/TreeNode.razor.cs
| 🇺🇸 English |   Fixed incorrect checking during initialization        |
| 🇨🇳 Chinese | 修复初始化时 checkbox 不能正常选中的问题          |
=> fix(module: tree): incorrect checking during initialization

site/AntDesign.Docs/Demos/Components/Radio/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Radio/doc/index.zh-CN.md
=> docs: update docs for radio

components/icon/Icon.razor.cs
=> fix twotone icon infinite re-render

package.json
=> chore: fix Dependabot alert

README.md
Issue #2546 
1. Git clone link in the readme is not updated.
2. I updated the link using the link given by @ElderJames in the Issue #2546 
| 🇺🇸 English |The git clone link is not working. Newbies using this repo is getting discourage because of this.|
=> Updated the git clone link

components/date-picker/internal/DatePickerBase.cs, components/date-picker/internal/DatePickerHeader.razor, components/date-picker/internal/DatePickerYearPanel.razor, tests/AntDesign.Tests/DatePicker/DatePickerTests.razor
Fixes https://github.com/ant-design-blazor/ant-design-blazor/issues/2378
=> fix:(module: datepicker):  culture is not applied correctly to the year

components/timeline/Timeline.razor.cs
| 🇺🇸 English |     fix issue #2271     |
| 🇨🇳 Chinese |     修复TimeLine的pending无法关闭的问题      |
=> fix(module: TimeLine): Unable to disable pending

components/image/Image.razor, components/image/Image.razor.cs, site/AntDesign.Docs/Demos/Components/Image/demo/ControlledPreview.razor, site/AntDesign.Docs/Demos/Components/Image/demo/controlled-preview.md
| 🇺🇸 English |   support controlled preview        |
| 🇨🇳 Chinese |   支持可控预览        |
=> feat(module: image): support controlled preview

components/core/Component/Overlay/OverlayTrigger.razor.cs
| 🇺🇸 English |  fixed right-click trigger can't open browser native menu         |
| 🇨🇳 Chinese |   修复 Trigger 右键不能打开浏览器菜单的问题        |
=> fix(module: overlay): right-click trigger can't open browser native menu

components/core/Component/ResizeObserver/ResizeObserver.cs
=> feat: add ResizeObserver component

components/page-header/PageHeader.razor, components/page-header/PageHeader.razor.cs
=> faet(module: PageHeader): support compact style

components/badge/Badge.razor, components/badge/Badge.razor.cs, components/badge/style/patch.less
=> fix(module: badge): show/hide montion optimization

components/cascader/Cascader.razor.cs
| 🇺🇸 English |    Fix bug that the cascade component cannot use allowclear to clear the content when searching    #2607   |
| 🇨🇳 Chinese |       修复Cascader组件在搜索时无法使用AllowClear清除内容的问题  #2607  |
=> fix(module: cascader): cannot use allowclear to clear the content when searching

components/cascader/Cascader.razor, components/cascader/Cascader.razor.cs, site/AntDesign.Docs/Demos/Components/Cascader/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Change.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Default.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Disabled.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Hover.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Search_.razor, site/AntDesign.Docs/Demos/Components/Cascader/demo/Size.razor, tests/AntDesign.Tests/Cascader/CascaderTests.razor
=> fix(module: cascader): Style confusion caused by the latest antd style

components/select/Select.razor.cs, site/AntDesign.Docs/Demos/Components/Form/demo/ControlHooks.razor
=> fix(select): select was not highlighted when validation failed

tests/AntDesign.Tests/Alert/AlertTests.cs
Adding code test coverage for Alert component
=> Add tests for alert component

tests/AntDesign.Tests/Comment/CommentTests.cs
#2644 
Adding test coverage - Comment component
=> test(module: comment): Add tests for component

components/tabs/Reuse/ReuseTabsRouteView.cs
=> fix(module: reusetabs): Invalid URI exception

.github/workflows/sonar.yml
=> chore: add sonar action

site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs, site/AntDesign.Docs/Pages/Components.razor.cs
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/2535
=> docs: fix demo & document edit url

components/tabs/Reuse/ReuseTabsRouteView.cs
=> fix(module: reusetabs): invaild uri exception

components/collapse/Panel.razor
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/2662
=> fix(module: collapse): fix outdated html structures

.github/workflows/sonar.yml
=> chore: fix sonar action trigger

components/table/Table.razor.cs, site/AntDesign.Docs/Demos/Components/Table/demo/RestoreQueryState.razor, site/AntDesign.Docs/Demos/Components/Table/demo/restore-query-state.md
=> fix(module: table): exception cause by reload data with state and the table has an ActionColumn

.github/workflows/nightly-build.yml
=> chore: fix test step for nightly build action

site/AntDesign.Docs/Demos/Components/Alert/demo/ErrorBoundaryDemo.razor, site/AntDesign.Docs/Demos/Components/Alert/demo/error-boundary.md, site/AntDesign.Docs/Demos/Components/Result/demo/ErrorBoundaryDemo.razor, site/AntDesign.Docs/Demos/Components/Result/demo/error-boundary.md
=> docs: add error boundary demos for Alert and Result

components/grid/GridRow.cs, site/AntDesign.Docs/Demos/Components/Grid/demo/Basic.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Flex.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/FlexAlign.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/FlexOrder.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/FlexStretch.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Gutter.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Offset.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Playground.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Responsive.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/ResponsiveMore.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/Sort.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/UseBreakpoint.razor, site/AntDesign.Docs/Demos/Components/Grid/demo/basic.md, site/AntDesign.Docs/Demos/Components/Grid/demo/flex-stretch.md, site/AntDesign.Docs/Demos/Components/Grid/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Grid/doc/index.zh-CN.md
=> feat(module: grid): create Row alias GridRow to be consistent with GridCol

site/AntDesign.Docs/Demos/Components/Notification/demo/ErrorBoundaryDemo.razor, site/AntDesign.Docs/Demos/Components/Notification/demo/error-boundary.md
=> docs: add Notification Error Handling demo

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
=> Changelog 0.12.3

components/table/TableModels/SortModel.cs
=> fix (module: table): rectify how to check if an IQueryable is IOrderedQueryable

components/select/Select.razor.cs
=> fix(module: select): remove redundant CreateDeleteSelectOptions() calls in render cycles (#2657)

components/table/Selection.razor, components/table/Selection.razor.cs
=> fix (module: selection): method typo

components/table/Selection.razor, components/table/Selection.razor.cs
=> feat(module: table): set value for table header checkbox Disabled attribute

components/core/CssSizeLength.cs, components/core/Helpers/CssStyleBuilder.cs, components/table/ColumnBase.cs, tests/AntDesign.Tests/Core/CssSizeLengthTests.cs, tests/AntDesign.Tests/Core/Helpers/CssStyleBuilderTests.cs
| 🇺🇸 English | Optimize `CssSizeLength` & `CssStyleBuilder` |
| 🇨🇳 Chinese | 优化`CssSizeLength` 和`CssStyleBuilder` |
=> perf: Optimize `CssSizeLength` & `CssStyleBuilder`

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md
| 🇺🇸 English |    Add Changelog for 0.12.7       |
| 🇨🇳 Chinese |    更新 0.12.7 版本的Changelog       |
=> changelog 0.12.7

site/AntDesign.Docs.Wasm/Program.cs
=> docs: fix Globalization crash

components/input/Input.cs, site/AntDesign.Docs/Demos/Components/Input/demo/BindOnInput.razor, site/AntDesign.Docs/Demos/Components/Input/demo/bind-on-input.md, site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md, site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md, tests/AntDesign.Tests/Input/InputTests.razor
=> refactor(module: input): rename to `BindOnInput`

components/table/Table.razor.cs
#2900 
| 🇺🇸 English |    修复 Table 设置HidePagination导致的无限循环       |
| 🇨🇳 Chinese |   Fixed Table infinite loop when `HidePagination` was set       |
=> fix(module: table): infinite loop when `HidePagination` was set

site/AntDesign.Docs.Server/Program.cs, site/AntDesign.Docs/Resources/en-US.json, site/AntDesign.Docs/Resources/zh-CN.json, site/AntDesign.Docs/wwwroot/data/products.json
=> docs: fix BlazorPolyfill error on .net7

components/table/Table.razor.cs
=> fix(module: table):  Infinite loop when `HidePagination` and `PageSize` were set at the same time and datasource is empty.
