- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
> docs: remove useless dependencies

- components/table/ActionColumn.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor
fixed #2871 
| 🇺🇸 English |  Fixed Table `Hidden` parameter for ActionColumn doesn't work        |
| 🇨🇳 Chinese |   修复 Table 的 ActionColumn 上的  `Hidden` 属性不起作用的问题       |
> fix(module: table): `Hidden` parameter for ActionColumn doesn't work

- components/input-number/InputNumber.razor.cs
fixed #2829
| 🇺🇸 English |    Fixed InputNumber triggering a constant Increase/Decrease in certain scenarios       |
| 🇨🇳 Chinese |   修复 InputNumber 在某些场景下触发不停 Increase/Decrease 的问题        |
> fix(module: inputnumber): Fixed an issue triggering a constant Increase/Decrease in certain scenarios

- CHANGELOG.en-US.md
- components/AntDesign.csproj
- components/input/Input.cs
> fix(module: input): remove the debug content

- components/core/JsInterop/modules/dom/eventHelper.ts
fixed #2976 
| 🇺🇸 English |  fix tabs close exception, remove dispose call after event listener is removed       |
| 🇨🇳 Chinese |   修复 Tabs 关闭异常，移除了js 中对引用对象的 Dispose 调用        |
> fix(module: event listener): remove dispose call after event listener is removed

- components/tabs/Tabs.razor.cs
fixed #2732
| 🇺🇸 English |  Fixed Tabs avoid exception when the first TabPane is set Disabled       |
| 🇨🇳 Chinese |    修复 Tabs 当第一个TabPane设置了 Disabled 后，首次渲染异常的问题       |
> fix(module: tabs): avoid exception when the first TabPane is set Disabled

- components/auto-complete/AutoComplete.razor
- components/auto-complete/AutoComplete.razor.cs
- components/auto-complete/AutoCompleteInput.cs
- components/auto-complete/AutoCompleteSearch.cs
- components/auto-complete/IAutoCompleteRef.cs
- components/input/Input.cs
- components/input/TextArea.razor.cs
fixed #869 
| 🇺🇸 English |   fixed the composition and debounce  for input       |
| 🇨🇳 Chinese |   修复 输入框的拼写会话和防抖        |
> fix(module: auto-complete): support input composition and debounce

- components/auto-complete/AutoComplete.razor.cs
- components/auto-complete/AutoCompleteInput.cs
fixed #2895
| 🇺🇸 English |   fixed auto-complete dropdown would open when page was render     |
| 🇨🇳 Chinese |   修复 AutoComplete  在页面刷新时自动打开       |
> fix(module: auto-complete): dropdown would open when page was render

- components/select/Select.razor.cs
- components/select/SelectBase.cs
- components/tree-select/TreeSelect.razor
fixed #2987
| 🇺🇸 English |  fix select   dropdown boundary adjust mode defult to InView      |
| 🇨🇳 Chinese |   修复 Select 下拉列表的边界调整模式为InView        |
> fix(module: select): dropdown boundary adjust mode defult to InView

- components/transfer/Transfer.razor.cs
- components/transfer/TransferItem.cs
fixed #534
| 🇺🇸 English |   Fixed Transfer DataSource refresh        |
| 🇨🇳 Chinese |   修复 Transfer DataSource 的刷新        |
> fix(module: transfer): DataSource refresh

- components/cascader/Cascader.razor
- components/cascader/Cascader.razor.cs
- components/core/Base/AntInputComponentBase.cs
- components/date-picker/DatePicker.razor
- components/date-picker/RangePicker.razor
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
- components/date-picker/internal/DatePickerInput.razor
- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- components/form/Internal/IFormItem.cs
- components/icon/Icon.razor.cs
- components/icon/IconService.cs
- components/input-number/InputNumber.razor
- components/input-number/InputNumber.razor.cs
- components/input/Input.cs
- components/input/InputPassword.razor.cs
- components/input/TextArea.razor
- components/input/TextArea.razor.cs
- components/select/Select.razor.cs
- components/select/SelectBase.cs
- components/select/internal/SelectContent.razor
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/ValidateStatic.razor
- tests/AntDesign.Tests/Input/TextAreaTests.razor
fixed #2361
fixed #2560
fixed #2429
| 🇺🇸 English |    Fixed Form validation status styles   |
| 🇨🇳 Chinese |   修复 Form 自定义校验的样式      |
> fix(module: form): validation status styles

- components/descriptions/Descriptions.razor.cs
fix 2230 More invalid messages of Descriptions in Console
https://github.com/ant-design-blazor/ant-design-blazor/issues/2230
> fix 2230 More invalid messages of Descriptions in Console

- components/input-number/InputNumber.razor
- components/input-number/InputNumber.razor.cs
fixed #3017
fixed #3014
| 🇺🇸 English |    Fixed InputNumber step rollback and null reference exception       |
| 🇨🇳 Chinese |  修复  InputNumber 的 Step 回退和空引用异常        |
> fix(module: InputNumber): avoid step rollback and null reference exception

- components/input-number/InputNumber.razor.cs
- site/AntDesign.Docs/Demos/Components/InputNumber/demo/Borderless.razor
- site/AntDesign.Docs/Demos/Components/InputNumber/demo/borderless.md
fixed #2804
| 🇺🇸 English |   Add  InputNumber borderless  style  |
| 🇨🇳 Chinese |  增加  InputNumber 无边框样式       |
> feat(module: InputNumber): support borderless

- components/radio/RadioGroup.razor.cs
| 🇺🇸 English |    Add Radio cascading type parameter for RadioGroup      |
| 🇨🇳 Chinese |  新增 Radio 的 RadioGroup 级联类型参数         |
> feat(module: radio): add cascading type parameter for RadioGroup

- components/table/ActionColumn.razor
- components/table/Column.razor
fixed #2836
| 🇺🇸 English |  Fixed Table  column title align incorrectly when filterable      |
| 🇨🇳 Chinese |  修复 Table 列标题在可筛选时的对齐样式问题         |
> fix(module: table): column title align incorrectly when filterable

- components/alert/Alert.razor.cs
- components/core/Component/Overlay/Overlay.razor.cs
- components/core/Component/Overlay/type/PlacementType.cs
- components/core/JsInterop/HtmlElement.cs
- components/date-picker/internal/DatePickerBase.cs
- components/menu/SubMenu.razor
- components/menu/SubMenu.razor.cs
- components/menu/internal/SubMenuTrigger.razor
- components/menu/internal/SubMenuTrigger.razor.cs
- components/tabs/Tabs.razor.cs
- tests/AntDesign.Tests/Menu/Menu.Horizontal.Tests.razor
- tests/AntDesign.Tests/Menu/Menu.Inline.Tests.razor
fixed #1246 
| 🇺🇸 English |   Fixed Menu submenu montion & style        |
| 🇨🇳 Chinese |     修复 Menu 子菜单的动画和样式      |
> fix(module: menu): submenu montion & style

- components/table/Table.razor
- components/table/Table.razor.cs
fixed #1317
| 🇺🇸 English |    Add Table empty template parameter and make it fixed while column scrolling       |
| 🇨🇳 Chinese |    增加 Table  空状态模板，并使它在列滚动时固定     |
> feat(module: table): add empty template parameter and make it fixed while column scrolling

- components/menu/SubMenu.razor
- components/menu/SubMenu.razor.cs
follow up #2096 
fixed #2095
| 🇺🇸 English |  Add Menu the PopupClassName parameter         |
| 🇨🇳 Chinese |   增加 Menu 的 PopupClassName 属性        |
> feat(module:menu): Add PopupClassName Property For SubMenu

- components/input/Input.cs
- components/input/TextArea.razor.cs
- site/AntDesign.Docs/Demos/Components/Input/demo/ShowCount.razor
- site/AntDesign.Docs/Demos/Components/Input/demo/show-count.md
fixed #2770 
| 🇺🇸 English |     Add Input ShowCount      |
| 🇨🇳 Chinese |     增加 Input 的 ShowCount      |
> feat(module: input): add ShowCount

- components/drawer/Drawer.razor.cs
#3045
| 🇺🇸 English |   fix(module: drawer): drawer-mask-close-immediately  |
| 🇨🇳 Chinese |       修复 drawer 遮罩层不能立即关闭的问题   |
> fix(module: drawer): drawer-mask-close-immediately (#3045)

- components/calendar/Calendar.razor.cs
- components/card/Card.razor.cs
- components/layout/Sider.razor.cs
- components/page-header/PageHeader.razor.cs
- components/radio/Radio.razor.cs
#2968 #2964 #2962 #2961 #2936 
| 🇺🇸 English |  Marked multiple redundant parameters as obsolete for future removal: `Calendar.OnSelect`, `Card.Body`, `Sider.OnCollapse`, `PageHeader.PageHeaderTitle`, `PageHeader.PageHeaderSubtitle`, `Radio.CheckedChange` |
| 🇨🇳 Chinese | 将多个冗余参数标记为已过时以供将来删除: `Calendar.OnSelect`, `Card.Body`, `Sider.OnCollapse`, `PageHeader.PageHeaderTitle`, `PageHeader.PageHeaderSubtitle`, `Radio.CheckedChange` |
> Mark redundant parameters as obsolete for future removal

- components/tabs/Reuse/ReuseTabsRouteView.cs
- src/AntDesign.Components.Authentication/AuthorizeReuseTabsRouteView.cs
| 🇺🇸 English |    reusetabs keep obsoleted usage       |
| 🇨🇳 Chinese |   reusetabs 保留之前的用法        |
> fix(module: tabs): reusetabs keep obsoleted usage

- components/tabs/Reuse/ReuseTabs.razor.cs
> fix(module: tabs): reusetabs null reference exception

- components/menu/SubMenu.razor.cs
fixed #3062
| 🇺🇸 English |   Fixed Menu incorrect submenu styles in RTL language        |
| 🇨🇳 Chinese |  修复 Menu 在RTL语言中错误的子菜单样式         |
> fix(module: menu): incorrect submenu styles in RTL language

- components/core/Helpers/DateHelper.cs
- tests/AntDesign.Tests/DatePicker/DatePickerTests.razor
#3061 
Wrote test and fixed bug in DatePicker.
| 🇺🇸 English | DatePicker |
| 🇨🇳 Chinese |     DatePicker     |
> Wrong selected date in the Calendar component #3061 fixed

- components/menu/MenuItem.razor
- components/menu/MenuItem.razor.cs
- components/menu/SubMenu.razor
- components/menu/SubMenu.razor.cs
> fix(module: menu): title padding direction in RTL language

- components/core/Extensions/ServiceCollectionExtensions.cs
- components/modal/confirmDialog/ConfirmService.cs
- components/modal/confirmDialog/IConfirmService.cs
- site/AntDesign.Docs/Demos/Components/Drawer/demo/Drawer_event.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/Confirm_Service.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/OverrideLocale.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/confirm_service.md
- site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/Tag/demo/Event.razor
> refactor(module:confirm): update ConfirmService to use interface

- components/pagination/Pagination.razor
- components/pagination/Pagination.razor.cs
#3071 
| 🇺🇸 English |  Fixed Pagination jump button icon direction in RTL language       |
| 🇨🇳 Chinese |   修复 Pagination 在RTL模式跳转按钮图标的方向        |
> fix(module: pagination): button icon direction in RTL language

- components/table/Table.razor
- components/table/Table.razor.Pagination.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/CustomPagination.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/PaginationDemo.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/TreeDataWithCircularReference.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/custom-pagination.md
- site/AntDesign.Docs/Demos/Components/Table/demo/pagination.md
fixed #3071 
| 🇺🇸 English |   Fixed Table default pagination position in RTL language        |
| 🇨🇳 Chinese |   修复 Table 分页器在 RTL 语言下的默认位置        |
> fix(module: table): pagination position in RTL language

- components/pagination/Pagination.razor.cs
| 🇺🇸 English |  Fixed Pagination `DefaultCurrent` doesn't work         |
| 🇨🇳 Chinese |   修复  Pagination `DefaultCurrent`  参数无作用       |
> fix(module: pagination): DefaultCurrent doesn't work

- components/core/Component/Overlay/Overlay.razor.cs
- components/date-picker/DatePicker.Razor.cs
- components/menu/SubMenu.razor.cs
- components/popconfirm/Popconfirm.razor.cs
- components/select/Select.razor.cs
- tests/AntDesign.Tests/Popconfirm/PopconfirmTests.razor
- tests/AntDesign.Tests/Select/Renders/Select.Render.Tests.razor
- tests/AntDesign.Tests/Select/Select.SelectOptions.Tests.razor
- tests/AntDesign.Tests/Select/Select.Tags.Tests.razor
| 🇺🇸 English |  Add Overlay support avoid show/hide in OnVisibleChange         |
| 🇨🇳 Chinese |  新增 Overlay 支持使用 OnVisibleChange 阻止显示/隐藏         |
> feat(module: overlay): support avoid show/hide in OnVisibleChange

- components/popconfirm/Popconfirm.razor.cs
- components/popconfirm/PopconfirmLocale.cs
- site/AntDesign.Docs/Demos/Components/Popconfirm/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Popconfirm/demo/Locale.razor
- site/AntDesign.Docs/Demos/Components/Popconfirm/demo/PlacementType.razor
- site/AntDesign.Docs/Demos/Components/Popconfirm/demo/locale.md
| 🇺🇸 English |  Fixed Popconfirm missing built-in localization     |
| 🇨🇳 Chinese |  修复 Popconfirm 补全内置的本地化     |
> fix(module: popconfirm): missing built-in localization

- components/segmented/Segmented.razor.cs
- components/segmented/SegmentedItem.razor.cs
> fix(module: segmented): exception cause by label index was changed

- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/Reuse/ReuseTabsService.cs
> fix(module: tabs): reusetabs title update

- components/modal/core/Dialog.razor
#3097
| 🇺🇸 English |   fix(module: Modal): every key down will trigger Modal re-render         |
| 🇨🇳 Chinese |     修复modal每次在按键的时候重渲染content的问题 | 
> fix(module: Modal): every key down will trigger Modal re-render (#3097)

- components/radio/RadioGroup.razor.cs
| 🇺🇸 English |   Fixed Radio avoid infinite loop when the binding vaule is not in options        |
| 🇨🇳 Chinese |   修复 Radio 避免当绑定值不在选项中时造成的无限循环      |
> fix(module: radio): avoid infinite loop when the vaule is not in options

- components/core/JsInterop/modules/components/inputHelper.ts
- components/input/TextArea.razor.cs
> fix(module: input): avoid textarea call jsinterop before rendering

- components/date-picker/DatePicker.Razor.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
- site/AntDesign.Docs/Demos/Components/DatePicker/demo/DisabledDate.razor
- tests/AntDesign.Tests/DatePicker/DatePickerKeyboardInputTests.razor
#3118
Fixes an issue #3118 when DisabledDate does not affect keyboard input. 
> fix:(module:datepicker): DisabledDate does not affect keyboard input

- components/auto-complete/AutoComplete.razor.cs
> fix(module: auto-complete): fill the input component only if `Backfill` is true

- components/transfer/Transfer.razor
- components/transfer/Transfer.razor.cs
- components/transfer/TransferChangeArgs.cs
- components/transfer/TransferDirection.cs
- components/transfer/TransferScrollArgs.cs
- components/transfer/TransferSearchArgs.cs
- site/AntDesign.Docs/Demos/Components/Transfer/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Transfer/doc/index.zh-CN.md
> fix(module: transfer): add ListStyle to custom the css for columns

- components/pagination/PaginationOptions.razor
- components/pagination/PaginationOptions.razor.cs
> fix(module: pagination): avoid trigger ChangeSize while the size was not be changed

- components/select/SelectBase.cs
> fix(module: select): OnSelectedItemsChanged is not triggered in form

- components/table/Column.razor
- components/table/Column.razor.cs
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3006
| 🇺🇸 English |  Fixed Table that the filter of column with the flags enum type place incorrectly       |
| 🇨🇳 Chinese |  修复 Table 的 flags enum 类型列的 filter 展示位置错误      |
> fix(module: table): the flags enum type filter place incorrectly

- components/select/Select.razor
| 🇺🇸 English |   Fixed Select empty incorrectly in virtualization mode        |
| 🇨🇳 Chinese |  修复 Select 在开启虚拟化时空状态显示不正常         |
> fix(module: select): empty incorrectly in virtualization mode

- components/input/TextArea.razor
- components/input/TextArea.razor.cs
- components/typography/Link.cs
- components/typography/Paragraph.cs
- components/typography/Text.cs
- components/typography/Title.cs
- components/typography/TypographyBase.cs
- site/AntDesign.Docs/Demos/Components/Typography/demo/Interactive.razor
- tests/AntDesign.Tests/Typography/LinkTests.cs
- tests/AntDesign.Tests/Typography/ParagraphTests.cs
- tests/AntDesign.Tests/Typography/TextTests.cs
- tests/AntDesign.Tests/Typography/TitleTests.cs
close https://github.com/ant-design-blazor/ant-design-blazor/issues/673
| 🇺🇸 English |    Add Typography editable text support       |
| 🇨🇳 Chinese |   增加  Typography 可编辑文本支持        |
> feat(module: typography): support editable

- components/core/JsInterop/modules/components/mentionsHelper.ts
- components/input/Input.cs
- components/mentions/Mentions.razor
- components/mentions/Mentions.razor.cs
- components/mentions/MentionsTextareaTemplateOptions.cs
- components/mentions/style/patch.less
- site/AntDesign.Docs/Demos/Components/Mentions/demo/Form.razor
- site/AntDesign.Docs/Demos/Components/Mentions/demo/TextareaTemplate.razor
- site/AntDesign.Docs/Demos/Components/Mentions/demo/textareatemplate.md
- tests/AntDesign.Tests/Input/InputTests.razor
- tests/AntDesign.Tests/Mentions/MentionsTests.razor
Add ability to customize the rendering of the textarea. This allows using the TextArea component if you want its extended functionality. Add tests. Update demos.
We require the functionality of the textarea component, but also the mentions functionality. This PR introduces the ability to provide a custom RenderFragment to render your own textarea. This allows using the TextArea component like we need.
| 🇺🇸 English | Add ability to customize the rendering of the textarea. This allows using the TextArea component if you want its extended functionality. |
| 🇨🇳 Chinese | 添加自定义文本区域呈现的能力。如果您想要其扩展功能，这允许使用 TextArea 组件 |
> feat(module: mentions): Add ability to customize the rendering

- components/input-number/InputNumber.razor
Added an id attribute on input element which uses the value provided for Id property with a suffix '_input'.
Very low risk as the Id on wrapping div remains the same thus doesn't impact existing code using it
| 🇺🇸 English | Added id attribute on input element in InputNumber component          |
> Assign Id to input element in InputNumber component

- components/descriptions/Descriptions.razor
- components/descriptions/DescriptionsItem.razor.cs
- components/descriptions/IDescriptionsItem.cs
- site/AntDesign.Docs/Demos/Components/Descriptions/demo/CustomStyle.razor
- site/AntDesign.Docs/Demos/Components/Descriptions/demo/custom-style.md
fixed #3156
| 🇺🇸 English |  Add Descriptions `LabelStyle` and `ContentStyle` for `DescriptionItem` custom styles         |
| 🇨🇳 Chinese |  增加 Descriptions 的 `LabelStyle` 和 `ContentStyle` 来自定义 `DescriptionItem` 的样式        |
> feat(module: descriptions): add `LabelStyle` and `ContentStyle` for custom styles

- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor.cs
- components/tree/style/patch.less
- site/AntDesign.Docs/Demos/Components/Tree/demo/Search_.razor
- site/AntDesign.Docs/Demos/Components/Tree/demo/search.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
| 🇺🇸 English |  add `SimplifySearchResults` to hide the nodes without any matched parent or child from the search results  |
| 🇨🇳 Chinese |  添加 `SimplifySearchResults` 来简化搜索结果的显示，隐藏父节点或子节点均无匹配的节点  |
> add `SimplifySearchResults ` to hide the nodes without any matched parent or child from the search results

- components/select/SelectBase.cs
- components/select/internal/SelectContent.razor
- site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md
fixed #3224
| 🇺🇸 English |   Add Select support for `accesskey` attribute.       |
| 🇨🇳 Chinese |    增加 Select 支持  `accesskey` 属性。     |
> feat(module: select): support for `accesskey` attribute.

- components/form/Internal/IFormItem.cs
fixed #3219
| 🇺🇸 English |  Refactor Form expose the feedback status of FormItem for the input component base class.       |
| 🇨🇳 Chinese |  重构 Form 为 input component base 基类中公开FormItem的一些属性         |
> refactor(module: form): expose the feedback status of FormItem for the input component base class.

- components/menu/Menu.razor.cs
- components/menu/MenuItem.razor
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3225
| 🇺🇸 English |   Add Menu `ShowCollapsedTooltip` parameter to handle Tooltip display        |
| 🇨🇳 Chinese |    新增 Menu `ShowCollapsedTooltip` 属性来控制 Tooltip 的显示       |
> feat(module: menu): add ShowCollapsedTooltip to handle tooltip display

- components/tree/Tree.razor.cs
There is currently no way to set the selection of a Tree component from outside. #3238
As the code currently stands, it's difficult to implement the ideal solution, which would be two-way binding of the SelectedNode, SelectedNodes SelectedKey and SelectedKeys properties, or DefaultCheckedKeys as described in #3238. 
As such, I've come up with this simple solution of exposing a method to get TreeNode objects directly from the Tree through their keys. Since the TreeNode class has public method SetSelection and the Tree class has DeselectAll, this covers all use-cases.
This is not mutually exclusive with a better solution, as the GetNode method is still potentially useful for other purposes (it does, for instance, have information on whether a node is collapsed or not, which the DataSource …
> feat(module: tree): Added public method GetNode(string key)

- components/auto-complete/AutoComplete.razor.cs
Reverts ant-design-blazor/ant-design-blazor#3140
> Revert "fix(module: auto-complete): fill the input component only if `Backfill` is true"

- components/layout/Sider.razor.cs
> feat(module: layout): add `DefaultCollapsed` for sider

- components/table/Table.razor
- components/table/Table.razor.Pagination.cs
- components/table/Table.razor.cs
- components/table/TableModels/QueryModel.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Virtualization.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/virtualization.md
fixed #3229 
| 🇺🇸 English |    Add support `ItemsProvider` for Virtualization       |
| 🇨🇳 Chinese |  增加 虚拟化的  `ItemsProvider`  支持，按需请求数据      |
> feat(module: table): add support `ItemsProvider` for Virtualization

- components/table/Table.razor
- components/table/Table.razor.cs
> fix(module: table): empty and row height issue when ScrollY was set

- components/pagination/Pagination.razor.cs
> fix(module: pagination): mini class name was changed

- components/layout/Sider.razor.cs
- site/AntDesign.Docs/Demos/Components/Layout/demo/Side.razor
fixed https://github.com/ant-design-blazor/ant-design-blazor/discussions/3200
> fix(module: layout): menu can't collapsed when sider is default to collapsed

- components/table/Table.razor
- components/table/Table.razor.cs
> fix(module: table): revert min-height for scroll y

- components/table/Table.razor.cs
> feat(module: table): add EF Core support for Virtualization ItemsProvider

- components/tabs/Reuse/ReuseTabs.razor.cs
fixed #3289
| 🇺🇸 English |   Fixed Tabs duplicated pinned tabs in reusetab        |
| 🇨🇳 Chinese |    修复 Tabs 当有固定标签时，再次导航改标签会重复的问题       |
> fix(module: tabs): duplicated pinned tabs in reusetabs.

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
> docs: update documentation

- components/select/SelectBase.cs
- components/tree-select/TreeSelect.razor.cs
> fix(module: tree-select): removing last option can't change the bind values

- components/core/HashCodes/HashCodeExtensions.cs
- components/core/HashCodes/HashCodeProvider.cs
- components/core/HashCodes/ParameterDescriptor.cs
fixed #3284
| 🇺🇸 English |   Fixed Table render incorrectly in ParametersHashCodeChanged mode in some case        |
| 🇨🇳 Chinese |  修复 Table 在 ParametersHashCodeChanged 模式下某些情况不渲染的问题        |
> fix(module: table): render incorrectly in ParametersHashCodeChanged mode in some case

- components/statistic/CountDown.razor.cs
fixed #1475
| 🇺🇸 English |   Fixed Statistic  that coundown pause while the navigate to other page      |
| 🇨🇳 Chinese |   修复  Statistic  的 CountDown 在切换其他页面时会暂停的问题     |
> fix(module: statistic): coundown pause while the navigate to other page

- components/slider/Slider.razor.cs
> fix(module: slider): slider does not always fire OnAfterChange

- components/table/Table.razor.cs
> fix(module: table): avoid exception at DisposeAsync method

- components/menu/MenuItem.razor
- components/menu/MenuItem.razor.cs
> fix(module: menu): MenuItem unselect incorrectly when menu was inline and collapsed

- components/steps/Steps.razor.cs
> fix(module: steps): missing RTL style

- site/AntDesign.Docs/Demos/Components/Segmented/demo/disabled.md
- site/AntDesign.Docs/Pages/Components.razor
- site/AntDesign.Docs/Pages/Index.razor.cs
> docs: fix infinite loop at home page and duplicated key

- components/form/FormItem.razor.cs
> fix(module: form): Help message change

- components/menu/MenuItem.razor.cs
> fix(module: menu): missing null check

- components/input/TextArea.razor
- components/input/TextArea.razor.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/RequiredMark.razor
> fix(module: input): incorrect html structure of TextArea icons

- components/checkbox/Checkbox.razor
- components/checkbox/Checkbox.razor.cs
- components/checkbox/CheckboxGroup.razor
- components/checkbox/CheckboxGroup.razor.cs
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/Group.razor
- tests/AntDesign.Tests/Checkbox/CheckboxGroupTests.razor
- tests/AntDesign.Tests/Checkbox/plane/CheckboxGroupTests.razor
…om checkbox group
fixed #3356
> fix(module: checkbox): passing disabled value to templated options from checkbox group

- components/select/SelectOption.razor
adds the aria-label to the select option element
> feat(Module:SelectOption) add aria-label to select option

- components/progress/Progress.razor
- components/progress/Progress.razor.cs
- components/progress/ProgressEnum.cs
- components/progress/style/entry.less
- components/progress/style/patch.less
> fix(module: progress): text wrapping issue of the line type

- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor.cs
- site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor
- site/AntDesign.Docs/Demos/Components/Tree/demo/Dynamic.razor
> feat(module: tree): add ExpandAll/CollapseAll TreeNode

- components/collapse/Panel.razor
- components/collapse/Panel.razor.cs
> feat(module: collapse): implement expand animation

- components/auto-complete/AutoComplete.razor.cs
- components/core/JsInterop/ObservableApi/resizeObserver.ts
> fix(module: autocomplete): dropdown resize

- site/AntDesign.Docs/Demos/Components/Table/demo/CustomRowStyle.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/custom-row-style.md
> docs(module: table): introduce how to use RowClassName with fixed column and hover rows

- components/modal/config/DialogOptions.cs
- components/modal/config/ModalStatus.cs
- components/modal/core/Dialog.razor
- components/modal/core/Dialog.razor.cs
- site/AntDesign.Docs/Demos/Components/Modal/demo/Maxable.razor
#3401
| 🇺🇸 English |      fix: centered conflict maximizable style     |
| 🇨🇳 Chinese |    修复  centered  和  maximizable  样式冲突 |
> fix(module: Modal): centered conflict maximizable style

- components/locales/ko-KR.json
Incorrect formatting (for Confirm and Form components) for ko-KR locale.
| 🇺🇸 English |  fix i18n: ko-KR locale Confim And Form         |
@microsoft-github-policy-service agree
> fix i18n: ko-KR locale Confim And Form

- components/table/Selection.razor
- components/table/Selection.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/RowSelection_.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/row-selection.md
> fix(module: table): avoid disabled selection would be selected when select-all checked

- components/button/Button.razor.cs
> fix(module: button): avoid fire `OnClick` when it is Loading

- .github/workflows/nightly-build.yml
- .github/workflows/preview-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-AOT.yml
- .github/workflows/release.yml
- components/AntDesign.csproj
- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
- site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj
- site/AntDesign.Docs/AntDesign.Docs.csproj
- tests/AntDesign.Tests.Js/AntDesign.Tests.Js.csproj
> chore: hosting the site with .NET 8

- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
> chore: disable WasmStripILAfterAOT for now

- components/date-picker/RangePicker.razor.cs
- site/AntDesign.Docs/Demos/Components/DatePicker/demo/DateRender.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/ControlHooks.razor
- follow up #3458 , fix the reference value of initValue
- fix the custom date render demo
> fix(module: datepicker): the reference value of initValue

- components/table/Table.razor
- components/table/Table.razor.Selection.cs
- components/table/TableModels/RowData.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/DataTable_.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/OnRowAndOnCell.razor
> fix(module: table): row selection shouldn't need the selection column

- components/modal/core/Dialog.razor.cs
- components/modal/modalDialog/Modal.razor.cs
- site/AntDesign.Docs/Demos/Components/Modal/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/ButtonProps.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/DraggableModal.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/FormInModal.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/Locale.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/MaxBodyHeight.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/Maxable.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/OverrideLocale.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/Position.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/Resizeable.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/async.md
> feat(module: modal): support two-way binding for `Visible` parameter

- components/input/Input.cs
- tests/AntDesign.Tests/Form/EditContext/Form.EditContext.BuildTests.razor
> fix(module: input): fix incorrectly validation and required message

- components/table/Table.razor
- components/table/Table.razor.cs
- site/AntDesign.Docs/AntDesign.Docs.csproj
- site/AntDesign.Docs/Demos/Components/Table/demo/Expand.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/expand.md
fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3471
| 🇺🇸 English |  Fixed Table supports datasource of abstract classes       |
| 🇨🇳 Chinese |    修复   Table  支持抽象类数据源     |
> fix(module: table): supports datasource of abstract classes

- components/layout/Sider.razor
> fix(module: layout): NoTrigger not effect when CollapsedWidth is zero

- components/layout/Sider.razor.cs
- tests/AntDesign.Tests/AntDesign.Tests.csproj
- tests/AntDesign.Tests/Layout/LayoutTests.razor
> test(module: layout): add test case for layout and sider

- components/table/Column.razor
- components/table/Column.razor.cs
- components/table/IFieldColumn.cs
- components/table/ITable.cs
- components/table/Table.razor
- components/table/Table.razor.cs
- components/table/TableModels/RowData.cs
- components/table/TableRow.razor
- components/tsconfig.json
- site/AntDesign.Docs.Server/Pages/Error.cshtml.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/GroupingRows.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/grouping-rows.md
- site/AntDesign.Docs/Shared/HeaderMenu.razor.cs
> feat(module: table): add row grouping

- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
> docs: missing the setup of AntContainer

- site/AntDesign.Docs/Pages/Mock.razor
- site/AntDesign.Docs/Routing/Route.cs
> docs: fix query string bingding for mock page

- components/select/Select.razor.cs
> #3355 Fixed Selected value will be reset when ValidateOnChange is on

- .github/workflows/nightly-build.yml
- .github/workflows/preview-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-AOT.yml
- .github/workflows/release.yml
- components/AntDesign.csproj
- components/card/Card.razor.cs
- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
- site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj
- site/AntDesign.Docs/AntDesign.Docs.csproj
- tests/AntDesign.TestKit/AntDesign.TestKit.csproj
> update Blazor to .NET 8

- components/core/RerenderStrategy.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md
> refactor: rename RenderMode to RerenderStrategy

- README-zh_CN.md
- README.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
> docs: update the webapp installation guide

- components/checkbox/style/patch.less
> feat(moduel: checkbox): fix ssr style

- components/table/Table.razor.RowData.cs
- components/table/TableModels/RowData.cs
> fix(module: table): the data of row did't update after it's data source was changed

- components/table/Table.razor.Pagination.cs
> fix(module: table): clear the row state after page index was changed in client resource mode

- components/core/Helpers/RenderFragmentHelper.cs
- components/table/Column.razor
- components/table/Table.razor
> refactor(module: table): Change some components to render fragments, reducing allocation and avoid side effects cause by life cycle

- components/table/Table.razor.Selection.cs
> fix(module: table): can't clear the selected rows if they were not on the current page

- scripts/gh-pages/index.html
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs.Wasm/wwwroot/index.html
- site/AntDesign.Docs.WasmHost/Pages/_Host.cshtml
> docs: fix blocked links for docsearch

- README-zh_CN.md
- README.md
- components/wwwroot/AntDesign.lib.module.js
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- scripts/gh-pages/index.html
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs.Wasm/wwwroot/index.html
- site/AntDesign.Docs.WasmHost/Pages/_Host.cshtml
- site/AntDesign.Docs/Shared/HeaderMenu.razor.cs
- site/AntDesign.Docs/wwwroot/js/docsearch.js
- tests/AntDesign.TestApp/Client/wwwroot/index.html
> feat(core): setup JS initializers

- components/input/TextArea.razor
- tests/AntDesign.Tests/Input/TextAreaTests.razor
- tests/AntDesign.Tests/Mentions/MentionsTests.razor
> fix(module: input): textarea missing rows attribute

- scripts/gh-pages/index.html
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs.Wasm/wwwroot/index.html
- site/AntDesign.Docs.WasmHost/Pages/_Host.cshtml
- site/AntDesign.Docs/Highlight/PrismHighlighter.cs
> docs: fix prism highlight

- components/tree/Tree.razor.cs
> fix(module: tree): should show all nodes while search value is empty

- tests/AntDesign.Tests/Select/Select.Tags.Tests.razor
> fix select test case by SearchDebounceMilliseconds

- components/wwwroot/AntDesign.lib.module.js
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs/App.razor
- tests/AntDesign.TestKit/AntDesign.TestKit.csproj
- tests/AntDesign.Tests/Select/Select.Tags.Tests.razor
- tests/AntDesign.Tests/Select/Select.Value.Tests.razor
- tests/AntDesign.Tests/Upload/UploadTests.razor
> feat: add support for custom script/style import locations

- components/select/SelectOption.razor.cs
fixed the issue cause by #3569 
> fix(module: select): avoid selected item being set to 0 when the default value of TItem is 0

- components/menu/Menu.razor.cs
> fix(module: menu): wrong judge

- components/form/Form.razor
- components/form/Form.razor.cs
- site/AntDesign.Docs/Demos/Components/Form/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Form/doc/index.zh-CN.md
https://github.com/ant-design-blazor/ant-design-blazor/issues/3453
You can not submit forms using post request what means you can not login using some methods such a cookie
| 🇺🇸 English | Adds `Method` parameter for `Form` component |
| 🇨🇳 Chinese |     |
> Add Method and FormName parameter for Form

- components/core/Helpers/Formatter.cs
> fix(module: table): thrown exception when property type is char

- components/table/Table.razor.RowData.cs
- components/table/Table.razor.cs
> fix(module: table): should flush cache only pagging

- components/select/SelectBase.cs
- components/select/internal/SelectContent.razor
- components/select/internal/SelectContent.razor.cs
> fix(module: select): placholder doesn't hide correctly

- site/AntDesign.Docs/Demos/Components/Table/demo/Expand.razor
- [ v ] Site / documentation update
See #3629
| 🇺🇸 English |     change to full namespace @using AntDesign.TableModels      |
| 🇨🇳 Chinese |     改为命名空间全名 @using AntDesign.TableModels      |
- [ v ] Doc is updated/provided or not needed
- [ v ] Demo is updated/provided or not needed
- [ v ] Changelog is provided or not needed
> docs: fix namespace (#3629)

- components/core/AntContainer.razor
- components/core/Extensions/ServiceCollectionExtensions.cs
- components/core/JsInterop/JSInteropConstants.cs
- components/core/JsInterop/interop.ts
- components/core/Services/Internal/NavMgrService.cs
- components/modal/modalDialog/ModalServiceForModal.cs
#3613
| 🇺🇸 English |   fix: modal dom instance clear when url changed        |
| 🇨🇳 Chinese |     修复 url 变化的时候 modal 实例未完全清理的问题      |
> fix: modal dom instance clear when url changed (#3613)

- components/collapse/Panel.razor.cs
> fix(module: collapse): Accordion doesn't work

- components/select/internal/SelectContent.razor
> fix(module: select): disabled the search input box

- site/AntDesign.Docs.WebApp/AntDesign.Docs.WebApp/Components/Pages/Error.razor
- site/AntDesign.Docs.WebApp/AntDesign.Docs.WebApp/Program.cs
- site/AntDesign.Docs/Pages/Index.razor.cs
> docs: fix base address for server side http request

- .github/workflows/AntDesignDocsWebApp.yml
- .github/workflows/nightly-build.yml
- package.json
> docs: fix webapp build action

- components/comment/Comment.razor.cs
- components/comment/style/patch.less
- site/AntDesign.Docs/Demos/Components/Comment/demo/Editor.razor
- site/AntDesign.Docs/Demos/Components/Comment/demo/List.razor
- site/AntDesign.Docs/Demos/Components/Comment/demo/Placement.razor
- site/AntDesign.Docs/Demos/Components/Comment/demo/placement.md
- site/AntDesign.Docs/Demos/Components/Comment/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Comment/doc/index.zh-CN.md
> feat(module: comment): avatar placement

- site/AntDesign.Docs/Resources/en-US.json
- site/AntDesign.Docs/Resources/zh-CN.json
- site/AntDesign.Docs/wwwroot/data/products.json
> docs: add antsk to products

- components/tabs/Reuse/ReuseTabsService.cs
- tests/AntDesign.TestApp/Client/Pages/Index.razor
issues: 3660
- [x ] New feature
> Update ReuseTabsService.cs  add  AddReuseTabsPageItem method

- components/table/Table.razor
- components/table/Table.razor.cs
> fix(module: table): remove loading and show no data when datasource is abstract and empty

- components/table/Column.razor.cs
https://github.com/ant-design-blazor/ant-design-blazor/issues/3650
https://github.com/ant-design-blazor/ant-design-blazor/assets/93575828/35f00ddf-79bc-4ca2-a2bc-a32cfcbeeded
> fix(module: table): 3650 filter carriage jump

- components/select/SelectBase.cs
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/TableSelect.razor
- site/AntDesign.Docs/Demos/Components/Select/demo/table-select.md
> feat(module: select): support table select

- .github/workflows/AntDesignDocsWebApp.yml
> chore: fix webapp WORKING_DIRECTORY

- components/table/Filters/DateFieldFilterType.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Filter.razor
> fix(module: table): DateField filter would throw exception when property type is nullable

- components/select/internal/SelectContent.razor
| 🇺🇸 English |     Fixed placeholder display in Select Content when the input (search) value is not null    |
| 🇨🇳 Chinese |      固定输入（搜索）值不为null时选择内容中的占位符显示     |
> Disable showing placeholder when input string is not null

- components/core/Base/AntInputComponentBase.cs
- tests/AntDesign.Tests/Form/Validation/Form.ValidationTests.razor
fixed #3712
fixed https://github.com/ant-design-blazor/ant-design-pro-blazor/issues/175
> fix(module: form): cause exception while has no FieldIdentifier

- components/upload/Upload.razor
- components/upload/Upload.razor.cs
- components/upload/style/patch.less
> style(module: upload): style with no button

- components/input/Input.cs
- components/input/TextArea.razor
- components/radio/Radio.razor
> fix(module: form): tests failure

- components/core/Base/AntInputComponentBase.cs
- components/core/Forms/ExpressionFormatter.cs
- components/core/Forms/HtmlFieldPrefix.cs
- components/core/Forms/ReverseStringBuilder.cs
- components/form/Form.razor
- components/form/Form.razor.cs
- components/input-number/InputNumber.razor
- components/input/Input.cs
- components/input/TextArea.razor
- components/modal/config/DialogOptions.cs
- components/modal/config/DialogOptionsBase.cs
- components/modal/core/Dialog.razor
- components/modal/core/Dialog.razor.cs
- components/modal/modalDialog/Modal.razor.cs
- components/modal/modalDialog/ModalHeader.razor
- components/modal/modalDialog/ModalHeader.razor.cs
- components/radio/Radio.razor
- components/radio/RadioGroup.razor.cs
- components/radio/style/patch.less
- site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
- site/AntDesign.Docs.Build/AntDesign.Docs.Build.csproj
- site/AntDesign.Docs/Demos/Components/Modal/demo/Header_.razor
- site/AntDesign.Docs/Demos/Components/Modal/demo/header.md
- site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/Radio/demo/EnumGroup.razor
> merge Feature

- components/table/Table.razor.RowData.cs
- components/table/Table.razor.cs
- components/table/TableModels/RowData.cs
| 🇺🇸 English |      fix table rows which have been remove from selectedRows would be selected again  （client side data）   |
| 🇨🇳 Chinese |   修复 table 选择行清理后，全选时还会被选中 （客户端数据）       |
> fix(module: table): rows which have been remove from selectedRows would be selected again

- components/core/Base/AntInputComponentBase.cs
- components/core/Reflection/PropertyReflector.cs
- components/form/Form.razor.cs
- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- components/form/Internal/IFormItem.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/CustomizedFormControls.razor
> fix(module: form): validation for custom controls

- components/input/TextArea.razor.cs
- components/input/TextAreaInfo.cs
- tests/AntDesign.Tests/Input/TextAreaTests.razor
Updated TextAreaInfo to be a public class so that JSInterop calls can be setup for unit tests.
Closes #3714
> refactor: Update TextArea.razor.cs

- components/form/Form.razor
- components/form/Form.razor.cs
- site/AntDesign.Docs/Demos/Components/Form/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Form/doc/index.zh-CN.md
> feat(module: form): add autocomplete parameter

- components/checkbox/CheckBoxOption.cs
- components/checkbox/Checkbox.razor
- components/checkbox/Checkbox.razor.cs
- components/checkbox/CheckboxGroup.razor
- components/checkbox/CheckboxGroup.razor.cs
- components/checkbox/EnumCheckboxGroup.cs
- components/checkbox/ICheckboxGroup.cs
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/CheckboxAll.razor
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/Group.razor
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/Layout.razor
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/MixedMode.razor
- tests/AntDesign.Tests/Checkbox/CheckboxGroupTests.razor
- tests/AntDesign.Tests/Checkbox/CheckboxTests.razor
- tests/AntDesign.Tests/Checkbox/plane/CheckboxGroupTests.razor
> feat(module: checkbox): support generic value

- site/AntDesign.Docs/Demos/Charts/Introduce/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Charts/Introduce/doc/index.zh-CN.md
Get started text doesn't compile, and uses obsolete properties.
Properties renamed to correct values, removed obsolete properties
> Updated get started for charts

- components/core/Helpers/DateHelper.cs
- components/date-picker/internal/DatePickerBase.cs
- components/date-picker/internal/DatePickerPanelChooser.razor
- components/date-picker/internal/DatePickerTemplate.razor.cs
fixed #3780
| 🇺🇸 English |   fixed DatePicker that disabled date is not judging correctly in the larger range panels     |
| 🇨🇳 Chinese |    修复  DatePicker  禁用日期逻辑在更大的范围选择中判断不正确     |
> fix(module: datepicker): disabled date is not judging correctly in the larger range panels

- components/core/Base/AntInputComponentBase.cs
https://github.com/ant-design-blazor/ant-design-blazor/issues/3784
> bugfix: AntInputComponentBase Dictionary Type judgement

- components/modal/modalDialog/ModalServiceForModal.cs
The CreateModal methods are no need to return a Task. So this PR is refactoring them to synchronous.
| 🇺🇸 English |   refacotr modal that the creating methods in ModalService will return ModalRef synchronously        |
| 🇨🇳 Chinese |     重构 Modal 的 ModalService 中创建模态框的方法同步地返回 ModalRef     |
> refactor(module: modal): modal creating methods in ModalService will return ModalRef synchronously

- components/core/Base/AntInputComponentBase.cs
- components/form/Form.razor.cs
- components/form/FormItem.razor.cs
- components/form/Internal/IForm.cs
> fix(module: form): IsModified work incorrectly when ValidateOnChange is false

- components/modal/config/ModalOptions.cs
- components/modal/modalDialog/ModalRef.cs
- site/AntDesign.Docs/Demos/Components/Modal/demo/FormInModal.razor
> feat(module: modal): support updaet loading state of the confirm button

- site/AntDesign.Docs/Demos/Components/Select/demo/TableSelect.razor
> docs: add search sample for table select demo

- components/IsExternalInit.cs
- site/AntDesign.Docs/IsExternalInit.cs
…een 3rd-party libs
fixed #3798
> fix: make IsExternalInit internal for avoiding runtime conflicts with 3rd-party libs

- components/core/Base/AntInputComponentBase.cs
> fix(module: form): the required data annotation doesn't work in dynamic model

- components/form/Form.razor.cs
- components/form/FormItem.razor.cs
- components/form/Internal/IForm.cs
- components/input/Input.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/DynamicModel.razor
> fix(module: form): shouldn't validate until submit in non-validate-on-change

- src/AntDesign.Extensions.Localization/EmbeddedJson/SimpleEmbeddedJsonLocalizerFactory.cs
- src/AntDesign.Extensions.Localization/EmbeddedJson/SimpleEmbeddedJsonStringLocalizer.cs
> fix(i18n): resource assembly loading incorrectly

- site/AntDesign.Docs/Routes.razor
- src/AntDesign.Extensions.Localization/EmbeddedJson/SimpleEmbeddedJsonStringLocalizer.cs
- src/AntDesign.Extensions.Localization/InteractiveStringLocalizer.cs
- src/AntDesign.Extensions.Localization/LocalizationService.cs
> fix(i18n): initialize creating localizer

- src/AntDesign.Extensions.Localization/EmbeddedJson/SimpleEmbeddedJsonLocalizerFactory.cs
- src/AntDesign.Extensions.Localization/EmbeddedJson/SimpleEmbeddedJsonStringLocalizer.cs
- src/AntDesign.Extensions.Localization/SimpleStringLocalizerOptions.cs
> fix(i18n): load resources where the assembly located at

- site/AntDesign.Docs/ServiceCollectionExtensions.cs
- src/AntDesign.Extensions.Localization/SimpleStringLocalizerOptions.cs
> fix(i18n): resource loading

- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
- src/AntDesign.Extensions.Localization/AntDesign.Extensions.Localization.csproj
> chore(i18n): publish the localization libraray to nuget

- components/tabs/Reuse/ReuseTabs.razor
- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/Reuse/ReuseTabsService.cs
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.zh-CN.md
- tests/AntDesign.TestApp/Client/Pages/Index.razor
> fix(module: reuse-tabs): shouldn't auto navigate to the first pinned tab

- components/core/Component/Overlay/Overlay.razor.cs
- components/core/Component/Overlay/OverlayTrigger.razor.cs
> fix(module: overlay): Parent overlay hides irregularly when child is open or closed. (#3836, #3837)

- components/tree-select/TreeSelect.razor
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.zh-CN.md
> feat(module: TreeSelect): Add ExpandedKeys and update document.

- site/AntDesign.Docs/Demos/Experimental/Introduce/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/DynamicTitle.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/TitleAttribute.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/title-attribute.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.zh-CN.md
> docs: imporve the doc of  reuse tabs

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> Changelog 0.19.0

- components/table/Filters/EnumFieldFilterType.cs
- components/table/Filters/FilterInputs.razor
| 🇺🇸 English |   fixed table enum field   filter throwing null ref exception when the field type is nullable      |
| 🇨🇳 Chinese |  修复 Table 当绑定字段类型是可空时，枚举选择器抛出异常        |
> fix(module: table): enum field filter throwing null ref exception when the field type is nullable

- components/tree-select/TreeSelect.razor
- components/tree-select/TreeSelect.razor.cs
- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor
- components/tree/TreeNode.razor.cs
- site/AntDesign.Docs/Demos/Components/Tree/demo/NodeCheckable.razor
- site/AntDesign.Docs/Demos/Components/Tree/demo/node-checkable.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/NodeCheckable.razor
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/node-checkable.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.zh-CN.md
> feat(module: tree): Add 'Checkable' to TreeNode.

- components/checkbox/Checkbox.razor.cs
- components/checkbox/CheckboxGroup.razor.cs
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/Group.razor
- site/AntDesign.Docs/Demos/Components/Checkbox/demo/MixedMode.razor
> fix(module: checkbox): checked incorrectly with checkbox group

- components/select/EnumSelect.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/EnumSelectDemo.razor
> fix(module: select): flags enum splitting incorrectly

- components/tree-select/TreeSelect.razor.cs
> fix(module: tree-select): The TreeSelect with single selection raises an excecption when clicking clear icon

- components/table/Column.razor
- components/table/Column.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/CustomFilterPanel.razor
- site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md
> feat(module: table): add parameter Filtered for marking filter is actived

- AntDesign.sln
- components/core/Reflection/ExpressionActivator.cs
- components/table/Table.razor.cs
> fix(module: table): create TItem instance with default constructor

- components/image/ImagePreviewGroup.razor.cs
> fix(module: image): ImagePreviewGroup throwing exception while there is no image.

- components/input-number/InputNumber.razor
- components/input-number/InputNumber.razor.cs
- components/input/Input.cs
- components/table/Column.razor
- components/table/Filters/BaseFieldFilterType.cs
- components/table/Filters/FilterInputs.razor
- components/table/Filters/IFieldFilterType.cs
- components/table/Filters/TableFilterInputRenderOptions.cs
- site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/Table/demo/CustomFieldFilter.razor
> feat(module: table): add support custom attributes for filter inupt

- components/checkbox/Checkbox.razor
> fix(module: checkbox): avoid propagation for the label

- components/date-picker/internal/DatePickerYearPanel.razor
> fix(module: date-picker): year unit was wrapping because of the format

- components/select/Select.razor.cs
> fix(module: select): throwing exception cause by browser's  auto complete

- components/auto-complete/AutoComplete.razor
- components/auto-complete/AutoComplete.razor.cs
- site/AntDesign.Docs/Demos/Components/AutoComplete/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/AutoComplete/doc/index.zh-CN.md
> fix(module: auto-complete): open dropdown only when there are matched options

- components/core/Reflection/ExpressionActivator.cs
- components/table/Table.razor.cs
> fix(module: table): trimming issue with ExpressionActivator

- site/AntDesign.Docs/Demos/Components/Icon/demo/Iconfont.razor
- site/AntDesign.Docs/Demos/Components/Icon/demo/ScriptUrl.razor
- site/AntDesign.Docs/Demos/Components/Icon/demo/iconfont.md
- site/AntDesign.Docs/Demos/Components/Icon/demo/scriptUrl.md
> refactor(module: icon): import JS directly to set iconfont

- components/core/Reflection/ExpressionActivator.cs
> fix(module: table): expression activator missing return

- components/modal/confirmDialog/Confirm.razor.cs
- components/modal/confirmDialog/ConfirmRef.cs
- components/modal/confirmDialog/ConfirmService.cs
> fix(module: modal): set result to tcs after press esc

- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor.cs
- site/AntDesign.Docs/Demos/Components/Tree/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
> feat(module: tree): Support to check/uncheck all the child nodes recursively.

- components/tree/Tree.razor.cs
> refactor(module: tree): Refactor 'SelectAll' to select all the nodes in the tree.

- components/select/Select.razor
- components/select/Select.razor.cs
- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
- components/select/SelectOption.razor.cs
- components/select/internal/SelectOptionGroup.razor.cs
- components/tree-select/TreeSelect.razor
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/SearchFilterCustomize.razor
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/CustomDropdownMenu.razor
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/custom-dropdown-menu.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.zh-CN.md
> feat(module: tree-select): Customize the dropdown menu via `DropdownRender`

- components/modal/config/ModalClosingEventArgs.cs
- components/modal/confirmDialog/Confirm.razor.cs
> fix(module: modal): doesn't return Yes/No result when create confirm by service

- components/select/SelectBase.razor.cs
> fix(module: select): Fix a bug which may raise an exception 'Index was out of Range'. (#3942)

- components/checkbox/Checkbox.razor.cs
> fix(module: checkbox): diabled style of wrapper

- components/tree-select/TreeSelect.razor
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.zh-CN.md
> feat(module: tree-select): Add `TreeDefaultExpandParent` & `TreeDefaultExpandedKeys`.

- components/tree/Tree.razor.cs
> feat(module: tree): Enable hover state display when `CheckOnClickNode` is true.

- components/modal/config/DialogOptionsBase.cs
- components/modal/confirmDialog/Confirm.razor.cs
- components/modal/confirmDialog/ConfirmRef.cs
- components/modal/confirmDialog/ConfirmService.cs
- components/modal/confirmDialog/ModalServiceForConfirm.cs
- components/modal/core/Dialog.razor.cs
- components/modal/core/DialogWrapper.razor
- components/modal/modalDialog/Modal.razor.cs
- components/modal/modalDialog/ModalServiceForModal.cs
> fix(module: modal): modal can't open again after navagate to a same page

- components/form/FormItem.razor.cs
- tests/AntDesign.Tests/Form/FormTests.razor
| 🇺🇸 English |       FormItem: fix null reference exception    |
| 🇨🇳 Chinese |       FormItem：修复空引用异常    |
> FormItem: fix null reference exception

- components/auto-complete/AutoComplete.razor.cs
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/UncertainCategory.razor
> fix(module: auto-complete): open dropdown on click when options is not empty by default

- components/modal/confirmDialog/ModalServiceForConfirm.cs
…s closed.
follow up https://github.com/ant-design-blazor/ant-design-blazor/pull/3963 for async methods.
> fix(module: modal): throwing exception when service-opened confirm was closed

- components/input/TextArea.razor.cs
- site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md
> fix(module: textarea): add missing borderless style

- components/menu/Menu.razor.cs
> fix(module: menu): matched item would be unselected on first load

- components/core/JsInterop/HtmlElement.cs
- components/core/JsInterop/modules/dom/infoHelper.ts
- components/core/JsInterop/modules/dom/types.ts
- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/TabPane.razor
- components/tabs/TabPane.razor.cs
- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs/Demos/Components/Tabs/demo/Basic.razor
- tests/AntDesign.Tests.Js/tests/modules/components/overlay.test.ts
- tests/AntDesign.Tests/Card/Card.Render.Tests.razor
- tests/AntDesign.Tests/Form/FormTests.razor
- tests/AntDesign.Tests/tabs/TabsTests.cs
- tests/AntDesign.Tests/tabs/TabsTests.razor
> fix(module: tabs): update the style of ink after tab title is changed

- components/modal/config/DialogOptions.cs
- components/modal/confirmDialog/Confirm.razor
- components/modal/confirmDialog/Confirm.razor.cs
- components/modal/core/Dialog.razor.cs
- components/modal/core/DialogWrapper.razor.cs
- components/modal/modalDialog/Modal.razor
- components/modal/modalDialog/Modal.razor.cs
> fix(module: modal): broken on close which DestroyOnClose is true

- components/tree/TreeNode.razor.cs
> fix(module: tree): The parent & other siblings will be checked if only the first child is in CheckedKeys/DefaultCheckedKeys

- .github/workflows/nightly-build-v5.yml
- scripts/gulp/tasks/library.ts
- site/AntDesign.Docs.Build/AntDesign.Docs.Build.csproj
> fix javascript building

- components/table/TableModels/RowData.cs
> fix(module: table): dead loop render for tree data

- components/date-picker/DatePicker.Razor.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
- site/AntDesign.Docs/Demos/Components/DatePicker/demo/PresettedRanges.razor
> fix(module: date-picker): OnChange won't be invoke after applying the presetted range

- AntDesign.sln
- site/AntDesign.Docs/AntDesign.Docs.csproj
- site/AntDesign.Docs/Demos/Components/Calendar/demo/Card_.razor
- site/AntDesign.Docs/Demos/Components/Calendar/demo/CustomizeHeader.razor
- site/AntDesign.Docs/Demos/Components/Calendar/demo/NoticeCalendar.razor
- site/AntDesign.Docs/Pages/StyleTest.razor
- site/AntDesign.Docs/Pages/StyleTest.razor.cs
- site/AntDesign.Docs/_Imports.razor
- src/AntDesign.Style.Generator/AntDesign.Style.Generator.csproj
- src/AntDesign.Style.Generator/CreateStyleGenerator.cs
- src/AntDesign.Style.Generator/Properties/launchSettings.json
> feat: add style generator

- components/table/Table.razor.RowData.cs
- components/table/Table.razor.Selection.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/TreeData.razor
> fix(module: table): selection with radio mode can't work with tree data

- site/AntDesign.Docs/Demos/Components/Table/demo/tree-data-with-circular-reference.md
> docs: fix table doc

- components/auto-complete/AutoComplete.razor
- components/input/Input.cs
- site/AntDesign.Docs/Pages/Test.razor
- tests/AntDesign.Tests/AutoComplete/AutoCompleteTests.cs
- tests/AntDesign.Tests/Input/InputTests.razor
> fix(module: input): can't apply Class to input element

- components/select/Select.razor
> refactor(module: select): fix IDE  error

- components/modal/config/ModalOptions.cs
- components/modal/modalDialog/Modal.razor.cs
- components/modal/modalDialog/ModalRef.cs
- components/modal/modalDialog/ModalServiceForModal.cs
> fix(module: modal): stete updating

- components/radio/RadioGroup.razor.cs
> fix(module: radio): can't refresh the UI in Modal

- components/tree-select/TreeSelect.razor.cs
- components/tree/Tree.razor.cs
> fix(module: tree-select): exception when searching with nodes have no title

- .github/workflows/release-AOT.yml
> fix doc release action for checkout error

- components/date-picker/DatePicker.Razor.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
> feat(module: DatePicker): enhance value format

- components/style/StyleManager.cs
- site/AntDesign.Docs/Pages/StyleTest.razor
- site/AntDesign.Docs/Pages/StyleTest.razor.cs
- site/AntDesign.Docs/Routes.razor
- site/AntDesign.Docs/ServiceCollectionExtensions.cs
- src/AntDesign.Style.Generator/CreateStyleGenerator.cs
> [v5] add style manager & generate css and hashid

- site/AntDesign.Docs/Pages/StyleTest.razor
- site/AntDesign.Docs/Pages/StyleTest.razor.cs
- src/AntDesign.Style.Generator/CreateStyleGenerator.cs
> feat(v5): define multiple style

- components/locales/en-GB.json
- components/locales/en-US.json
- components/locales/zh-CN.json
- components/locales/zh-TW.json
- components/table/Filters/DateFieldFilterType.cs
- components/table/Filters/FilterInputs.razor
- components/table/TableFilter.cs
- components/table/TableLocale.cs
- components/table/TableModels/FilterModel.cs
> feat(module: table): support between compare for built-in filter of date types

- .github/workflows/nightly-build-v5.yml
- src/AntDesign.Style.Generator/AntDesign.Style.Generator.csproj
> feat(v5): publish style generator

- components/modal/core/Dialog.razor
- components/modal/core/Dialog.razor.cs
- components/modal/style/patch.less
> feat(module: modal): support selection when disabled mask & vertical resizable

- components/modal/config/DialogOptions.cs
- components/modal/core/Dialog.razor.cs
- components/modal/core/DialogWrapper.razor.cs
- components/modal/modalDialog/Modal.razor.cs
> feat(module: modal): support for ForceRender

- components/modal/core/Dialog.razor.cs
> fix(module: modal): merge conflict

- components/watermark/Watermark.razor.cs
> faat(module: watermark): support conent updating

- components/cascader/Cascader.razor
- components/cascader/Cascader.razor.cs
- site/AntDesign.Docs/Demos/Components/Cascader/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Cascader/doc/index.zh-CN.md
> feat(module: cascader): add placement parameter

- components/select/Select.razor.cs
- components/select/SelectBase.razor.cs
> refactor(module: select): friendly error message for CustomTagLabelToValue

- components/tree/TreeNode.razor
> fix(module: tree): Add support to `DataItem` without `ChildrenExpression` (#2759).

- components/core/Reflection/PropertyReflector.cs
> feat(module: form): support array index validation

- components/carousel/Carousel.razor
- components/carousel/Carousel.razor.cs
- site/AntDesign.Docs/Demos/Components/Carousel/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Carousel/doc/index.zh-CN.md
> feat(module: carousel): add Dots and DotsClass parameters

- components/tag/Tag.razor
- components/tag/Tag.razor.cs
- site/AntDesign.Docs/Demos/Components/Tag/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tag/doc/index.zh-CN.md
> feat(module: tag): Add icon theme parameter

- components/core/Component/Overlay/Overlay.razor.cs
- components/core/Component/Overlay/OverlayTrigger.razor.cs
> feat(module: overlay): support @bind-Visible

- components/table/ColumnBase.cs
- components/table/IColumn.cs
- components/table/ITable.cs
- components/table/Table.razor
- components/table/Table.razor.cs
> fix(module: table): scroll bar width adaptive

- components/breadcrumb/Breadcrumb.razor
- components/breadcrumb/Breadcrumb.razor.cs
- components/breadcrumb/BreadcrumbItem.razor
- components/breadcrumb/BreadcrumbOption.cs
- components/menu/MenuService.cs
- site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Integration.md
- site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Integration.razor
- site/AntDesign.Docs/Demos/Components/Breadcrumb/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Breadcrumb/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
> feat(module: Breadcrumb): auto match routes and generate items

- components/table/Table.razor.cs
fixed #3643
| 🇺🇸 English |   add the InvokeDataSourceHasChanged method to allow derived classes to call it for refresh the state of the table     |
| 🇨🇳 Chinese |    增加  InvokeDataSourceHasChanged 方法给派生类在刷新DataSource后调用，以刷新Table状态    |
> feat(module: table): add the InvokeDataSourceHasChanged method to allow derived classes to call it for refresh the state of the table

- components/table/TableModels/FilterModel.cs
- components/table/TableModels/ITableFilterModel.cs
- components/table/TableModels/QueryModel.cs
TableFilter currently has only one IQueryable <T>method, and some components prefer to use Expression<T, bool> as parameter for the Filter.I just extend IQueryable<T>function to an Expression<T,bool> function
- ☑️ Doc not needed
- ☑️Demo not needed
- ☑️ Changelog needed
> add extra Expression<T,bool> method for FilterModel and Table's QueryModel

- components/core/Base/AntInputComponentBase.cs
- components/core/ConfigProvider/Form/FormValidateErrorMessages.cs
- components/core/Forms/IControlValueAccessor.cs
- components/core/Reflection/PropertyReflector.cs
- components/form/Form.razor
- components/form/Form.razor.cs
- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- components/form/FormLocale.cs
- components/form/Internal/IForm.cs
- components/form/Internal/Validate/FormValidateHelper.cs
- components/form/Internal/Validate/ValidationAttribute/ArrayRangeAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/NumberAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/StringRangeAttribute.cs
- components/form/Validate/Rule/FormValidationContext.cs
- components/form/Validate/Rule/FormValidationRule.cs
- components/locale-provider/Locale.cs
- components/locale-provider/LocaleProvider.cs
- components/locales/zh-CN.json
- tests/AntDesign.Tests/Form/Validation/FormValidateHelperTest.cs
> feat(module: form): using built-in i18n for validation message

- components/core/Component/Overlay/Overlay.razor.cs
> fix(overlay): avoid interop during prerendering

- components/modal/core/Dialog.razor
- components/modal/core/Dialog.razor.cs
> fix(module: modal): maximize incorrectly after resizing

- components/form/FormItem.razor
- components/form/FormItem.razor.cs
> fix(module: form): use FormItem label or property displayname as the label of error messages

- components/locales/ar-EG.json
- components/locales/az-AZ.json
- components/locales/ca-ES.json
- components/locales/de-DE.json
- components/locales/en-GB.json
- components/locales/es-ES.json
- components/locales/et-EE.json
- components/locales/fa-IR.json
- components/locales/fr-FR.json
- components/locales/he-IL.json
- components/locales/hi-IN.json
- components/locales/hr-HR.json
- components/locales/it-IT.json
- components/locales/ja-JP.json
- components/locales/ka-GE.json
- components/locales/ko-KR.json
- components/locales/nb-NO.json
- components/locales/nl-BE.json
- components/locales/nl-NL.json
- components/locales/pl-PL.json
- components/locales/pt-BR.json
- components/locales/pt-PT.json
- components/locales/ro-RO.json
- components/locales/sk-SK.json
- components/locales/sr-RS.json
- components/locales/sv-SE.json
- components/locales/th-TH.json
- components/locales/tr-TR.json
- components/locales/uk-UA.json
- components/locales/zh-TW.json
> i18n: update form locales

- components/locales/bn-BD.json
- components/locales/by-BY.json
- components/locales/fr-CA.json
- components/locales/ga-IE.json
- components/locales/gl-ES.json
- components/locales/kk-KZ.json
- components/locales/km-KH.json
- components/locales/kmr-IQ.json
- components/locales/lt_LT.json
- components/locales/ml-IN.json
- components/locales/si-LK.json
- components/locales/tk-TK.json
- components/locales/uk-UA.json
- components/locales/ur-PK.json
- components/locales/uz-UZ.json
- components/locales/zh-HK.json
| 🇺🇸 English |   add more locales        |
> i18n: add more locales

- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/TableSelect.razor
> fix(module: select): control select visible

- components/form/Form.razor
- components/form/Form.razor.cs
- components/form/FormItem.razor.cs
- components/form/Internal/IFormItem.cs
- components/form/Internal/Validate/FormValidateHelper.cs
- components/form/Validate/Rule/FormValidationRule.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/Localization.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/localization.md
> fix(module: form): validation exception

- site/AntDesign.Docs/Shared/CodeBox.razor
> docs: rerender demo on language changed

- components/core/Base/AntInputComponentBase.cs
- components/core/ConfigProvider/Form/FormValidateErrorMessages.cs
- components/core/Forms/IControlValueAccessor.cs
- components/core/Helpers/EnumHelper.cs
- components/core/Helpers/THelper.cs
- components/form/Form.razor.cs
- components/form/FormItem.razor.cs
- components/form/Internal/Validate/FormValidateHelper.cs
- components/form/Internal/Validate/ValidationAttribute/OneOfAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/TypeAttribute.cs
- components/form/Validate/Rule/FormFieldType.cs
- components/form/Validate/Rule/FormValidationContext.cs
- tests/AntDesign.Tests/Form/Validation/FormValidateHelperTest.cs
- tests/AntDesign.Tests/Select/Form/Select.MultipleModeTests.razor
> fix(module: form): validation attributes transfer

- components/form/Form.razor.cs
- docs/i18n.en-US.md
- docs/i18n.zh-CN.md
- site/AntDesign.Docs/Demos/Components/Form/demo/Localization.razor
- site/AntDesign.Docs/Demos/Components/Form/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Form/doc/index.zh-CN.md
> docs: update i18n document

- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor.cs
> fix(module: tree): Fix the issue that node's 'CheckAllChildren' does not trigger a change in 'CheckedKeys'

- site/AntDesign.Docs/Demos/Components/Table/demo/GroupingRows.razor
- site/AntDesign.Docs/Pages/Components.razor
- site/AntDesign.Docs/Pages/Components.razor.cs
> docs: Optimize document presentation performance

- components/table/ColumnBase.cs
- components/table/ColumnContext.cs
- components/table/ITable.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/DataTable_.razor
> fix(module: table): column change

- components/table/ColumnBase.cs
- components/table/ColumnContext.cs
> fix(module: table): style would be messy when columns skipped fixed or no width was set

- components/tabs/Tabs.razor.cs
> fix(module: tabs): The Ink is not rendered when changing active page through ActiveKey.

- components/AntDesign.csproj
- components/core/Helpers/PropertyAccessHelper.cs
- components/core/Reflection/PropertyReflector.cs
- components/form/Form.razor.cs
- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- components/form/Internal/IFormItem.cs
- components/form/Internal/Validate/FormValidateHelper.cs
- components/form/Validate/Rule/FormValidationContext.cs
- components/input/Input.cs
- site/AntDesign.Docs/Demos/Components/Form/demo/ComplexFormControl.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/DynamicRule.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/FormContext.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/GenerateFormItem_.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/Localization.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/complex-form-control.md
- site/AntDesign.Docs/Demos/Components/Form/demo/localization.md
> fix(module: form): remove complex object validator

- site/AntDesign.Docs/Pages/Components.razor
- site/AntDesign.Docs/Pages/Components.razor.cs
> docs: fix anchors

- components/locales/bn-BD.json
- components/locales/by-BY.json
- components/locales/fr-CA.json
- components/locales/ga-IE.json
- components/locales/gl-ES.json
- components/locales/kk-KZ.json
- components/locales/km-KH.json
- components/locales/kmr-IQ.json
- components/locales/lt_LT.json
- components/locales/ml-IN.json
- components/locales/si-LK.json
- components/locales/tk-TK.json
- components/locales/ur-PK.json
- components/locales/uz-UZ.json
- components/locales/zh-HK.json
After updating to v20.0.2 we started getting exception:
`JsonReaderException: '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 3 | BytePositionInLine: 4.`
After some investigation I have noticed that there is a problem reading `lt_LT` locale. Then I noticed that there are comments in lt locale json file and JSON deserialized does not expect them.
So this PR just removes comments that causes exception.
| 🇺🇸 English | remove comments from lt locale json file  |
> i18n: remove comments from locale json files

- components/drawer/Drawer.razor.cs
- components/drawer/DrawerService.cs
- components/drawer/config/DrawerOptions.cs
- site/AntDesign.Docs/Demos/Components/Drawer/demo/Drawer_event.razor
- site/AntDesign.Docs/Demos/Components/Drawer/demo/Drawer_service.razor
- site/AntDesign.Docs/Demos/Components/Drawer/demo/Multiple.razor
> refactor(module: drawer): Change the Height and Width of the Drawer to the string type to support the percentage argument

- components/select/SelectBase.razor.cs
> fix(module: select): An exception is raised when values change in some cases.

- components/drawer/Drawer.razor.cs
> fix(module: drawer): closing animation effect

- components/form/Form.razor.cs
> fix(module: form): check if _editContext exists when disposing

- components/table/Column.razor.cs
- components/table/Table.razor.Selection.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/RowSelection_.razor
> feat(module: table): add SelectAll event callback

- site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
> docs: fix demo discovery

- components/AntDesign.csproj
- components/core/Documentation/PublicApiAttribute.cs
- components/tree-select/TreeSelect.razor.cs
- components/tree/TreeNode.razor.cs
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/CustomDropdownMenu.razor
- site/AntDesign.Docs/Pages/Static/Components/Overview.razor
- site/AntDesign.Docs/Resources/en-US.json
- site/AntDesign.Docs/Resources/zh-CN.json
> remove InternalsVisibleTo AntDesign.Docs

- components/date-picker/DatePicker.Razor.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
Update the Focus method access level
- [ X] Bug fix
> Update the Focus method access level

- components/card/Card.razor
- components/card/Card.razor.cs
- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- tests/AntDesign.TestApp/Client/Pages/Index.razor
- tests/AntDesign.Tests/Card/Card.Render.Tests.razor
… status
| 🇺🇸 English | Fix the issue where the Tabs under the Card cannot remember the input status          |
| 🇨🇳 Chinese |  修复Card下面的Tabs不能记忆输入状态的问题         |
> Fix the issue where the Tabs under the Card cannot remember the input status

- .github/workflows/preview-build.yml
- components/drawer/Drawer.razor
- components/drawer/Drawer.razor.cs
- components/drawer/DrawerContainer.razor
- site/AntDesign.Docs/Demos/Components/Drawer/demo/Basic.razor
- tests/AntDesign.Tests/Drawer/DrawerTests.cs
> fix(module: drawer): closing effects

- components/auto-complete/AutoComplete.razor.cs
- components/auto-complete/AutoCompleteInput.cs
- components/auto-complete/IAutoCompleteRef.cs
> fix(module: auto-complete): open panel immediately when options was changed

- components/select/SelectBase.razor
- components/select/internal/SelectContent.razor
> fix(module: select): fix reference and remove the duplicaed div

- components/tabs/Tabs.razor.cs
> fix(module: tabs): add end remove

- components/tree/TreeNodeTitle.razor
> fix(module: tree): recover pointer events

- components/date-picker/internal/DatePickerBase.cs
> refactor(module: date-picker): make close() public

- .github/workflows/AntDesignDocsWebApp.yml
- .github/workflows/nightly-build.yml
- .github/workflows/release-AOT.yml
- .github/workflows/release.yml
> chore: fix upload-artifact actions

- .github/workflows/release-AOT.yml
> fix build action

- components/core/Base/AntComponentBase.cs
- components/core/Base/AntDomComponentBase.cs
- components/select/SelectBase.razor
fix the issue cause by PR #4175 
> fix(module: select): dropdown broken

- site/AntDesign.Docs/Pages/Components.razor
- site/AntDesign.Docs/Shared/DocDemoView.razor
> docs: fix doc demo

- scripts/gh-pages/index.html
> docs: fix g2plot js

- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
> fix(module: treeselect): select content reference throwing exception

- components/button/Button.razor.cs
- site/AntDesign.Docs/Demos/Components/Button/demo/Loading.razor
- site/AntDesign.Docs/Demos/Components/Button/demo/loading.md
> feat(module: button): add AutoLoading parameter

- components/core/Extensions/ParameterViewExtensions.cs
- components/core/JsInterop/modules/dom/eventHelper.ts
- components/menu/Menu.razor.cs
- components/menu/MenuItem.razor.cs
- components/menu/MenuLink.cs
> fix(module: menu): avoid the SelectedKeys set to null when it was not bound.

- components/tabs/TabPane.razor
- components/tabs/TabPane.razor.cs
- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs/Demos/Components/Tabs/demo/ContextMenu.razor
- site/AntDesign.Docs/Demos/Components/Tabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tabs/doc/index.zh-CN.md
- tests/AntDesign.Tests/Card/Card.Render.Tests.razor
> fix(module: tabs): draggable and contextmenu incottectly

- components/tabs/Reuse/ReuseTabs.razor
- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/Reuse/ReuseTabsService.cs
- components/tabs/Tabs.razor.cs
> refactor(module: reusetabs): inherts tabs

- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- site/AntDesign.Docs/Demos/Components/Form/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Form/demo/RequiredMark.razor
- [√] New feature
FormItem do not have a feature to give user good UI to display tooltip
Add Tooltips parameter in formitem component.
| 🇺🇸 English | Feat: Add Tooltip to formitem component          |
| 🇨🇳 Chinese |功能:FormItem组件添加文字提示           |
- [√] Doc is updated/provided or not needed
> Feat(form item tooltip)

- components/core/Component/KeepAlive.cs
- components/tabs/Reuse/ReuseTabs.razor
- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/Reuse/ReuseTabsPageItem.cs
- components/tabs/Reuse/ReuseTabsService.cs
- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/dynamic-title.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/singleton.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/title-attribute.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.zh-CN.md
- site/AntDesign.Docs/Routes.razor
> feat:(module: reusetabs): Allow reusetabs to operate independently of cascaded routing data

- components/input/Search.razor.cs
- [√] Bug fix
#4210 
AddAttribute for search component
| 🇺🇸 English | AddAttribute for search component button          |
| 🇨🇳 Chinese | 给Search组件的Button添加属性          |
- [] Demo is updated/provided or not needed
> fix: Search component disable parameter does not disable button

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
> docs: add breaking changes for 1.0 RC1

- components/tabs/Tabs.razor.cs
> fix(module: tabs): GoTo method would throwing null reference exception

- components/menu/MenuItem.razor
- components/menu/MenuItem.razor.cs
> fix(module: menu): tooltip doesn't work

- components/input/Search.razor.cs
> fix(module: search): Remove the invalid attribute.

- components/tabs/Tabs.razor.cs
> fix(module: tabs): getting size indefinitely when it is rendered but hidden.

- .github/workflows/preview-build.yml
- .github/workflows/release-AOT.yml
- site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
- site/AntDesign.Docs.Build.CLI/Documentations/GenerateApiDocumentation.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
- site/AntDesign.Docs/Pages/Components.razor
> docs: fix file name for prerendering html

- components/tree-select/TreeSelect.razor
- components/tree-select/TreeSelect.razor.cs
- components/tree/Tree.razor.cs
- components/tree/TreeNode.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- site/AntDesign.Docs/Demos/Components/Tree/demo/NodeSelectable.razor
- site/AntDesign.Docs/Demos/Components/Tree/demo/node-checkable.md
- site/AntDesign.Docs/Demos/Components/Tree/demo/node-selectable.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/NodeSelectable.razor
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/node-checkable.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/demo/node-selectable.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/TreeSelect/doc/index.zh-CN.md
> feat(module: tree): Add `Selectable` & `SelectableExpression` to mark whether TreeNode can be selected or not.

- components/tree-select/TreeSelect.razor.cs
> fix(module: treeselect): Fix a bug which may trigger `OnSelectedItemChanged` twice.

- components/core/JsInterop/modules/components/tableHelper.ts
- components/table/Table.razor.cs
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
| 🇺🇸 English | fix AutoHeight algorithm          |
| 🇨🇳 Chinese | 修改AutoHeight算法          |
> fix(module:table) fix AutoHeight algorithm

- components/tabs/Tabs.razor.cs
- site/AntDesign.Docs/Demos/Components/Tabs/demo/EditableCard.razor
> Fix ink in tabs when adding new tabPane

- components/core/Base/AntInputComponentBase.cs
- components/core/Reflection/PropertyReflector.cs
> fix(module: form): support field validation

- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- components/tabs/style/index.less
| 🇺🇸 English |Fix tab size issue           |
| 🇨🇳 Chinese |修复Tab size问题           |
> Fix tab size issue

- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- components/tabs/style/index.less
- components/tabs/style/patch.less
| 🇺🇸 English | fix tab size issue          |
| 🇨🇳 Chinese | 修复tab size问题          |
> fix(module:tabs) fix tab size issue

- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
- components/tabs/style/index.less
- components/tabs/style/patch.less
| 🇺🇸 English |    fix tab size issue       |
| 🇨🇳 Chinese |  修复tab size问题         |
> fix(module:tabs): fix tab size issue

- components/form/Form.razor.cs
> fix(module: form): prevent building edit context in dead loop

- components/tabs/Reuse/ReuseTabs.razor
- components/tabs/Reuse/ReuseTabs.razor.cs
- components/tabs/Reuse/ReuseTabsService.cs
- components/tabs/TabPane.razor
- components/tabs/TabPane.razor.cs
> pref(module: tabs): make tab pane only render once

- components/space/Space.razor.cs
- components/space/SpaceItem.razor.cs
- components/space/types/SpaceAlign.cs
- components/space/types/SpaceSize.cs
- site/AntDesign.Docs/Demos/Components/Space/demo/Align.razor
- site/AntDesign.Docs/Demos/Components/Space/demo/Size.razor
This simply adds string constants for size and align for space as they were missing.
Added string constants for align and size for space
> Add space string constants

- .github/workflows/AntDesignDocsWebApp.yml
- .github/workflows/nightly-build.yml
- .github/workflows/preview-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-AOT.yml
- .github/workflows/release.yml
- site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj
- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
Use standard target framework, remove unnecessary conditions
> Update net9 target usage

- components/tabs/Reuse/ReuseTabsService.cs
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Ignore.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Ignore.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.zh-CN.md
> fix(module: reuse-tabs): page filter after getting the config from pages

- components/steps/Step.razor
- components/steps/Step.razor.cs
- components/steps/Steps.razor.cs
- components/steps/StepsDirection.cs
- components/steps/StepsLabelPlacement.cs
- components/steps/StepsSize.cs
- components/steps/StepsStatus.cs
- components/steps/StepsType.cs
- site/AntDesign.Docs/Demos/Components/Steps/demo/Clickable.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/CustomizedProgressDot.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/Error.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/Icon_.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/Nav.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/ProgressDot.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/SmallSize.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/StepNext.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/Vertical.razor
- site/AntDesign.Docs/Demos/Components/Steps/demo/VerticalSmall.razor
This simply adds string constants for various steps attributes as they were missing.
Added string constants for various steps attributes
> Add steps constants

- components/select/SelectBase.razor.cs
- components/select/internal/SelectContent.razor
- components/select/internal/SelectContent.razor.cs
> fix(module: select): clear the search value when the dropdown is closing

- components/select/Select.razor.cs
- components/select/SelectBase.razor.cs
- components/select/internal/SelectContent.razor
- components/select/internal/SelectContent.razor.cs
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/Search.razor
- site/AntDesign.Docs/Demos/Components/Select/demo/search.md
> fix(module: select): clear and discovery the search value

- components/tree-select/TreeSelect.razor.cs
> feat(module: tree-select): Add some public methods.

- components/auto-complete/AutoComplete.razor
- components/auto-complete/AutoComplete.razor.cs
- components/core/Extensions/ParameterViewExtensions.cs
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/basic.md
- site/AntDesign.Docs/Demos/Components/AutoComplete/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/AutoComplete/doc/index.zh-CN.md
breaking change:
AllowFilter is default to false.
> fix(module: auto-complete): prevent opening empty panel

- components/empty/Empty.razor
- components/empty/Empty.razor.cs
> fix(module: empty): the image doesn't show in dropdown

- components/core/JsInterop/modules/components/overlay.ts
- components/core/JsInterop/modules/dom/infoHelper.ts
- site/AntDesign.Docs.Build.CLI/KnownChineseTranslations.json
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/PopupContainer.razor
- tests/AntDesign.Tests.Js/package-lock.json
- tests/AntDesign.Tests.Js/package.json
> fix(module: overlay): dropdown should follow the scrolling with trigger

- components/core/JsInterop/modules/components/overlay.ts
> fix(module: overlay): dropdown scrolling

- components/tree/style/patch.less
> fix(module: tree): the style of line indent

- components/select/Select.razor.cs
- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
- components/select/SelectOption.razor
- components/select/SelectOption.razor.cs
- components/select/internal/SelectContent.razor.cs
- components/tree-select/TreeSelect.razor.cs
> fix(module:select): Resolve issues with search input in Select/TreeSelect.

- components/tree-select/TreeSelect.razor.cs
> fix(module:tree-select): Fix that the clear button cannot deselect the selected item when TItemValue is a non-nullable type.

- components/space/Space.razor.cs
- components/space/SpaceItem.razor.cs
- components/space/types/SpaceAlign.cs
- components/space/types/SpaceSize.cs
- site/AntDesign.Docs/Demos/Components/Space/demo/Align.razor
- site/AntDesign.Docs/Demos/Components/Space/demo/Size.razor
Reverts ant-design-blazor/ant-design-blazor#4277
> Revert "Revert "Add space string constants""

- components/form/FormItem.razor.cs
> fix(module: form): setting dictionary as model would thrown NRE

- components/core/JsInterop/modules/dom/manipulationHelper.ts
- components/drawer/Drawer.razor.cs
- components/drawer/style/entry.less
- components/drawer/style/patch.less
- components/modal/core/Dialog.razor
- components/modal/core/Dialog.razor.cs
- components/modal/modalDialog/Modal.razor.cs
- components/modal/style/patch.less
> fix(module: modal): use css var to hide/show the scroll bar of body

- components/drawer/style/patch.less
- components/image/style/patch.less
- components/modal/style/patch.less
> fix(module: modal): only hide scrollbar when enable mask

- components/locales/lt_LT.json
> fix(locale): add missing number range message of It_LT locale

- components/modal/core/Dialog.razor.cs
> fix(module: modal): should call js interop after renderering

- components/locales/nl-NL.json
- [☑️] Other (about what?)
None
Table component showed English texts in the filter options, added missing translation for Dutch in locales json.
Added missing translation items for Dutch.
| 🇺🇸 English | Table component added missing translation items for Dutch. |
- [☑️] Doc is updated/provided or not needed
- [☑️] Demo is updated/provided or not needed
- [☑️] Changelog is provided or not needed
> Added missing translation items for Dutch.

- components/select/SelectBase.razor.cs
> fix(module: tree-select): the selection doesn't bind default values

- components/tree-select/TreeSelect.razor.cs
- components/tree/Tree.razor.cs
> fix(module:tree/tree-select): Fix tree/node's null value may cause exception.

- README-zh_CN.md
- README.md
- components/AntDesign.csproj
- docs/introduce.en-US.md
- docs/introduce.zh-CN.md
- site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
- site/AntDesign.Docs.WebApp/AntDesign.Docs.WebApp.csproj
- src/AntDesign.Extensions.Localization/AntDesign.Extensions.Localization.csproj
> Update to .NET 9 GA

- components/locales/nl-NL.json
Add dutch translation for ReuseTabs Reload property
Add dutch translation for ReuseTabs Reload property
| 🇺🇸 English | Add dutch translation for ReuseTabs Reload property |
- [☑️] Doc is updated/provided or not needed
- [☑️] Demo is updated/provided or not needed
- [☑️ ] Changelog is provided or not needed
> Add dutch translation for ReuseTabs Reload

- site/AntDesign.Docs/Demos/Components/Table/demo/RouterPagination.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/RowSelection_.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/ajax.md
- site/AntDesign.Docs/Demos/Components/Table/demo/basic-bind-field.md
- site/AntDesign.Docs/Demos/Components/Table/demo/bordered.md
- site/AntDesign.Docs/Demos/Components/Table/demo/custom-field-filter.md
- site/AntDesign.Docs/Demos/Components/Table/demo/custom-row-style.md
- site/AntDesign.Docs/Demos/Components/Table/demo/custom-sort.md
- site/AntDesign.Docs/Demos/Components/Table/demo/dynamic.md
- site/AntDesign.Docs/Demos/Components/Table/demo/ellipsis.md
- site/AntDesign.Docs/Demos/Components/Table/demo/filter.md
- site/AntDesign.Docs/Demos/Components/Table/demo/fixed-columns-header.md
- site/AntDesign.Docs/Demos/Components/Table/demo/grouping-columns.md
- site/AntDesign.Docs/Demos/Components/Table/demo/head.md
- site/AntDesign.Docs/Demos/Components/Table/demo/nested-table.md
- site/AntDesign.Docs/Demos/Components/Table/demo/on-row-and-on-cell.md
- site/AntDesign.Docs/Demos/Components/Table/demo/resizable-column.md
- site/AntDesign.Docs/Demos/Components/Table/demo/restore-query-state.md
- site/AntDesign.Docs/Demos/Components/Table/demo/router-pagination.md
- site/AntDesign.Docs/Demos/Components/Table/demo/row-selection.md
- site/AntDesign.Docs/Demos/Components/Table/demo/toggle-column.md
- site/AntDesign.Docs/Demos/Components/Table/demo/tree-data-with-circular-reference.md
- site/AntDesign.Docs/Demos/Components/Table/demo/tree-data.md
Some of the English documentation was inconsistent or unclear due to translation.
> Various updates to English documentation for Table

- .gitignore
- components/AntDesign.csproj
- site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
- site/AntDesign.Docs.Build/AntDesign.Docs.Build.csproj
- site/AntDesign.Docs/AntDesign.Docs.csproj
- site/AntDesign.Docs/Routes.razor
- tests/AntDesign.TestKit/AntDesign.TestKit.csproj
- tests/AntDesign.Tests/AntDesign.Tests.csproj
> chore: update the building staff to .NET 9 target

- components/spin/Spin.razor.cs
> fix(module: spin): show text style

- components/table/ActionColumn.razor.cs
- components/table/Column.razor.cs
- components/table/ColumnContext.cs
- components/table/IColumn.cs
- components/table/Selection.razor.cs
This moves the `Hidden` parameter on `ColumnBase` to `IColumn`. I had the need to customize the `Table` component and work with the `ColumnContext`, but I could not validate if a column was hidden. Also fixed a minor spelling mistake of an internal method name.
> IColumn Hidden

- components/table/Table.razor.RowData.cs
- components/table/TableModels/GroupResult.cs
- components/table/TableModels/RowData.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/GroupingRows.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/grouping-columns.md
- site/AntDesign.Docs/Demos/Components/Table/demo/grouping-rows.md
… 
fixed #4355
| 🇺🇸 English |    row grouping cannot be expanded programmatically because it is not cached correctly       |
| 🇨🇳 Chinese |   行分组由于未正确缓存导致无法通过程序方式展开        |
> fix(module: table): row grouping cannot be expanded programmatically because it is not cached correctly

- .github/workflows/preview-build.yml
- .github/workflows/preview-deploy.yml
- .github/workflows/release-AOT.yml
> chore: deploy on cloudflare pages

- site/AntDesign.Docs/Demos/Components/Layout/demo/TopSide.razor
- site/AntDesign.Docs/Demos/Components/Layout/demo/TopSide2.razor
> docs: fix layout demo for menu title

- components/modal/modalDialog/Modal.razor.cs
> feat(module: modal): add parameter AfterOpen

- components/table/ColumnBase.cs
- components/table/ColumnContext.cs
- components/table/GenerateColumns.razor.cs
- components/table/ITable.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/GenerateColumns_.razor
The problem is that component initialisation order is not guaranteed so assigning column index by column context is very brittle and in case if some columns in table have nested component structure it can mess up order and incorrect indexes will be assigned which leads to broken table. With this change, there is an option to disable automatic column index assignment through context and assign indexes to columns by hand. It does not change behaviour with default parameter values so if AutoColIndex property isn't assigned to table, nothing changes. Alternative way of stabilising table is to assign columns as an array of render fragments, however it will require significant changes in API.
Risks are new exposed API which then can be difficult to rollback once it will be used in projects.
| …
> Add disable auto column index feature

- components/table/Column.razor
- components/table/ColumnBase.cs
- components/table/ITable.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Expand.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/TreeData.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/tree-data.md
> feat(module: table): support lazy load for tree data

- components/AntDesign.csproj
- components/theme/util/StyleUtil.cs
> chore: reparing for AntDesign.AI components

- .github/workflows/nightly-build-v5.yml
> chore: fix github actions for publish nuget

- .github/workflows/nightly-build-v5.yml
> chore: fix github actions for building

- .github/workflows/nightly-build-v5.yml
> chore: packing without styel gen

- components/table/Table.razor.RowData.cs
- [ √] Bug fix
@dotnet-policy-service agree
> The issue that grouped sub-data is not refreshed is fixed

- components/typography/Title.cs
- site/AntDesign.Docs/Demos/Components/TypographyBase/demo/Interactive.razor
- site/AntDesign.Docs/Demos/Components/TypographyBase/demo/Level.razor
> feat(module: typography): add level 5 for title

- site/AntDesign.Docs.Server/Program.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Dynamic.razor
- site/AntDesign.Docs/Services/HttpClientHandler.cs
- [ X] Bug fix
Please visit [issue #4378](https://github.com/ant-design-blazor/ant-design-blazor/issues/4378)
**Issue reason :**
The GitHub API requires a User-Agent header to identify the client making the request.
For Dynamic data sample of the Table component **The error 403 (Forbidden)**  is happening in local debugging means that the GitHub API deny the request due to User-Agent Header Missing.
**Solution :**
I've added **User-Agent** to the header of request for local debugging.
Also if Github denied the request with unexpected reasons to avoid errors, I used Try/Catch.
> Fixed error when fetching data for the table (dynamic data sample) in local.

- components/input/Input.cs
- site/AntDesign.Docs/Demos/Components/Input/demo/TextAreaBasic.razor
> fix(module: input): the OnPressEnter doesn't work for TextArea

- components/icon/IconService.cs
> feat(module: icon): support custom svg string

- components/statistic/Statistic.razor.cs
> fix(module: statistic): overflow exception cause by int extraction

- components/date-picker/internal/DatePickerPanelBase.cs
- components/date-picker/internal/DatePickerTemplate.razor
- components/modal/config/DialogOptionsBase.cs
- components/modal/type/ConfirmIcon.cs
- components/result/Result.razor.cs
> fix: some style issue cause by the typed enum parameters change

- site/AntDesign.Docs/Pages/Components.razor
> docs: fix demo clearing when navigating

- components/tabs/Tabs.razor.cs
> fix(module: tabs): ink rendering when adding tabs

- components/badge/Badge.razor.cs
- components/badge/BadgeRibbon.razor.cs
- components/badge/BadgeSize.cs
- site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
- site/AntDesign.Docs/Demos/Components/Badge/demo/Ribbon.razor
- site/AntDesign.Docs/Demos/Components/Badge/demo/Size.razor
- site/AntDesign.Docs/Demos/Components/Badge/demo/colorful.md
- site/AntDesign.Docs/Demos/Components/Badge/demo/link.md
- site/AntDesign.Docs/Demos/Components/Badge/demo/offset.md
- site/AntDesign.Docs/Demos/Components/Badge/demo/ribbon.md
- site/AntDesign.Docs/Demos/Components/Badge/demo/size.md
- site/AntDesign.Docs/Demos/Components/Badge/demo/status.md
> refactor(module: badge): changed the type of Size and Color of BadgeRibbon to be enum

- components/upload/Upload.razor
- components/upload/UploadButton.razor.cs
- site/AntDesign.Docs/Demos/Components/Upload/demo/PictureStyle.razor
> fix(module: upload): error cause by OneOf converting

- components/core/JsInterop/modules/components/backtopHelper.ts
- site/AntDesign.Docs/Demos/Components/BackTop/demo/Custom.razor
> fix(module: backtop): scrolling in a dead loop

- components/auto-complete/AutoComplete.razor.cs
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/CustomFilter.razor
- site/AntDesign.Docs/Demos/Components/AutoComplete/demo/custom-filter.md
> refactor(module: auto-complete): make ShowPanel obsoleted

- components/table/Table.razor.cs
- site/AntDesign.Docs.Build.CLI/Documentations/GenerateApiDocumentation.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/TreeData.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/auto-height.md
- site/AntDesign.Docs/Demos/Components/Table/demo/colspan-rowspan.md
- site/AntDesign.Docs/Demos/Components/Table/demo/grouping-rows.md
- site/AntDesign.Docs/Demos/Components/Table/demo/head.md
- site/AntDesign.Docs/Demos/Components/Table/demo/row-template.md
- site/AntDesign.Docs/Demos/Components/Table/demo/tree-data.md
- site/AntDesign.Docs/Demos/Components/Table/faq.en-US.md
- site/AntDesign.Docs/Demos/Components/Table/faq.zh-CN.md
- site/AntDesign.Docs/Pages/Components.razor
- site/Shared/DemoComponent.cs
> docs(module: table): update treedata demo and orders

- components/tabs/Reuse/ReuseTabsPageItem.cs
- components/tabs/Reuse/ReuseTabsService.cs
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/NonRouteData.razor
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/non-route-data.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/doc/index.zh-CN.md
- site/AntDesign.Docs/Routes.razor
> Fix(module  reusetabs)  parameter update for singleton page

- components/typography/Typography.cs
> feat(module: Typography): add Typography article type

- site/AntDesign.Docs/Demos/Components/Dropdown/demo/Basic.razor
✅ Demo update
✅ Doc is updated/provided or not needed
> Unused Dropdown has been removed

- components/cascader/Cascader.razor
- components/cascader/Cascader.razor.cs
- site/AntDesign.Docs/Demos/Components/Cascader/demo/CustomTrigger.razor
- site/AntDesign.Docs/Demos/Components/Cascader/demo/custom-trigger.md
(cherry picked from commit 6e6369e89e3355c2dffe235d4a8b03d7dcde2742)
#	components/cascader/Cascader.razor
> feat(module: cascader): support custom trigger

- components/core/Component/Overlay/OverlayTrigger.razor.cs
- components/style/patch.less
> fix: inline style for overlay trigger warpper with inline child element

- scripts/gh-pages/index.html
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs.Wasm/wwwroot/index.html
- site/AntDesign.Docs.WebApp/Components/App.razor
> docs: fix docsearch undefined error

- components/cascader/Cascader.razor
- components/cascader/Cascader.razor.cs
- components/core/Component/Overlay/OverlayTrigger.razor.cs
- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
- components/tree-select/TreeSelect.razor.cs
> refactor(module: cascader): inherits from SelectBase

- components/cascader/Cascader.razor.cs
- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
> feat(module: select): add Placement for select-base components

- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Head_.razor
> fix(module: table): default sort directions was wrong

- components/core/Component/Overlay/Overlay.razor.cs
- components/core/Component/Overlay/OverlayTrigger.razor.cs
> feat(module: overlay): support control visiblity by Visible parameter

- components/cascader/Cascader.razor.cs
> feat(module: cascader): support value binding

- components/space/Space.razor.cs
- components/space/SpaceItem.razor.cs
> fix(module: space): size and align style

- scripts/gh-pages/index.html
- site/AntDesign.Docs.Server/Pages/_Layout.cshtml
- site/AntDesign.Docs.Wasm/wwwroot/index.html
- site/AntDesign.Docs.WebApp/Components/App.razor
> docs: add peter cat

- components/table/Column.razor
- components/table/Filters/FilterInputs.razor
> fix(module: table): add min-width for filter input

- components/badge/BadgeRibbon.razor.cs
- tests/AntDesign.Tests/badge/RibbonTests.cs
> fix(module: badge): ribbon preset color

- components/auto-complete/AutoComplete.razor.cs
> fix(module: auto-complete): show panel when adding options asynchronously

- components/menu/MenuService.cs
- site/AntDesign.Docs/Demos/Experimental/ReuseTabs/demo/Layout_.razor
> fix(module: breadcrumb):  auto-generating should be matched against the MenuItem's RouterMatch

- components/timeline/Timeline.razor.cs
- components/timeline/TimelineItem.cs
- site/AntDesign.Docs/Demos/Components/Timeline/demo/Color.md
- site/AntDesign.Docs/Demos/Components/Timeline/demo/Color.razor
- tests/AntDesign.Tests/Timeline/TimelineTests.razor
- tests/AntDesign.Tests/_Imports.razor
> fix(module: timeline): color incorrectly

- site/AntDesign.Docs/Pages/Components.razor.cs
- site/AntDesign.Docs/Shared/CodeBox.razor
> docs: fix codebox expand

- components/core/JsInterop/modules/dom/manipulationHelper.ts
> fix(module: modal): shouldn't show padding without scrollbar

- components/tabs/Reuse/ReuseTabs.razor.cs
> fix(module: ReuseTabs): throwing NRE when any route value is null

- tests/AntDesign.TestKit/AntDesign.TestKit.csproj
- tests/AntDesign.Tests/AntDesign.Tests.csproj
> chore: remove FluentAssertions from TestKit

- components/table/Filters/FilterInputs.razor
> fix(module: table): the BoundaryAdjustMode of filter components

- components/table/Table.razor.cs
- components/table/TableModels/QueryModel.cs
> fix(module: table): possible infinite loop when pager is hidden and pagesize is set

- components/core/DictionaryConverter.cs
- components/table/Column.razor
- components/table/Column.razor.cs
- components/table/Filters/BaseFieldFilterType.cs
- components/table/Filters/DateFieldFilterType.cs
- components/table/Filters/FilterTypeResolver.cs
- components/table/Filters/IFieldFilterType.cs
- components/table/Filters/StringFieldFilterType.cs
- components/table/IColumn.cs
- components/table/IFieldColumn.cs
- components/table/PropertyColumn.cs
- site/AntDesign.Docs.Server/Program.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/DataTable_.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/Dynamic.razor
> feat(module: table): dynamic column support recognizes the type of filter by the object column type

- components/core/Component/Overlay/Overlay.razor.cs
- components/table/Column.razor
- components/table/Column.razor.cs
…on from between to equals
fixed #4317
> fix(module: table): error was thrown when changing the filter operation from between to equals

- components/table/ISelectionColumn.cs
- components/table/Selection.razor.cs
- components/table/Table.razor.cs
> fix(module: table): checked selection would be cleared by disabled one on pagging

- components/table/ColumnBase.cs
- components/table/Selection.razor.cs
> fix(module: table): the check-all state can't be updated correctly

- components/form/FormItem.razor
- components/form/FormItem.razor.cs
> fix(module: form): change Help message dynamicly

- components/tabs/TabPane.razor
> fix(module: tabs): when a tab is closed, the context menu of the tab to its right does not work

- components/locales/tr-TR.json
None
tr-TR locale has been updated. Missing translations have been added (e.g. table filter operators). Some existing translations have been replaced with more accurate ones.
| 🇺🇸 English | tr-TR locale has been updated. |
> fix(locale): update tr-TR locale

- components/flex/Flex.razor.cs
- components/flex/FlexDirection.cs
- site/AntDesign.Docs/Demos/Components/Flex/demo/Align.razor
- site/AntDesign.Docs/Demos/Components/Flex/demo/Basic.razor
- site/AntDesign.Docs/Demos/Components/Flex/demo/Combination.razor
- site/AntDesign.Docs/Demos/Components/Flex/demo/Gap.razor
- site/AntDesign.Docs/Demos/Components/Flex/doc/index.en-US.md
Refactored the `Vertical` attribute to use `FlexDirection`, similar to `Space.Direction`. This also allows for expansion in the future to support other `flex-direction` CSS values.
Replaced `Flex.Vertical` with `Flex.Direction`
> Refactor Vertical property on Flex to Direction

- CHANGELOG.en-US.md
- CHANGELOG.zh-CN.md
- components/table/Table.razor.Pagination.cs
> docs(table): describe the behavior of HidePagination

- components/date-picker/DatePicker.Razor.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
> refactor(module: datepicker): separate the Disabled parameter of DatePicker and RangePicker

- components/progress/Progress.razor.cs
> fix(module: progress): Status parameter is incorrect

- components/core/JsInterop/modules/components/overlayHelper.ts
> fix(module: overlay): position is not correctly adjusted when it is opened beyond the boundary

- components/table/Table.razor.Selection.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/RowSelection_.razor
> fix(module: table): prevert trigger SelectedRowsChanged when the SelectedRows was changed outside

- components/menu/Menu.razor.cs
- components/menu/MenuService.cs
> fix(module: reuse-tabs): the title is not collected in its entirety from the menu

- components/locale-provider/LocaleProvider.cs
- tests/AntDesign.Tests/Cascader/CascaderTests.razor
> pref(locale): support json source generator for locale file Deserializaztion

- components/message/MessageExtensions.cs
- site/AntDesign.Docs/Demos/Components/Message/demo/LoadingWhen.razor
- site/AntDesign.Docs/Demos/Components/Message/demo/loading-when.md
- site/AntDesign.Docs/Demos/Components/Message/doc/index.en-US.md
- site/AntDesign.Docs/Demos/Components/Message/doc/index.zh-CN.md
close #4490 
All related infomation can be found in #4490 
为 IMessageService 提供了 LoadingWhen<T> 和 LoadingWhen 方法
- [] Changelog is provided or not needed
> Implement LoadingWhen API for IMessageService

- package.json
Fix the error when run by `npm run start`
> chore(node.js): fix the startup script of node.js to adapt to the .net9.0

- .github/workflows/nightly-build.yml
- .github/workflows/pull-request.yml
- components/date-picker/internal/DatePickerBase.cs
- tests/AntDesign.TestKit/AntDesignTestBase.cs
- tests/AntDesign.Tests/Avatar/AvatarTests.cs
- tests/AntDesign.Tests/DatePicker/DatePickerTests.razor
- tests/AntDesign.Tests/DatePicker/RangePickerTests.razor
https://github.com/xunit/xunit/issues/1742
Fix the System.ArgumentException exception in CI caused by implicit conversion
> fix the System.ArgumentException caused by implicit conversion

- .github/workflows/AntDesignDocsWebApp.yml
- .github/workflows/nightly-build.yml
- .github/workflows/preview-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release-AOT.yml
- .github/workflows/release.yml
| 🇺🇸 English |upgrade Node.js version to meet dependency requirements|
> upgrade Node.js version to meet dependency requirements

- components/table/Column.razor
- components/table/Table.razor.RowData.cs
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Expand.razor
> fix(module: table): avoid duplicated expand button while both RowExpandable and OnExpand was set

- components/form/Form.razor.cs
> fix(form): invoke StateHasChanged to update form state after validation

- docs/faq.en-US.md
- docs/faq.zh-CN.md
... when binding events, with an example for the `<Select>` component.
> docs(faq): Added explanation for CS1503 compilation error

- components/table/Column.razor
- components/table/ColumnBase.cs
- components/table/ITable.cs
- components/table/Table.razor
- components/table/Table.razor.cs
> refactor(table): streamline row expand logic and improve readability

- components/avatar/Avatar.razor.cs
- components/badge/Badge.razor.cs
- components/button/Button.razor.cs
- components/core/Base/AntInputComponentBase.cs
- components/flex/Flex.razor.cs
- components/input/Search.razor.cs
- components/menu/MenuLink.cs
- components/progress/Progress.razor.cs
- components/steps/Step.razor.cs
- components/upload/Upload.razor.cs
| 🇺🇸 English |     Replace HashTable with Dictionary<TKey, TValue>     |
| 🇨🇳 Chinese |    使用Dictionary<TKey, TValue>替换HashTable    |
> refactor: replace HashTable with Dictionary<TKey, TValue>

- components/form/Internal/Validate/FormValidateHelper.cs
- tests/AntDesign.Tests/Form/Validation/FormValidateHelperTest.cs
> refactor(module: form): add Model property to validation context

- components/core/CssSizeLength.cs
- components/core/DictionaryConverter.cs
- components/core/Helpers/Formatter.cs
- components/date-picker/internal/DateTimeInputMaskConverter.cs
- components/drawer/Drawer.razor.cs
- components/form/Internal/Validate/ValidationAttribute/TypeAttribute.cs
- components/grid/Col.razor.cs
- components/mentions/Mentions.razor.cs
- components/progress/Progress.razor.cs
| 🇺🇸 English |     Improve Regex with Source Generator      |
| 🇨🇳 Chinese |    使用源生成器提升Regex性能       |
> perf: Improve Regex with SG

- components/LocalizedIntellisenseFiles/ja-JP/AntDesign.xml
- components/LocalizedIntellisenseFiles/ko-KR/AntDesign.xml
- components/LocalizedIntellisenseFiles/ru/AntDesign.xml
- components/LocalizedIntellisenseFiles/zh-CN/AntDesign.xml
- components/LocalizedIntellisenseFiles/zh-HK/AntDesign.xml
- components/LocalizedIntellisenseFiles/zh-TW/AntDesign.xml
- components/collapse/Collapse.razor.cs
- components/core/Extensions/DataConversionExtensions.cs
- components/core/Extensions/EnumerableExtensions.cs
- components/core/Extensions/HttpClientExtensions.cs
- components/core/Extensions/ServiceCollectionExtensions.cs
- components/core/JsInterop/EventArg/MouseEvent.cs
- components/core/Services/ClientDimensionService.cs
- components/date-picker/RangePicker.razor.cs
- components/date-picker/internal/DatePickerBase.cs
- components/drawer/Drawer.razor.cs
- components/modal/modalDialog/Modal.razor.cs
- components/slider/Slider.razor.cs
- components/table/Table.razor.cs
* Fix some file namespace from `AntDesign.core.xxx` to `AntDesign.Core.xxx`
* Improve `EnumerableExtensions` which works at many places
* Add `params ReadOnlySpan<T>` which shall be better than `params T[]` for most scenes
| 🇺🇸 English |     Add `params ReadOnlySpan<T>` override     |
| 🇨🇳 Chinese |     新增`params ReadOnlySpan<T>`重载     |
> perf: Add `params ReadOnlySpan<T>` override

- components/upload/Upload.razor
fixed #4527
| 🇺🇸 English |    Fix the rendering issue when deleting items from the Upload file list.       |
| 🇨🇳 Chinese |   修复 Upload 文件列表删除时渲染问题        |
> fix(module: upload): render issue with file list removing

- components/notification/Notification.razor
- components/notification/Notification.razor.cs
- components/notification/NotificationItem.razor
- components/notification/NotificationItem.razor.cs
- components/notification/config/NotificationConfig.cs
> feat(module: notification): Supports pausing to disappear when the mouse moves over a notification

- components/message/Message.razor
- components/message/Message.razor.cs
- components/message/MessageItem.razor
- components/message/MessageItem.razor.cs
> feat(module: message): Supports pausing to disappear when the mouse moves over a message

- components/core/Component/Overlay/OverlayTrigger.razor.cs
- components/core/Extensions/HttpClientExtensions.cs
- components/core/Helpers/JsonSerializerHelper.cs
- components/core/JsInterop/DomEventListener.cs
- components/upload/UploadFileItem.cs
It's recommended to use a singleton of `JsonSerializerOptions` rather than create an instance each time for json serialization.
| 🇺🇸 English |      use `JsonSerializerOptions` singleton if possible     |
| 🇨🇳 Chinese |   尽量使用`JsonSerializerOptions`单例        |
> perf: use `JsonSerializerOptions` singleton if possible

- components/core/JsInterop/modules/components/uploadHelper.ts
- components/upload/Upload.razor.cs
- components/upload/UploadButton.razor.cs
- site/AntDesign.Docs.Server/Controllers/UploadController.cs
- site/AntDesign.Docs.Server/Program.cs
- site/AntDesign.Docs/Pages/UploadTest.razor
> feat(module: upload): add support for batch file uploads

- components/form/Form.razor.cs
- components/form/FormItem.razor.cs
- components/form/Internal/IFormItem.cs
> fix(module: form): changing the required rule dynamicly

- site/AntDesign.Docs/Demos/Components/Upload/demo/InputFile_.razor
- site/AntDesign.Docs/Demos/Components/Upload/demo/input-file.md
> docs(module: upload): add a demo for drag-and-drop inputfile support

- components/core/JsInterop/modules/components/uploadHelper.ts
- components/upload/Upload.razor.cs
- components/upload/UploadButton.razor.cs
> feat(module: upload): add withCredentials option for file uploads

- components/table/Table.razor.cs
> fix(module: table): no expand icon when ExpandTemplate was set

- components/collapse/Collapse.razor.cs
- components/collapse/Panel.razor.cs
- site/AntDesign.Docs/Demos/Components/Collapse/demo/ControlledActiveKeys.razor
- site/AntDesign.Docs/Demos/Components/Collapse/demo/controlled-activekeys.md
- Added `ActiveKeys` and `ActiveKeysChanged` parameters for external control of active panels.
- Introduced `_internalActiveKeys` for improved state management.
- Replaced `Click` method with `TogglePanelState` for clarity and functionality.
- Updated `Activate` and `Deactivate` methods to utilize new active keys logic.
- Modified header click handling in `Panel.razor.cs` to align with changes.
- Removed unnecessary translations from `KnownChineseTranslations.json`.
- Added example in `ControlledActiveKeys.razor` for using `@bind-ActiveKeys`.
- Updated documentation in `controlled-activekeys.md` for new feature guidance.
> feat(module: collapse): supports two-way binding for activing panels

- components/table/Column.razor
- components/table/Column.razor.cs
- components/table/ColumnBase.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Ellipsis.razor
> feat(module: table): Add EllipsisShowTitle property for columns

- components/core/JsInterop/modules/components/tableHelper.ts
- components/table/ColumnBase.cs
- components/table/ITable.cs
- components/table/Table.razor
- components/table/Table.razor.cs
- site/AntDesign.Docs/Demos/Components/Table/demo/Sticky.razor
- site/AntDesign.Docs/Demos/Components/Table/demo/sticky.md
- Added support for sticky scrolling in the table component, allowing the sticky scroll bar to appear when the table content is scrollable and the bottom of the table is not visible.
- Introduced methods for enabling and updating the sticky scroll behavior, including mouse drag functionality for the sticky scroll bar.
- Updated the table header and body to accommodate the new sticky scroll feature, ensuring proper styling and visibility.
- Enhanced the ColumnBase and ITable interfaces to support sticky positioning.
- Modified Table.razor to conditionally render the sticky scroll elements based on the new IsSticky property.
> feat(module: table): implement sticky scroll

- components/select/Select.razor.cs
- tests/AntDesign.Tests/Select/Select.Value.Tests.razor
- tests/AntDesign.Tests/Select/Select.Values.Tests.razor
> refactor(module: select): remove triggering events on value initialization

- components/select/Select.razor.cs
- components/select/SelectBase.razor.cs
- Updated the filtering mechanism to allow for a custom filter expression, with a fallback to default behavior if the custom expression is not provided or fails.
- Refactored the `CreateSelectOptionItem` method to handle item creation more robustly, including error handling for type conversions and custom tag logic.
- Removed redundant filter expression parameter initialization and improved code clarity.
fixed #4552
> refactor(module: select): enhance filtering logic and improve option creation

- components/select/Select.razor.cs
- components/select/internal/SelectContent.razor.cs
> fix(module: select): prevent search triggering during IME composition

- components/date-picker/RangePicker.razor.cs
- Updated value comparison logic to use EqualityComparer for better accuracy.
- Enhanced cloning of values to ensure proper state management when values change.
- Refactored array handling to prevent potential null reference exceptions and ensure correct value assignment.
- Added StateHasChanged call to ensure UI updates after value changes.
> fix(module: date-picker): improve value comparison and cloning in RangePicker

- components/tabs/Tabs.razor
- components/tabs/Tabs.razor.cs
> feat(module: tabs): add swipe functionality for tab navigation

- components/input/TextArea.razor
- tests/AntDesign.Tests/Input/TextAreaTests.razor
> fix(module: input): the Class parameter should assign to the textarea element

- site/AntDesign.Docs/Pages/Components.razor
- site/AntDesign.Docs/Pages/Docs.razor
> feat: add carbon ads script to Components and Docs pages

- components/splitter/SplitterPanel.cs
> fix(module: splitter): SplitterPanel missing namespace, also fixed CS8785 and RZ3008

- components/cascader/Cascader.razor.cs
- components/select/Select.razor.cs
- components/select/SelectBase.razor
- components/select/SelectBase.razor.cs
- components/select/SelectOption.razor.cs
- components/tree-select/TreeSelect.razor.cs
- site/AntDesign.Docs/Demos/Components/Cascader/demo/CustomTrigger.razor
- site/AntDesign.Docs/Demos/Components/Select/demo/Basic.razor
This commit introduces new parameters `ChildContent` and `SelectOptions` to the `Cascader`, `Select`, `SelectBase`, and `TreeSelect` components, allowing for more flexible content rendering. The `Select` component now includes an alias for `SelectOptions`, improving usability. Updates to `SelectBase` ensure proper handling of these parameters, and the `Basic.razor` file has been modified to showcase the new functionality with additional `SelectOption` entries. These changes enhance the component API and customization capabilities for developers.
> refactor(module: select): Add ChildContent as an alias of the SelectOptions renderfargment

- components/grid/Row.razor.cs
- components/grid/RowAlign.cs
- components/grid/RowJustify.cs
- components/space/SpaceAlign.cs
> fix(module: Grid): Add missing properties for RowAlign and SpaceAlign

- components/select/Select.razor.cs
- components/select/SelectBase.razor.cs
- components/select/SelectOption.razor.cs
- site/AntDesign.Docs/Demos/Components/Select/demo/Basic.razor
> fix(module: select): the default selected templated options didn't display on initialize

- components/splitter/Splitter.razor
Updated the Splitter component to wrap the FirstPane and SecondPane content in the KeepAlive component. This change enhances the state management of the panes, ensuring that their content remains preserved during re-renders, improving performance and user experience.
> refactor(module: splitter): Wrap pane content in KeepAlive component for improved state management

- site/AntDesign.Docs/Demos/Components/Modal/demo/FormInModal.razor
Fix Spelling Errors
- [ ✅] Site / documentation update
| 🇺🇸 English |     Fix Spelling Errors      |
| 🇨🇳 Chinese |        修正拼写错误   |
> Fix Spelling Errors

- components/carousel/Carousel.razor
- components/core/ConfigProvider/Form/FormValidateErrorMessages.cs
- components/date-picker/internal/DatePickerDatetimePanel.razor
- components/date-picker/locale/FormatAnalyzer.cs
- components/form/ColLayoutParam.cs
- components/form/Form.razor.cs
- components/form/FormItem.razor
- components/form/FormItem.razor.cs
- components/form/Internal/Validate/FormValidateHelper.cs
- components/form/Internal/Validate/ValidationAttribute/ArrayLengthAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/ArrayRangeAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/NumberAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/NumberMaxAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/NumberMinAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/OneOfAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/StringRangeAttribute.cs
- components/form/Internal/Validate/ValidationAttribute/TypeAttribute.cs
- components/input/Input.cs
- components/menu/SubMenu.razor
- components/table/Filters/StringFieldFilterType.cs
- components/upload/UploadButton.razor.cs
In the current version `1.4.1`, the validation error message of the `StringLengthAttribute` still reverses the min-max values of the string length: "xxx must be between 10 and 2 characters." This PR has fixed this problem and also supports the newly added `LengthAttribute` in .NET 8.
Additionally, this issue has optimized multiple scenarios of string case conversion and comparison, striving to eliminate the allocation of temporary strings to improve component performance.
| 🇺🇸 English |   Fix `StringLengthAttribute` validation message in Form; Add `LengthAttribute` validation of Form;  Optimize string ops |
| 🇨🇳 Chinese |  修复表单`StringLengthAttribute`校验信息；新增表单`LengthAttribute`验证；优化字符串操作    |
⚠️ Please check all items below before …
> fix(module: form): Improve validation messages

- components/core/JsInterop/modules/components/tableHelper.ts
- components/core/JsInterop/modules/dom/infoHelper.ts
- components/core/JsInterop/modules/dom/manipulationHelper.ts
- tests/AntDesign.Tests.Js/tests/domInit.ts
- tests/AntDesign.Tests.Js/tests/modules/dom/infoHelper.test.ts
- tests/AntDesign.Tests.Js/tests/modules/dom/manipulationHelper.test.ts
- Added manipulationHelper class with parseNumericValue method to safely parse CSS numeric values, handling cases like 'auto', 'inherit', and 'initial'.
- Updated tableHelper and infoHelper to utilize manipulationHelper for margin and padding calculations, improving robustness against invalid CSS values.
- Enhanced tests for manipulationHelper to cover various edge cases and ensure correct behavior for auto, inherit, and initial values.
fixed #4609
> feat(module: dom): Introduce manipulationHelper for safe CSS value parsing

- components/upload/Upload.razor
- components/upload/Upload.razor.cs
- components/upload/UploadButton.razor.cs
- components/upload/UploadState.cs
- site/AntDesign.Docs/Demos/Components/Upload/demo/UploadManually.razor
- site/AntDesign.Docs/Demos/Components/Upload/demo/uploadManually.md
- site/AntDesign.Docs/Demos/Components/Upload/doc/index.zh-CN.md
Added the manual upload functionality attribute UseManuallyMode; when the attribute is set to true, the file will not be uploaded immediately after it is changed, but will wait for the StartUpload method to execute before calling the upload script.
> feat(module: upload):manual upload

- components/table/style/patch.less
> fix(module: table): Adjust striped row background for fixed headers and columns

- components/core/Base/AntInputBoolComponentBase.cs
Added early return checks in OnValueChange and ChangeValue methods to prevent unnecessary updates when the new value is the same as the current value. This optimization reduces redundant operations and ensures event handlers are only invoked on actual value changes.
> fix(module: checkbox): prevent unnecessary updates when the new value is the same as the current value

- components/input-number/InputNumber.razor.cs
- site/AntDesign.Docs/Demos/Components/InputNumber/demo/Generic.md
- tests/AntDesign.Tests/InputNumber/InputNumberTests.razor
> feat(module: input-number): enhance initial value handling for nullable inputs

- components/table/Table.razor.Selection.cs
- components/table/TableModels/RowData.cs
- components/table/TableRow.razor
> feat(module:table): Add `ScrollItemIntoView` to make a specified row visible in the view.

- components/upload/Upload.razor
- site/AntDesign.Docs/Demos/Components/Upload/demo/Paste.razor
- site/AntDesign.Docs/Demos/Components/Upload/demo/UploadManually.razor
> feat(module: upload): show the image using the object URL first before uploading it when in defer mode.
