.github/workflows/gh-pages.yml
components/AntBlazor.xml
components/core/Helpers/StyleHelper.cs
components/layout/AntLayoutContent.razor
components/layout/AntLayoutSiderBase.cs
site/AntBlazor.Docs.ServerApp/Properties/launchSettings.json
site/AntBlazor.Docs/Shared/MainLayout.razor

feat：
1.add the "longBodyMode" parameter to AntLayoutSider.
2.add the "longContentMode" parameter to AntLayoutContent
3.add the self-adaption mode to side bar.
fix：
1.fix doc project page layout. 
2.set the default width value, cause if use forgot set this value, there throw the nullreference exception.
3.fix the user set 100% or xxxVH etc. the old style will add the px end of string. 
style： 
1.fix the menu margin, you will found that you lost one menu item which lastest in list.
2.add the footer to main layout
refactor：
1.Hide the adWidth

Fix some bug and add a little operation

---

.editorconfig
AntBlazor.sln
components/AntBlazor.csproj

- Invalid Property Naming convention will now throw an error instead of a warning, which will act like a Linter. However the build will still succeed on the GitHub workflow and locally(with errors) due to [this issue that has to be resolved by Microsoft](dotnet/roslyn#33558)
- Disabled the XML comments, it's handy but not always needed at this point.

Add EditorConfig for naming conventions

---

components/AntBlazor.csproj

这里的 $(SolutionDir) 需要在 sln 里面注入，如果直接构建 csproj 文件，那么将会找不到他的定义

Fix compile csproj

---

site/AntBlazor.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs

如果使用 Attributes  判断的时候，需要使用 HasFlag 的方法判断，因为这个值可能是多个值合并的
但是使用 HasFlag 的方法判断不够直观，于是就修改为 Exist 方法

Modify the method to judge the existence of the folder

---

site/AntBlazor.Docs/Services/ConcurrentCache.cs

When judging whether the value exists, the value still exists. But when getting the value, the value is killed by other threads
原先在 1 线程判断存在，在准备调用 dictionary[key].Value 返回的时候，在 2 线程更改删除了这个内容

Fix multi thread unsafe use method

---

components/button/AntButton.razor.cs
components/button/AntButtonType.cs
site/AntBlazor.Docs/Demos/Button/demo/Basic.razor
site/AntBlazor.Docs/Pages/Button.razor

This is according to Ant Design latest documentation. Also fixed "danger link button" not in correct color.

Fix: Remove "Danger" from Button Type

---

.gitattributes

Hi Team:
I found this project is marked as `CSS` project in github. So I create this pr to make github use `C#` as main language.
This pr will make `.css` and `.less` file list as C#, after apply these changes, the github display will as below:

Make github main language as C#

---

components/input/Search.razor.cs

已经使用await进行了等待，没有必要固定等待10秒，而且查询请求也无法固定成10秒。
I have used "await" to wait, there is no need to wait for 10 seconds, and the query request cannot be fixed to 10 seconds.

Fix: Search component wait time

---

components/spin/Spin.razor.cs

修正了“Spin”的“ Spinning”属性无效问题
Fixed an issue where the "Spinning" attribute of "Spin" was invalid

Fix : Spin "Spinning" attribute is invalid

---

site/AntBlazor.Docs/AntDesign.Docs.csproj

The current WorkingDirectory is set to $(SolutionDir) whilst $(SolutionDir)docs results in ../../docs
Steps to reproduce issue this fixes:
```
git clone https://github.com/ant-design-blazor/ant-design-blazor
npm install
npm start
----
/home/kieran/ant-design-blazor/site/AntBlazor.Docs/AntDesign.Docs.csproj(58,5): error MSB3073: The command "dotnet site/AntDesign.Docs.Build.CLI/bin/Debug/netcoreapp3.1/AntDesign.Docs.Build.CLI.dll docs2html ../../docs /home/kieran/ant-design-blazor/site/AntBlazor.Docs/wwwroot/docs" exited with code 1.
```

Update docs path in debug build

---

components/select/Select.razor.cs
site/AntBlazor.Docs/Demos/Select/demo/ClearValues.razor
site/AntBlazor.Docs/Demos/Select/demo/clear-values.md

I have to clear all selected tag values in the input filed of a select component in the form. So, I made a couple of changes in the base code of the Select component. Here are the explanations of changes.
1. ClearAll() method
Exposed method to a parent component.
2. ResetState() method
I made this method to avoid code duplicate of OnClearClick and ClearAll methods. It is always a better approach to have one main method for two or more same actions.
3. Removed all code of OnClearClick() method and called ResetState() method.
Please, notice that the md Select/demo/clear-values.md file should be rewritten based on the appropriate documentation. I just copied it from the bordered.md, but you know better than me what should be in there.
I am open to any kinds of suggestions. :) 
Kind regards, …

feat: clearall method to clear all items in the list

---

components/statistic/CountDown.razor
components/statistic/CountDown.razor.cs
site/AntBlazor.Docs/Demos/Statistic/demo/Countdown.razor

Let users does not need to handle any other unescaped character in a format string any more.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings#other-characters

refactor(module: statistic): simplify format string for countdown

---

components/input/Input.cs
components/input/TextArea.razor.cs

1、Input的value延迟更新功能会导致Input的OnInput事件异常，TextArea数据绑定失效，所以我删除了此功能
2、我任务在TextArea的OnInputAsync函数中不应该触发OnChange事件
3、我测试没有发现TextArea中调用base.OnInputAsync(args)存在失去焦点问题。

fix: input and textarea bug

---

components/core/EventCallbackArgs/OnResizeEventArgs.cs
components/input/Input.cs
components/input/TextArea.razor
components/input/TextArea.razor.cs
site/AntBlazor.Docs/Demos/Input/demo/Area.razor

1. Input BuildRenderTree: hardcode the arguments for sequence numbers.
Using a calculation or counter to generate the sequence number can lead to poor performance. [see the doc](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1#manual-rendertreebuilder-logic)
2. TextArea feat: support AllowClear、OnResize
3. TextArea fix:  fix the bugs(which [pr308](https://github.com/ant-design-blazor/ant-design-blazor/pull/308) had fix) in a better way

refactor: improve input and textarea

---

components/grid/Col.razor.cs

- Spans were not use emitting when using `Xs={ Span = 3 }`.
- Closes https://github.com/ant-design-blazor/ant-design-blazor/issues/321

fix(module: grid): fixed using size (xs, sm, etc) span with offset

---

components/anchor/Anchor.razor.cs
components/anchor/AnchorLink.razor.cs
components/anchor/IAnchor.cs
components/carousel/Carousel.razor.cs
components/carousel/CarouselSlick.cs
components/checkbox/Checkbox.razor.cs
components/descriptions/DescriptionsItem.razor.cs
components/icon/Icon.razor.cs
components/mentions/Mentions.razor.cs
components/mentions/MentionsOption.razor.cs
components/menu/MenuItem.razor.cs
components/radio/Radio.razor.cs
components/radio/RadioGroup.razor.cs
components/select/Select.razor.cs
components/select/SelectOptGroup.razor.cs
components/select/SelectOption.razor.cs
components/table/ColumnBase.cs
components/tabs/TabPane.razor.cs
components/timeline/Timeline.razor.cs
components/timeline/TimelineItem.cs

Children components using CascadingParameter add itself to parent component.However, when children components disposed, they are not remove from parent component. For example, when items in checkgroup have changed , it may causes Index was outside the bounds of the array at AntDesign.CheckboxGroup.OnCheckboxChange.To fix these bug, Adding remove function in dispose process is the solution of this commit.
子组件释放时候，并没有从父组件中的list中移除。
1导致timeline内容发生变化时，子内容显示不正确。
2.导致子组件会不断积累在父组件中。
3.radiogroup会发生System.IndexOutOfRangeException异常。

fix: children components dispose

---

components/core/Base/AntInputComponentBase.cs

fix #350 
| 🇺🇸 English |    fixed AntInputComponentBase always triggers statehaschanged |
| 🇨🇳 Chinese |  修复 AntInputComponentBase 总是触发 StateHasChanged  |

fix(module: AntInputComponentBase ): always triggers statehaschanged

---

site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs

The website is completely broken when accessing from a computer with a culture different from either en-US or zn-CH. This PR fixes the LanguageService to fallback to en-US when needed.

fix(docs): handles fallback to en-US if resources are not available

---

components/button/Button.razor.cs
tests/button/ButtonTests.cs

Once a button is rendered, changing Shape or Type has no effect. This change allows the Shape and Type to be changed after the initial render, just like other properties..

fix(module: button): allows type and shape to change

---

components/core/HashCodes/HashCode.cs
components/core/HashCodes/HashCodeExtensions.cs
components/core/HashCodes/HashCodeProvider.cs
components/core/HashCodes/ParameterDescriptor.cs
components/core/RenderMode.cs
components/table/Table.razor.cs

* #707 
* #579
在Blazor的Page，输入框的每个键入事件，会触发一次整个Page所有组件的渲染过程。在数据管理系统中，最常用的设计是顶部是多个数据查询输入框，中间部分是Table显示数据，如果Table的内容比较丰富（比如10列10行），搜索框每键入一个字母，在老爷机里肉眼能感觉到0.5秒或以上的卡顿，当然这个卡顿不是Input组件的问题，而是Table组件的复杂度在渲染时造成的。
我们可以改进让组件不进行没有意义的渲染，从而加快整个Page的渲染速度，Page上的Input在输入时不再卡顿。判断组件的某次渲染是否为有意义，可以使用计算组件下所有参数的HashCode是否有变化的方法，比如Table组件，计算其参数的 HashCode ,耗时大概0.2ms，而渲染一次耗时约500ms，这个投资是划算的。
组件的参数类型，我们可以分为三大类
* IDictionary<string, object>
* IEnumerable
* 非集合的普通类型
对于IDictionary<string, object>和IEnumerable，我们需要读取里面的元素进行HashCode计算，普通类型则直接使用对象提供的GetHashCode()方法。最后，我们为组件提供一个GetParametersHashCode()的扩展方法，用于计算其所有参数值的HashCode。
同时，我们为Table组件增加一个RenderMode组件参数，用于选择总结是渲染，还是参数值的HashCode变化了才渲染，以适应不同的场景的需求。

为组件提供所有参数值的哈希计算方法，用于改善复杂组件的渲染卡顿问题。

---

components/core/Extensions/HttpClientExtensions.cs

System.Text.Json在反序列化时，要求输入的流或二进制数据必须为utf8编码，虽然utf8是web默认的编码，但http允许服务指定返回其它编码的响应内容，所以HttpClientExtensions.GetFromJsonAsync()方法应该增加检测响应内容编码是否为utf8的逻辑，如果不是utf8需要先转码为utf8再反序列化。

修复HttpClientExtensions反序列化时没有判断内容是否为utf8编码的问题

---

components/core/Extensions/DataConvertionExtensions.cs

DataConvertionExtensions的Convert函数，旨在将泛型类型TFrom转换为既定的TTo类型，在实现上使用了表达树，但表达树编译后没有使用缓存委托，而是每次调用都会触发编译。我们可以使用UnSafe类提供的As这个Api来完成同样的功能，获得更高的性能。

提高DataConvertionExtensions的性能

---

components/core/Reflection/PropertyReflector.cs
components/form/FormItem.razor.cs

首先，PropertyReflector是一个内部类，所以才会进行这个破坏性的属性名称与类型修改。
RequiredAttribute声明的AttributeUsage的AllowMultiple值是false，意味着通过反射拿到的成员的RequiredAttribute，最多只有一个，所以我们将PropertyReflector的这个属性设计为非集合类型更合理，这个改动不影响任何已公开的Api。

PropertyReflector将IEnumerable<RequiredAttribute>属性替换为RequiredAttribute

---

components/core/CssSizeLength.cs

一般的，在实现GetHashCode上，我们倾向于使用异或两值，这个得到的值不会溢出。现在，我们还可以使用基础库提供的HashCode.Combine()方法来实现。

使用HashCode.Combine重构CssSizeLength的GetHashCode()方法

---

components/core/JsInterop/Element.cs
components/modal/Dialog.razor
components/modal/Dialog.razor.cs
components/radio/Radio.razor

#696 
| 🇺🇸 English |  1. Wrong type mapping between scrolltop and scrollleft in element; 2. Fix the problem that Radio triggers OnClick event twice; 3. Frequent click results in modal to close automatically. |
| 🇨🇳 Chinese | 1. Element中scrollTop与scrollLeft错误的类型映射; 2.修复Radio触发两次OnClick事件的问题; 3.快速点击下Modal自动关闭的问题. |

fix: modal box randomly closed when multiple mouse click performed within it (#696)

---

components/table/Table.razor.cs

当Table组件设置DataSource时，我们需要为_waitingReload变量赋值用以决定是否需要重新加载组件。当前使用HashCode<IEnumerable<TItem>>来比较数据源会引入问题，原因是TItem的GetHashCode（更多情况下）没有被正确重写。由于_waitingReload是在OnAfterRender()方法内使用的，将_waitingReload恢复为总是设置为true值，既可以保持RenderMode=Always的正确性，也不会影响到RenderMode=ParametersHashCodeChanged的场景。

Table设置数据源时_waitingReload应该总是为true值

---

components/steps/Step.razor

Hi there,
this is the fix for issue #759. Tested with both size modes (default/small) in Chrome/Edge/Firefox.

fix(module: steps) - Visual fix for issue #759

---

components/auto-complete/AutoComplete.razor
components/auto-complete/AutoComplete.razor.cs

当通过Visible参数控制OverlayTrigger时，Overlay组件无法自主关闭（参考：[pr743](https://github.com/ant-design-blazor/ant-design-blazor/pull/743)）
overlay cann't be close when it is controlled via visable param (see: [pr743](https://github.com/ant-design-blazor/ant-design-blazor/pull/743))
| 🇺🇸 English |       fix(module: AutoComplete): overlay couldn't close    |
| 🇨🇳 Chinese |       fix(module: AutoComplete): 下拉面板无法关闭   |

fix(module: AutoComplete): overlay couldn't close

---

components/menu/Menu.razor.cs
components/menu/MenuItem.razor
components/menu/MenuItem.razor.cs
components/menu/SubMenu.razor.cs
site/AntBlazor.Docs/Demos/Components/Menu/demo/SiderCurrent2.razor
site/AntBlazor.Docs/Demos/Components/Menu/demo/sider-current2.md
site/AntBlazor.Docs/Demos/Components/Menu/doc/index.en-US.md
site/AntBlazor.Docs/Demos/Components/Menu/doc/index.zh-CN.md

Hi there,
a little PR for the menu modul. 
What's new?
+ MenuItem - `[Property] Title` - Allows to set the Title directly as parameter and not only as ChildComponent.
Changes:
+ Menu - `[Property] Selectable` - Angluar implementation adapted.
EN-US Documentation updated.
-
-
-

feat(modul: menu) - MenuItem Title

---

components/badge/BadgeRibbon.razor
components/badge/style/ribbon.less
site/AntBlazor.Docs/Demos/Components/Badge/demo/Ribbon.razor
tests/badge/RibbonTests.cs

- [ x ] Bug fix
- [ x ] Demo update
When using BadgeRibbon with a preset color, text color is the same as background color.
Here is a snapshot of the bug
```
<BadgeRibbon Text="Pushes open the window" Color="orange">
<Card Bordered>And raises the spyglass.</Card>
</BadgeRibbon>
<br />
<BadgeRibbon Text="Pushes open the window" Color="#832">
<Card Bordered>And raises the spyglass.</Card>
</BadgeRibbon>
```
Solution : Fix less file.
Updated ribbon less file. 
Added two ribbon examples with color set (preset and custom)

fix : badgeribbon with preset color

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/modal/Modal.razor.cs
components/modal/ModalServiceForModal.cs

#757 
| 🇺🇸 English | When the page changes, the dom of the modal component whose destroyonclose is false is automatically deleted |
| 🇨🇳 Chinese | 当页面发生变化时自动删除DestroyOnClose为false的Modal组件的DOM |

fix(module: modal): dom cannot be destroyed when the page changed on DestroyOnClose is false

---

components/modal/ModalContainer.razor
components/modal/config/ModalOptions.cs

#807 
| 🇺🇸 English | Inspection before use ModalOptions.AfterClose Is it null |
| 🇨🇳 Chinese | 使用前检查ModalOptions.AfterClose是否为null |

fix(module: modal): throw error when using ModalService if not set ModalOptions.AfterClose (#807)

---

components/select/Select.razor.cs
components/select/SelectOption.razor.cs
components/select/SimpleSelect.cs
components/select/internal/SelectContent.razor
components/select/internal/SelectContent.razor.cs
site/AntBlazor.Docs/Demos/Components/Select/demo/SimpleSelectDemo.razor
site/AntBlazor.Docs/Demos/Components/Select/demo/simple-select.md

feat(module: select): add a simple select with string value

---

components/core/Component/overlay/OverlayTrigger.razor.cs
components/menu/SubMenu.razor

| 🇺🇸 English |     fix: submenu couldn't auto close      |
| 🇨🇳 Chinese |    修复: SubMenu 无法自动关闭      |

fix: submenu couldn't auto close

---

components/input-number/InputNumber.razor.cs
components/input-number/InputNumberMath.cs
site/AntBlazor.Docs/Demos/Components/InputNumber/demo/Generic.razor
site/AntBlazor.Docs/Demos/Components/InputNumber/doc/index.en-US.md
site/AntBlazor.Docs/Demos/Components/InputNumber/doc/index.zh-CN.md

| 🇺🇸 English | support all numeric types |
| 🇨🇳 Chinese | 支持全部数字类型 |

refactor(module: input-number): support all numeric types

---

components/input/Input.cs

字典添加maxlength属性时，判断主键是否存在。避免多次添加报错

 修改Input控件添加MaxLength属性报错问题

---

components/alert/Alert.razor.cs
site/AntBlazor.Docs/Demos/Components/Alert/demo/Description.razor

#875 
Fix is simple - modified conditions which are used to apply `ant-alert-description` to span with desciption (span was rendered but with default `display: none` style).
One thing to mention - the user can simultaneously pass the value in the `Description` parameter and define the content in `ChildContent`. In this case, two span tags with a description are inserted and render side by side instead of one below the other. I did not try to fix this because it is a rather rare case and I also feel average about CSS;]
⚠️ Please check all items below …

Make description element visible if passed in ChildContent

---

components/upload/Upload.razor.cs

1.Use Upload component,when upload failed,[OnSingleCompleted]File.Response only has a "error" string.
2.[OnSingleCompleted]File.Response should be responseCode.

'Upload' component change to use responseCode not a "error" string when upload failed

---

components/input/Input.cs

Closes #579 
Code based on source from @Magehernan
If the parameter is not set, then there is no behaviour change, once the debounce milliseconds is set, then this will activate the changes.

Implement optional key debouncing

---

components/grid/Row.razor.cs

fix #907 
The problem is that `actualBreakpoint` stays in `null` after searching target breakpoint.
The solution is using default value - biggest breakpoint (Xxl).

Fix actualBreakpoint NRE in Row

---

components/slider/Slider.razor
components/slider/Slider.razor.cs
components/slider/style/index.less

This addresses a number of small issues with slider:
1. When clicked and dragged to the left, often before first movement to the left a movement to the right was executed: 
2. When dragging, especially after page load, nothing was happening: 
3. For ranged slider, when dragging one edge beyond the other range, the focus was not following (I am referring to transparent gradient border that is showing when edge gets focus) :
4. For ranged slider, when quickly dragging one edge beyond the other edge, the "not changed" edge also moves:
5. When dragging an edge, text selection should be inactive:
1. Required changes to calculation method of the edge position.
2. Previously added method ```IsMoveInEdgeBoundary``` was removed from ```OnMouseMove``` event handler.
3. When side switch is …

fix(module:slider): drag, select, focus and rapid reposition fix

---

components/modal/ComfirmContainer.razor.cs

#883 
| 🇺🇸 English |  fix: using ConfimRef to close Confirm dialog but not reset body's scroll bar  |
| 🇨🇳 Chinese | 修复使用 ConfimRef  关闭 Confirm 对话框时无法重置 body 滚动条的问题  |

fix: using ConfimRef to close Confirm dialog but not reset body's scroll bar (#883)

---

components/core/Component/overlay/Overlay.razor.cs
components/menu/SubMenu.razor
components/menu/SubMenu.razor.cs

#916 #922 
| 🇺🇸 English | The Placement of SubMenu can now be changed and it will be set to BottomLeft or RightTop as before if you don't set it. |
| 🇨🇳 Chinese | 现在可以设置 SubMenu 的 Placement 参数，如果不设置它的话，Placement 会和以前一样被设置为 BottomLeft 或者 RightTop。 |

Expose SubMenu's Placement

---

components/core/Component/overlay/Overlay.razor.cs

If Dropdown ChildContent is a link but not a Button and Placement is xxxRight, the overlay couldn't be aligned to the right.
| 🇺🇸 English |  Fix the bug that Overlay can't be aligned to the right when the trigger's ChildContent is not button and the Placement is xxxRight.      |
| 🇨🇳 Chinese |  修复当Overlay的trigger的ChildContent不是button时不能靠右对齐的bug。    |

Overlay can be aligned to right when trigger is not button.

---

components/modal/modalDialog/Modal.razor.cs
components/modal/modalDialog/ModalServiceForModal.cs

#926 
| 🇺🇸 English |  fix the Blazor error caused by using modal component directly: Cannot read property 'removeChild' of null  |
| 🇨🇳 Chinese | 修复直接使用Modal组件可能引起Blazor报错: Cannot read property 'removeChild' of null |

fix: remove non auto destroyed Modal DOM created by ModalService (#926)

---

components/list/ListItemMeta.razor
components/list/ListItemMeta.razor.cs

- [ X ] Bug fix
The documentation in the demo specify that ListItemMeta have a description property that should support a ReactNode via the DescriptionTemplate property.  Like Avatar and Title properties.
see: https://antblazor.com/en-US/components/list#API
<AntList Bordered DataSource="@viewmodel.Data" ItemLayout="@ListItemLayout.Vertical" Size="small">
<ChildContent Context="item">
<ListItem Extra="@extra((item, ""))">
<ListItemMeta Description="My description">  
<AvatarTemplate>
<span>Avatar</span>
</AvatarTemplate>
<TitleTemplate>
<span>Title</span>
</TitleTemplate>
<DescriptionTemplate>   
<span>Description</span>
</DescriptionTemplate>
</ListItemMeta>
</ListItem>
</ChildContent>
</AntList>
None.

ListItemMeta component should support a ReactNode format

---

components/table/ColumnBase.cs
components/table/ColumnContext.cs
components/table/Table.razor
components/table/Table.razor.cs
site/AntBlazor.Docs/Demos/Components/Table/demo/Head_.razor
site/AntBlazor.Docs/Demos/Components/Table/demo/head.md

fix(module: table): sorter works incorrectly

---

components/table/Column.razor
components/table/ColumnContext.cs

fix(module: table): exception if field is null

---

components/date-picker/RangePicker.razor.cs

fix(module: range-picker): throw exception when has default value

---

components/cascader/Cascader.razor.cs

fix(module: cascader): re-initialize options after options is changed

---

components/alert/Alert.razor

`<Alert>` in react ant-design is based on `<div>` elements while in ant-design-blazor is based on `<span>` elements, what causes this type of behaviour when resized:
Notice that also close button is not visible for closable alert.
Also gif demo:
The fix proposed by this PR is bringing the design directly in line with react ant-design:
1. Wrap all previous `<span>` elements with extra `<div class="ant-alert-content">` element
2. Replace all `<span>` with `<div>` elements.
New behaviour after changes:

fix(module:alert): Change span to div when applicable for better responsive experience

---

components/core/JsInterop/interop.ts

#873 
The bug was appearing in `Dropdown` when `ChildContent` was not an element but a simple text:
```razor
<ChildContent>
Dropdown 
</ChildContent>
```
Here, "Dropdown" is not an element. If it was wrapped in (for example) `<span>`, this bug would not surface.
The problem here is that the underlying `Overlay` is trying to get Childcontent's first child. By default with current approach child content is wrapped in a `div` - so `Overlay` will try to get `div`'s first child. If there is no element inside (for "Dropdown" there is no element), the `Overlay` will be delivered `<body>` element.
The fix is to check if first child is null and when it is, then just return the passed element (for that issue it will be `div`). 
**Possible issues**
This is a quick fix. The `getFirstChildDomInfo` is …

fix(module:overlay): getFirstChildDomInfo will return passed dom instead of body when no child element exists

---

components/calendar/internal/CalendarPanelChooser.razor

This is a critical fix for `Calendar` component. When changes were done to `DatePicker` and `RangePicker` (my PR #933) a change was done to one of the parameters used by `Calendar` component. I missed that, because `Calendar` does not use the property directly. Without that fix, `Calendar` component does not render at all (it raises an exception). I am sorry to say, that current demo page is broken as well...

fix(module:calendar): critical exception for ChangePickerValue

---

components/layout/Sider.razor
components/layout/Sider.razor.cs

fix(module: layout): missing trigger when sider open from zero-width mode

---

components/core/Component/overlay/Overlay.razor.cs
components/core/Component/overlay/OverlayTrigger.razor.cs

Removes js event handler firing on window resize from `OverlayTrigger` (this event handler is used to move the overlay as window resizes) on Dispose().
When `Overlay` is disposed, it tries to remove itself from the DOM. This works well when a page is changed using built in navigation or when a particular component is removed by the framework. 
This does not work well when the page is for example refreshed or new address is typed manually, because the dispose method is trying to remove DOM element that no longer exists.
To recreate:
* start the project `npm start`
* navigate to `https"//localhost:5001`
* navigate to `components/tooltip`
* hover over any control that should have a tooltip (so the tooltip appears)
* press F5
* observe the console; in about a minute (at least in my dev …

fix(module:overlay): Interop delElementFrom() exception on page refresh

---

components/menu/MenuDivider.razor
site/AntBlazor.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor
site/AntBlazor.Docs/Demos/Components/Dropdown/demo/Item.razor
site/AntBlazor.Docs/Demos/Components/Menu/demo/Horizontal.razor

Added new component `MenuDivider`. 
Update to docs:
- menu divider usage in `Dropdown`
- menu divider usage in `Menu`
- tooltip usage with `Dropdown` (change includes added loading icon to sync with react ant-design docs)

feat(module:menudivider): Add Menu divider

---

components/menu/Menu.razor
components/menu/Menu.razor.cs
components/menu/MenuItem.razor
components/menu/MenuItem.razor.cs
components/menu/MenuLink.cs

🤔 This is a ...
#737 
#833 
#919 
#1014 
All changes are directly connected with issues. 
Plus performance optimization, as stated below.
During tests I found out that single click was causing cascading calls that were causing multiple unnecessary refreshes. After some serious debugging and trial and error I think I got to the point it is only doing necessary calls. Just to give a ballpark figure - with 5 menus, single click was causing 5 refreshes of each menu on average (my total was 29 refreshes overall). With this PR only changing menus are refreshing (so 2 changes in total - what is weird, 3 refreshes if order of menu clicking is reversed).

fix(module:menu): fix loop on same route & performance & duplicate highlight

---

components/core/Component/overlay/Overlay.razor.cs
components/table/Table.razor.cs
site/AntBlazor.Docs/Demos/Components/Slider/demo/Basic.razor

This issue can be demonstrated on the demo pages for tables, but should surface anytime `Table` component is used (and actually any other component that uses `Overlay`). After page refresh, in about a minute a whole bunch of exceptions can be observed in the console (the log file is based on demo docs; it is pure 40kb text):
[tableExceptionsOnReload.log](https://github.com/ant-design-blazor/ant-design-blazor/files/5863104/tableExceptionsOnReload.log)
The fix is similar to PR #1008. 
On top of that, there are also fixes to `Overlay` component. There were calls to no longer existing trigger elements based on no longer existing element classes (at least I could not find them and it does not really makes any sense to have those calls in my eyes). Also, there were calls to overlay container …

fix(module:table) Table exception on refresh

---

components/input-number/InputNumber.razor
components/input/Input.cs
components/input/TextArea.razor

#1047 
Missing `disabled` attribute on `input` element. 
There is a certain assumption here (visible in the changes in `Input.cs`): if `disabled` attribute is set to `true` in any fashion, it will always prevail.
BTW: @ElderJames I noticed that for example `Cascader` component does not have `Disabled` property. Is this by design?

fix: Input, InputNumber, TextArea disabled attribute fix

---

components/core/Helpers/PropertyAccessHelper.cs
components/table/Internal/ColumnDataIndexHelper.cs
docs/path-based-property-access.en-US.md
docs/path-based-property-access.zh-CN.md
site/AntBlazor.Docs/Demos/Components/Table/demo/DataIndex.razor
site/AntBlazor.Docs/Demos/Components/Table/demo/custom-row-style.md
site/AntBlazor.Docs/Demos/Components/Table/demo/data-index.md
tests/Core/PropertyAccessHelperTest.cs

| 🇺🇸 English | access object's property by path-based string |
| 🇨🇳 Chinese | 基于路径字符串的对象属性访问 |

feat: access object's property by path-based string

---

components/steps/Step.razor.cs

I believe that we should be invoking a State Change here. Currently the navigation is not working otherwise.
I am not aware of any breaking changes here.

fix: steps navigation was blocked

---

components/menu/Menu.razor.cs
components/menu/MenuItem.razor
components/menu/MenuItem.razor.cs
components/menu/SubMenu.razor
components/menu/SubMenu.razor.cs
site/AntBlazor.Docs/Demos/Components/Menu/demo/InlineCollapsed.razor
site/AntBlazor.Docs/Demos/Components/Menu/doc/index.en-US.md
site/AntBlazor.Docs/Demos/Components/Menu/doc/index.zh-CN.md

| 🇺🇸 English |   add MenuItem tooltip and SubMenu trigger type        |
| 🇨🇳 Chinese |   增加tooltip和 submenu浮层弹出触发类型        |

feat(module: menu): add menuitem tooltip and submenu trigger type

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/select/Select.razor
components/select/Select.razor.cs
components/select/SelectOption.razor
components/select/SelectOption.razor.cs
components/select/internal/SelectContent.razor
components/select/internal/SelectContent.razor.cs
components/select/internal/SelectOptionItem.cs
site/AntBlazor.Docs/Demos/Components/Select/doc/index.en-US.md

#257 
#594 
#662 
#877 
#878 
#1065 
and a number of other issues discovered during fixing.
I started fixing the `Select` component because I wanted to fix searchable multiple choice and tags + tokenization. This is fixed now, but there are a lot of changes. There is a `Hashset` structure that stores all selectable items. I noticed this structure was being traversed very often in multiple different methods. Often the algorithm time complexity  for a method was O(2n), O(3n), O(n*n). I decided to introduce new variables to store the items for different scenarios and different parts of the component. I managed to reduce the complexity to mostly O(n) or even O(1). In several places I moved to `foreach` loop instead of `linq` loops, just to cover more ground in single loop instead of calling …

fix(module: select): multiple fixes and optimizations

---

components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs

#1068
#1070
If `Value` provided to `RangePicker` was null, it was throwing `NullReferenceException`. Now during initialization, the `Value` is checked and if `null`, it is instantiated to `TValue`. 
Placeholders were not reset on clear - are now.

fix(module:rangepicker): placeholder and value equals null

---

components/input/Input.cs

Closes #1013
A couple events should set `ignoreDebounce = true` - lowered the default debounce value as its way too big to be normal

Fix pressing enter not updating the value

---

components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs

Due to the strongly typed nature of C#, `DatePicker` can get either nullable or not nullable dates. When not nullable are used, clearing the values was inputing min value for `DateTime`. There is not much we can do about (we can decide to take current date for example). This PR fixes the not nullable clearing scenario when defaults are set - in such case, date picker will assume defaults instead of `DateTime.Min`. For nullable the picker will be cleared.

fix(module:datepicker): for not nullable - on clear set to defaults

---

components/cascader/Cascader.razor
components/cascader/Cascader.razor.cs

#1108 
| 🇺🇸 English |     Add a pull-down effect to Cascader (integrated Overlay components)      |
| 🇨🇳 Chinese |     给Cascader增加下拉效果（集成Overlay组件）      |

feat: Add a pull-down effect to Cascader (integrated Overlay components)

---

components/modal/config/ModalClosingEventArgs.cs
components/select/Select.razor.cs

#1111 
1. Renamed `DefaultActiveFirstItem` to `DefaultActiveFirstOption` following the docs (it is in sync with react antDesign)
2. When current locale are of a country that uses comma as decimal separator, the calculated css width was delivered with a comma (for example 333,123123). Css was not understanding that and was ignoring the value.
3. Translated Chinese comment.
4. Fix similar to #662 that was applier to `DefaultActiveFirstOption`
5. Changing bound object to value outside of the `Select` component wasn't changing selection in the component.

fix(module:select): property rename to follow docs

---

components/core/Component/overlay/Overlay.razor.cs
components/core/Component/overlay/OverlayTrigger.razor.cs
components/core/Component/overlay/type/PlacementDirection.cs
components/core/Component/overlay/type/PlacementType.cs
components/core/Component/overlay/type/TriggerBoundaryAdjustMode.cs
components/menu/SubMenu.razor.cs
site/AntDesign.Docs/Demos/Components/Dropdown/demo/BoundaryAdjustMode.razor
site/AntDesign.Docs/Demos/Components/Dropdown/demo/boundary-adjust-mode.md

#1081 
| 🇺🇸 English |     add overlay boundary detection and orientation adjustment      |
| 🇨🇳 Chinese |     增加overlay的边界检测和方向调整      |

feat(model: overlay): add boundary detection adjustment

---

components/menu/Menu.razor.cs
components/menu/MenuItem.razor.cs
components/menu/MenuLink.cs

#1110
`Menu` except the fix got some extra optimization. I also noticed that accordion is not working but since @mutouzdl is doing some heavy work in that area, I will not be touching it.

fix(module:menu): active parent menu for routed links

---

components/core/JsInterop/interop.ts
components/select/Select.razor.cs
components/select/internal/SelectContent.razor
components/select/internal/SelectContent.razor.cs

When `Mode="tags"` set, newly created `SelectOptionItem` was not being properly updated. `Item` property was only created with initial letter and no updates were done further.
<s>Edit: I accidentally pushed to the same branch fixes for #1110, so I will leave them here as well... `Menu` except the fix got some extra optimization. I also noticed that accordion is not working but since @mutouzdl is doing some heavy work in that area, I will not be touching it. </s> _(moved to PR #1134)_
Edit2: 
1. Commit ac85729 is fixing FireFox issue. I discovered it in select component - for multiple/tags mode, FireFox was rising "Permission denied to access property "toJSON". A number of trial-and-error led me to a property `originalTarget` of dom element. So I am omitting that...
2. Commit 32cd7d4 is …

fix(module:select): new tag item label and value fix

---

components/core/CssSizeLength.cs
components/table/ColumnBase.cs
components/table/ColumnContext.cs
components/table/TableModels/SortModel.cs

close #1046 
| 🇺🇸 English |    support more generic units for scroll x/y       |
| 🇨🇳 Chinese |     ScrollX/ScrollY 增加更多长度单位的支持      |

fix(module: table): support more generic units for scroll x/y

---

components/table/Table.razor.Selection.cs

```
<Modal Visible="false">
<Table SelectedRows="SelectedRows">...</Table>
</Modal>
```
Setting `SelectedRows` before table rendered leads to a NullReferenceException:

fix(module:table): set selectedRows exception

---

components/core/JsInterop/interop.ts
components/table/Table.razor
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/demo/EditCell.razor
site/AntDesign.Docs/Demos/Components/Table/demo/EditRow.razor
site/AntDesign.Docs/Demos/Components/Table/demo/edit-cell.md
site/AntDesign.Docs/Demos/Components/Table/demo/edit-row.md

| 🇺🇸 English |   add editable cell/row demo        |
| 🇨🇳 Chinese |  增加单元格编辑和行编辑的 demo         |

docs(module: table): add editable cell/row demo

---

components/list/ListItem.razor.cs

Removed an unintended console writeline that is causing flooded output
https://github.com/ant-design-blazor/ant-design-blazor/issues/1154
| 🇺🇸 English |   Removed unintended console output from SetGutterStyle   |

fix(module:list): unintended output from SetGutterStyle

---

components/select/Select.razor.cs
components/select/internal/SelectItemPropertyHelper.cs

| 🇺🇸 English | use Func to get/set value instead of reflection  |
| 🇨🇳 Chinese | 使用Func代替反射读写数据 |

refactor(module: select): use Func to get or set value instead of reflection

---

components/table/Table.razor
components/table/Table.razor.Pagination.cs
components/table/Table.razor.cs

fix(module: table): show empty status when there are no data

---

components/select/Select.razor.cs
components/select/internal/SelectContent.razor

Fixes #1171 
During my tests, it came out that if I had a class that the label was attached to a property that it had only a getter, then `Select` was crashing. The source of problems was the PR #1168. The `_setLabel` was prepared regardless of the type of select. The property that is attached to label needs to have a setter only for `SelectMode.Tags`. 
Several fixes to solve #1171. The result it this:
Update of the overlay position was not really effective, as it was doing its updates before all the relevant changes were pushed to DOM. Adding `Task.Delay(1)` solved this issue. I am not really happy with it. The other option would be maybe to use [ResizeObserver](developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) but there might be a problem with browser compatibility. 
All …

fix(module: Select) bind value change lock, tags and labels fix, overlay reposition

---

components/input/Search.razor.cs

fix(module:select): Loading animation toggling properly

---

components/table/Table.razor
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor

| 🇺🇸 English |   bring OnRowClick back     |
| 🇨🇳 Chinese |   带回 OnRowClick 事件     |

fix(module: table): bring OnRowClick back

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/select/Select.razor.cs
components/select/internal/SelectContent.razor.cs

Fixes #1176 
Except fixes to #1176, this commit also adds the following:
1. Clear selection when "Delete" key or "Backspace" key pressed.
2. Exposes new attribute `DisableSubmitFormOnEnter`: Default behavior for `Select` component on a `Form` is to submit on Enter. The exception is when Enter is pressed while select options are visible (then Enter will set picked option as the value). If `DisableSubmitFormOnEnter = true` then Enter will not submit on a `Form`.
3. Interop gets a new event handler that prevents default for passed array of keys (more flexible)
4. EditContext is notified about a change in `Select` component (if `Form.ValidateOnChange == true`)
Also, I can create a docs sample for `DisableSubmitFormOnEnter` behaviour based on this gif:
| ---------- | …

Select enter on form

---

.github/workflows/preview-build.yml
.github/workflows/pull-request.yml
components/table/Table.razor.Pagination.cs
site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor

| 🇺🇸 English |  fix invoke OnChange twice on pagination was changed         |
| 🇨🇳 Chinese |  修复在翻页时出发OnChange两次的问题         |

fix(module: table): invoke OnChange twice on pagination was changed

---

components/input-number/InputNumber.razor
components/input-number/InputNumber.razor.cs

No such issue
InputNumber‘s functions is not complete compared to offical AntDesign component.
1. When hold mouse down will always trigger the increase or decrease
2. `ArrowUp` or `ArrowDown` key can increase or decrease value
| 🇺🇸 English |   add long-click and keyboard operation        |
| 🇨🇳 Chinese |    增加长按和键盘操作      |

feat(module: InputNumber): Add long click and keyboard event

---

components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerTemplate.razor.cs

I fix these bugs:
1. Quarter panel's ranges are not correct, see #945
2. Selected date on end picker is incorrect in Month and Quarter mode, follow these steps:
step1. Select start date on 2021-2
step2. Select end date on 2022-5
Finally, the end date would be 2021-5(it should be 2022-5)
And I found another issue #1259. I tried to fix it, but i failed.
| 🇺🇸 English |     [selected date on end picker]、[quarter panel's ranges]  are incorrect      |
| 🇨🇳 Chinese |     [从结束日期面板选择的日期]、[季度面板的日期范围效果]  不正确      |

fix(module: rangepicker): [selected date on end picker]、[quarter panel's ranges]  are incorrect

---

components/upload/Upload.razor
components/upload/Upload.razor.cs
components/upload/UploadButton.razor.cs
site/AntDesign.Docs/Demos/Components/Upload/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Upload/doc/index.zh-CN.md

Added missing event `OnDownload` (exists in react antDesign)
Added 2 new events `BeforeAllUpload` and its async counterpart. Use case - to check whole upload list for duplicates, instead go file-by-file using `BeforeUpload`.
| 🇺🇸 English |  Added events: `OnDownload`, `BeforeAllUpload` & `BeforeAllUploadAsync`         |

feat(module:upload): missing and new event

---

components/select/Select.razor.cs
components/select/internal/SelectContent.razor

Issue mentioned in [this PR1307](https://github.com/ant-design-blazor/ant-design-blazor/pull/1307#issuecomment-812895579)
Removeable item is basically a span with icon, that has the `@onclick` event. That event has also `@onclick:stopPropagation="true"`. What I did not know, that this does not apply to DOM events, but only to blazor events ([source](https://github.com/dotnet/aspnetcore/issues/30199)). I could probably try to make some complex js, but the simples change was to keep this as local as possible. But, if a dedicated function in `interop.ts` is required, it can probably be done.

fix(module:select): propagation on item remove

---

components/core/Reflection/PropertyReflector.cs

https://github.com/ant-design-blazor/ant-design-blazor/issues/1278
Display attribute is widely used to specify display text for entity properties. Table component should consider [Display] attribute as a possible source of column names. However, currently table component only takes advantages of [DisplayName] attribute, but not [Display] attribute. To solve this issue, should support [Display] attribute as well as [DisplayName] attribute.

feat(module:table): add support for column names from Display attribute

---

components/avatar/Avatar.razor.cs

Fixes #1340 
When scale was applied to styles, it was not made regional settings resilient. So there would be a scenario when avatar style would get something like this `scale(0,9340293843421312)` (with comma instead of dot). So when js `getDomInfo` was reading this, it was getting a value that was much grater than Int32. When c# was trying to put that into Int32, it was failing, thus exception.
@TsakiDev, thank you for you invaluable help! I could not have discovered this without your help. 

fix(module:avatar): text size calc regional independent

---

components/avatar/Avatar.razor
components/avatar/Avatar.razor.cs
components/core/CssSizeLength.cs
tests/AntDesign.Tests/Core/CssSizeLengthTests.cs

In `Avatar` component `Size` parameter was not doing anything when size was explicitly passed (for example "45.55px" did nothing).
Following the advice from PR #1355 I extended `CssSizeLength` to handle decimal & double data types. Also, it can handle no unit (need for example in `scale` or `z-index`). I created tests to check how the handling of different numeric data types works. 
I fixed the issue with `Avatar` and `Size` parameter.
Side note: `Avatar` was using a helper method `StyleHelper.ToCssPixel()`. It seems to me that `CssSizeLength` does same + much more so I also replaced it. I think this helper could be retired in favour of `CssSizeLength` in all occurrences. 

fix(module:avatar): size calculation & CssSizeLength functionality expansion

---

components/select/Select.razor.cs

Fixes #1365 
When item is clicked, `Select` component was checking if new value == `default`. In `enum` this is usually first item. If the evaluation was true, then `Select` was assuming there is no value selected, and was removing it from selection. 
I added a check if value is enum.

fix(module:select): enum default value protection

---

tests/AntDesign.TestKit/AntDesignTestBase.cs
tests/AntDesign.Tests/AntDesign.Tests.csproj
tests/AntDesign.Tests/Divider/DividerTests.razor
tests/AntDesign.Tests/_Imports.razor

test(module:divider): divider tests

---

components/select/Select.razor.cs
tests/AntDesign.Tests/Select/Actions/Select.OnDataSourceChangeTests.razor
tests/AntDesign.Tests/_Imports.razor

Fixes #1412
Added object reference comparer to figure out if `DataSource` has really changed to a different one.

fix(module:select): OnDataSourceChange called when expected

---

components/core/Component/Overlay/Overlay.razor.cs
components/core/Component/Overlay/OverlayTrigger.razor.cs

Fixes #1405
Change in `OverlayTrigger` addresses the fact that `Unbound` actually needs the reference to trigger in the `RefBack` for it to work properly.
Once that was done I discovered that in wasm there was a scenario when clicking on a filter was immediately closing it:
This was not happening in the docs. Actually, once I copied only the code from Table.DataIndex demo, it started showing. If I added another demo to the same razor file, like Table.Built-in filters, this problem was not showing. Eventually I tracked it to the fact that hiding is happening in `OnMouseUp` js event, while showing was in `OnAfterRenderAsync`. The problem is that `OnMouseUp` is raised by `jsinterop` and `OnAfterRenderAsync` is not. So if there was small number of events/elements/noise then `OnMouseUp` was …

fix(module:overlay): Table filter pop up

---

components/core/Component/Overlay/Overlay.razor.cs
components/menu/SubMenu.razor

#1396 
1. 我对比了Ant Design的SubMenu，它不需要检测边界，当菜单内容过多时，以滚动条展示即可。
所以，我取消了SubMenu的边界检测。
2. 在内容超过边界时，正常情况下需要反向弹出，但是，反向弹出时，仍然可能出现超过边界的情况。这种情况下，不进行反向弹出。
------------------------translate--------------------------
1. I compared the Menu of Ant Design, which does not need to detect the boundary. When the contents of the Menu are too much, it can be displayed with a scroll bar.
So, I set  SubMenu's TriggerBoundaryAdjustMode to none.
2. When the content exceeds the boundary, it normally needs to be popped reverse. However, when the content is popped reverse, it may still exceed the boundary.In this case, no reverse ejection is performed.

fix(module: overlay): issues in boundaryAdjustMode

---

components/table/Column.razor
components/table/FilterExpression/StringFilterExpression.cs
components/table/TableFilter.cs

fixes #1433
| 🇺🇸 English | fix error for EndsWith filter operator |
| 🇨🇳 Chinese | 修复使用“结尾是”过滤条件时的错误 |

fix(module: table): fix wrong spell for TableFilterCompareOperator.EndsWith

---

components/core/Base/AntInputComponentBase.cs
components/form/FormItem.razor.cs
components/locales/en-GB.json
components/locales/pl-PL.json
components/select/Select.razor.cs
site/AntDesign.Docs/Demos/Components/Form/demo/Size.razor
tests/AntDesign.Tests/Select/Form/Select.MultipleTests.razor

Fixes #1453 
Fixes #1428 
Fixes #1120
My solution added new `ValuesExpression` to the `AntInputComponentBase` that is expecting `IEnumerable<>`. By default then it tries to use `ValueExpression` and if null, then falls back to `ValuesExpression`. Similar changes were made to `FormItem`. After that there were minor changes in `Select` to handle validation. 
Solution also adds tests but they will be useful only once net6 is released and AntBlazor adapts it. This is due to a known limitation of templating templates and calling context inside the template. [Bunit source (check the bottom of the section)](https://bunit.dev/docs/providing-input/passing-parameters-to-components.html#passing-html-based-templates). In my dev I already moved AntBlazor to net6-preview3 and these tests are working. …

fix(module:select): support IEnumerable in form

---

components/core/Component/Overlay/Overlay.razor.cs
components/core/Helpers/DateHelper.cs
components/date-picker/DatePicker.Razor.cs
components/date-picker/DatePicker.razor
components/date-picker/RangePicker.razor
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor.cs
components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerTemplate.razor
components/date-picker/internal/DatePickerTemplate.razor.cs
components/date-picker/locale/DatePickerLocale.cs

1. Fixes #1431 
2. Addresses parts of #1429 ([this comment](https://github.com/ant-design-blazor/ant-design-blazor/issues/1429#issuecomment-828196477)):
a. When first clicked, the RangePicker panel will first display on the left side of the page.
b. The height of the RangePicker is refreshed twice when it is opened.
3. When panel was opening, `OnBlur` event is being fired.
4. When Tab+Shift on `RangePicker` was leaving the input, it is not loosing focus.
5. Initial render of `RangePicker` if rendered above the input is placed too low when panel renedered above input element:
Closing and reopening the panel would fix that to expected behavior:
1. `DatePicker` in `OnBlur` event handler was calling `Close()` method and should not.
2. a. This was an issue with `Overlay` manifesting only in …

fix(module:datepicker): Date picker panel click closing + some issues from #1431

---

components/form/Form.razor.cs

Fixes #1128 
~I would like to expose `EditContext.GetValidationMessages()` method. Currently it is not available. My use case is that I have 3 components (Parent=>Child=>Grandchild). Each of the components is basically a form with one-to-many relationship and one-to-one on a dynamic component relationship. To the end user I want to show all validation messages in a single place. Without direct access to validation messages, it is impossible (or I cannot find it).~
> I would like to expose `EditContext`. Currently it is not available. My use case is that I have 3 components (Parent=>Child=>Grandchild). Each of the components is basically a form with one-to-many relationship and one-to-one on a dynamic component relationship. To the end user I want to show all validation messages in a …

feat(module:form): expose EditContext

---

components/table/Internal/ColumnExpressionHelper.cs
tests/AntDesign.Tests/table/ColumnExpressionHelperTest.cs

Fix #1470 
Iterate backwards through the expression tree until we find the `MemberExpression`.
| 🇺🇸 English | fix exception is thrown when the DataIndex ends with the get_Item method |
| 🇨🇳 Chinese | 修复DataIndex以get_Item方法结束时会抛异常的问题 |

fix: exception is thrown when the DataIndex ends with the get_Item method

---

components/table/Column.razor.cs
components/table/Internal/ColumnExpressionHelper.cs
tests/AntDesign.Tests/table/ColumnExpressionHelperTest.cs

If there is only get_Item call of List or Dictionary in DataIndex expression tree, there is no MemberExpression, which causes an exception. 
Now I change it to set DisplayName to null when MemberExpression is not found.
| 🇺🇸 English | set DisplayName to null if MemberExpression is not found in the DataIndex expression tree |
| 🇨🇳 Chinese | 表达式树中找不到MemberExpression时, DisplayName置为null |

fix(module: table): set DisplayName to null if MemberExpression is not found in the DataIndex expression tree

---

components/core/Base/AntInputComponentBase.cs
components/input-number/InputNumber.razor.cs
components/input-number/InputNumberMath.cs
site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md
site/AntDesign.Docs/Demos/Components/InputNumber/demo/Culture.md
site/AntDesign.Docs/Demos/Components/InputNumber/demo/Culture.razor
site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.zh-CN.md

Fixes #1477 
I added `CultureInfo` to base class `AntInputComponentBase`. I decided to do that in base class, because of the method `TryParseValueFromString` that is using current culture for conversion, when probably it should use passed culture. This is mostly important for server-side deployments, when browser culture not always is used and this way consumer can force browser settings.
Generally to me it seems that this component is a bit overengineered. I think it may be possible to make it a bit simpler while getting the same functionality without sacrificing performance. Also, I think this component should move from `double` to `decimal`, this way we will avoid rounding issues, especially there are a lot of rounding issues already:
Another issue is `Parser` attribute. The docs state …

fix(module:inputnumber): allow culture info to format input

---

components/form/FormItem.razor
components/form/FormItem.razor.cs

There is no way to style `<label>` element in the `FormItem` component. My use case was that I wanted to change from `white-space: nowrap;` to `white-space: normal;` (I have localization and in some language the text label is too long and is hiding behind form element).
| 🇺🇸 English |  Added `LabelStyle` to `FormItem` for custom <label> element styling.         |

feat(module:formitem): expose LabelStyle parameter

---

components/core/Base/AntInputComponentBase.cs
components/form/Form.razor.cs
tests/AntDesign.TestKit/AntDesign.TestKit.csproj
tests/AntDesign.TestKit/AntDesignTestBase.cs
tests/AntDesign.TestKit/TestNavigationManager.cs
tests/AntDesign.Tests/AntDesign.Tests.csproj
tests/AntDesign.Tests/Form/EditContext/Form.EditContext.BuildTests.razor
tests/AntDesign.Tests/Form/Model/ModelTests.razor
tests/AntDesign.Tests/Input/InputTests.razor
tests/AntDesign.Tests/_Imports.razor

Fixes #1254
Addresses also closed #851 and #1128
Key part of the change is in `Form.razor.cs`. All `_editContext = new EditContext()` have been replaced with `BuildEditContext()` method. The issue with `EditContext` is that it cannot be just newed, because it may (and actually does) contain delegates attached to events (refer to [this issue](https://github.com/dotnet/aspnetcore/issues/18963)). So the method is using reflection to delete delegates from events of the "old" `_editContext` and transfers them to new `_editContext`. This is especially important, since `EditContext` is now also exposed as a property so any consumer can attach any number of handlers that are outside of `Form`'s control 
To keep with convention, all the events of the `EditContext` have been exposed as parameters …

Form edit context dynamic change

---

components/core/Base/AntInputComponentBase.cs
components/date-picker/internal/DatePickerBase.cs

fixes #1491
#1480 add `CultureInfo` property to base input class, but there is already a `CultureInfo` property for DatePicker.  

fix(module:datepicker): fix multiple CultureInfo properties

---

components/core/Base/AntInputComponentBase.cs

A minor optimization of @anranruye PR #1510. Moved reflection to `OnInitialized` since the type of the input is set once. 

fix(module:antinputcomponentbase): guid optimization

---

components/core/Component/Overlay/Overlay.razor.cs

#1415
Then you use Overlay component you can provide "PopupContainerSelector" to append overlay to your own container (instead body), but if your container scrolled overlay positioned incorrectly
All components that use "Overlay" base now  can take scroll position into account

fix:(module:overlay): positioning should take scroll into account

---

components/core/JsInterop/JSInteropConstants.cs

Current master is not building.
Edit: It is not building in my .net 6 changed deployment. 
Added missing `using` statement.
Edit: It is only needed for .net 6, due to `[Obsolete]` annotation used but only behind compiler preprocessor directive.

fix: missing using is causing build failure

---

components/core/Component/Overlay/OverlayTrigger.razor.cs
components/dropdown/Dropdown.razor
components/dropdown/Dropdown.razor.cs
components/dropdown/DropdownButton.cs
site/AntDesign.Docs/Demos/Components/Button/demo/Block.razor
site/AntDesign.Docs/Demos/Components/Button/demo/Multiple.razor
site/AntDesign.Docs/Demos/Components/Button/demo/multiple.md
site/AntDesign.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor

Current behaviour is this:
Expected is this:
1. Hovering over left button should not open the dropdown.
2. When loading, dropdown should be disabled.
3. Overlay should be position to the right edge of the right button.
1. The issue here was that overlay trigger was set on the wrapping div instead of on the right button. 
2. Exposed `Loading` parameter. This is different than in react, but actually is the same as in a number of other components.
3. Hardcoded the position of the overlay in `DropdownButton`
Other changes:
1. Fixed docs for the `Button` in area of `Multiple` and fixed styling for block buttons.
| 🇺🇸 English |  Added `Loading` parameter to `DropdownButton`         |
⚠️ Please check all items below …

fix(module:dropdownbutton): align with react

---

components/button/Button.razor.cs
components/button/ButtonType.cs
components/core/AntSizeLDSType.cs
components/core/Component/Overlay/Overlay.razor.cs
components/core/Component/Overlay/OverlayTrigger.razor.cs
components/dropdown/Dropdown.razor
components/dropdown/Dropdown.razor.cs
components/dropdown/DropdownButton.cs
components/dropdown/internal/DropdownGroupButton.razor
site/AntDesign.Docs/Demos/Components/Button/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Button/demo/Danger.razor
site/AntDesign.Docs/Demos/Components/Button/demo/Disabled.razor
site/AntDesign.Docs/Demos/Components/Button/demo/block.md
site/AntDesign.Docs/Demos/Components/Button/demo/danger.md
site/AntDesign.Docs/Demos/Components/Button/demo/ghost.md
site/AntDesign.Docs/Demos/Components/Button/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Button/doc/index.zh-CN.md
site/AntDesign.Docs/Demos/Components/Dropdown/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.zh-CN.md

`DropdownButton` is missing `Button` standard behaviours like `Ghost`, `Danger`, etc.
This is a follow-up to my PR #1588.
You will see a lot of changes here, because I was also try to follow the suggestion in #1495. 
So this PR adds:
1. All missing functionality of a regular `Button` to `DropdownButton`:
- `Block`
- `Danger`
- `Ghost`
- `Loading`
- `Type` - was already existing but this PR adds ability to set type separately for left and right button
- `ButtonsRender` - I decided to hide this in `Dropdown` by making it `internal` and expose it only in `DropdownButton` - since this is strictly related to `DropdownButton`, I do not think it should be visible from regular `Dropdown`.
2. Adds new demos and API docs
3. Adds new button type - `text` to `Button` component
4. Fixes the `Button` …

fix: DropdownButton missing properties & docs fix for Dropdown & Button

---

components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs

Fixes #1615 
Both pickers had a method `UpdateCurrentValueAsString` which was called on data change and was only doing something if the component was attached to a form. The problem with it is that it was trying to apply the string value of the input to `CurrentValue`. But that code is a general code that sits in `AntInputComponentBase`. It does not handle well the datepicker specific data format. So it was failing a lot and was resetting also the data. I decided to remove it. 
Also, I noticed that for `RangePicker`, when in `Form`, `EditContext.NotifyFieldChanged` was never called. In regular `DatePicker` this call is done when `CurrentValue` is updated. But in `RangePicker` `CurrentValue` is never updated as a whole, only array items are. So I added the appropriate code. Also, maybe it …

fix(module:datepicker): in form behavior

---

components/locales/nl-BE.json
components/locales/nl-NL.json

Many values were missing from the Dutch locales nl-BE and nl-NL, leading to null reference exceptions. The first day of the week and date format were also incorrect for the Dutch language region.
The en-US locale was used as the basis for these additions.
| 🇺🇸 English |       Add missing values to nl-BE and nl-NL locales and correct the first day of the week and date formats.    |

Add missing values to Dutch locales

---

components/select/Select.razor.cs
site/AntDesign.Docs/Demos/Components/Select/demo/Basic.razor

fixes #1454
| 🇺🇸 English | When the item in the data source and the value property of select use the same type, it is not necessary to specify ValueName; When LabelName is not specified, the return value of the ToString() method of the item in the data source is used as the label |
| 🇨🇳 Chinese | 当数据源中的项和Select的Value属性使用相同类型时，无需指定ValueName；当不指定LabelName时，将使用数据源中的项的ToString()方法的返回值作为Label |

feat(module: select): support simple data source

---

components/tag/Tag.razor.cs
components/tag/style/entry.less
components/tag/style/patch.less
site/AntDesign.Docs/Demos/Components/Tag/demo/Basic.razor

Fixes #1657
Added `patch.less` with class `ant-tag-clickable` that is added when `OnClick.HasDelegate == true`.
| 🇺🇸 English | Shows pointer cursor when `OnClick` is set.          |

fix(module:tag): show pointer cursor when OnClick.HasDelegate

---

components/dropdown/Dropdown.razor
components/dropdown/Dropdown.razor.cs
components/dropdown/DropdownButton.cs
site/AntDesign.Docs/Demos/Components/Button/demo/multiple.md
site/AntDesign.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.zh-CN.md
tests/AntDesign.Tests/Dropdown/DropdownButton/DropdownButtonTests.razor
tests/AntDesign.Tests/Tag/TagTests.razor

1. Adds ability to add css class & style to each button.
2. Refactored razor file to use `RenderFragment` template. This is simplifying testing (no need to do separate tests for `Unbound` and `ChildContent` versions).
3. Switched `Type` to `OneOf` to simplify user experience when using the same type for both buttons.
4. Altered demo to show the usage of new properties
| 🇺🇸 English | Add `ButtonsStyle` & `ButtonsClass` parameters that allow to style each button separately. `Type` accepts single value that will be applied to both buttons. |

feat(module:dropdownbutton): each button customization

---

components/date-picker/DatePicker.razor
components/date-picker/RangePicker.razor
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerInput.razor

Fixes #1676
| 🇺🇸 English | fix date picker width for custom and culture-based format |

fix(module:date-picker): fix date picker width

---

components/table/Table.razor
components/table/Table.razor.cs

Add the ability to have all items in a table by setting  DefaultExpandAllRows to true.
#1566 (ExpandAll table tree data)
1. Sometimes there's a need to have all nodes expanded on load so that the user doesn't have to manually expand all items.
2. ![image](https://user-images.githubusercontent.com/4659350/123958017-d40a9e00-d9ac-11eb-8b23-01b17402122f.png)
3. Add new property `bool` `DefaultExpandAllRows` to `Table`. In razor component where `showItems`are looped over,  `RowData<TItem>.Expanded` is set to `DefaultExpandAllRows` so that it is rendered as expanded on load.
| 🇺🇸 English |  Abiliy to have all items in a table expanded on load  |

feat(module: table): support expanding all items in table

---

components/core/JsInterop/interop.ts

Treat all 2xx status codes as success in the upload module.
#1655 (The 'Upload' component will treat the 201 (created) HTTP status code as a failure result)
Depending on how the server receiving to the uploaded file is configured, successful requests might not be responded with 200 as a status code. Fix is to be less strict and treat any 2xx status code as successful.
| 🇺🇸 English | Treat all 2xx status codes in responses in the upload module as successful |

fix(module: upload): treat 2xx response codes success

---

components/statistic/CountDown.razor.cs

Calls to OnFinish callback now won't cause InvalidOperationException.
https://github.com/ant-design-blazor/ant-design-blazor/issues/1712
Use InvokeAsync for OnFinish call

fix(module:CountDown): fix CountDown OnFinish callback exception(#1712)

---

components/select/Select.razor.cs

Fixes #1719
Fixes #1536 
| 🇺🇸 English | allow change both data source and value in one render period |

fix(module:select): allow change both data source and value in one render period

---

components/modal/config/ModalOptions.cs

#1741
| 🇺🇸 English |  fix wrong seter in ModalOptions.ConfirmLoading (always is true)   |
| 🇨🇳 Chinese |     ModalOptions.ConfirmLoading中setter错误赋值（总是true）|

fix: wrong setter in ModalOptions.ConfirmLoading

---

components/core/Reflection/PropertyReflector.cs
site/AntDesign.Docs/Demos/Components/Form/demo/Basic.razor

fix(module: form): DisplayName for FormItem will be not default to property name

---

components/select/Select.razor.cs

Fixes #1735
A sample:
This issue is introduced by #1720 . In #1720, I changed the position to call `OnValueChange` method. In most cases, this change is safe. However, `OnValueChange` should do nothing for the first call(by evaluating the `_isInitialized` field), but the method is now first called after `_isInitialized` is set to `true`. We can solve this issue by simply move `_isInitialized = true;` to after the call to `OnValueChange`. Let me know if you think we should use a new variable or variable name in this case.
| 🇺🇸 English | fix the issue that can not set select component initial value for non-datasource approach  |
| 🇨🇳 Chinese | 修复当使用SelectOption方案时不能为Select组件设置初始值的问题 |

fix(module: select): can not set initial value for non-datasource approach

---

components/select/Select.razor.cs
components/select/SelectOption.razor.cs
components/select/internal/SelectContent.razor
components/select/internal/SelectContent.razor.cs
tests/AntDesign.Tests/Select/Form/Select.MultipleTests.razor
tests/AntDesign.Tests/Select/Select.Tags.Tests.razor

1. Fixes #1645 
2. Any mouse button click on "x" in selected item is removing it.
1. `SelectOption` was being removed in the `Dispose()` method irrespective of it being selected. `Dispose` method now checks if `SelectOption` is selected and prevents removing.
2. Selected item will be removed only if the "x" receives left mouse button click.

fix(module:select): duplicated tags

---

components/upload/Upload.razor
components/upload/Upload.razor.cs
components/upload/UploadButton.razor
components/upload/UploadButton.razor.cs
site/AntDesign.Docs/Demos/Components/Upload/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/DefaultFileList.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/Directory.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/Drag.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/FileList.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/PictureStyle.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/drag.md
tests/AntDesign.Tests/Upload/UploadTests.razor

| 🇺🇸 English |     support drag upload       |
| 🇨🇳 Chinese |    支持拖住上传       |

feat(module: upload): support drag

---

components/core/ComponentStatus.cs
components/drawer/Drawer.razor.cs
components/drawer/DrawerContainer.razor
components/drawer/DrawerContainer.razor.cs
components/drawer/DrawerService.cs
components/drawer/config/DrawerOptions.cs

#1749 
| 🇺🇸 English | 1. Fix the bug: scroll bar of the body is enabled after closing one of the multiple drawers. 2. remove parameter NoAnimation.   |
| 🇨🇳 Chinese |  1. 修复在多Drawer时关闭一个Drawer就恢复页面滚动条的bug；2. 移除不可实现的参数 NoAnimation |

fix: unexpected behavior of Drawer(#1749)

---

components/tree/TreeNode.razor.cs

https://github.com/ant-design-blazor/ant-design-blazor/issues/1770
Once the short-circuit optimization removed, the state of a parent node's checkbox is calculated correctly.
| 🇺🇸 English | Fix parent checkbox state calculation in a Tree |

fix(module:tree) Fix parent checkbox state calculation (ant-design-blazor#1770)

---

components/select/Select.razor.cs

Fixes #1783
| 🇺🇸 English | accept `null` as select option value |

fix(module: select): fix null value

---

components/tree/TreeNode.razor.cs

https://github.com/ant-design-blazor/ant-design-blazor/issues/1770
https://github.com/ant-design-blazor/ant-design-blazor/pull/1781
It turned out the solution put forward in #1781 fixed only half of the problem - after testing, a different edge case popped up. This fix should cover both of them.
| 🇺🇸 English |Fix parent checkbox state calculation in a Tree|

fix(module: tree): one more fix to parent checkbox state calculation

---

components/tree/Tree.razor.cs
site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor

BREAKING CHANGE
Inaccurate name and description of the methods.
BREAKING CHANGE - method names changed
| 🇺🇸 English |Amend name and description of the methods for checking and unchecking all nodes in a tree.|

refactor(module:tree): rename Checked/Dechecked methods to Check/Uncheck

---

components/date-picker/internal/DatePickerDatetimePanel.razor

#1817 `ShowToday = false` was not working when `ShowTime` was set to `true`
| 🇺🇸 English | DatePicker: fix ShowToday behaviour when ShowTime set to true |

fix(module: date-picker): fix ShowToday when ShowTime is true (#1817)

---

components/date-picker/DatePicker.Razor.cs

```
<DatePicker @bind-Value="dateTime1"></DatePicker>
<br />
@dateTime1.ToString("yyyy-MM-dd HH:mm:ss.ffff")
@code{
DateTime dateTime1 = DateTime.Now;
}
```
| 🇺🇸 English | remain millisecond value when change the picker value |

fix(module:date-picker): remain millisecond value when change the picker value

---

components/core/Helpers/EnumHelper.cs
components/radio/EnumRadioGroup.cs
site/AntDesign.Docs/Demos/Components/Radio/demo/EnumGroup.razor
site/AntDesign.Docs/Demos/Components/Radio/demo/enum-group.md

| 🇺🇸 English |  support enum type for `RadioGroup`  ,use `EnumRadioGroup`        |
| 🇨🇳 Chinese |   支持将枚举类型作为的选项，使用 `EnumRadioGroup`        |

feat(module: radio): support enum type for `RadioGroup`

---

components/menu/Menu.razor.cs
components/menu/MenuItem.razor.cs

fixed #1691
| 🇺🇸 English |   menu item click event should be triggered when menu selectable is false        |
| 🇨🇳 Chinese |   修复  menu item 的点击事件在 `Selectable=false` 时不触发的问题      |

fix(module: menu): menu item click event should be triggered when menu selectable is false

---

components/core/JsInterop/modules/components/uploadHelper.ts
components/upload/Upload.razor
components/upload/Upload.razor.cs
components/upload/UploadButton.razor.cs
site/AntDesign.Docs/Demos/Components/Upload/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Upload/doc/index.zh-CN.md
tests/AntDesign.Tests/Upload/UploadTests.razor

* add method parameter to upload component
* update documentation
* add test
https://github.com/ant-design-blazor/ant-design-blazor/issues/1852
I needed to use the `method` parameter of the Upload component described by the documentation, but found that the parameter did not exist, and the documentation did not reflect the implementation in multiple ways. This PR implements the `Method` parameter as initially advertised, and cleans up the documentation to sort the parameters for readability and remove the ones that do not exist.
| 🇺🇸 English |  Upload component now supports customizing the HTTP method, but still defaults to POST |

feat(module: upload): support Method (#1852)

---

components/locales/en-US.json
components/locales/zh-CN.json
components/table/Column.razor
components/table/FilterExpression/DateFilterExpression.cs
components/table/FilterExpression/EnumFilterExpression.cs
components/table/FilterExpression/GuidFilterExpression.cs
components/table/FilterExpression/IFilterExpression.cs
components/table/FilterExpression/NumberFilterExpression.cs
components/table/FilterExpression/StringFilterExpression.cs
components/table/TableFilter.cs
components/table/TableLocale.cs

Fixes #1854 
The purpose of this PR is to modify the expected behavior of the default filter for the `DateTime` column of the table. The original default filter eliminates the milliseconds of the selected time when filtering, but does not eliminate the milliseconds in the data, resulting in the Equal option never being obtained the expected result.
I think that usually only the year, month and day need to be considered when filtering the `DateTime` in the table, so the PR only keeps the year, month and day in the options and data when filtering, and removes the rest of the data. 
And this PR also fixes a spelling error.
| 🇺🇸 English |  rename `GetDefaultCampareOperator` to `GetDefaultCompareOperator`  and add `leftExpr = …

Add Date filter to the DateTime column of table 

---

components/checkbox/CheckboxGroup.razor.cs

Fixes #1716
When `Options` is changing, an attached function that calculates `CheckboxGroup` current value should also be changed. This PR is forcing the change.
I see another issue here which is tightly connected to performance. Currently. because `Options` are `OneOf`, the reset of its value is done on basically any action done on the component (so clicking on a single checkbox in the group triggers the `Options` to be set again). This I think is due to the fact that `Options` is not a primitive type (as stated in #992). In this case though I do not think we can use a primitive type. What we could use is a class that will internally hold `CheckboxOption` array and will also internally monitor for the changes. My idea here is that such class could very quickly know if it changed and a …

fix(module:checkboxGroup): option change does not lock checkboxes

---

components/table/Column.razor
components/table/FilterExpression/DateFilterExpression.cs

原有代码在选择过滤的时间时减去了毫秒 (因为时间选择器无法选择毫秒), 但在过滤时, 未对数据的毫秒进行处理, 这导致了在使用 `Equal` 或者 `Less than or equal` 模式时. 这就导致了, 比如在 `Equal` 模式中选择了 2021年8月23日21时01分00秒, 但无法筛选出数据中为该时间的数据 (除非其恰好为0毫秒). 于是我认为在比较时应该将数据中的毫秒也减去, 即在生成的表达式中加入减去毫秒的语句.
* 要解决的问题: 在过滤时同时去除所选项的毫秒数和数据中的毫秒数.
* 实现: 首先移除了在选择过滤时间时去除毫秒的方法, 将其转移到了 `GetFilterExpression` 方法中, 在生成判断表达式前将 `leftExpr` 和 `rightExpr` 的毫秒数同时消去.

remove milliseconds when filtering

---

components/breadcrumb/BreadcrumbItem.razor
components/core/Component/Overlay/OverlayTrigger.razor.cs
components/core/JsInterop/JSInteropConstants.cs
components/dropdown/Dropdown.razor
components/dropdown/Dropdown.razor.cs
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Dropdownmenu.razor
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Separator.md
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Separator.razor
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/With.razor
tests/AntDesign.Tests/Dropdown/DropdownButton/DropdownButtonTests.razor
tests/AntDesign.Tests/tabs/TabsTests.razor

Breadcrumb can have dropdown with Overlay property, that feature has been added. Additionaly, in Dropdown component ChildContent was wrapped to `ant-dropdown-trigger` according to AntDesign, for applying to icon style font-width = 10 instead of 14.
BreadcrumbItem can have Href property to automatically create NavLink.

Breadcrumb updates

---

components/form/Form.razor.cs
components/form/FormItem.razor.cs
components/form/Internal/IForm.cs

Fixes [#1990](https://github.com/ant-design-blazor/ant-design-blazor/issues/1900)
The form component removes the formItem when it is disposed.  
IForm.cs Add  RemoveFormItem method:
```
internal void RemoveFormItem(IFormItem formItem);
```
Form.razor.cs Implementation IForm RemoveFormItem  method:
```
void IForm.RemoveFormItem(IFormItem formItem)
{
_formItems.Remove(formItem);
}
```
FormItem.razor.cs Call Form RemoveFormItem method on Dispose
```
protected override void Dispose(bool disposing)
{
if (CurrentEditContext != null && _validationStateChangedHandler != null)
{
CurrentEditContext.OnValidationStateChanged -= _validationStateChangedHandler;
}
Form?.RemoveFormItem(this);
base.Dispose(disposing);
}
```
| …

fix(module: form): fix the form component modifies the bound model to throw an exception in Rule validation mode

---

site/AntDesign.Docs/Demos/Components/Table/demo/Dynamic.razor
site/AntDesign.Docs/Demos/Components/Table/demo/dynamic.md

docs: add dynamic table demo

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/modules/components/inputHelper.ts
components/input/Input.cs
components/input/InputPassword.razor.cs
components/input/TextArea.razor
components/input/TextArea.razor.cs
site/AntDesign.Docs/Demos/Components/Input/demo/Area.razor
site/AntDesign.Docs/Demos/Components/Input/demo/TextAreaBasic.razor
site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md
tests/AntDesign.Tests/Input/TextAreaTests.razor

Fixes #1869
1. Added `Rows` parameter. This is to cover the requirement of the issue & to align with antD. Defaults to 3, which is approx of current default of antD (in antD case it looks like the default to about 2.8).
2. Minor typescript optimizations (explicit types)
3. For `AutoSize` added style `resize:none` (align with antD) that turns-off ability to manually resize the `TextArea`. This also could be an additional parameter, but antD does not have it.
4. Debug warning if consumer tries to use either `MinRows` or `MaxRows` and set `AutoSize = false` (with automatic switch to `true`)
5. Included PR #1917 changes also in the `TextArea` component
6. Added comments, rearranged new parameter properties to keep alphabetical order (my ocd...)
7. Remove from `TextArea` unnecessary (IMO) …

fix(module:textarea): add rows parameter

---

components/input-number/InputNumber.razor
components/input-number/InputNumber.razor.cs

InputNumber can show correct keyboard on mobile devices, according to that example https://inputmodes.com/
| . | Old | New |
| --- | --- | --- |
| Android - not float |  ![image](https://user-images.githubusercontent.com/12235437/132419687-2169b22e-f440-4d5f-b9c0-0e69837a12a8.png)  | ![image](https://user-images.githubusercontent.com/12235437/132419397-00269220-dd20-4bc8-89bb-b8072e4b1699.png)  |
| Android - float|  ![image](https://user-images.githubusercontent.com/12235437/132419770-8ea0107d-dd2b-4e91-b1f1-e279061b9d39.png) | ![image](https://user-images.githubusercontent.com/12235437/132419789-6a50256b-c01d-4815-bb0e-ca5088ada634.png) |
| iOS - not float | ![image](https://user-images.githubusercontent.com/12235437/132420143-19001225-a2bc-4b74-ba78-5dad3fed9af1.png) | …

Add inputmode for input number

---

tests/AntDesign.TestKit/AntDesignTestBase.cs
tests/AntDesign.Tests/AntDesign.Tests.csproj

Few days ago I discovered this [Fine Code Coverage](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage) extension to VS that allows to generate coverlet reports and actually track the coverage. For `AntBlazor` it looks like this:
It required 2 changes to `AntDesign.Test.csproj` file, which I would deem completely harmless, except when you are using the aforementioned extensions - then extremely useful. 
There is a problem here though - after running tests, it takes some time for the coverage report to generate. I consulted with the creator of the extension and we found out that this is not the problem of the extension but either coverlet or blazor. Maybe you remember that we used to have a serious delay when tests were running in CI - like 18 minutes. Only …

change: test cs project to include testProjectWithAdapter

---

components/core/JsInterop/modules/components/OverlayPosition.cs

In cultures where decimal separator is ',' overlay would be ill-positioned
If user has locale with ',' as decimal separator and the calculated left / top values have a decimal part the resulting formatted value will be not be parsable by browser:
| 🇺🇸 English | Fix positioning overlay items when locale has ',' as decimal separator          |

fix(module:overlay): format number InvariantCulture

---

components/table/ColumnContext.cs
components/table/ITable.cs
components/table/Table.razor.cs
site/AntDesign.Docs.Server/Properties/launchSettings.json

fix(module: table): incorrectly render on first loading

---

components/core/Extensions/EnumerableExtensions.cs
components/descriptions/Descriptions.razor.cs
components/grid/Row.razor.cs
site/AntDesign.Docs/Demos/Components/Grid/demo/Playground.razor
site/AntDesign.Docs/Demos/Components/Grid/demo/playground.md

| 🇺🇸 English |  Fixed grid issue with gutter match due to breakpoint enum name case        |
| 🇨🇳 Chinese |   修复 Grid 由于breakpoint枚举命名大小写导致breakpoint匹配的问题        |

fix(module: grid): issue with gutter match due to breakpoint enum name case

---

components/table/ITable.cs
components/table/Table.razor.Pagination.cs
components/table/Table.razor.cs

feat(module: table): reload data with specific page index and size

---

components/calendar/internal/CalendarPanelChooser.razor

https://github.com/ant-design-blazor/ant-design-blazor/issues/2067
Setting `Calendar.DateFullCellRender` property would result in a cast exception thrown. That was because that function (1 parameter) was passed to `DatePickerBase` which required 2 parameters. I propose a solution where we create a new anonymous function which calls the original `Calendar.DateFullCellRender` with the second parameter discarded.
| 🇺🇸 English |     Fixed `Calendar.DateFullCellRender` throwing an exception   |

fix(module: calendar): DateFullCellRender throws an exception (#2067)

---

components/core/Component/Overlay/OverlayTrigger.razor.cs
components/locale-provider/Locale.cs
components/locales/en-US.json
components/locales/zh-CN.json
components/tabs/Reuse/ReuseTabs.razor
components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsLocale.cs
components/tabs/Reuse/ReuseTabsPageAttribute.cs
components/tabs/Reuse/ReuseTabsPageItem.cs
components/tabs/Reuse/ReuseTabsRouteView.cs
components/tabs/TabPane.razor
components/tabs/TabPane.razor.cs
components/tabs/Tabs.razor.cs
site/AntDesign.Docs/Demos/Components/Tabs/demo/ContextMenu.razor
site/AntDesign.Docs/Demos/Components/Tabs/demo/contextmenu.md
site/AntDesign.Docs/Demos/Components/Tabs/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Tabs/doc/index.zh-CN.md
tests/AntDesign.TestApp/Client/Pages/Authentication.razor
tests/AntDesign.TestApp/Client/Pages/Counter.razor
tests/AntDesign.TestApp/Client/Pages/FetchData.razor
tests/AntDesign.TestApp/Client/Pages/Index.razor
tests/AntDesign.TestApp/Client/Shared/MainLayout.razor

feat(module: tabs): add context menu and page config for reusetabs

---

components/locale-provider/LocaleProvider.cs

Fixes #2059
| 🇺🇸 English | fix: AntDesign.LocaleProvider type initializer throws CultureNotFoundException |

fix(module:locale-provider): fix culture not found

---

components/typography/TypographyBase.cs

When using `copyable` components inheritting `TypographyBase`, such as `AntDesign.Text`, if  the value of `CopyConfig.Text` is null or empty, the `OnCopy` action will be ignored. So developers cannot set self-defined content and inform the user of a message like 'Copied!' at the same time. And also the current doc/demo doesn't mention this, so I think it's a bug. 
The solution is to change the codes of `Copy` method.
| 🇺🇸 English | Fix `OnCopy` not invoked when `Text` is null or empty |
| 🇨🇳 Chinese | 修复`Text`为null或空字符时`OnCopy`未被执行的问题  |

fix(module: typography):  Fix `OnCopy` not invoked when `Text` is null or empty

---

components/cascader/Cascader.razor.cs

fix(module: cascader): crashes when options is null (#563)

---

components/cascader/Cascader.razor
components/cascader/Cascader.razor.cs

feat(module: cascader): display indicator when options is null or empty

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/modules/dom/manipulationHelper.ts
components/icon/IconService.cs
components/typography/TypographyBase.cs
tests/AntDesign.Tests/Card/Card.Render.Tests.razor
tests/AntDesign.Tests/Menu/Menu.Inline.Tests.razor
tests/AntDesign.Tests/Tag/TagTests.razor
tests/AntDesign.Tests/button/ButtonTests.razor

Fixes #1981
Background:
1. element inner html string is copied, rather than a human-readable text.
2. the copy feature doesn't work for old browsers(such as IE)
Solution:
1. copy text rather than html. try to copy the element content as rich-text at first. if failed, copy the element innerText instead.
2. click event doesn't work on `<svg>` element for ie. add "pointer-events:none" css attribute to the svg element to trigger the click event of the parent `<a>` element. this also fix `OnClick` event for `Icon` component.
| 🇺🇸 English | typography: copy content as text rather than html, fix copy feature for ie; icon: fix OnClick event for ie  |

fix(module:typography): fix copy

---

components/select/Select.razor.cs

it fix the #2120 
No visible changes 
- [x ] Demo is updated/provided or not needed

fix(module:select): it's incorrect to detect type this way, it throws when class inheritance is used

---

components/transfer/Transfer.razor

- none
The buttons for tranfering items from one side to the other had unnecessary spacing.
This is caused by the `<span>` element which is rendered inside the button.
Since the button includes an API to prevent this, I added a check for it.
| 🇺🇸 English |      Apply `NoSpanWrap` to button when string is emty     |

fix(module:transfer): transfer button spacing

---

components/core/Base/AntInputComponentBase.cs
components/date-picker/RangePicker.razor.cs
components/form/FormItem.razor.cs
components/input/Input.cs
components/select/Select.razor.cs
components/select/SelectBase.cs
components/tree-select/TreeSelect.razor.cs
site/AntDesign.Docs/Demos/Components/Form/demo/EditForm.razor
site/AntDesign.Docs/Demos/Components/Form/demo/editform.md
site/AntDesign.Docs/_Imports.razor

Issue was detailed on Discord
When trying to convert my app to use AntDesign, none of the validation styling worked. Doing some research I found that none of the controls could be used as a drop in replacement for default Blazor Controls. No validation was getting fired as the EditContext was fully able to cascade down. This in addition to the validation styling being part of the FormItem was a problem for me. 
I have updated the FormItem to be able to be used in the default EditForm and updated the AntInputComponentBase to be able to cascade the EditContext. Added a demo of this in the `Form` area of the documents.

feat(module: core) Allow controls to be used in default EditForm

---

components/core/JsInterop/modules/dom/manipulationHelper.ts
tests/AntDesign.Tests.Js/tests/domInit.ts
tests/AntDesign.Tests.Js/tests/modules/dom/manipulationHelper.test.ts

https://github.com/ant-design-blazor/ant-design-blazor/issues/2102#
| 🇺🇸 English |  fix: error width for disable body scroll   |
| 🇨🇳 Chinese |  修复禁用body滚动条时宽度设置的问题         |

fix: error width for disable body scroll

---

.github/workflows/pull-request.yml
components/checkbox/CheckboxGroup.razor.cs
site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj

fixed #2169 
| 🇺🇸 English |  fix value binding for checkbox group         |
| 🇨🇳 Chinese |   修复 CheckboxGroup 绑定 Value 的变量不能修改选中框的问题     |

fix(module: checkbox): value binding for checkbox group

---

components/radio/Radio.razor
components/radio/Radio.razor.cs
components/radio/RadioGroup.razor.cs
tests/AntDesign.Tests/Radio/RadioGroupTests.razor

Now if a radio is in a group, its `Disabled` will be always the same as `RadioGroup`. However, sometimes people may want to keep some radio disabled, so we should ignore the sync for a disabled radio when it becomes a child of group.
Also, BTW, this PR has fixed some other problems.
* Remove `IsChecked` which is duplicated of `Checked` in `Radio`
* Remove check of `Disabled` in `Select` and `UnSelect`, which should be checked before the method calls
* Use `EqualityComparer` in `EqualsValue`
* Fix extra `ValueChanged` invoking in `OnRadioChange`
* Add some test cases about `Disabled` sync of `RadioGroup`
| 🇺🇸 English |    Improve sync logic about `Disabled` between `RadioGroup` and `Radio`s    |
| 🇨🇳 Chinese | …

Improve sync logic about `Disabled` between `RadioGroup` and `Radio`s

---

components/date-picker/DatePicker.razor

Fix up suffix icon show issue
| 🇺🇸 English |    Fix up suffix icon show issue       |

Fix up suffix icon show issue

---

components/table/Table.razor.Pagination.cs

Fixes #2236
| 🇺🇸 English | when pageIndex and pageSize change together, trigger PageSizeChanged event before PageIndexChanged event, and trigger OnChange event only one time |

fix(module:table): trigger PageSizeChanged event before PageIndexChanged event

---

components/table/FilterExpression/StringFilterExpression.cs

The code used a cyrillic Es (looks like a C) mistakenly. Changed to use ASCII C.
FIXES #2250.

FIXES #2250: Use ASCII C instead of Cyrillic

---

components/result/Result.razor

`Results` component does not have a `Style` forwarding
Added `Style` forwarding for root `div`

Add missed style to Results

---

components/button/Button.razor
components/button/Button.razor.cs
site/AntDesign.Docs/Demos/Components/Button/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Button/doc/index.zh-CN.md
tests/AntDesign.Tests/button/ButtonTests.cs

Adds in a Parameter for AriaLabel that's used as the value for the aria-label attribute on the button.
Step closer to helping with ADA compliance.  Since this is my first pull request, I wanted to keep it small and targeted so feedback/guidance was easier.  I did notice that it's asking me to target the feature branch where the documentation was based off master.  If I target feature it includes far more changes.  If needed, I can abandon and recreate this off the feature branch. 
1.  Screen readers leverage the aria-label to help direct impaired users.  
2. Nothing visual was changed.  
3. The simplest approach is to add a Parameter on the Button component to allow developers to bind a label value that a Screen Reader could use to help impaired users.  This seemed like the best approach …

Feature - Adds AriaLabel Parameter

---

components/select/Select.razor
components/select/SelectBase.cs
components/select/internal/SelectContent.razor
components/select/internal/SelectContent.razor.cs
components/tree-select/TreeSelect.razor
site/AntDesign.Docs/Demos/Components/Select/demo/SearchBox.razor
site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md

https://github.com/ant-design-blazor/ant-design-blazor/issues/1965
In select control when we have EnableSearch set to true with DataSource counting few thousand of items we are facing pretty huge lag on typing search text. This problem occurs when running app locally and the lag is even bigger when app is deployed.
1. Problem: lag when typing on search input when select DataSource has few thousand of items. The lag is observed as visual glitch when we hold backspace or type very fast (the effect may not be that visible on the gif):
2. Solution: Added SearchDebounceMilliseconds property following the example of debounce implementation in Input.razor. Example of the same data source as above, but with SearchDebounceMilliseconds set to 350:
Added SearchDebounceMilliseconds property. Default …

Select search debounce

---

components/modal/modalDialog/Modal.razor.cs

#2288 
| 🇺🇸 English |  fix(module: modal): get rtl from ConfigProvider  |
| 🇨🇳 Chinese |   Modal：从ConfigProvider获取Rtl        |

fix(module: modal): get rtl from ConfigProvider

---

.github/workflows/release.yml

While debugging through the code of AntDesign from a consuming project I noticed that SourceLink is not working properly and I got the output of the IL decompilation. Upon verification I noticed that AntBlazor includes SourceLink as a package, however it was not a deterministic build. SourceLink requires that deterministic builds are enabled.
[NuGet package explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) gives me the following output:
I added the required compiler flag to the release workflow.
Further resources about the prerequisites regarding SourceLink:
https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/
https://github.com/dotnet/sourcelink/blob/main/docs/README.md#continuousintegrationbuild
| ---------- | …

Enable deterministic builds for CI

---

components/select/Select.razor
components/select/internal/SelectContent.razor

Fixes the Id of the input so the aria-owns and aria-controls property values point to a valid identifier.
Noticed while running accessibility plugins through our app.  The values provided to the `aria-owns` and `aria-controls` point to a non-existing identifier.  
1. The problem is related to ADA and providing valid values to the aria properties.  In this case, I think the input's identifier was just missing the `_list` suffix that was added to these properties.  Because it wasn't, there are two elements with the same identifier.
2. N/A
3. Append the `_list` suffix to the input.
N/A
| 🇺🇸 English |     X      |

refactor(Select): Fix invalid aria values

---

components/core/Base/AntInputComponentBase.cs
components/core/Reflection/PropertyReflector.cs
components/radio/RadioGroup.razor.cs
tests/AntDesign.Tests/Radio/RadioGroupTests.razor

Default the name value so the tab order is preserved.
Tabbing through a form that has multiple RadioGroups loses the tab order unless RadioGroups have a name value set.  This is problematic for users who are disabled and rely purely on the keyboard to complete their form.
1.  Multiple RadioGroups on the same form throw the tab order off.
2. N/A
3. Set a default name value on the RadioGroup if one isn't provided.
| 🇺🇸 English |      x     |

fix(module:Radio) Default name value

---

components/select/SelectBase.cs

fix(module: select): can't clear selected option when set value null

---

components/form/Form.razor.cs
tests/AntDesign.Tests/Form/EditContext/Form.EditContext.ValidationTests.razor

An InvalidOperationException is thrown when more than one input of a given form is bound to a property with the same name and we want rules based validation, even if they belong to a different instance.
This can happen in a couple of ways, for example we can have a view model that has two properties: *Player1* and *Player2*, both of type *Player*. Currently, we cannot add an input field for *model.Player1.Name* and *model.Player2.Name* both because we would have two fields with *FieldName* *Name*.
Similarly, if our view model had a *Contacts* property of *List<ContactInformation>* type, we could not bind the properties of *ContactInformation* to input fields, because they would clash.
The problem seems to be caused by the way equality is checked for fields in the line below: …

Fix FieldIdentifier equality check in Rules Mode OnFieldChanged

---

components/tooltip/Tooltip.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/Basic.razor

Applies a tabindex to the wrapping div to help with focus driven from tabbing.
The Tooltip does not allow keyboard-based users to access their content because it's not a tab-able element.  Adding a `tabindex` to the `div` that's handling the events fixes this.
1. Users cannot interact with the Tooltip placed on an element via Keyboard.
2. N/A
3. Apply a tabindex to the wrapping `div` that handles the event listeners. 
Users will be able to tab to elements that leverage the Tooltip component.

fix(module:Tooltip) Tabindex

---

components/form/FormItem.razor
components/form/FormItem.razor.cs
site/AntDesign.Docs/Demos/Components/Form/demo/ValidateWithFeedback.razor
site/AntDesign.Docs/Demos/Components/Form/demo/validate-with-feedback.md

ADA. Visual indication beyond text and color of an error at the field level is helpful for disabled users when filling out forms.  
1. Currently, the only way to show an error icon on a field is if the developer is controlling the validation directly via `HasFeedback`.  But showing the error icon as visual feedback is also helpful when a FormItem is invalid based on the validations sets on the model object.  From an ADA perspective, users need a way to associate an error state to a form field without relying on color.  Though the descriptive text underneath is helpful, the icon helps them quickly distinguish between help text and validation text.
2. N/A
3. Allow the FormItems to opt-in to this visual indication.  Alternatively, consider setting this at the Form level and letting it …

feat(module:form) Add Feedback Icon when Invalid

---

components/calendar/Calendar.razor.cs
components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/modules/dom/manipulationHelper.ts
components/date-picker/DatePicker.Razor.cs
components/date-picker/IDatePicker.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor.cs
components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerPanelChooser.razor
components/date-picker/internal/DatePickerTemplate.razor.cs
components/date-picker/locale/FormatAnalyzer.cs

feat(module:datepicker): Scroll to selected time in DatePicker/TimePicker

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/core/JsInterop/modules/components/iconHelper.ts
components/icon/Icon.razor
components/icon/Icon.razor.cs
components/icon/IconFont.razor.cs
components/icon/IconService.cs
components/tsconfig.json
package.json
site/AntDesign.Docs/Demos/Components/Icon/demo/Twotone.razor
site/AntDesign.Docs/Demos/Components/Icon/demo/two-tone.md
site/AntDesign.Docs/Demos/Components/Icon/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Icon/doc/index.zh-CN.md

resolve https://github.com/ant-design-blazor/ant-design-blazor/issues/1600
| 🇺🇸 English |     two-tone color icon implements      |
| 🇨🇳 Chinese |     实现双色图标      |

feat(icon): two-tone color icon implements

---

site/AntDesign.Docs/Demos/Components/Icon/demo/Iconfont.razor
site/AntDesign.Docs/Demos/Components/Icon/demo/ScriptUrl.razor
site/AntDesign.Docs/Demos/Components/Icon/demo/iconfont.md
site/AntDesign.Docs/Demos/Components/Icon/demo/scriptUrl.md

docs: fix icon demo exception when prerendering

---

components/input-number/InputNumber.razor
components/input-number/InputNumber.razor.cs
site/AntDesign.Docs/Demos/Components/InputNumber/demo/Basic.razor

fixed #2526 
| 🇺🇸 English |   add `PlaceHolder` parameter        |
| 🇨🇳 Chinese |   增加  `PlaceHolder` 属性       |

feat(module: input-number): add `PlaceHolder` parameter

---

components/modal/core/Dialog.razor.cs
components/modal/core/DialogWrapper.razor.cs
components/modal/type/ModalAnimation.cs

#2558
| 🇺🇸 English | reset enter animation className   |
| 🇨🇳 Chinese |    重置modal打开时候的动画       |

fix(module: modal): unreset enter animation className

---

components/calendar/Calendar.razor.cs
components/date-picker/DatePicker.Razor.cs
components/date-picker/IDatePicker.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerTemplate.razor.cs
tests/AntDesign.Tests/DatePicker/DatePickerTests.razor
tests/AntDesign.Tests/DatePicker/RangePickerTests.razor

https://github.com/ant-design-blazor/ant-design-blazor/issues/2538

fix(module: datepicker): value not updated when changed programmatically

---

components/tooltip/Tooltip.razor
components/tooltip/Tooltip.razor.cs

https://github.com/ant-design-blazor/ant-design-blazor/issues/2566
In the current shape, tooltip component is stealing focus (when user is jumping through elements on the page using Tab key) even if children elements of the tooltip have `tabindex` set to `-1`.  Enabling customization of tooltip's tabindex via parameter allows developer to alter this behavior if needed. The default behavior (`tabindex="0"`) required for proper functioning of the focus trigger (https://github.com/ant-design-blazor/ant-design-blazor/pull/2404) remains the same, so we are on the safe side - it's up to the user to consciously opt-out.
| 🇺🇸 English | Tooltip: enable setting TabIndex via parameter. |
⚠️ Please check all items below …

feat(module: tooltip): enable setting TabIndex via parameter

---

site/AntDesign.Docs/Demos/Components/List/demo/Draggable.razor
site/AntDesign.Docs/Demos/Components/List/demo/draggable.md

By adding a div element in `ListItem` and setting `draggable='true'` and providing some `ondragover`/`ondragstart`/`ondrop` envent handlers to `simple list` making the list items can be dragged and dropped to arrange the list sequence.

add a draggable list item demo

---

components/date-picker/RangePicker.razor
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor.cs
components/date-picker/internal/DatePickerPanelChooser.razor
site/AntDesign.Docs/Demos/Components/DatePicker/demo/PresettedRanges.razor
site/AntDesign.Docs/Demos/Components/DatePicker/demo/presetted-ranges.md

| 🇨🇳 Chinese |    新增 RangePicker 预设范围       |

feat(module: DatePicker): support perset time ranges

---

components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerTemplate.razor.cs
tests/AntDesign.Tests/DatePicker/RangePickerTests.razor

https://github.com/ant-design-blazor/ant-design-blazor/issues/1429
Fixes quarter/week range selection when the end value is set first.

fix:(module:rangepicker): date selection

---

components/tree/Tree.razor.cs
components/tree/TreeNode.razor.cs

| 🇺🇸 English |     Fix the problem that the coexistence of Disable and Checked attributes of TreeNode does not take effect     |
| 🇨🇳 Chinese |      修复TreeNode的Disable和Checked属性共存不生效的问题     |

修复TreeNode的Disable和Checked属性共存不生效的问题

---

components/statistic/CountDown.razor.cs
components/statistic/StatisticComponentBase.razor.cs
site/AntDesign.Docs/Demos/Components/Statistic/demo/Countdown.razor

| 🇺🇸 English |    CountDown can auto refresh when set value       |
| 🇨🇳 Chinese |       添加CountDown的reset功能，设置绑定的value后countdown会自动刷新    |

fix(module: statistic): make CountDown reset after the value was changed

---

components/statistic/CountDown.razor.cs

| 🇺🇸 English |    Fix the bug that countdown will not refresh in the background       |
| 🇨🇳 Chinese |     修复CountDown在后台不会刷新的问题      |

fix(module: statistic): CountDown value can't update in background

---

components/image/Image.razor.cs

…can't display in preview
fixed #2595
| 🇺🇸 English | an image which was setted after a fallback image can't display in preview          |
| 🇨🇳 Chinese | 在回退图像后设置的图像无法在预览中显示          |

fix(module: image): an image which was setted after a fallback image can't display in preview

---

components/dropdown/DropdownButton.cs
components/select/Select.razor.cs
components/select/SelectBase.cs
site/AntDesign.Docs/Demos/Components/Select/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Select/demo/Coordinate.razor
site/AntDesign.Docs/Demos/Components/Select/demo/CustomDropdownMenu.razor
site/AntDesign.Docs/Demos/Components/Select/demo/DefaultForm.razor
site/AntDesign.Docs/Demos/Components/Select/demo/DefaultToggleDatasource.razor
site/AntDesign.Docs/Demos/Components/Select/demo/Optgroup.razor
site/AntDesign.Docs/Demos/Components/Select/demo/OptionLabelProp.razor
site/AntDesign.Docs/Demos/Components/Select/demo/Search.razor
site/AntDesign.Docs/Demos/Components/Select/demo/TrackItemChanges.razor
tests/AntDesign.Tests/button/ButtonTests.razor

fix(module: select): change events from `Action` to `EventCallback`

---

components/badge/Badge.razor.cs

fix(module: badge): offset didn't support negative numbers

---

components/input/Input.cs

| 🇺🇸 English |   fix bug that OnChange will invoke twice when paste data to Input #2591    |
| 🇨🇳 Chinese |     修复将数据粘贴到Input时OnChange将调用两次的错误   #2591   |

fix(module: input): OnChange will invoke twice when paste data to Input 

---

components/upload/UploadFileItem.cs

| 🇺🇸 English | Uploading control image recognition supports user-defined modification of image file extension, adding webp format, and repairing that the filename does not exist. A subscript out of range exception is generated |
| 🇨🇳 Chinese | 上传控件图片识别支持自定义修改图片文件扩展名，与添加 WebP 格式，修复 FileName 不存在 . 时产生下标越界异常         |

upload control and add webp ext and custom image extension

---

components/pagination/Pagination.razor
components/pagination/PaginationPager.razor

Fixes #2124 
There're several issues with Pagination component, some are invisible, while some are affecting user experience under small screens
1. Immediately after the component is loaded, the class attribute of PaginationPager 5 is not properly set:
`class="ant-pagination-item-after-jump-prev ant-pagination-item ant-pagination-item-5 ant-pagination-item-after-jump-prev"`
- Should be `before-jump-next` instead of `after-jump-prev`
- There're 2 `ant-pagination-item-after-jump-prev`, which is redundant
2. Click Page 5, we can see that PaginationPager 5 still holds `ant-pagination-item-after-jump-prev` class, which is  unexpected
3. Then click Page 3, both PaginationPager 3 and 5 holds `ant-pagination-item-after-jump-prev` class, so they'll disappear when the screen width is small.
So, …

fix(module: Pagination): Pager 3 and 5 may be invisible when window width is small and there're many pages

---

components/core/Extensions/ServiceCollectionExtensions.cs
components/message/IMessageService.cs
components/message/Message.razor.cs
components/message/MessageService.cs
site/AntDesign.Docs/Demos/Components/Drawer/demo/DropdownInDrawer.razor
site/AntDesign.Docs/Demos/Components/Icon/demo/List.razor
site/AntDesign.Docs/Demos/Components/Input/demo/SearchLoading.razor
site/AntDesign.Docs/Demos/Components/Message/demo/ContinueWith.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Duration.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Info.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Loading.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Other.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Update.razor
site/AntDesign.Docs/Demos/Components/Message/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Message/doc/index.zh-CN.md
site/AntDesign.Docs/Demos/Components/Modal/demo/Confirm.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/Confirm_Service.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
site/AntDesign.Docs/Demos/Components/Popconfirm/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Popconfirm/demo/DynamicTrigger.razor
site/AntDesign.Docs/Demos/Components/Popconfirm/demo/PlacementType.razor
site/AntDesign.Docs/Demos/Components/Steps/demo/StepNext.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/Avatar.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/DefaultFileList.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/FileList.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/PictureCard.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/PictureStyle.razor
site/AntDesign.Docs/Shared/MainFooter.razor.cs

#2631
Testing that an application triggers an AntDesign.Message is not currently possible because it is defined only as a concrete class. Refactoring it to be a class implementing an interface allows us to inject the interface into code and thus allows unit testing.
| 🇺🇸 English | Changed MessageCenter to be used through an interface IMessageCenter. Existing code will continue to function, but new code should inject IMessageCenter. |
| 🇨🇳 Chinese | 将 MessageCenter 更改为通过接口 IMessageCenter 使用。 现有代码将继续运行，但新代码应注入 IMessageCenter。 |

Update MessageService to implement and register as an interface

---

components/cascader/Cascader.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/input-number/InputNumber.razor.cs
components/tree-select/TreeSelect.razor.cs

fix(module: form): fix error status for entry components

---

components/avatar/Avatar.razor.cs
components/avatar/AvatarShape.cs
components/skeleton/Skeleton.razor.cs
components/skeleton/SkeletonElement.razor.cs
components/skeleton/SkeletonType.cs
site/AntDesign.Docs/Demos/Components/Avatar/demo/Badge_.razor
site/AntDesign.Docs/Demos/Components/Avatar/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Skeleton/demo/Element.razor
site/AntDesign.Docs/Shared/ContributorsList.razor
tests/AntDesign.Tests/Avatar/AvatarGroupTests.cs
tests/AntDesign.Tests/Avatar/AvatarTests.cs

#2644 
Add tests in addition to small refactors:
- Fix typo in Avatar
- Remove code in Avatar that wasn't affecting visuals as expected
- Make Avatar shape a constant. Update Skeleton component and demos to use it
- Update Avatar component to calculate size after parameters set method due to it changing one of the properties it relies on.
N/A there should be no differences from a user's perspective. The removed code was not affecting the UI at all due to being invalid CSS.

test(modules: avatar, avatargroup): Add tests for components and small refactors

---

components/select/Select.razor
components/select/Select.razor.cs
site/AntDesign.Docs/Demos/Components/Select/demo/BigData.razor
site/AntDesign.Docs/Demos/Components/Select/demo/big-data.md

https://github.com/ant-design-blazor/ant-design-blazor/issues/2080

feat(module: select): add virtualization support

---

components/select/Select.razor.cs

fix(module: select): remove redundant CreateDeleteSelectOptions() calls in render cycles

---

components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor.cs
components/date-picker/internal/DatePickerPanelChooser.razor

#2637 
The Ok button should be preset in the TimePicker or DatePicker with time, as well as the Now button. The Today button should not be shown in the TimePicker. This pull request fixes this.

fix:(module:datepicker): timepicker value resets to default

---

components/breadcrumb/Breadcrumb.razor
components/breadcrumb/Breadcrumb.razor.cs
components/breadcrumb/BreadcrumbItem.razor
components/breadcrumb/BreadcrumbOption.cs
site/AntDesign.Docs/Demos/Components/Breadcrumb/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Breadcrumb/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Breadcrumb/doc/index.zh-CN.md
tests/AntDesign.TestKit/AntDesign.TestKit.csproj
tests/AntDesign.Tests/AntDesign.Tests.csproj
tests/AntDesign.Tests/Breadcrumb/BreadcrumbItemTests.cs
tests/AntDesign.Tests/Breadcrumb/BreadcrumbTests.cs

#2540 - OnClick
#2649 - Remove unusable code
#2644 - Test coverage
#2658 - Wrong HTML markup causing last separator to display
- A user discovered we document an OnClick parameter for BreadcrumbItem, but it was not implemented. Now it is. Also added to the demo.
- Discovered when testing there is unreachable/unusable code for future features. Removed for now. Left public API alone but added comments about currently not being used.
- Test coverage for Breadcrumb/Item
- Update the markup of Breadcrumb/BreadcrumItem to match Ant.Design React
| 🇺🇸 English | Add OnClick parameter to BreadcrumbItem. Markup of Breadcrumb updated to match Ant.Design React. This could break custom CSS targeting this component's resulting markup. |
| 🇨🇳 Chinese …

Add OnClick parameter to BreadcrumbItem, Add Tests, Remove unusable code

---

components/icon/Icon.razor.cs
components/icon/IconService.cs
site/AntDesign.Docs/Demos/Components/Icon/demo/Twotone.razor
site/AntDesign.Docs/Demos/Components/Icon/demo/two-tone.md
tests/AntDesign.TestKit/AntDesign.TestKit.csproj
tests/AntDesign.Tests/AntDesign.Tests.csproj

fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/2662

refactor(module: icon): fix two-tone icon state update & first rendering

---

components/tabs/TabPane.razor

fix(module: tabs): the content overflow at animated mode

---

components/tabs/TabPane.razor
tests/AntDesign.Tests/tabs/TabsTests.razor

fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/2675

fix(module: tabs): panel without animated display incorrectly

---

components/table/TableModels/ITableSortModel.cs
components/table/TableModels/SortModel.cs

fix (table) : Converting IQueryable to IOrderedQueryable returned null

---

components/date-picker/RangePicker.razor.cs

fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/2676

fix(module: datepicker): an exception is caused when passes the value as null

---

components/table/TableModels/SortModel.cs

fix(module: table): table sort subsequent OrderBy overrode precedent one

---

components/segmented/Segmented.razor.cs
site/AntDesign.Docs/Demos/Components/Segmented/demo/Dynamic.razor

fix(module: segmentd): default value binding incorrectly with options

---

components/message/MessageItem.razor.cs

fix(module: message): exception casue by Invariant Globalization setting

---

components/tree-select/TreeSelect.razor
components/tree-select/TreeSelect.razor.cs
components/tree/Tree.razor.cs
components/tree/TreeNodeTitle.razor
site/AntDesign.Docs/Demos/Components/TreeSelect/demo/Search.razor
site/AntDesign.Docs/Demos/Components/TreeSelect/demo/search.md

Enabling Search on TreeSelect not working.
When you try to use search on tree select it not work, the code is like the search in select, so base on that i include the part that was missing and make it work.
At the same time i impove the search on tree because it was case sensitive. I make it work with ignore case and found that the code that apply styles to titles was using the input so i change that to use the original value and insert the span with class and style to make it work.
Fix search on treeselect 
Change tree search  to ignoreCase and fix display of match to respect the original value.

fix(module TreeSelect / Tree): search not working on TreeSelect

---

components/date-picker/RangePicker.razor
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs

#1259
This also fixes:
RangePicker end panel not shown in RTL mode
RangePicker range preset value resets when time input is enabled
RangePicker keeps focus when input canceled
RangePicker cannot clear value when one of the inputs has a focus

fix:(module:datepicker): RangePicker has incorrect start/end panels

---

components/date-picker/internal/DatePickerBase.cs
components/date-picker/locale/FormatAnalyzer.cs
tests/AntDesign.Tests/DatePicker/locale/FormatAnalyzerTests.cs

#2714
The culture of DatePicker is not taken into account when parsing manual input.

fix:(module:datepicker): correct culture not applied when manual input

---

components/menu/MenuItem.razor
components/tooltip/Tooltip.razor
components/tooltip/Tooltip.razor.cs
site/AntDesign.Docs/Demos/Components/Avatar/demo/Group.razor
site/AntDesign.Docs/Demos/Components/Comment/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Drawer/demo/DropdownInDrawer.razor
site/AntDesign.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor
site/AntDesign.Docs/Demos/Components/Form/demo/ComplexFormControl.razor
site/AntDesign.Docs/Demos/Components/Form/demo/CustomizedLabel.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/ArrowPointAtCenter.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/AutoAdjustOverflow.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/Icon_.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/PlacementType.razor
site/AntDesign.Docs/Demos/Components/Tooltip/demo/icon.md
site/AntDesign.Docs/Demos/Components/Tooltip/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Tooltip/doc/index.zh-CN.md

> I can't be sure of the correctness of the translation into Chinese with the help of a translator, I left places for the Chinese text as `TODO: Translate`
Tooltip component uses OneOf Title instead separated Title and TitleTemplate
Users will have to use TitleTemplate if used RenderFragment to Title
| 🇺🇸 English | Tooltip component uses `RenderFragment TitleTeplate` instead `OneOf Title` |
| 🇨🇳 Chinese | TODO: Translate |

Use TitleTemplate in Tooltip

---

package.json
scripts/gulp/tasks/library.ts
scripts/gulp/util/task-helpers.ts

Related issue: #2694 
Added task to the gulp pipeline to include the .less files.
Low risk, I think.  I'm not 100% that these files will end up in the .nupkg file.
| 🇺🇸 English |   Altered gulp pipeline to include less files so they end up in /staticwebassets/less in the nuget package.        |

Copy .less files to wwwroot folder

---

components/radio/RadioGroup.razor
site/AntDesign.Docs/Demos/Components/Radio/demo/EnumGroup.razor
tests/AntDesign.Tests/Radio/RadioGroupTests.razor

fixed #2743 
| 🇺🇸 English |  fixed Radio that the disabled parameter for RadioGroup with `RadioOption<TValue>` options doesn't work         |
| 🇨🇳 Chinese |  修复 Radio 的 disabled 属性在 使用了 RadioOption<TValue> 作为options 的 RadioGroup   中不起作用的问题    |

fix(module: radio): the disabled parameter for RadioGroup with `RadioOption<TValue>` options doesn't work

---

components/IsExternalInit.cs
components/core/Extensions/ElementReferenceExtensions.cs
components/core/JsInterop/DomEventListener.cs
components/core/JsInterop/DomEventSubscription.cs
components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/modules/dom/eventHelper.ts
components/core/JsInterop/modules/dom/infoHelper.ts

follow up #1857
fixed #2136
fixed #2241

fix(module: Core): Remove the event listener when the component is disposed

---

components/core/EventCallbackArgs/DateTimeChangedEventArgs.cs
components/core/Helpers/DateHelper.cs
components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerStatus.cs
components/date-picker/internal/DatePickerTemplate.razor.cs
site/AntDesign.Docs/Demos/Components/TimePicker/demo/Value.razor
tests/AntDesign.Tests/DatePicker/DatePickerKeyboardInputTests.razor

#2713 
#2729
This pull request brings DatePicker/RangePicker behavior closer to the behavior of the original ant.design.
Fixes:
- OnChange event behavior #2713 
- Cannot switch year in the RangePicker header #2729 
- Date input with keyboard
- Input panels wrong when start/end is in the same period
- The ending week is not highlighted correctly in Picker=='week'
- The start date is not highlighted during the end date input in the date picker with the time
- Other minor fixes and refactorings

fix:(module:datepicker): OnChange event behavior is incorrect

---

site/AntDesign.Docs/Demos/Components/Steps/doc/index.en-US.md

No issue reported. Related to docs page https://antblazor.com/en-US/components/steps
I have found a typo in https://antblazor.com/en-US/components/steps 
Replaced `Dtatus` with `Status`
| 🇺🇸 English | Fixed typo in Steps documentation |
| 🇨🇳 Chinese | 修复了 Steps 文档中的错字 |

Fix typo in Steps demo docs: Dtatus -> Status

---

components/modal/confirmDialog/Confirm.razor.cs

#2772 
| 🇺🇸 English |  fix: Confirm dialog closeable   |
| 🇨🇳 Chinese |      Confirm 错误的响应 close icon 事件    |

fix: Confirm dialog closeable(#2772)

---

components/input-number/InputNumber.razor.cs
site/AntDesign.Docs/Demos/Components/InputNumber/demo/Precision.md
site/AntDesign.Docs/Demos/Components/InputNumber/demo/Precision.razor
tests/AntDesign.Tests/InputNumber/InputNumberTests.razor

feat (module: InputNumber) : support parameter Precision

---

components/segmented/Segmented.razor.cs
components/segmented/SegmentedItem.razor.cs
site/AntDesign.Docs/Demos/Components/Segmented/demo/Disabled.razor

fixed #2760 
| 🇺🇸 English |   Fixed Segmented that the Disabled parameter does not work on items and cannot be dynamically toggled       |
| 🇨🇳 Chinese |  修复 Segmented 的 Disabled 参数对项不起作用，也不能动态切换的问题         |

fix(module: segmented): The Disabled parameter does not work on items and cannot be dynamically toggled

---

components/core/JsInterop/modules/dom/eventHelper.ts

fix(module: core): event listener was broken

---

components/descriptions/Descriptions.razor

Currenttly, it's lose `div.ant-descriptions-item-container` element 
Sync dom structure with `ant design` framework [link](https://ant.design/components/descriptions-cn/#components-descriptions-demo-vertical)
| 🇺🇸 English | fix descriptions component miss div element |
| 🇨🇳 Chinese | 修复描述列表组件缺少的div元素 |

fix(module: descriptions): add missing `div` element

---

components/menu/SubMenu.razor

| 🇺🇸 English |    Fixed Menu that class name of the expand icon for submenu        |
| 🇨🇳 Chinese |  修复 Menu 子菜单展开图标的样式         |

fix(module: menu): fix class name of the expand icon for submenu

---

components/core/Component/Overlay/Overlay.razor
components/core/Component/Overlay/OverlayTrigger.razor.cs
components/dropdown/Dropdown.razor
components/dropdown/Dropdown.razor.cs
site/AntDesign.Docs/Demos/Components/Dropdown/demo/Arrow.razor
site/AntDesign.Docs/Demos/Components/Dropdown/demo/ArrowCenter.razor
site/AntDesign.Docs/Demos/Components/Dropdown/demo/arrow-center.md
site/AntDesign.Docs/Demos/Components/Dropdown/demo/arrow.md
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Dropdown/doc/index.zh-CN.md

| 🇺🇸 English |  Add Dropdown arrow parameter       |
| 🇨🇳 Chinese |  增加  Dropdown 箭头样式     |

feat(module: dropdown): support arrow parameter

---

components/auto-complete/AutoComplete.razor.cs

#2752 #2748
| 🇺🇸 English |      fix search panel show     |
| 🇨🇳 Chinese |       修复搜索时弹列表有时候不显示    |

fix: AutoComplete search bug (#2752 #2748)

---

components/cascader/Cascader.razor

fix(module: Cascader) AllowClear was not working when false

---

components/drawer/Drawer.razor
components/drawer/Drawer.razor.cs
components/drawer/DrawerContainer.razor
components/drawer/config/DrawerOptions.cs
site/AntDesign.Docs/Demos/Components/Drawer/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Drawer/doc/index.zh-CN.md

a property for modifying the style of the header in the drawer component
- [ x] New feature
- [x ] Component style update
This pull request adds a HeaderStyle property to the Drawer component
[Blazor Drawer](https://antblazor.com/en-US/components/drawer#ant-blazor-e99e3914-0b8c-4d6b-a87a-8ab2599cc25c)
When changing css for the Drawer header, there is no property available to do so. This PR add that property, for changing for example, the background-color of the header in the Drawer.
The new property in the Drawer component looks like this
```
<Drawer 
Visible="@Visible" 
Placement="@Placement" 
Title="CompanyName" 
OnClose="_ => Close()" 
BodyStyle="@DrawerBackgroundColor" 
HeaderStyle="@HeaderBackgroundColor"> @* <--added this property * @
...
</Drawer>
```
This is an example of what the …

feat(module:drawer): add property HeaderStyle to Drawer component

---

components/slider/Slider.razor
components/slider/Slider.razor.cs
tests/AntDesign.Tests/Slider/SliderTests.cs

- Add tests for slider
- Remove commented out code. 
- Refactor checking a double against zero to check against a tight range around zero because it will fail sometimes. 
- Update aria attributes on handles to have proper values.
#2644 
| 🇺🇸 English |    Slider accessibility updates with aria labels       |

test(module: slider) Add tests, Small refactors

---

components/button/DownloadButton.razor
components/button/DownloadButton.razor.cs
components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/core/JsInterop/modules/components/downloadHelper.ts
components/core/JsInterop/modules/components/export.ts
site/AntDesign.Docs/Demos/Components/Button/demo/Download.razor
site/AntDesign.Docs/Demos/Components/Button/demo/Size.razor
site/AntDesign.Docs/Demos/Components/Button/demo/download.md
site/AntDesign.Docs/Demos/Components/Button/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Button/doc/index.zh-CN.md
tests/AntDesign.Tests/button/DownloadButtonTests.razor

Close #2293
| 🇺🇸 English |     Add `DownloadButton`      |
| 🇨🇳 Chinese |     新增`DownloadButton`     |

feat(module:button): Add `DownloadButton`

---

components/badge/Badge.razor
components/badge/Badge.razor.cs
site/AntDesign.Docs/Demos/Components/Badge/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Badge/doc/index.zh-CN.md
tests/AntDesign.Tests/badge/BadgeTests.cs
tests/AntDesign.Tests/badge/RibbonTests.cs

| 🇺🇸 English | Fix bug where Title parameter was not being rendered. |

test(module: badge): Test Badge component, format document, fix small bug with class name

---

components/drawer/Drawer.razor
components/drawer/Drawer.razor.cs
site/AntDesign.Docs/Demos/Components/Drawer/demo/formindrawer.md
site/AntDesign.Docs/Demos/Components/Drawer/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Drawer/doc/index.zh-CN.md
tests/AntDesign.TestKit/AntDesignTestBase.cs
tests/AntDesign.Tests/Drawer/DrawerTests.cs

Bug fix:
- Content string would never render (wrong condition checked)
Refactors:
- Remove `this.`
- Remove code that didn't do anything helpful from my testing - will comment on inline
- Moved code to make it more obvious only one condition can exist at a time - will comment on inline
Documentation site update to match available parameters
#2644 
| 🇺🇸 English |    Fix bug where Content wouldn't render in Drawer if it was a string and not RenderFragment       |
| 🇨🇳 Chinese |  修复如果内容是字符串而不是 RenderFragment，则内容不会在 Drawer 中呈现的错误         |

test(module: drawer): Test, refactor and document Drawer

---

components/cascader/Cascader.razor.cs
site/AntDesign.Docs/Demos/Components/Cascader/demo/Disabled.razor
site/AntDesign.Docs/Demos/Components/Cascader/demo/disabled.md
tests/AntDesign.Tests/Cascader/CascaderTests.razor

fixed #2825 
| 🇺🇸 English |   Add Cascader `Disabled` parameter        |
| 🇨🇳 Chinese |   增加 Cascader `Disabled` 属性       |

feat(module: cascader): add `Disabled` parameter

---

components/back-top/BackTop.razor
components/back-top/BackTop.razor.cs
tests/AntDesign.Tests/BackTop/BackTopTests.razor

| 🇺🇸 English |   fix backtop doesn't remove the dom when visible is false        |
| 🇨🇳 Chinese |   修复 BackTop 在隐藏时没有真正清除 dom        |

fix(module: backtop): doesn't remove the dom when visible is false

---

components/core/EventCallbackArgs/DateTimeChangedEventArgs.cs
components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
site/AntDesign.Docs.Server/Pages/Error.cshtml
site/AntDesign.Docs.Server/Pages/Error.cshtml.cs
site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.zh-CN.md
site/AntDesign.Docs/Demos/Components/TimePicker/demo/Value.razor

#2307 
This pull request adds the OnOk event to the DatePicker/RangePicker (with time). The event is invoked when the value input is confirmed with the Ok button.

feat:(module: datepicker): add OnOk event

---

components/tabs/Tabs.razor
components/tabs/Tabs.razor.cs
tests/AntDesign.Tests/tabs/TabsTests.razor

https://github.com/ant-design-blazor/ant-design-blazor/issues/2372

feat: #2372 Added support of tab bar css style and class

---

components/core/Base/AntInputComponentBase.cs
components/form/FormItem.razor.cs
components/input/Input.cs
tests/AntDesign.Tests/Input/InputTests.razor

fix(module: input): convert error status work incorrectly

---

components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
tests/AntDesign.Tests/DatePicker/DatePickerKeyboardInputTests.razor
tests/AntDesign.Tests/DatePicker/RangePickerTests.razor

#2841
This fixes two issues from #2841. 
Also, it brings RangePicker's behavior closer to the original antdesign. It gives the ability to select the range values more conveniently. Now it's possible to select the start date later than the end date without clearing the value.

fix:(module: datepicker): tab key does not confirm the value

---

components/locales/ru-RU.json

incorrect day order displayed on calendars and datepickers for russian locale, relates to changes made in commit: 894439adec248573a9e19a20453a730307824e5c
| 🇺🇸 English |  fix day order in calendar header for russian locale        |

fix:(module: locale): wrong day order

---

components/core/JsInterop/modules/dom/manipulationHelper.ts
components/date-picker/internal/DatePickerDatetimePanel.razor.cs

The smoothScrollTo function continued to loop when it shouldn't causing various issues with the selected time animation in the DatePicker/RangePicker with time input. I replaced it with the ts function from the picker used in the ant.design. This issue should be hot-fixed ASAP.

fix:(module:datepicker): smoothScrollTo causes an infinite loop

---

components/core/Extensions/ArrayExtensions.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatePanel.razor
components/date-picker/internal/DatePickerDatetimePanel.razor
components/date-picker/locale/DatePickerLocale.cs
components/locale-provider/Locale.cs
components/locale-provider/LocaleProvider.cs
components/locales/de-DE.json
components/locales/en-GB.json
components/locales/nl-BE.json
components/locales/nl-NL.json
components/locales/pl-PL.json
components/locales/ru-RU.json
components/locales/zh-TW.json
components/select/SelectLocale.cs
components/table/TableLocale.cs
components/transfer/TransferLocale.cs
site/AntDesign.Docs/Demos/Components/DatePicker/demo/Globalization.razor
site/AntDesign.Docs/Demos/Components/DatePicker/demo/globalization.md
tests/AntDesign.Tests/Core/Extensions/ArrayExtensionsTests.cs

fix(module: datepicker): wrong day order and fallback to use globalization libaray when there is no day locale

---

components/core/JsInterop/modules/components/uploadHelper.ts

fix(module: upload): should get error raw response

---

components/locales/cs-CZ.json

fix(module: locale): wrong shortWeekDays for cs-CZ locale

---

components/tree/TreeEventArgs.cs
components/tree/TreeNodeTitle.razor.cs

should solve #2863
I couldn't test it, but it should work if the underlying code works. 
If it does, the example code on the website can be changed to implement dropping, which should be pretty straightforward.

should solve #2863

---

components/segmented/Segmented.razor.cs
components/segmented/SegmentedItem.razor.cs
tests/AntDesign.Tests/Segmented/SegmentedTests.razor

fixed #2868
While TValue is value type, `DefaultValue !=null` is always true, but the DefaultValue default is not the binding value, so it would cause incorrect binding at initial time.
| 🇺🇸 English | Fixed  binding value type causes an incorrect initialization selection        |
| 🇨🇳 Chinese |   修复绑定值类型导致初始化选中错误        |

fix(module: segmented): binding value type causes an incorrect initialization selection

---

components/modal/config/ModalOptions.cs
components/modal/core/Dialog.razor.cs
components/modal/modalDialog/ModalCancelFooter.razor
components/modal/modalDialog/ModalCancelFooter.razor.cs
components/modal/modalDialog/ModalOkFooter.razor
components/modal/modalDialog/ModalOkFooter.razor.cs
site/AntDesign.Docs/Demos/Components/Modal/demo/CustomModalFooter.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/custom-modal-footer.md

#2769
| 🇺🇸 English |   feat(modal): add only one OK footer and onlt one Cancel footer    |
| 🇨🇳 Chinese |  为 Modal 内置仅有一个 OK 按钮的 Footer   和仅有一个 Cancel 按钮的 Footer        |

feat(modal): add only one OK footer and onlt one Cancel footer

---

site/AntDesign.Docs/Demos/Components/Table/demo/OData.razor
site/AntDesign.Docs/Demos/Components/Table/demo/odata.md

feat(module: table): support for odata

---

components/date-picker/RangePicker.razor.cs

This fixes an issue where an incorrect week comparison makes it impossible to select the week from a different year. The week comparison should also check the date's year, not only the week's number.

fix:(module:datepicker): incorrect week comparison causes disabled input

---

components/date-picker/internal/DatePickerDatePanel.razor
components/date-picker/internal/DatePickerPanelBase.cs
components/date-picker/internal/DatePickerTemplate.razor.cs

#945 
This adds selected week range visualization to the `RangePicker` with `Picker="@DatePickerType.Week"`.
As a downside, selecting the week that exists on both panels looks a bit cramped.
vs the current version which looks like below

feat:(module: datepicker): Add selected week range visualization

---

components/input/Input.cs

fixed #2887 
| 🇺🇸 English |  Fixed input that when its value is changed in code, it would rollback on click       |
| 🇨🇳 Chinese |  修复 Input 在被从代码修改值时，再点击输入框会回退的问题          |

fix(module: input): when its value is changed in code, it would rollback on click

---

components/date-picker/internal/DatePickerDatetimePanel.razor.cs

#2915
Fixes InvalidOperationException in the DatePicker/RangePicker (with time input enabled) that happens after clicking the input field when Value is null.

fix:(module:datepicker): Exception on input with time when Value is null

---

components/tree-select/TreeSelect.razor
components/tree-select/TreeSelect.razor.cs

#2939 
The TreeSelect component didn't allow a TitleTemplate attribute to be specified. This adds that as a parameter.
| 🇺🇸 English | It is now possible to override the TitleTemplate in a TreeSelect component |

feat(module:tree-select): Add TitleTemplate parameter

---

components/core/Helpers/ClassMapper.cs

fix 2911 (css classes gets appended twice)
https://github.com/ant-design-blazor/ant-design-blazor/issues/2911

fix 2911 (css classes gets appended twice)

---

components/table/Column.razor.cs

fixed #2938
Enum types can not use `==` when they are boxed.
| 🇺🇸 English |  Fxied Table can't restore the query state of filters which value is enum type         |
| 🇨🇳 Chinese |   修复 Table 不能恢复枚举类型的 Filter 的查询状态     |

fix(module: table): can't restore the query state of filters which value is enum type

---

components/core/Helpers/Formatter.cs

fixed #1474
fixed #2917 
https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/?WT.mc_id=DT-MVP-5003987#annotating-reflection
| 🇺🇸 English |  Fixed Statistic CountDown format incorrectly when publish with trimming         |
| 🇨🇳 Chinese |   修复  Statistic 的 CountDown 再裁剪发布时格式化无效的问题    |

fix(module: statistic): countdown format incorrectly when publish with trimming

---

components/table/Table.razor.Selection.cs
components/table/Table.razor.cs
site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj

fix https://github.com/ant-design-blazor/ant-design-blazor/issues/2921
Fix IQueryable or IEnumerable using AsNoTracking will cause select data duplication bug

fix 2921 Fix IQueryable or IEnumerable using AsNoTracking will cause select data duplication bug

---

components/table/Selection.razor

fix https://github.com/ant-design-blazor/ant-design-blazor/issues/2233
Table Selection Component Hidden Property not working

fix 2233 Table Selection Component Hidden Property not working

---

site/AntDesign.Docs/Demos/Components/Table/demo/Head_.razor
site/AntDesign.Docs/Demos/Components/Table/demo/head.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md

update the demo for https://github.com/ant-design-blazor/ant-design-blazor/discussions/2822
| 🇺🇸 English |  add Table a search box in the filter & sorter demo         |
| 🇨🇳 Chinese |  增加 Table 的查询和排序demo中增加查询框         |

docs(module: table): add a search box in the filter & sorter demo

---

components/input/Input.cs

This has been seen multiple times when using bUnit tests. For more information, see #2956.
#2956
Detailed in the above-mentioned ticket.
Fix periodic null reference exception when testing input component using the bUnit testing library.

Fix null reference exception

---

components/tabs/TabPane.razor.cs

- Cancel the use of ShouldRender to control rendering
- We may need to re-tune performance issues later
| 🇺🇸 English |  Fixed some issues with dynamic rendering          |
| 🇨🇳 Chinese |  修复一些关于动态渲染的问题         |

fix(module: tabs): render issues

---

components/core/Base/AntInputComponentBase.cs
components/input/Input.cs
tests/AntDesign.Tests/Input/InputTests.razor

fix(module: input): `OnChange` would trigger three times and clear icon would cover the suffix

---

components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs

We ran into the need to use custom disabled logic, but also wanted to keep the default logic that kept the start/end in the proper order. 
~This PR adds a property to allow that setting which "mode" you want to use and then wraps the DisabledDate function provided in a method to check the type of check to run. It then either runs one or both.~
Through discussion below, this PR updates the disabled logic to always apply the default logic even when custom is provided.
| 🇺🇸 English | Update RangePicker disabled date logic to always apply default logic even when custom is provided. This keeps ranges in the proper order even with custom disabled logic. |
| 🇨🇳 Chinese | 更新 RangePicker 禁用日期逻辑以始终应用默认逻辑，即使在提供自定义时也是如此。即使使用自定义禁用逻辑，这也会使范围保持正确的顺序。 …

fix(module: RangePicker): Always run default disabled logic, even with custom function provided

---

components/tabs/Tabs.razor.cs

fixed #2180
| 🇺🇸 English |   Fix avoid active pane after tabs is dispsed        |
| 🇨🇳 Chinese |  修复 Tabs 关闭异常，阻止在 disposed 后还触发渲染器         |

fix(module: tabs): avoid active pane after tabs is dispsed

---

components/input/Input.cs
components/input/Search.razor.cs
site/AntDesign.Docs/Demos/Components/Input/demo/SearchBox.razor

fixed #2989
| 🇺🇸 English |   fixed wrong style of Search with clear button        |
| 🇨🇳 Chinese |   修复 Search 组件设置了清除按钮的样式        |

fix(module: input): wrong style of Search with clear button

---

components/select/SelectBase.cs
components/tree-select/TreeSelect.razor.cs

fixed #2878
| 🇺🇸 English |  Fixed TreeSelect value bind incorrectly when default value was set          |
| 🇨🇳 Chinese |   修复  TreeSelect 当绑定了默认值后，不能正确修改值的问题       |

fix(module: tree-select): value bind incorrectly when default value was set

---

components/transfer/Transfer.razor.cs

I added reinitializacion of values when TargetKeys or SelectedKeys change from outside so it properly display the correct values.
I am using this in production and works fine, and is more easy to use this way. I hope it helps.

feet-bug(module: Transfer): refresh data on change SelectedKeys or TargetKeys parameters

---

components/select/Select.razor.cs
components/select/SelectBase.cs
tests/AntDesign.Tests/Select/Select.Tags.Tests.razor

fixes #2965 
When there was a select component set to `Tags` mode and the datasource was empty, any entered tag options were being hidden from user even though they went through the two way binding. 
There was an issue where whenever the datasource was empty it would use `Clear()` on the option list instead of letting the change trickle down to where it updates the option list based on the datasource.  To ensure the user entered tags do not go away I add them after the option list is created.
| 🇺🇸 English |  Select mode Tags will retain tag options when datasource is empty   |
| 🇨🇳 Chinese |  選擇模式標籤將在數據源為空時保留標籤選項  |

fix(module: select): add tags when datasource is empty

---

components/tabs/Tabs.razor.cs

fixed #2732
| 🇺🇸 English |   Fixed Tabs exception at first load while activekey is specificed to a disabled tab      |
| 🇨🇳 Chinese |    修复 Tabs 当 Activekey  指定了一个禁用的 TabPane 时，或第一个 TabPane 就是禁用时，初次加载会抛异常的问题   |

fix(module: tabs): exception at first load while activekey is specificed to a disabled tab

---

components/cascader/Cascader.razor.cs
site/AntDesign.Docs/Pages/Test.razor

fixed #2435
| 🇺🇸 English |    Fixed Cascader boudary adjust mode default to InView       |
| 🇨🇳 Chinese |    修复   Cascader 边界调整模式默认改为 InView     |

fix(module: cascader): make boudary adjust mode default to InView

---

components/tabs/Tabs.razor.cs

fix 2725 ReuseTabs close other tab rendering error
The original judgment logic of this module will result in a style rendering exception if the closed tab is not the currently selected tab
https://github.com/ant-design-blazor/ant-design-blazor/issues/2725

fix(module: tabs): ReuseTabs close other tab rendering error

---

components/select/Select.razor.cs
components/select/SelectBase.cs
tests/AntDesign.Tests/Select/Select.SelectOptions.Tests.razor

This can be seen in the "hide selected" demo on the documentation. If you select an option in the list, then type in a search that would include that selected option it displays - it should not. If you then remove the search it will still display. This PR fixes those issues.
| 🇺🇸 English | fix(module:select): Fix bug where selected options will display even with HideSelected set to true when searching or clearing search |
| 🇨🇳 Chinese | fix(module:select)：修复在搜索或清除搜索时即使将 HideSelected 设置为 true 也会显示所选选项的错误 |

fix(module:select): Selected options will display even with HideSelected set to true when searching or clearing search

---

components/input/Input.cs

add EventCallback OnClear to component Input<T> as a parameter it is called when the input contents are cleared by clicking the clear icon
In some cases, we need to be notified when the user clears input contents by clicking the clear icon, for example if a keywork-searching was in effect, we need to reset the search results. But current there's no callback defined for this event.
The solution is quite simple, just add an event callback into component Input, and invoke it when user clears the contents.
`
[Parameter]
public EventCallback OnClear { get; set; }
`

feat(module: input): add EventCallback OnClear

---

components/input/Input.cs
components/transfer/Transfer.razor

fixed #1029
add `OnClear` callback for #2979
| 🇺🇸 English |   Fixed Transfer throw exception when it's in Form         |
| 🇨🇳 Chinese |    修复 Transfer 在 Form 内抛异常的问题       |

fix(module: transfer): throw exception when it's in form

---

components/core/Component/Overlay/OverlayTrigger.razor.cs
tests/AntDesign.Tests/Menu/Menu.Horizontal.Tests.razor

fixed #2107
fixed #2739
| 🇺🇸 English |   Fixed Overlay would show after mouse leave the trigger      |
| 🇨🇳 Chinese |   修复 Overlay 会在鼠标离开触发元素之后还打开        |

fix(module: Overlay): overlay show after mouse leave trigger

---

components/select/SelectBase.cs
tests/AntDesign.Tests/Select/Select.SelectOptions.Tests.razor

Issue: Select component can not present the sequence of each selected item.
For example: Select 2, 1 items in Select component, Select'd Values is 1, 2 (reversed sequence) instead of 2,1 (correct sequences)
Solution: Initlaize a private variable to fix the condition.

Protected selected items' selection sequences;

---

components/table/Table.razor.cs

…DataSource changes
#3038 
`_showItems` was always one update behind when `HidePagination` was set to true. Moved this to happen before the query model is built so that the table body is built with all items in `DataSource` when `HidePagination` is set to true.

Table hide pagination fix

---

components/input/Input.cs
tests/AntDesign.Tests/Input/InputTests.razor
tests/AntDesign.Tests/Input/TextAreaTests.razor

#3104 
Textarea is no longer rendering max length onto the markup - this fixes that and adds tests to prevent a regression.
| 🇺🇸 English | fix(module: Textarea): Fix Textarea not rendering maxlength on textarea |
| 🇨🇳 Chinese | fix(module: Textarea)：修复 Textarea 不在 textarea 上渲染 maxlength |

fix(module: Textarea): Fix Textarea not rendering maxlength on textarea

---

components/tabs/Reuse/ReuseTabs.razor.cs

fix 2860 ReuseTabs Switching tabs when the base url is not the default / causes url errors
fix [https://github.com/ant-design-blazor/ant-design-blazor/issues/2860](https://github.com/ant-design-blazor/ant-design-blazor/issues/2860)
Except the default path is "", any other page parameter must start with /, so just replace the empty character of the default path, otherwise a bug will occur when the BaseURL is not /

fix(module: tabs): ReuseTabs occur error when the base url is not the default

---

components/input-number/InputNumber.razor

Was previously styling certain InputNumbers with 100% width, recent update to the library broke this functionality. 

Allow passing Style and ID to InputNumber without a wrapper

---

components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsService.cs

[fix3152](https://github.com/ant-design-blazor/ant-design-blazor/issues/3152)
Rewrite the logic of ReuseTabs about the tab key. In fact, the logic of GetNewKeyByUrl does not need to be a separate method. The value of the tab key is mainly derived from CurrentUrl, so use the ternary operator directly for the default page when the get set of CurrentUrl When it is an empty string, it is temporarily replaced with /, and adjusted to a real empty string when actually jumping
重写了 ReuseTabs 关于 tab key 的逻辑，之前其中 GetNewKeyByUrl 的逻辑其实没必要单独独立一个方法，tab key 的取值主要是源自 CurrentUrl，所以直接在 CurrentUrl 的 get set 时利用三元运算符针对 默认页时为 空字符串的情况进行了临时替换为 / ，并在实际跳转时调整为真实的 空字符串

fix(module: tabs): rewrite the logic of ReuseTabs about tab key

---

components/core/Helpers/DateHelper.cs

Fixes `System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.'` in the `CombineNewDate` method. This happens when the day value is bigger than the days in the month in the DateTime it tries to create.

fix:(module:datepicker): un-representable DateTime when day>daysInMonth

---

components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/DatePickerDatePanel.razor

The WeekPicker is currently using DateHelper.GetWeekOfYear(DateTime date, DayOfWeek firstDay) for the calculation of the Week number. DateHelper is using the InvariantCulture. 
FirstDayOfWeek of the InvariantCulture is Sunday
For example, for de-DE culture, the default value of FirstDayOfWeek is Monday
Additionaly CalendarWeekRule of InvariantCulture is FirstDay
For de-DE it is FirstFourDayWeek
those differences result in different Weeknumbers for both cultures.
For Example the 3rd April 2023 is Week 15 for Invariant and 14 for de-DE
To resolve this Issue we can use the CultureInfo Property of the DatePicker
```
var calendar = CultureInfo.Calendar;
var calendarWeekRule = CultureInfo.DateTimeFormat.CalendarWeekRule;
var week = calendar.GetWeekOfYear(date1,calendarWeekRule, …
```

Change Calculation of Calendarweek for WeekPicker

---

components/tabs/TabPane.razor
components/tabs/TabPane.razor.cs
components/tabs/Tabs.razor
components/tabs/Tabs.razor.cs
tests/AntDesign.TestKit/AntDesignTestBase.cs
tests/AntDesign.Tests/tabs/TabsTests.razor

fixed #3143 
fixed #3174
| 🇺🇸 English |  Fixed Tabs animated cause display incorrectly        |
| 🇨🇳 Chinese |  修复 Tabs 的 Animated 属性导致显示不正常       |

fix(module: tabs): animated cause display incorrectly

---

components/table/Table.razor.cs

Thrown exception was not logged because LogError overload was used incorrectly. When calling JS while disposing a component a JSDisconnectedException could be thrown, which should be ignored.
Closes #3215
#3215 

fix(module:table): fix not logging exception and ignore JSDisconnectedException

---

components/tree-select/TreeSelect.razor
components/tree-select/TreeSelect.razor.cs

I wanted to use the `OnNodeLoadDelayAsync` for `TreeSelect`. Essentially the same problem as #2939, that the parameter could not be given. This time I decided to fix it by using attribute splatting, so that all `Tree` attributes can be accessed in `TreeSelect`.
| 🇺🇸 English |  All additional parameters of `Tree` that can't be given to `TreeSelect` directly can now be given in a dictionary to the `TreeAttributes` parameter |

feat(module:tree-select): Use attribute splatting for internal tree

---

components/drawer/Drawer.razor
tests/AntDesign.Tests/Drawer/DrawerTests.cs

-
Without this close button triggers form submit if drawer is defined within form (<button> without type specified defaults to form submit behavior).
| 🇺🇸 English |  Added `type="button"` to close button in Drawer  component  |
Should not break anything or require changes from user side.

Fix: Add `type="button"` to Drawer close button.

---

components/tree/Tree.razor.cs
components/tree/TreeNode.razor.cs
components/tree/style/patch.less
site/AntDesign.Docs/Demos/Components/Tree/demo/Search_.razor
site/AntDesign.Docs/Demos/Components/Tree/demo/search.md
site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md

Reverts ant-design-blazor/ant-design-blazor#3221
#3242 is better implement.

Revert "add `SimplifySearchResults ` to hide the nodes without any matched parent or child from the search results"

---

components/table/Table.razor
components/table/Table.razor.cs

…ering stage, and avoid unnecessary use of ResizeObserver
fixed #3273

fix(module: table): empty status position incorrectly during pre-rendering stage, and avoid unnecessary use of ResizeObserver

---

components/tree/TreeNode.razor.cs
tests/AntDesign.Tests/Tree/TreeTests.razor

Possible https://github.com/ant-design-blazor/ant-design-blazor/issues/2896
In https://github.com/ant-design-blazor/ant-design-blazor/pull/2507, `Tree#DataSource` and `Tree#ChildrenExpression` are changed to `IEnumerable` making modifying DataSource in place not possible. This issue is currently present in [Tree demo draggable](https://antblazor.com/en-US/components/tree#components-tree-demo-draggable) page at the time of writing.
This PR aims to fix this by skipping `ToList()` call when the `DataSource` is IList in both TreeNode `ChildDataItems` and `GetParentChildDataItems`.
Additionally, some test cases are added to verify it.

fix(module: tree): fix IList `DataSource` cannot be modify in place

---

components/select/SelectBase.cs

When making a custom input component that required support for both a single `Value` as well as multiple `Values`, I encountered the problem that setting `SelectBase`'s `Values` to null (in the case I was using only a single `Value` would call `NotifyFieldChanged`. Since the field didn't actually change, but the component was rerendered on a validation state change, this resulted in an infinite loop.
I added a case for when both `value` and `_selectedValues` are `null`, in which case `NotifyFieldChanged` is not called.
`EditContext.NotifyFieldChanged` is no longer called when `Values` is kept `null`.
| 🇺🇸 English | Fix incorrect call of `EditContext.NotifyFieldChanged` when `SelectBase.Values` is set (unchanged) to null  |
| 🇨🇳 Chinese …

fix(module: select): NotifyFieldChanged on null Values

---

components/core/JsInterop/DomEventListener.cs

fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3184
| 🇺🇸 English |     remove the shared event subscriptions from it's store after there are no one are listening the event      |
| 🇨🇳 Chinese |    修复 DomEventListener  移除不再订阅共享事件的事件列表，避免再次订阅时没创新事件监听器       |

fix(module: core): remove the shared event subscriptions from it's store after there are no one are listening the event

---

components/radio/RadioGroup.razor.cs
tests/AntDesign.Tests/Radio/RadioGroupTests.razor

fix(module: radio): infinite loop render after changing the bind value out of the optons.

---

components/tree/TreeNodeTitle.razor

- Tree自定义SearchExpression后Title中不包括过滤内容导致的bug
- 判断要匹配字符串在Title内的index，只有 index>-1才做匹配高亮

 fix(module: tree): Fix search crash issue after Tree custom SearchExpression

---

components/table/Internal/TItemProxy.cs
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/demo/BasicBindField.razor
site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor
site/AntDesign.Docs/Demos/Components/Table/demo/basic-bind-field.md
site/AntDesign.Docs/Demos/Components/Table/demo/custom-sort.md
site/AntDesign.Docs/Demos/Components/Table/demo/data-index.md
site/AntDesign.Docs/Demos/Components/Table/demo/generate-columns.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md

fixed #1026
Due to the limitations of our design, context.Property is used to bind the data, but this requires access to the instance reference.
Finally, we fixed the problem by using DispatchProxy to create instances of the interface.
| 🇺🇸 English |    Add Table the items of DataSource support interface types       |
| 🇨🇳 Chinese |   增加 Table 支持接口类型的   DataSource  子项   |

feat(module: table): the items of DataSource support interface types

---

site/AntDesign.Docs/Demos/Components/Statistic/demo/Separator.md
site/AntDesign.Docs/Demos/Components/Statistic/demo/Separator.razor

No example discussed here: https://github.com/ant-design-blazor/ant-design-blazor/issues/3163
@dotnet-policy-service agree

Separator usage in Statistic Doc

---

components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs

Fixes #3303 when OnOpenChange called twice on close

fix(module: datepicker): RangePicker. OnOpenChange called twice on close

---

components/date-picker/DatePicker.razor
components/date-picker/RangePicker.razor
components/date-picker/internal/DatePickerBase.cs
site/AntDesign.Docs/Demos/Components/DatePicker/demo/Placement_.razor
site/AntDesign.Docs/Demos/Components/DatePicker/demo/placement.md
site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/DatePicker/doc/index.zh-CN.md

feat(module: datepicker): support specific popup placement

---

components/tabs/Reuse/ReuseTabs.razor.cs

fxed https://gitee.com/ant-design-blazor/ant-design-blazor/issues/I7N3IF

fix(module: tabs): ReuseTabs throwing navigate exceptiion while base path was set

---

components/select/SelectBase.cs
site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
tests/AntDesign.Tests/Select/Renders/Select.Render.Tests.razor

Add AutoFocus to select components to provide same functionalty as other input components
To extend support for auto focus across more input components.
Add AutoFocus parameter for all components based on SelectBase
| 🇺🇸 English | AutoFocus for all select components          |

feat(module:selectbase): add AutoFocus to select base component

---

components/tabs/Reuse/ReuseTabs.razor
components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsPageAttribute.cs
components/tabs/Reuse/ReuseTabsPageItem.cs

closes #3290 
| 🇺🇸 English |    add reusetabs KeepAlive parameter to choose whether to keep the page state       |
| 🇨🇳 Chinese |    增加 ReuseTabs KeepAlive属性，表示是否保持 Tab 页面的状态       |

feat(module: tabs): add keepalive parameter to choose whether to keep the page state

---

components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsPageAttribute.cs
components/tabs/Reuse/ReuseTabsPageItem.cs

| 🇺🇸 English |   add order options for pinned tabs in reusetabs        |
| 🇨🇳 Chinese |    增加 Order 指定特殊标签的顺序       |

feat(module: tabs): add order options for pinned tabs in reusetabs

---

components/core/JsInterop/modules/components/inputHelper.ts

fix(module: input): null check for the js of textarea resizable

---

components/form/FormItem.razor.cs
components/form/Internal/IFormItem.cs
components/input/Input.cs

when a form variable is decorated with the required validation, the required attribute is added to the input html
no breaking changes

feat(module:input) adds required attribute to input elements.

---

components/drawer/Drawer.razor.cs
site/AntDesign.Docs/Demos/Components/Drawer/demo/Basic.razor

| 🇺🇸 English |   add Drawer parameter VisibleChanged for two-way binding support        |

feat(module: drawer): add VisibleChanged for two-way binding support

---

components/modal/config/DialogOptions.cs
components/modal/config/ModalOptions.cs
components/modal/confirmDialog/Confirm.razor
components/modal/core/Dialog.razor
components/modal/core/Dialog.razor.cs
components/modal/core/DialogWrapper.razor
components/modal/modalDialog/Modal.razor
components/modal/modalDialog/Modal.razor.cs
components/modal/modalDialog/ModalContainer.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/Resizeable.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/custom-modal-footer.md
site/AntDesign.Docs/Demos/Components/Modal/demo/max-body-height.md
site/AntDesign.Docs/Demos/Components/Modal/demo/maxable.md
site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_confirm.md
site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_modal.md
site/AntDesign.Docs/Demos/Components/Modal/demo/resizeable.md
site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md

#3263
| 🇺🇸 English |   feat: add resizable paramter for modal, and modal can be resized horizontally <br/> fix: the class and id parameters are not valid in modal component usage    |
| 🇨🇳 Chinese |     Modal 组件新增resizable 参数，允许水平方向对modal进行宽度调整 <br/> 修复 modal 在组件用法中 id 和 class 参数不生效的问题    |

feat(module: modal): add horizontal resizable

---

components/locales/zh-CN.json
components/tabs/Reuse/ReuseTabs.razor
components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsLocale.cs
components/tabs/Reuse/ReuseTabsService.cs
tests/AntDesign.TestApp/Client/Pages/TestTabs.razor

feat(module: tabs): reusetabs support reload page inside blazor

---

components/table/Column.razor.cs
components/table/ITable.cs
components/table/Table.razor.cs

fix(module: table): reset PageIndex when filters and sorters change

---

components/notification/Notification.razor.cs

#3175 
| 🇺🇸 English |     fix(module: notification): change sync statehaschanged to async (#3175)      |
| 🇨🇳 Chinese |   通知组件使用异步  statehaschanged       |

fix(module: notification): change sync statehaschanged to async (#3175)

---

components/core/JsInterop/modules/components/tableHelper.ts
components/table/ColumnBase.cs
components/table/Table.razor
components/table/Table.razor.cs
components/table/style/patch.less
site/AntDesign.Docs/Demos/Components/Table/demo/ResizableColumn.razor
site/AntDesign.Docs/Demos/Components/Table/demo/resizable-column.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md

Implement the resizable part of #2170

feat(module: table): add resizable column

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/core/JsInterop/modules/components/export.ts
components/core/JsInterop/modules/components/imageHelper.ts
components/image/Image.razor
components/image/Image.razor.cs
components/image/ImagePreview.razor
components/image/ImagePreview.razor.cs

feat(module: image): add drag and drop for preview images

---

components/core/Reflection/PropertyReflector.cs

fix: localization support，use 'DisplayAttribute.GetName()' method 。

---

components/input/Input.cs

fixed https://github.com/ant-design-blazor/ant-design-blazor/issues/3461
| 🇺🇸 English | Fixed input can't change value onblur when composition inputting        |

fix(module: input): can't change value onblur when composition inputting

---

components/input-number/InputNumber.razor
components/input-number/InputNumber.razor.cs
site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/InputNumber/doc/index.zh-CN.md

Add MaxLength parameter for InputNumber.
[InputNumber doesn't have attribute for maxlength #3454](https://github.com/ant-design-blazor/ant-design-blazor/issues/3454)
As described in the issue, the parameter Max and Min can NOT completely replace the function of maxlength for the component `<InputNumber>`. Parameter Maxlength is added and apply to the `<input>`. 
| 🇺🇸 English |      Add MaxLength parameter for InputNumber     |
| 🇨🇳 Chinese |      数字输入框添加MaxLength属性     |

Add MaxLength parameter for InputNumber

---

components/AntDesign.csproj
components/core/Extensions/ServiceCollectionExtensions.cs
components/tabs/Reuse/ReusePages.razor
components/tabs/Reuse/ReuseTabs.razor
components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsService.cs
tests/AntDesign.TestApp/Client/Shared/MainLayout.razor

| 🇺🇸 English |    support separate the tab from the page,  also page reloading       |
| 🇨🇳 Chinese |    支持拆分标签和页面，并支持页面刷新       |

feat(module: ReuseTabs): support separate the tab from the page

---

components/table/Table.razor.RowData.cs
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Table/doc/index.zh-CN.md

fix(module: table): setup RowKey EqualityComparer for caches

---

components/date-picker/DatePicker.Razor.cs
components/date-picker/RangePicker.razor.cs
components/date-picker/internal/DatePickerBase.cs
tests/AntDesign.Tests/DatePicker/RangePickerTests.razor

#3452
This fixes two major issues:
- The issue when the focus is not removed from the RangePicker #3452
- Pressing the Enter or Tab key clears the selected value in the DatePicker and RangePicker. This was caused in the b329aa68d0f00c00eeefe8eb419f3a30e6a0d4af 

fix(module:datepicker): RangePicker focus not cleared

---

components/mentions/Mentions.razor
components/mentions/Mentions.razor.cs
components/mentions/MentionsDynamicOption.cs
site/AntDesign.Docs/Demos/Components/Mentions/demo/Async.razor
site/AntDesign.Docs/Demos/Components/Mentions/demo/async.md
tests/AntDesign.Tests/Mentions/MentionsTests.razor

#3261 
Mentions dynamic async list loading
| 🇺🇸 English | Add dynamic async loading of mentions |
| 🇨🇳 Chinese | 添加提及的动态异步加载 |

feat(module: mentions): Add dynamic async loading of mentions

---

components/date-picker/internal/DatePickerBase.cs
components/date-picker/internal/InternalConvert.cs
tests/AntDesign.Tests/DatePicker/DatePickerTestData.cs
tests/AntDesign.Tests/DatePicker/TimePickerTests.razor

#3498 
The ArgumentOutOfRangeException occurs in the TimePicker when internally converting DateTime.MinValue with DateTimeKind.Local to the DateTimeOffset. The solution is to change DateTime.Kind to Unspecified during the conversion.
Fixes System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset') in the TimePicker. 

fix:(module:datepicker): ArgumentOutOfRangeException in TimePicker

---

components/core/JsInterop/JSInteropConstants.cs
components/core/JsInterop/interop.ts
components/core/JsInterop/modules/components/export.ts
components/core/JsInterop/modules/components/watermarkHelper.ts
components/watermark/Watermark.razor
components/watermark/Watermark.razor.cs
site/AntDesign.Docs/Demos/Components/Watermark/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/Custom.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/Image.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/ImageScrolling.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/MultiLine.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/Scrolling.razor
site/AntDesign.Docs/Demos/Components/Watermark/demo/basic.md
site/AntDesign.Docs/Demos/Components/Watermark/demo/custom.md
site/AntDesign.Docs/Demos/Components/Watermark/demo/image-scrolling.md
site/AntDesign.Docs/Demos/Components/Watermark/demo/image.md
site/AntDesign.Docs/Demos/Components/Watermark/demo/multi-line.md
site/AntDesign.Docs/Demos/Components/Watermark/demo/scrolling.md
site/AntDesign.Docs/Demos/Components/Watermark/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Watermark/doc/index.zh-CN.md

fixed #3440
fixed #3442 
fixed #3500
We haven't implement the cssinjs where the antd 5.x used, so this component's style is not the same with antd.
| 🇺🇸 English |    add new component WaterMark       |
| 🇨🇳 Chinese |     新增水印组件      |

feat(module: watermark): add new component WaterMark

---

components/tabs/Reuse/ReuseTabsPageAttribute.cs
components/tabs/Reuse/ReuseTabsService.cs

fix(module: tabs): default to open first pinned page with reusetabs

---

components/radio/style/patch.less

fix(module: radio): checked effect in ssr

---

components/core/Helpers/EnumHelper.cs

fix(module: core): enum name supports localization

---

components/select/Select.razor.cs
tests/AntDesign.Tests/Select/Actions/Select.Clear.Tests.razor

fix(module: select): clear selectd option when the default value isn't in the options

---

components/upload/UploadButton.razor.cs
tests/AntDesign.Tests/Upload/UploadTests.razor

Fix UploadButton to use System.IO.Path.GetExtension instead of Substring to support filenames without extensions
https://github.com/ant-design-blazor/ant-design-blazor/issues/3553
Uploading a file that does not have a file extension using the Upload[button] component results in the following exception being thrown:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: ArgumentOutOfRange_Generic_MustBeNonNegative, startIndex, -1 Arg_ParamName_Name, startIndex
ArgumentOutOfRange_ActualValue, -1
System.ArgumentOutOfRangeException: ArgumentOutOfRange_Generic_MustBeNonNegative, startIndex, -1 Arg_ParamName_Name, startIndex
ArgumentOutOfRange_ActualValue, -1
at …
```

Fix exception when uploading a file without an extension 

---

components/table/Table.razor.cs

fix(module: table): clear the selection state after pages was changed outside

---

components/components.less
components/core/CssSizeLength.cs
components/core/Helpers/CssStyleBuilder.cs
components/flex/Flex.razor.cs
components/flex/style/entry.less
components/flex/style/index.less
site/AntDesign.Docs/Demos/Components/Flex/demo/Align.razor
site/AntDesign.Docs/Demos/Components/Flex/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Flex/demo/Combination.razor
site/AntDesign.Docs/Demos/Components/Flex/demo/Gap.razor
site/AntDesign.Docs/Demos/Components/Flex/demo/Wrap.razor
site/AntDesign.Docs/Demos/Components/Flex/demo/align.md
site/AntDesign.Docs/Demos/Components/Flex/demo/basic.md
site/AntDesign.Docs/Demos/Components/Flex/demo/combination.md
site/AntDesign.Docs/Demos/Components/Flex/demo/gap.md
site/AntDesign.Docs/Demos/Components/Flex/demo/wrap.md
site/AntDesign.Docs/Demos/Components/Flex/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Flex/doc/index.zh-CN.md

feat(module: flex): add flex component

---

components/table/Column.razor.cs

fix(module: table): JSException on filter input autofocus

---

components/collapse/Collapse.razor.cs
components/collapse/Panel.razor.cs
site/AntDesign.Docs/Demos/Components/Collapse/demo/Basic.razor
site/AntDesign.Docs/Demos/Components/Collapse/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Collapse/doc/index.zh-CN.md

feat(module: collapse): add Animation parameter

---

components/input/Input.cs

fix(module: input): hide the clear icon when the input was disabled

---

components/table/Table.razor

fix(module: table): rows can't rerender in some cases

---

components/menu/Menu.razor.cs
components/menu/SubMenu.razor
components/menu/SubMenu.razor.cs

feat(module: menu): add submenu collapse montion

---

components/wwwroot/AntDesign.lib.module.js
docs/getting-started.en-US.md
docs/getting-started.zh-CN.md
scripts/gh-pages/index.html
site/AntDesign.Docs.Wasm/wwwroot/index.html

- [x Bug fix
fixed #3606 
fixed #3607 

add more options for js initializers

---

components/table/Table.razor.cs

fix(module: table): UnselectAll() was not work

---

components/table/Table.razor.RowData.cs
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/demo/Ajax.razor

fix(module: table): select all work incorrectly

---

components/select/Select.razor
components/select/Select.razor.cs
site/AntDesign.Docs/Demos/Components/Select/demo/BigData.razor

#3460 Select Virtualization Bug
#3410 Select - Virtualization of 2000 items
When Select filters options it not remove the option from the DOM it only hide it and leave it on the collection SelectOptionItems.
When passing all items include the hidden the virtualization component can't calculate the height of the scroll.
I create a member _filterOptionsVirtualization to store only the items that aren't hidden and refactor the template to use it, This way is a better more performant than recreating every time is renders.
I create another method to fill list with all the options when it start and when the search is clear to maintain the list that is needed because the virtualization component don't support IEnumerable and it was using .ToList every time it was rendered.
Please any suggestion …

(module: select) Fix scroll in select not working correctly when EnableVirtualization is true.

---

components/core/JsInterop/modules/dom/dragHelper.ts
site/AntDesign.Docs/Demos/Components/Modal/demo/DraggableModal.razor

| 🇺🇸 English |       refactor: the implementation of dragger    |
| 🇨🇳 Chinese |        修改 Dragger 的实现方法   |

refactor: the implementation of dragger

---

components/segmented/SegmentedOption.cs

It self explain, but: new `SegmentedOption<int>(1, "one")` will render "1" instead of "one" which is a label i set

Fix label in SegmentedOption

---

components/select/Select.razor.cs
site/AntDesign.Docs/Demos/Components/Select/demo/SearchFilterCustomize.razor
site/AntDesign.Docs/Demos/Components/Select/demo/search-filter-customize.md
site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md
tests/AntDesign.Tests/Select/Select.FilterExpression.Tests.razor

In spanish and other language you have characters like áéíóúñ and more, that for searching hide if you use the simple character.
By default it continue working like before but now you can pass a function to personalize how to compare the values and have more liberty to customize it by your requirements.
Added parameter FilterExpression for customize how to filter the labels in a select, is optional and by default work like before, no need to change anything.

feat(module: select) Add FilterExpression on select for customize how to filter when searching

---

components/select/Select.razor
components/select/Select.razor.cs
components/select/SelectOption.razor
site/AntDesign.Docs/Demos/Components/Select/demo/CustomDropdownMenu.razor
site/AntDesign.Docs/Demos/Components/Select/demo/ListboxStyle.razor
site/AntDesign.Docs/Demos/Components/Select/demo/list-box-style.md

| 🇺🇸 English |   Fixed Select that the  DropdownRender doesn't pass original content into renderfargment      |
| 🇨🇳 Chinese |   修复 Select 的 DropdownRender 属性没有传入原内容       |

fix(module: select): DropdownRender doesn't pass original content into renderfargment

---

components/core/Extensions/ServiceCollectionExtensions.cs
components/core/JsInterop/JSInteropConstants.cs
components/core/Services/ClientDimensionService.cs
components/table/ColumnBase.cs
components/table/ITable.cs
components/table/Table.razor
components/table/Table.razor.cs
site/AntDesign.Docs/Demos/Components/Table/demo/FixedColumnsHeader.razor

Table scroll style is not consistent with the browser default style.
In order to solve the issue of misplacement of table fixed columns, a property called `ScrollBarWidth `was added. 
By reading the source codes of `antd` and `ant design vue`, I found that we can get the scrollbar size in the browser by calling js method.
I kept the ScrollBarWidth attribute and made it null by default, in which case the scroll bar style is consistent with the browser default style.
and we can still set this property manually.
| 🇺🇸 English |   fix default ScrollBar style in Table   |
| 🇨🇳 Chinese |  修复Table中默认滚动条样式  |

fix default scroll style

---

components/select/internal/SelectContent.razor.cs
tests/AntDesign.Tests/Select/Select.Value.Tests.razor

Fix clearing input in Select when value selected via search
Need to update Blazor state
| 🇺🇸 English |      Fix clearing input in Select when value selected via search     |
| 🇨🇳 Chinese |       修正通过搜索选择值时在选择中清除输入    |

Fix clearing input in Select when value selected via search

---

components/select/internal/SelectOptionGroup.razor

fix(module: select)group names are not hidden when searching

---

components/core/JsInterop/modules/components/tableHelper.ts
components/core/JsInterop/modules/dom/eventHelper.ts

#3725 | #3732  
| 🇺🇸 English |  fix resizable table with `ScrollY ` |
| 🇨🇳 Chinese |  修复带有`ScrollY`的可伸缩列表  |

fix(module: table): resizable table with ScrollY

---

components/table/Table.razor.RowData.cs
components/table/Table.razor.cs

Also fixed #3768, fixed #3654, fixed #2815

fix(module: table): row expand incorrectly because the cache is cleared due to re-rendering

---

components/progress/Progress.razor.cs

- [√] Bug fix
strokecolor does not works for progress bar of circle type.
Add private function GetCircleColor.
| 🇺🇸 English | fix: strokecolor does not works for circle type progress bar |
| 🇨🇳 Chinese | 修复: 环形进度条, strokecolor不生效          |

fix:progress bar strokecolor

---

components/tabs/Reuse/ReusePages.razor
components/tabs/Reuse/ReuseTabs.razor.cs
components/tabs/Reuse/ReuseTabsService.cs
tests/AntDesign.TestApp/Client/Shared/MainLayout.razor

feat(module: reuse-tabs): make the Page of ReuseTabsService public.

---

components/select/Select.razor.cs
tests/AntDesign.Tests/Select/Actions/Select.OnDataSourceChange.Tests.razor

#3750 and #3021
In my project we have faced this issue mentioned above, so i have investigated the root cause.
Due to how HashSet works internally on .NET, when an item is removed from a HashSet (using the Remove method), the space allocation maybe still be there, so when a new item is added (using the Add method), it is not guaranteded to be inserted at the end of the HashSet, so it will not follow the order from the Datasource sent to the Select component, causing the bug.
The solution is to call the Clear method on the HashSet SelectOptionItems after storing all the existing options in the Dictionary, and add everything from the new Datasource, and keep the select state of existing items.
| 🇨🇳 Chinese | …

Fix List order after datasource change

---

components/form/FormItem.razor
components/form/FormItem.razor.cs

fix(module: form): null reference exception

---

components/input-number/InputNumber.razor.cs

Fixed the problem of thousand-point pasting failure

Fixed the problem of thousand-point pasting failure

---

components/core/JsInterop/modules/dom/manipulationHelper.ts

fix(module: modal): throwing exception when JS remove element

---

components/core/Helpers/EnumHelper.cs
site/AntDesign.Docs/Demos/Components/Select/demo/EnumSelectDemo.razor
tests/AntDesign.Tests/Core/Helpers/EnumHelperTests.cs

fix(module: select): EnumSelect throwing exception cause by nullable enum type

---

components/input-number/InputNumber.razor.cs
tests/AntDesign.Tests/InputNumber/InputNumberTests.razor

Fixes: https://github.com/ant-design-blazor/ant-design-blazor/issues/3867
The `if` check uses `_surfaceType` to set the round function which does not account for nullable floating types. 
https://github.com/ant-design-blazor/ant-design-blazor/blob/a53a8e24fc0df29a80f7fc6c0a52d8329b718fe0/components/input-number/InputNumber.razor.cs#L216
This PR fixes this by using `underlyingType`. Additionally, a test is added for it.

fix(module: InputNumber): Fix nullable floating types not round with "Precision" set

---

components/menu/MenuItem.razor.cs

There is no issue for this bug
I was wrapping my menu items into their own components for reuse. After this, the menu items selection was not updated properly.
I recorded a minimal set of examples (the no content case was discovered during testing for this fix):
The StateHasChanged, which is called on the hosting menu, not the MenuItem itself, does not seem to trigger the css classes to be refetched by Blazor. Issue #3204 maybe related to this.
After some testing, I decided to just call the StateHasChanged on the MenuItem when Select/Deselect is called. After all, these methods only get called when the active state was actually changed. Which fixed the issue:
Minimal example code:
| 🇺🇸 English | MenuItem's `IsSelected` visual state is …

fix(module: menu): MenuItem IsSelected visual state for non-default use cases

---

components/core/Base/AntInputComponentBase.cs
components/select/Select.razor.cs
tests/AntDesign.Tests/Select/Select.Value.Tests.razor

[https://github.com/ant-design-blazor/ant-design-blazor/issues/3875](https://github.com/ant-design-blazor/ant-design-blazor/issues/3875)
Per the [Blazor docs ](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#after-parameters-are-set-onparameterssetasync), "Asynchronous work when applying parameters and property values must occur during the [OnParametersSetAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.onparameterssetasync) lifecycle event:"
The issue that this PR fixes is that the Select module was performing asynchronous operations during OnParametersSet, including calling user defined event callbacks. If those callbacks (or any other internal Ant code on the code path) threw any exceptions …

fix(module:select): Set parameters asynchronously

---

components/menu/Menu.razor.cs
components/table/Filters/DateFieldFilterType.cs
components/table/Filters/FilterInputs.razor
components/table/Filters/FilterTypeResolver.cs
site/AntDesign.Docs/Demos/Components/Table/demo/Filter.razor

feat(module: table): add built-in filter support for DateOnly & TimeOnly fields.

---

components/AntDesign.csproj

Starting with .NET 8, Source Link for the following source control providers is included in the .NET SDK and enabled by default
see details: https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects
and verified the git info still exists when removed the source link package
| 🇺🇸 English |     Remove  `Microsoft.SourceLink.GitHub` package reference     |
| 🇨🇳 Chinese |     移除 `Microsoft.SourceLink.GitHub` 包引用      |

build: remove source link pakcge

---

components/Properties/AssemblyInfo.cs

Since we already have `<InternalsVisibleTo Include="AntDesign.Tests" />` in project file, it would generate the `InternalsVisibleTo` assembly attribute, so there's no need to include the assembly attribute in the code
| 🇺🇸 English |  Remove duplicated InternalsVisibleTo         |
| 🇨🇳 Chinese |     移除重复的 InternalsVisibleTo 设置      |

fix: remove duplicated InternalsVisibleTo

---

components/AntDesign.csproj
components/AntDesign.targets

[Issue](https://github.com/stratosblue/IntelliSenseLocalizer/issues/11)
在nuget包的每个 `TargetFramework` 中都包含本地化智能感知文件有一点浪费资源。通过在nuget包中存放一份本地化智能感知文件，使用 `targets` 来复制到最终目录能够减小其空间占用
- 仅在`Debug`模式下会进行复制
- 仅在`Build`之前进行复制
- 未`Build`引用包的项目之前不会有本地化提示
- 已存在的文件会自动跳过
| 🇺🇸 英文 | reduce nuget package size by copying intellisense files before build         |
| 🇨🇳 中文 | 通过在构建时复制本地化智能感知文件来减小nuget包大小         |

chore: reduce nuget package size by copying intellisense files before build

---

components/form/Internal/Validate/ValidationAttribute/NumberMaxAttribute.cs
components/form/Internal/Validate/ValidationAttribute/NumberMinAttribute.cs

fix(module: form): exception during validation for some nullable types

---

components/form/Form.razor
components/form/Form.razor.cs

refactor(module: form): make validate mode default to Complex

---

components/form/GenerateFormItem.razor.cs
site/AntDesign.Docs/Demos/Components/Form/demo/GenerateFormItem_.razor

| 🇺🇸 English | The `GenerateFormItem` automatically generates forms and recognizes the `ReadOnlyAttribute` in the `TModel` properties, making it effective. |
| 🇨🇳 Chinese | GenerateFormItem自动生成表单时，识别TModel属性中的ReadOnlyAttribute标识，并使其生效 |

feat(module: form): GenerateFormItem support recognize ReadOnlyAttribute to set component's disabled

---

docs/faq.en-US.md
docs/faq.zh-CN.md
site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
site/AntDesign.Docs.Wasm/Program.cs
site/AntDesign.Docs/Pages/Components.razor.cs
site/AntDesign.Docs/Pages/Docs.razor.cs
site/AntDesign.Docs/ServiceCollectionExtensions.cs
site/AntDesign.Docs/Services/DemoService.cs
site/AntDesign.Docs/Services/DemoServiceCache.cs

There is no related issue. See also: https://x.com/shunjiey/status/1833658288208310406.
The Docs WebAssembly app is not SEO-friendly because each document page is not pre-rendered. So, I tried to enable the build-time static pre-rendering by using the ["BlazorWasmPreRendering.Build"](https://www.nuget.org/packages/BlazorWasmPreRendering.Build) NuGet package.
There are no changes from the component user's perspective. This pull request only affects the infrastructure of the document site.

Enable static pre-rendering on the Docs WebAssembly app

---

components/input/Input.cs
site/AntDesign.Docs/Demos/Components/Input/demo/Clear.md
site/AntDesign.Docs/Demos/Components/Input/demo/Clear.razor
site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
tests/AntDesign.Tests/Input/InputTests.razor

#4167 
Allows different or more complex logic for when the clear icon should be shown, e.g. even when the input is empty (but not null).
| 🇺🇸 English | New `ShowClear` parameter allows overriding when the clear button is shown. |

feat(module: input): Allow overriding when clear button is shown

---

components/cascader/Cascader.razor.cs

fix(module: cascader): wrong placement and selected node order

---

components/tabs/TabPane.razor.cs
site/AntDesign.Docs/Demos/Components/Tabs/demo/Basic.razor

fix(module: tabs): make it possible to work without setting keys of TabPane

---

components/grid/Col.razor.cs

When specifying the `Flex` attribute on a grid col, it is rendered as an inline style with no ending semicolon. This can cause issues if a user also specifies their own styling. For example:
```razor
<GridCol Flex="@("auto")" Style="display: flex; align-items: center;">
```
Will render as:
```html
<div class="ant-col" style=" flex: auto display: flex; align-items: center;">
```

End col inline style with semicolon

---

components/modal/core/Dialog.razor
components/modal/core/Dialog.razor.cs

Move `Dialog` MaskClick Function into MouseUp Event Callback
[Mousedown on the modal content and mouseup on the mask will sometimes close the modal #4272](https://github.com/ant-design-blazor/ant-design-blazor/issues/4272)
| 🇺🇸 English | Move `Dialog` MaskClick Function into MouseUp Event Callback. Fixed #4272 |
| 🇨🇳 Chinese | 将 `Dialog` 遮罩层的点击事件功能移至鼠标松开回调。修复 #4272  |

Move `Dialog` MaskClick Function into MouseUp Event Callback

---

components/table/Table.razor.cs

Fixed the issue that the column could not be deleted when compiling colums, and colIndex was used to delete it
- [√] Bug fix

Fixed the issue that the column could not be deleted when compiling colums, and colIndex was used to delete it

---

components/table/Table.razor.cs
components/table/style/patch.less

Please see the related issue : [#4371](https://github.com/ant-design-blazor/ant-design-blazor/issues/4371)
I've added the **Striped** property to the **Table** component and now we can use **Striped** or **Striped="@true"** for this purpose.
And there is what is expected :
- Striped property has been added to the Table component
- Doc is not updated yet
- Demo is not updated yet
- Changelog is provided

Striped property has been added to the Table component

---

components/input/Input.cs
tests/AntDesign.Tests/Input/InputTests.razor

✅New feature
Currently for **input** tags which have prefix and suffix does not have a feature to add  custom class to the **Wrapper Span**.
Suppose that there are a bunch of inputs in a form in the page which want to are expected to have same margins now we must use **WrapperStyle** for all of them with redundant styles.
Does it make sense to have a **WrapperClass** ?
✅Test Is Added
✅Doc is updated
✅Demo is updated
✅Changelog is provided

Adding WrapperClass for Input

---

components/core/Base/AntDomComponentBase.cs
components/core/Extensions/StringBuilderExtensions.cs
components/tag/Tag.razor.cs
tests/AntDesign.Tests/Icon/IconServiceTests.cs

Improve the current impl of `Tag`.
The tag currently still store the preset colors with `HashTable` after adding `TagColor` enums, which is not suggested by .NET now.
This PR replaces `HashTable` with the generic `Dictionary` and improves the code quality about resolving the color related properties.
| 🇺🇸 English |  Optimize the `Tag` implement  |
| 🇨🇳 Chinese |  优化`Tag`组件代码实现   |

perf(module: tag): use generic color dictionary and improve code quality

---

components/table/Filters/StringFieldFilterType.cs

[#4492 ](https://github.com/ant-design-blazor/ant-design-blazor/issues/4492)
Be able to filter out rows from a table that contain a certain string value in a column.
Implement TableFilterCompareOperator.NotContains for StringFieldFilterType  
| 🇺🇸 English | Adds string table filter option Not Contains |

StringFieldFilterType implement TableFilterCompareOperator.NotContains

---

components/form/Form.razor
components/list/AntList.razor
components/table/Table.razor
tests/AntDesign.Tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html
tests/AntDesign.Tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html
tests/AntDesign.Tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html
tests/AntDesign.Tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html
tests/AntDesign.Tests/List/List.Render.Tests.razor

When doing custom styling outside AntDesign, it can be hard to know why a spin container is rendered. This change adds wrapper class names for spinners on forms, lists, and tables.

Add spin wrapper classes for form, list, and table

---

components/drawer/Drawer.razor.cs

部分情况下，关闭Drawer，触发StateHasChanged的时机不正常，导致Drawer z-index异常(InnerZIndexStyle不更新)，例如：下图中，Drawer关闭后，仍然可以看到它的阴影
| 🇺🇸 English |   Fix z-index exception when closing Drawer  |
| 🇨🇳 Chinese |  修复关闭Drawer时，z-index异常  |

fix(module: drawer): leaves a shadow after being closed

---

components/flex/Flex.razor.cs

#4528 
FlexGap.Normal was not present in _gapMap dictionary 
| 🇺🇸 English |  All Flex components that have the default FlexGap now no longer give an KeyNotFoundException |

fix: add FlexGap.Normal to _gapMap dictionary (#4528)

---

site/AntDesign.Docs/Demos/Components/Overview/demo/Overview.razor
site/AntDesign.Docs/Pages/Static/Components/Overview.razor

Component search is broken because `Children` can be `null`, additional `Where` fixes that.
Now in documentation:
https://github.com/user-attachments/assets/9c9538d0-3891-4482-9c29-2621ee540df8
After fix:
https://github.com/user-attachments/assets/121bdb08-d92c-4350-b848-e235dcc879c1

fix: Broken components search

---

components/flex/Flex.razor.cs

Flex组件中，Justify设置中误用了Align的值
| 🇺🇸 English |     fix Flex Justify value     |
| 🇨🇳 Chinese |     修复Flex的Justify属性      |

fix(module: flex): the value of Align is misused in the Justify parameter

---

.github/workflows/preview-deploy.yml

/cc @ElderJames
Post fix for #4557. The branch filter is not needed since it has to run on pull requests. Sorry about that.

Remove the branch filter since it is meant to work from pull requests

---

components/message/IMessageService.cs
components/message/Message.razor.cs
components/message/MessageExtensions.cs
components/message/MessageService.cs
components/message/config/MessageConfig.cs
site/AntDesign.Docs/Demos/Components/Input/demo/SearchLoading.razor
site/AntDesign.Docs/Demos/Components/Message/demo/ContinueWith.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Loading.razor
site/AntDesign.Docs/Demos/Components/Message/demo/LoadingWhen.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Other.razor
site/AntDesign.Docs/Demos/Components/Message/demo/Update.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/Confirm.razor
site/AntDesign.Docs/Demos/Components/Modal/demo/Confirm_Service.razor
site/AntDesign.Docs/Demos/Components/Popconfirm/demo/ButtonProps.razor
site/AntDesign.Docs/Demos/Components/Upload/demo/PictureStyle.razor
site/AntDesign.Docs/Shared/MainFooter.razor.cs

- Added synchronous methods for Error, Info, Loading, Open, Success, and Warning in IMessageService.
- Updated existing asynchronous methods to follow the new naming convention (e.g., ErrorAsync, InfoAsync).
- Modified MessageService to handle the new synchronous methods and adjusted the PreOpen method to support animation options.
- Updated related demo files to reflect the changes in method calls from asynchronous to synchronous where applicable.
| 🇺🇸 English |    update IMessageService to support synchronous and asynchronous message methods       |
| 🇨🇳 Chinese |    IMessageService 支持异步与同步方法       |
1. **Method Return Types**
- Before: All message methods returned `Task`
- After: Methods are split into synchronous (void) and …

feat(module: message): update IMessageService to support synchronous and asynchronous message methods

---

components/input/Input.cs
components/input/TextArea.razor.cs
tests/AntDesign.Tests/Input/InputTests.razor

Updated the Input component to include a new parameter, DefaultToEmptyString, which controls whether the value is set to an empty string or null when the input is empty or whitespace. The TryParseValueFromString method has been overridden to implement this logic. Removed the DefaultToEmptyString parameter from the TextArea component. Added unit tests to verify the new behavior of the Input component.

feat(module: input): Bring DefaultToEmptyString parameter to Input from TextArea

---

components/tabs/Tabs.razor.cs
tests/AntDesign.Tests/tabs/TabsTests.razor

- Moved the check for active tab after the OnTabClick invocation to ensure the event is fired correctly for both active and inactive tabs.
- Added a new unit test to verify that OnTabClick is triggered when a tab is clicked, regardless of its active state.
fixed #4584

fix(module: tabs): Ensure OnTabClick is fired correctly when tabs are clicked

---

components/tabs/Tabs.razor
components/tabs/Tabs.razor.cs

Refactor `Tabs.razor` to use `tab.TabIndex` instead of `tab.GetHashCode()` for rendering content, ensuring proper tab order.
Remove manual reordering of `_tabs` in `Tabs.razor.cs`, as tabs are now rendered in the correct order directly.
Update the condition for activating the previous tab to use `_tabs.IndexOf(tab)` instead of `tab.TabIndex`, improving reliability and alignment with the collection's natural order.
These changes improve maintainability and address potential issues with tab ordering and activation.

fix(module: tabs): avoid rerendering on tab was close

---

components/select/Select.razor.cs

Updated the condition for throwing an `ArgumentNullException` for `ValueName` to check if `DataSource` contains elements (`DataSource?.Any() == true`) instead of verifying if `SelectOptions` is `null`. This ensures the exception is triggered only when a valid `DataSource` exists and other criteria are met.

fix(module: select): should only check ValueName at DataSource mode
